### ISSUE TITLE
Support for Google BigQuery Storage Client for Java

### ISSUE THREAD

**Issue by wleese** [GoogleCloudPlatform/spring-cloud-gcp#1015]
**Is your feature request related to a problem? Please describe.**
With the latest version of spring-cloud-gcp available as of writing, I'd like to be able to use the BigQuery write-api as described on https://cloud.google.com/bigquery/docs/write-api
It would seem that currently only the older methods of writing data are supported.

**Describe the solution you'd like**
I'd like spring-cloud-gcp bigquery support to use the BigQuery write-api, in order to reap the benefits (cost reduction, performance, configurable consistency guarantees) described by Google in their documentation.

**Comment by elefeint** [comment]
Thanks for the request!
Does your current use-case require directly interacting with BigQuery, or is it for a Spring Integration-based application?

**Comment by wleese** [comment]
@elefeint Indeed we'd like to specifically interact with BigQuery, as within the company certain data will only be available there (provided by users or other applications), and/or because BigQuery provides a nice interface for our Business Analysts and engineers to work with, etc, etc. 

Within our company, there could be quite a few reasons to want to use BigQuery directly.

**Comment by elefeint** [comment]
Then until we provide built-in support in this project, you have a good workaround by using the BigQuery client library exactly as described in the documentation. 
Spring Cloud GCP does not currently autoconfigure `BigQueryWriteClient` object for you, so you would configure one manually.

**Comment by elefeint** [comment]
Addressed in #1219 .
