### ISSUE TITLE
Add support for inserting only for DatastoreOperations

### ISSUE THREAD

**Issue by cranberrysoft** [GoogleCloudPlatform/spring-cloud-gcp#1024]
Currently, there is no way in Spring Data Datastore GCP to insert only an Entity for both Repositories and DatastoreTemplate.

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/2b1100817fc5eb1017e395ec431f2f209546eac1/spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreOperations.java#L61
https://googleapis.dev/java/spring-cloud-gcp/latest/org/springframework/cloud/gcp/data/datastore/core/DatastoreOperations.html#save-T-com.google.cloud.datastore.Key...-

as it is for example for Mongo
https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/MongoOperations.html#insert-T-

This feature would be useful when you want to make sure there is only one entity with a given ID persisted in your Datastore.

I would like to have a new method
`DatastoreOperations.insert()`

which is only inserting.

I can see there is already a method add in DatastoreWriter so it should be quite straightforward to implement

**Comment by zhumin8** [comment]
Thanks for your request. To clarify on your use-case, the current `save` method inserts an entity if it does not exist, updates it otherwise. It already guarantees no duplicated ID inserted to your Database.

If you need to do insert only and skip when ID already existing, as a work around, you can achieve by adding a read logic to check if already in Database.

**Comment by cranberrysoft** [comment]
Hey, @zhumin8 my specific use case is for deduplicating messages coming from a message broker. I wanted to use the atomicity of insert for Datastore.

>If you need to do insert only and skip when ID already existing, as a work around, you can achieve by adding a read logic to check if already in Database.

Does it mean if I run read() and save() within the same transaction for an entity with a key "KEY" only one transaction would finish successfully and other transactions would fail, assuming the operation would run concurrently?

According to the Datastore documentation https://cloud.google.com/datastore/docs/concepts/cloud-datastore-transactions#uses_for_transactions it seems so however it's not easy to test for me. 

Assuming DatastoreOperations save() uses Mutation "UPSERT"  which makes me thinking if this would still by applicable https://cloud.google.com/datastore/docs/reference/data/rest/v1/projects/commit#mutation

**Comment by zhumin8** [comment]
Glad that the workaround works for you. 
We'll consider this `insert()` method as an enhancement at the `DatastoreTemplate` level. And we are happy to review code if you are interested in contributing.

To your other questions:
> I'm also wondering why DatastoreTemplate has almost all private methods, not protected? 

Yes, we'd like to keep these implementation details private so we don't break backward compatibility when possibly changing them in the future.

> Also the interesting finding is...Also the interesting finding is

This sounds interesting. Could you file a separate issue for this with some more details?

**Comment by 2021H1030039G** [comment]
Can I contribute to this issue?

**Comment by elefeint** [comment]
@2021H1030039G This isn't the right difficulty level for a first-time contributor, sorry. I recommend browsing issues marked with "good first issue" -- https://github.com/search?q=%22good+first+issue%22
