### ISSUE TITLE
Access multiple namespaces within one thread

### ISSUE THREAD

**Issue by lisamittmann** [GoogleCloudPlatform/spring-cloud-gcp#1036]
**Is your feature request related to a problem? Please describe.**
Hey - I am trying ti figure out how to access multiple namespaces within on thread. I have a spring boot set up and when a request is coming in, I need to access multiple namespaces to process it. In the first step I need to retrieve data from one namespace based on the incoming request. This is information is then used to process the request and persist it in a different namespace. 

**Describe the solution you'd like**
I would like to be able to annotate an entity object with a specific namespace where it "lives"
```
@Entity
@Namespace("someNamespace")
public class Document {
   String name;
}
```

**Describe alternatives you've considered**
I've looked into the suggestion from this issue: https://github.com/spring-attic/spring-cloud-gcp/issues/2204
But this solution seems to only work if you use the same namespace within a thread. We would like to switch namespaces based on the entity we are using. 

**Additional context**
None

**Comment by elefeint** [comment]
Namespaces are meant to partition data that has the same structure (same entities) but is used by different tenants. In your use-case, the entities are different, so the data would already be separated by `kind`.

For a custom Kind name that differs from the class name, you can pass it to the `@Entity` annotation:
```
@Entity ("someKind")
public class Document {
   String name;
}
```

**Comment by lisamittmann** [comment]
Hey @elefeint thx for the quick reply. When separating data by kind, the different entities would still end up in the same namespace, correctly?

We are actually trying to reuse a dataset within different applications. We have application A with namespace A and application B with namespace B. Also we have application C with a common namespace C which application A + B need to access. 
Is there a way to facilitate that without having to duplicate the data from namespace C in namespace A + B? 
Namespace C is a common data set, which application A + B both need to process incoming requests.

**Comment by elefeint** [comment]
Without specifying a namespace, all datastore entities get saved into the default namespace. I think the term "entity" might be creating confusion. A Datastore Entity is a single object, equivalent to a row in a relational database. A Spring Data Entity is a class corresponding to a table in a relational database, or a *kind* in Datastore. So you can have a Spring Data Entity corresponding to a Datastore Kind with instances of the entity mapping to Datastore data in multiple namespaces. However, a Datastore entity (being a single object/row) will be stored in a specific namespace, and cannot change its namespace after creation. So, a Spring Data Entity corresponds to multiple Datastore entities that can be in multiple namespaces, but each Java object instance of the entity corresponds to a single Datastore entity in a single, fixed-at-creation namespace.

From the Spring Cloud GCP perspective, you can typically get any custom requirement implemented by dropping down to the client library level. In your case, you could create 3 different `com.google.cloud.datastore.Datastore` objects going against different namespaces like this:

```
  Datastore datastoreA = DatastoreOptions.newBuilder().setProjectId("...").setNamespace("a").build().getService();
  Datastore datastoreB = DatastoreOptions.newBuilder().setProjectId("...").setNamespace("a").build().getService();
  Datastore datastoreC = DatastoreOptions.newBuilder().setProjectId("...").setNamespace("a").build().getService();
```

In principle, you could also construct higher level Spring Cloud GCP objects by combining these client library objects with autowired helper objects, following how it's [done in autoconfiguration](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/v3.1.0/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/GcpDatastoreAutoConfiguration.java#L172).

A word of caution, though -- if namespaces A, B and C all have different data (kind) structures, then it's really not what namespaces were designed for. Namespaces are for splitting data between different users of the same data structures. You will likely run into other cases where using namespaces to split data into "databases" will cause friction.

**Comment by lisamittmann** [comment]
@elefeint thx for the clarification.

In our used case application A, B and C do have different data kind structures, because each application has a different purpose, resulting in different data objects.

From your explanation I gather, though, that we're not using the namespaces correctly. 
What would be your suggested data structure layout in this scenario? 
All the applications run within the same GCP project, but have individual cloud run instances on which they run.
Should we rather only have one project specific namespace used by all applications creating different data kinds (i.e. different tables) or is there an elegant way to have separate namespaces for each application which are accessible from other applications as well?

**Comment by elefeint** [comment]
This specific usecase was not a fit, but a broader usecase that does require explicitly setting namespace is in #1104. Closing as duplicate.
