### ISSUE TITLE
Reading Uncommitted data in same transaction 

### ISSUE THREAD

**Issue by dvgaba** [GoogleCloudPlatform/spring-cloud-gcp#1101]
**Describe the bug**
In same @Transactional when we do multiple operations using Spring Repository we are not able to read data committed in same transaction 
1. repo.save(); 
2. repo.findById() //This will not return data saved in earlier call, even though code is running in same transaction block.

The same work while using JDBC connection and setting auto commit as false. 
1. Insert a record
2. Read from Db  //This will return data stored in previous call. 

Not have a sample handy as this happened at work but any insights on this behavior will help.

**Comment by dvgaba** [comment]
Test code is here

https://github.com/dvgaba/spanner-transaction-test

Sample output 

`Insert counts: 1
 ==== ==== ==== ==== ==== from db via JDBC  ==== ==== ==== ==== ====98591012-a393-4aa2-9e7c-dd2c62db04a7
2022-04-22 12:26:00.614  INFO 27576 --- [           main] c.g.c.s.a.c.GcpContextAutoConfiguration  : The default project ID is central-weft-348007

 ==== ==== ==== ==== ==== ==== ====from db via REPO  ==== ==== ==== ==== ====Optional.empty
2022-04-22 12:26:00.975  INFO 27576 --- [           main] com.test.spanner.SpannerApplication      : Started SpannerApplication in 3.296 seconds (JVM running for 3.821)

Process finished with exit code 0
`

**Comment by elefeint** [comment]
Like @zhumin8 said, you can't read uncommitted changes even while being in the same transaction. Another aspect described in the linked documentation explains why: "All reads within that transaction return data from the same timestamp." This timestamp by definition has to be before your current transaction began affecting data state; otherwise the timestamp before and after the write would have to differ.

**Comment by elefeint** [comment]
Although it's interesting that JDBC driver behaves differently. 
@olavloite Could you double check my thinking here -- if autocommit is off, then reading data after an insert should not return the newly inserted data?

**Comment by dvgaba** [comment]
@olavloite thanks. That makes sense and clarifies. Appreciated.
