### ISSUE TITLE
Add instance and database to Spanner emulator startup

### ISSUE THREAD

**Issue by lkleeven** [GoogleCloudPlatform/spring-cloud-gcp#1115]
**Is your feature request related to a problem? Please describe.**
We're using the [Spanner emulator docker image](https://cloud.google.com/spanner/docs/emulator#docker) for integration testing our Spanner database. What we're currently missing is an easy way to provide the Spanner emulator with the instance and database to create. Currently this only seems possible through added scripts and/or code initializing these things after the emulator has started. This makes it very hard to integrate with other tooling like the docker-maven-plugin and our gitlab-ci setup.

**Describe the solution you'd like**
We'd very much like this to be available in the emulator on image startup, maybe through environment variables. To prevent us from needing to add extra tools on top for something that feels like basic functionality.

**Describe alternatives you've considered**
Adding custom scripts and program code to applications/projects.

**Additional context**
NA

**Comment by elefeint** [comment]
I see that you've filed a similar issue against `gcloud` CLI. That's ultimately a better place for this feature request, since Spring Cloud GCP only addresses a subset of Java users.
I will close this issue in favor of https://issuetracker.google.com/231997056
