### ISSUE TITLE
 spring-cloud-gcp-trace - how to add inject custom spans and include traceid in response

### ISSUE THREAD

**Issue by ColeSiegelTR** [GoogleCloudPlatform/spring-cloud-gcp#1118]
Hi

I'm using https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample and it works great to push traces and associated logs to GCP, but I am trying to figure out how I can propagate the traceId into the response so that if errors occur we can easily look up this ID.

Also looking to add tracer decorator to specific code blocks in order to trace them along with the automatic instrumentation provided by the library.

Is this possible?

**Comment by elefeint** [comment]
To find information about the current trace, inject a `org.springframework.cloud.sleuth.Tracer` into your code. This [StackOverflow answer](https://stackoverflow.com/a/57427497/10441462) has a code sample.

Annotating methods with [`@NewSpan`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/c697d1555e55864ecf1ff81a058ca6a51e9af54b/spring-cloud-gcp-samples/spring-cloud-gcp-trace-sample/src/main/java/com/example/WorkService.java#L51) allows tracing of specific blocks. If you need to add information, Spring Cloud Sleuth allows [many types of customizers](https://docs.spring.io/spring-cloud-sleuth/docs/3.1.x/reference/html/project-features.html#features-brave-customizations).

**Comment by ColeSiegelTR** [comment]
Thanks a lot for the help @elefeint I was able to use the examples you provided to solve both the use cases.
