### ISSUE TITLE
PubSub only - Phantom attempted use of com/google/cloud/spring/data/datastore/core/DatastoreTransactionManager

### ISSUE THREAD

**Issue by gmorgen1** [GoogleCloudPlatform/spring-cloud-gcp#1124]
**Describe the bug**
Even though I have only included pubsub starter, GCP seems to be trying to autoconfigure everything causing problems.  I even explicitly disabled all other gcp features.

Spring Boot 2.6.7
Spring Cloud GCP 3.1.2

The only POM dependency is 
			<groupId>com.google.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-pubsub</artifactId>

application.properties:
spring.cloud.gcp.pubsub.enabled=true
spring.cloud.gcp.spanner.enabled=false
spring.cloud.gcp.core.enabled=false
spring.cloud.gcp.config.enabled=false
spring.cloud.gcp.datastore.enabled=false
spring.cloud.gcp.logging.enabled=false
spring.cloud.gcp.trace.enabled=false
spring.cloud.gcp.firestore.enabled=false
spring.cloud.gcp.metrics.enabled=false

It is trying to pull in something from Datastore for some reason:

"Condition OnBeanCondition on com.google.cloud.spring.autoconfigure.datastore.DatastoreTransactionManagerAutoConfiguration$DatastoreTransactionManagerConfiguration#datastoreTransactionManager matched due to @ConditionalOnMissingBean (types: org.springframework.transaction.PlatformTransactionManager; SearchStrategy: all) did not find any beans"

java.lang.NoClassDefFoundError: com/google/cloud/spring/data/datastore/core/DatastoreTransactionManager

**Comment by elefeint** [comment]
Could you create a reproducible sample?

**Comment by zhumin8** [comment]
Closing as part of cleanup. 
Please re-open if it's still relevant.
