### ISSUE TITLE
spring-cloud-gcp-starter-logging - custom logback configuration

### ISSUE THREAD

**Issue by ColeSiegelTR** [GoogleCloudPlatform/spring-cloud-gcp#1125]
Hi,

I am wondering if there is a way to append a custom object to the log context `jsonPayload` with the `spring-cloud-gcp-starter-logging` library.

I've tried adding the object's properties to `MDC` which automatically includes them as key-values in the log `jsonPayload`, but I would like them to be nested inside an object.

I thought maybe the `customJson` option could help me (https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/docs/src/main/asciidoc/logging.adoc#log-via-console), but when I try using the example self-configured appender in my `logback-spring.xml` file, my application cannot start with error `Could not create component [layout] of type [org.springframework.cloud.gcp.logging.StackdriverJsonLayout] java.lang.ClassNotFoundException: org.springframework.cloud.gcp.logging.StackdriverJsonLayout`

```
<configuration >
  <property name="projectId" value="${projectId:-${GOOGLE_CLOUD_PROJECT}}"/>

  <appender name="CONSOLE_JSON" class="ch.qos.logback.core.ConsoleAppender">
    <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
      <layout class="org.springframework.cloud.gcp.logging.StackdriverJsonLayout">
        <projectId>${projectId}</projectId>

        <includeTraceId>true</includeTraceId>-->
        <includeSpanId>true</includeSpanId>-->
        <includeLevel>true</includeLevel>
        <includeThreadName>true</includeThreadName>
        <includeMDC>true</includeMDC>
        <includeLoggerName>true</includeLoggerName>
        <includeFormattedMessage>true</includeFormattedMessage>
        <includeExceptionInMessage>true</includeExceptionInMessage>
        <includeContextName>true</includeContextName>
        <includeMessage>true</includeMessage>
        <includeException>true</includeException>
        <customJson>{"custom-object": { "custom-key": "get-this-dynamically" } }</customJson>
      </layout>
    </encoder>
  </appender>
</configuration>
```

I am wondering if `customJson` would be the correct approach to append JSON object to the log context at runtime, if so, how could I make a dynamic reference in `customJson` instead of hard-coded strings? Also, am I missing some other dependency that is not included in the starter? Maybe the starter should also include `org.springframework.cloud.gcp.logging.StackdriverJsonLayout` or where should I get this file from?

**Comment by elefeint** [comment]
Actually, it's not the dependencies. `org.springframework.cloud.gcp.logging.StackdriverJsonLayout` is the wrong package -- it's `com.google.cloud` since v2.0
