### ISSUE TITLE
Switch r2dbc-postgresql from groupId io.r2dbc to org.postgresql

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#1200]
The [Spring Boot 2.7 release notes say](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#r2dbc-driver-changes):

> In the [Borca release](https://r2dbc.io/2022/02/04/r2dbc-borca-released), the group ID of `r2dbc-postgresql`, the driver for PostgreSQL, has changed from `io.r2dbc` to `org.postgresql`. `r2dbc-mysql`, the driver for MySQL, has been removed. Consider using `r2dbc-mariadb` as a replacement.

`com.google.cloud:spring-cloud-gcp-starter-sql-postgres-r2dbc:3.3.0` depends on `io.r2dbc:r2dbc-postgresql:0.8.12.RELEASE`. This needs to be changed to `org.postgresql:r2dbc-postgresql` in a future version to keep up with developments.

**Comment by elefeint** [comment]
Yep. I am working on it; it's blocking upgrade to Spring Boot 2.7.

**Comment by breun** [comment]
We noticed that there is also an issue with `r2dbc-pool:0.9.0.RELEASE`, which is currently provided by Spring Boot 2.7.3 via `r2dbc-bom:Borca-SR1`, which [causes all connections to be evicted immediately](https://github.com/r2dbc/r2dbc-pool/issues/129). `r2dbc-pool:0.9.1.RELEASE` fixes this, but that version is not yet managed via an `r2dbc-bom` release. I don't know if this is a temporary override you would apply via Spring Cloud GCP or if you'll want to wait for a Spring Boot version that fixes this.

**Comment by elefeint** [comment]
To avoid breaking existing users who are still on Spring Boot 2.6, we won't be changing the version of Postgres R2DBC driver until the next major release of Spring Cloud GCP (that will target Spring Boot 3.0).

You are probably excluding the old driver and including the new one already, but #1185 adds documentation to do so for Spring Boot 2.7 users.
The pool fix is by now released in Spring Boot 2.7.4, so time took care of that.
