### ISSUE TITLE
Please document release schedule

### ISSUE THREAD

**Issue by markusheiden** [GoogleCloudPlatform/spring-cloud-gcp#1214]
**Is your feature request related to a problem? Please describe.**
The release schedule isn't documented anywhere.

I wonder when Spring Cloud GCP becomes Spring Boot 2.7 compatible.

**Describe the solution you'd like**
Something like https://calendar.spring.io/

**Describe alternatives you've considered**
Googling, but I found nothing.

**Comment by elefeint** [comment]
We have plans to align Spring Cloud GCP release schedule with the client libraries for next year. In the meantime, releases are on as needed basis.

Spring Cloud GCP is not officially compatible with Spring Boot 2.7 yet, although most things will work. There is one issue with R2DBC dependencies -- #1200.

We expect to release Spring Cloud GCP compatible with Spring Boot 2.7 in September. Once it's out, it will be documented [here](https://googlecloudplatform.github.io/spring-cloud-gcp/3.3.0/reference/html/index.html#compatibility-with-spring-project-versions).

**Comment by markusheiden** [comment]
At least Spring Config Server (using Spring Cloud Bus/Stream via PubSub) is not working either. Updates from the config server to the clients result in class incompatibilities on the client side. If you are interested in error details, I may provide them.

It would be nice to know the release dates upfront to plan and not need to look up the documentation every now and then. So for now thanks for providing estimation for that for the next release.

**Comment by elefeint** [comment]
Yes, could you open a separate issue for the config server?
