### ISSUE TITLE
Custom `loggingEventEnhancer` is not working for Spring-cloud-gcp-trace with `com.google.cloud.logging.logback.LoggingAppender`

### ISSUE THREAD

**Issue by kamit-transient** [GoogleCloudPlatform/spring-cloud-gcp#1218]
**Describe the bug**
I am using sing `spring-cloud-gcp-starter-trace` ,`spring-cloud-gcp-starter-logging` with version `2.0.11` using logback.

I need to add some additional data to logs at run time, for that I am providing `SpringCloudGcpLogEnhancer` which implements `LoggingEventEnhancer` but the problem is:

When I am using ` <loggingEventEnhancer>com.google.cloud.spring.logging.TraceIdLoggingEnhancer</loggingEventEnhancer> `
Logs are getting sent to GCP Log Explorer(SD) from the **Local as well** but when I am  using `<loggingEventEnhancer>ca.abc.xyz.infrastructure.logging.springcloud.gcp.SpringCloudGcpLogEnhancer</loggingEventEnhancer>` Logs are NOT getting sent to GCP from our **local System**.

I tried quite a few approaches but the issues  persists. What could be the possible workaround to use custom `loggingEventEnhancer` to send the logs to GCP log explorer?

**Sample**

Here is the  `logback config` file
```
<included>
    <property name="STACKDRIVER_LOG_NAME" value="${STACKDRIVER_LOG_NAME:-spring.log}"/>
    <property name="STACKDRIVER_LOG_FLUSH_LEVEL" value="${STACKDRIVER_LOG_FLUSH_LEVEL:-WARN}"/>

    <appender  name="STACKDRIVER" class="com.google.cloud.logging.logback.LoggingAppender">
        <log>${STACKDRIVER_LOG_NAME}</log> <!-- Optional : default spring.log -->
        <loggingEventEnhancer>ca.loblaw.pharmacy.infrastructure.logging.springcloud.gcp.SpringCloudGcpLogEnhancer</loggingEventEnhancer>
     <!--   <loggingEventEnhancer>com.google.cloud.spring.logging.TraceIdLoggingEnhancer</loggingEventEnhancer> -->
        <flushLevel>${STACKDRIVER_LOG_FLUSH_LEVEL}</flushLevel> 
    </appender>

    <root level="INFO">
        <appender-ref ref="STACKDRIVER"/>
    </root>

</included>

```

**Comment by elefeint** [comment]
What happens when you provide multiple enhancers at the same time?

I would also try providing ehnancers under `<layout class="com.google.cloud.spring.logging.StackdriverJsonLayout">`, and not directly under `<appender>`. Both might work, but we've tested with the latter -- see the [docs](https://googlecloudplatform.github.io/spring-cloud-gcp/3.3.0/reference/html/index.html#log-via-console) for example (scroll to "This is an example of such an Logback configuration").

**Comment by kamit-transient** [comment]
> What happens when you provide multiple enhancers at the same time?

Both enhancers get called but in that case, logs are not published to GCP Log explorer from local.

> I would also try providing ehnancers under <layout class="com.google.cloud.spring.logging.StackdriverJsonLayout">, and not directly under <appender>. Both might work, but we've tested with the latter -- see the [docs](https://googlecloudplatform.github.io/spring-cloud-gcp/3.3.0/reference/html/index.html#log-via-console) for example (scroll to "This is an example of such an Logback configuration").

I am not an expert on logabck part, so my question is, can this be done with the **API logging approach** as well? 

For clarity, I am not using the `JsonConsoleAppender` rather I am using `LoggingAppender` with the below config:

```
<included>
    <property name="STACKDRIVER_LOG_NAME" value="${STACKDRIVER_LOG_NAME:-spring.log}"/>
    <property name="STACKDRIVER_LOG_FLUSH_LEVEL" value="${STACKDRIVER_LOG_FLUSH_LEVEL:-WARN}"/>

    <appender  name="STACKDRIVER" class="com.google.cloud.logging.logback.LoggingAppender">
        <log>${STACKDRIVER_LOG_NAME}</log> <!-- Optional : default spring.log -->
        <loggingEventEnhancer>ca.loblaw.pharmacy.infrastructure.logging.springcloud.gcp.SpringCloudGcpLogEnhancer</loggingEventEnhancer>
     <!--   <loggingEventEnhancer>com.google.cloud.spring.logging.TraceIdLoggingEnhancer</loggingEventEnhancer> -->
        <flushLevel>${STACKDRIVER_LOG_FLUSH_LEVEL}</flushLevel> 
    </appender>

    <root level="INFO">
        <appender-ref ref="STACKDRIVER"/>
    </root>

</included>

```

**Comment by kamit-transient** [comment]
I tried the suggested approach for API logging, but that's not working.

I think it's more likely a bug than a question.  Should you change the label to Bug then? @elefeint

**Comment by elefeint** [comment]
I think I know what's going on. For console-based logging, our documentation instructs users to add enhancers as `<loggingEventEnhancer>` under `StackdriverJsonLayout`.

However, you are using API logging, for which there is no enhancer documentation on Spring Cloud GCP. Looking at the [Cloud Logging Logback appender](https://github.com/googleapis/java-logging-logback#about-cloud-logging-logback-appender 
), which `com.google.cloud.logging.logback.LoggingAppender` comes from, the enhancer tag should be passed as `<enhancer>`, not as `<loggingEventEnhancer>`.

For your purposes, here is an example that works: https://github.com/elefeint/examples/tree/main/logging-multiple-enhancers

For this repo, we will update the documentation to reference the main cloud logback appender.

**Comment by elefeint** [comment]
I looked at it some more for documentation, and both `<loggingEventEnhancer>` and `<loggingEnhancer>` are valid configurations for the logback appender. However,  `<loggingEventEnhancer>`  classes must implement `com.google.cloud.logging.logback.LoggingEventEnhancer`, and `<loggingEnhancer>` must implement `com.google.cloud.logging.LoggingEnhancer`; otherwise the enhancer will be ignored [here](https://github.com/googleapis/java-logging-logback/blob/2a3ed97797f7225b7282b536897366e37b44aecf/src/main/java/com/google/cloud/logging/logback/LoggingAppender.java#L282).

**Comment by athul-rajan** [comment]
@kamit-transient I am facing the same issue while using loggingEventEnhancer. But I could not find any documentation for loggingEventEnhancer in that logback appender.  But instead, I saw 'enhancer'. Could you please confirm if you were able to use 'loggingEventEnhancer' and made it working? 'enhancer' is also not working in my case.
