### ISSUE TITLE
PubSub batch settings

### ISSUE THREAD

**Issue by mcaa90** [GoogleCloudPlatform/spring-cloud-gcp#1255]
Hello, 

I am using the pubsub library to send messages with this version<spring-cloud-gcp.version>3.2.0</spring-cloud-gcp.version>
i want to use the batch seetings but when i see the code in the method that publish the PubSubMessage a new publisher is created each time we publish a message so i want to know how the batch is working please ?

**Comment by elefeint** [comment]
Publishers are [cached per-topic](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/v3.2.0/spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/support/CachingPublisherFactory.java#L44).

To enable batching, all of batching settings must be set to above defaults:
- `spring.cloud.gcp.pubsub.publisher.batching.enabled`
- `spring.cloud.gcp.pubsub.publisher.batching.element-count-threshold`
- `spring.cloud.gcp.pubsub.publisher.batching.request-byte-threshold`
- `spring.cloud.gcp.pubsub.publisher.batching.delay-threshold-seconds`

**Comment by mcaa90** [comment]
Thanks for the answer but my question is about how does it work because in the pubSubTemplate a new publisher is created each time with these settings 
if i look at the google documentation the batching is used when creating one publisher then do many calls to publish method not a publisher for each one 
Thank you

**Comment by mcaa90** [comment]
Thank you for the answer, and where/when the shutdown of this publisher is called please ?

**Comment by elefeint** [comment]
They are currently not shut down automatically (see #864 for details), but as you acquire a `Publisher` object when calling `createPublisher()`, your application can shut it down.
