### ISSUE TITLE
Try to upgrade to Spring Boot 3.0

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/spring-cloud-gcp#1280]
Inventory all issues.

Release notes: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes

**Comment by breun** [comment]
Hi @elefeint! Can you already say something about roughly when you expect/intend to release a version of Spring Cloud GCP which supports Spring Boot 3 and Spring Cloud 2022?

**Comment by breun** [comment]
Ok, thanks. We're very eager to provide Spring Boot 3.0 to our colleagues as soon as we can, but we depend on Spring Cloud GCP as well, so we'll need to be a bit more patient then. Will there be milestone releases and/or release candidates for Spring Cloud GCP users that want to try things out early?

**Comment by elefeint** [comment]
No, sorry -- we stopped doing release candidates when we left the spring-cloud organization.
