### ISSUE TITLE
Convertor for ByteString to String is not working in v3.4.0

### ISSUE THREAD

**Issue by nitin065** [GoogleCloudPlatform/spring-cloud-gcp#1296]
**Describe the bug**
I have added to build.gradle to use v3.4.0 and added `spring.config.import property: sm://` and set `spring.cloud.gcp.secretmanager.legacy: false`.

But still, I m getting `No converter found capable of converting from type [com.google.protobuf.ByteString$LiteralByteString] to type [java.lang.String]`.

I have tried to debug the code and have following observation:

[GenericConversion.Converters](https://github.com/spring-projects/spring-framework/blob/1439c5bb8fa5ca8752b4d81232c8114aa8a376f4/spring-core/src/main/java/org/springframework/core/convert/support/GenericConversionService.java#L501) (from spring core 5.3.22) have a Map object `converters`, which have count of 167 when addConverter is called from [GcpSecretManagerEnvironmentPostProcessor](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/v3.0.0/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerEnvironmentPostProcessor.java#L36-L55).
![IssuePic1](https://user-images.githubusercontent.com/20437084/196102972-efaab77d-a5fe-47fc-a1fc-d2efc4826036.PNG)

But sometimes later [remove method](https://github.com/spring-projects/spring-framework/blob/5.3.x/spring-core/src/main/java/org/springframework/core/convert/support/GenericConversionService.java#L525) is called (**once**), but before that itself the count is reduced to 73. 
![IssuePic2](https://user-images.githubusercontent.com/20437084/196102982-1350f554-35e5-4814-aa72-a17823c4c4b1.PNG)

When it actually hit the code to [find](https://github.com/spring-projects/spring-framework/blob/5.3.x/spring-core/src/main/java/org/springframework/core/convert/support/GenericConversionService.java#L538) the converter for ByteString the count is 52 without ByteString converter. 

It looks like there are 10 converters object has been created with different count of converters added:
![image](https://user-images.githubusercontent.com/20437084/196108455-a22c57b8-b67a-4744-8f63-bcf2ea0750b9.png)

But when I add a custom converter as mentioned in [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/955#issuecomment-1048101815), the count would be 53, with my custom converter present.

Am I missing something or some configuration?

PS: I have datasource configuration in place, so fetching data from GSM happens prior to application completes startup.

**Comment by elefeint** [comment]
@JoeWang1127 Could you take a look?

**Comment by JoeWang1127** [comment]
@nitin065 Hi, could you create a demo project showing the error? In the mean time, have your checked the [sample project](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample) in our repo?

**Comment by nitin065** [comment]
@JoeWang1127 Yes, I did. Only difference is I am not using SecretManagerTemplate class. I will try to come up with a sample project.

**Comment by nitin065** [comment]
@JoeWang1127 I have found the root cause. Basically we have following code present:
`PropertySourcesPlaceholderConfigurer configurer = new PropertySourcesPlaceholderConfigurer();`
` configurer.setIgnoreUnresolvablePlaceholders(true);`

And [here](https://github.com/spring-projects/spring-framework/blob/1439c5bb8fa5ca8752b4d81232c8114aa8a376f4/spring-context/src/main/java/org/springframework/context/support/PropertySourcesPlaceholderConfigurer.java#L140) based on the flag, it chooses the property resolver, which causes to initialize [default conversion service](https://github.com/spring-projects/spring-framework/blob/1439c5bb8fa5ca8752b4d81232c8114aa8a376f4/spring-core/src/main/java/org/springframework/core/env/AbstractPropertyResolver.java#L263)
 
I updated the [test project](https://github.com/nitin065/gmstest) with reproducible code.

**Comment by elefeint** [comment]
@spencergibb @philwebb Have you seen issues before where custom conversion service changes were lost in `ignoreUnresolvablePlaceholders` mode? We've been using an `EnvironmentPostProcessor` [to register `ByteString` converters](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/58b9fb9e034c7208df5398facbc96c5e8cdae916/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerEnvironmentPostProcessor.java#L39), but it seems that the customized environment is not used when `ignoreUnresolvablePlaceholders` is set. Any suggestions? Or will users have to register their own converters in this case?

**Comment by JoeWang1127** [comment]
Hi @nitin065, could you tell me more about why you need to create a `PropertySourcesPlaceholderConfigurer` bean instead of using the default one.
I forked your project and created this [PR](https://github.com/nitin065/gmstest/pull/1/files) to show that the project works without this bean.

**Comment by philwebb** [comment]
I tried to look at the sample but it fails with "class path resource [<removed>] cannot be opened because it does not exist". I guess I need to change the configuration? I can't really tell what the converter is used for so I don't know if it's an ordering issue or something else. If you have instructions on how to replicate the problem I might be able to look further.

**Comment by nitin065** [comment]
@philwebb , in bootstrap.yaml and application.yaml, I removed my personal information and kept the placeholder as `<removed>`, you will need to replace them.

> Hi @nitin065, could you tell me more about why you need to create a `PropertySourcesPlaceholderConfigurer` bean instead of using the default one. 

@JoeWang1127 Yes, it works without that bean. But we are using an internal library (developed by another team) and it is configured to set this bean and the `setIgnoreUnresolvablePlaceholders` method call with true.

**Comment by nitin065** [comment]
Did anyone got chance to look further? Thanks in advance for the efforts.

**Comment by elefeint** [comment]
@nitin065 since you have custom configuration that's triggering a path without Spring Cloud GCP's custom converter, the simplest solution is likely for you to define custom converters in the app, [like this](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/955#issuecomment-1048101815).

**Comment by JoeWang1127** [comment]
Close as lack of customer feedback. Please reopen the issue if necessary.

**Comment by mmoayyed** [comment]
Hello, I am using Spring Cloud GCP 4.1.1, with Spring Boot 3.0.3 and I think I may have run into a similar problem. My app config is super simple:

In application.properties:

```properties
spring.config.import=sm://

cas.authn.accept.users=${sm://projects/.../secrets/cas_authn_accept_users}
```

What's happening here is that when the placeholder is resolved, the actual value for the setting is `<ByteString@3f4caee4 size=19 contents="...">`. This is because `PropertySourcesPlaceholdersResolver` in Spring Boot does the following:

```java
protected String resolvePlaceholder(String placeholder) {
        if (this.sources != null) {
            Iterator var2 = this.sources.iterator();

            while(var2.hasNext()) {
                PropertySource<?> source = (PropertySource)var2.next();
                Object value = source.getProperty(placeholder);
                if (value != null) {
                    return String.valueOf(value);
                }
            }
        }

        return null;
 }
```

The result is always converted to a String, which basically turns out to be `ByteString#toString()`. The environment converters are never hit. 

Does this sound like something I should discuss with the Spring Boot project, or is there more to research here? If this is non obvious/trivial to diagnose, I can try to reproduce with a sample app.

**Comment by JoeWang1127** [comment]
Hi @mmoayyed, thanks for your question.

Could you open a new issue and post a sample reproducer? I'll follow up there.

**Comment by stevenenen** [comment]
for anyone still running in to this problem, I found something that works for me:

So, this file adds the necessary converters: /com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerEnvironmentPostProcessor.class

but only when this is enabled: spring.cloud.gcp.secretmanager.enabled
