### ISSUE TITLE
Firestore: No qualifying bean of type 'org.springframework.transaction.TransactionManager' available

### ISSUE THREAD

**Issue by VitorBittencourt** [GoogleCloudPlatform/spring-cloud-gcp#1297]
**Describe the bug**
`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.transaction.TransactionManager' available`

As soon as I upgraded some dependencies the @Transactional annotation stopped working.
Original working versions are:
```xml
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.5.5</version>
```
+
```xml
<groupId>com.google.cloud</groupId>
<artifactId>spring-cloud-gcp-dependencies</artifactId>
<version>2.0.4</version>
```

Tried with some different versions combinations. Latest with:
```xml
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.6.12</version>
```
+
```xml
<groupId>com.google.cloud</groupId>
<artifactId>spring-cloud-gcp-dependencies</artifactId>
<version>3.3.0</version>
```
Since https://github.com/GoogleCloudPlatform/spring-cloud-gcp mentions GCP3.x should be compatible with Spring Boot 2.6.x

**Sample**
Minimum sample can be found here: https://github.com/VitorBittencourt/transaction-error.git
To test, just start the app (I'm using firestore emulator, but same error was first seen in the real thing) and send a
POST request to localhost:8080/foo/save/123

**Comment by elefeint** [comment]
It's a bug in our autoconfiguration. As part of #620, the transaction manager autoconfiguration was removed from the main Firestore autoconfig but was not added to Spring's metadata, so it's not automatically loaded.

As a workaround, you can add this bean in your own configuration:
```
	@Bean
	public ReactiveFirestoreTransactionManager firestoreTransactionManager(
			FirestoreGrpc.FirestoreStub firestoreStub, FirestoreClassMapper classMapper,
			GcpFirestoreProperties gcpFirestoreProperties,
			GcpProjectIdProvider projectIdProvider) {
		String firestoreRootPath = gcpFirestoreProperties.getFirestoreRootPath(projectIdProvider);
		return new ReactiveFirestoreTransactionManager(firestoreStub, firestoreRootPath, classMapper);
	}
```

Thank you for the reproducer sample; it was very helpful.

**Comment by VitorBittencourt** [comment]
And I just confirmed that the workaround works.
Thanks!

**Comment by mpeddada1** [comment]
Excellent, thank you for your confirmation! We will leave this issue open in the meantime.
