### ISSUE TITLE
GcsFileInfo.isDirectory Doesn't Accurately Reflect Resource Type

### ISSUE THREAD

**Issue by fiidim** [GoogleCloudPlatform/spring-cloud-gcp#1298]
**Describe the bug**
`GcsFileInfo.isDirectory` field doesn't accurately reflect whether or not the read file is a directory or not.  It doesn't look like the field is populated in the `BlobInfo`, so the only way to accurately decide whether or not it's a directory is to check for a trailing slash, and a size of 0.   If neither are palatable, then perhaps the field should be removed, or marked as Unsupported.  I'm using `spring-cloud-gcp 3.3.0` which in turn uses `google-cloud-storage 2.6.1`

**Sample**
Here is the `BlobInfo` for the same directory:
```
Blob{bucket=<bucketname>, name=i_am_a_folder/, generation=1665775659838103, size=0, content-type=text/plain, metadata=null}
```
GcsFileInfo Shows:
```
file_remoteFileInfo={"directory":false,"filename":"i_am_a_folder/","link":false,"modified":1665775659881,"permissions":"Use [BlobInfo.getAcl()] to obtain permissions.","remoteDirectory":"<bucketname>","size":0}
```

Here is the `BlobInfo` for the same file:
```
Blob{bucket=<bucketname>, name=i_am_a_file.dat, generation=1665676522889173, size=8036, content-type=application/octet-stream, metadata=null}
```

GcsFileInfo Shows:
```
file_remoteFileInfo={"directory":false,"filename":"i_am_a_file.dat","link":false,"modified":1665676522924,"permissions":"Use [BlobInfo.getAcl()] to obtain permissions.","remoteDirectory":"<bucketname>","size":8036}
```

Am I missing something?

**Comment by elefeint** [comment]
How are you getting `GcsFileInfo` objects -- are you using one of the Spring Integration adapters? Which one?

Could you create a minimal reproducible sample of the issue?

**Comment by fiidim** [comment]
I'm using the samples provided in this repository as a base -> [spring-cloud-gcp-integration-storage-sample](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-samples/spring-cloud-gcp-integration-storage-sample/src/main/java/com/example/GcsSpringIntegrationApplication.java).

The `GcsFileInfo` I pulled from the `MessageHeaders()` from `file_remoteFileInfo`, as well as a breakpoint when the Blob is pulled.

**Comment by fiidim** [comment]
The simplest reproduction is to have a GCS bucket with a folder, and use an `@InboundChannelAdapter` like your example.
```java
    @Bean
    @InboundChannelAdapter(channel = "streamChannel", poller = @Poller(fixedDelay = "5000"))
    public MessageSource<InputStream> streamingAdapter(final Storage gcs) {
    	final GcsStreamingMessageSource adapter =
                new GcsStreamingMessageSource(new GcsRemoteFileTemplate(new GcsSessionFactory(gcs)));
        adapter.setRemoteDirectory(gcsBucketSupplierProperties.getBucket());
        adapter.setFilter(files ->
                Arrays.stream(files)
                        .filter(f -> f.getName().contains(gcsBucketSupplierProperties.getIncomingPath()))
                        .filter(f -> f.getName().endsWith(gcsBucketSupplierProperties.getFileExtension()))
                        .collect(Collectors.toUnmodifiableList())
        );
        return adapter;
    }
```

If you watch the files arrive via the filter, you will see the `isDirectory` flag isn't set.

**Comment by zhumin8** [comment]
Thanks for providing the reproduction steps. I was able to observe the same result with an empty folder. I also did the same test with cloud-storage directly, and results are the same. According to [javadoc here](https://cloud.google.com/java/docs/reference/google-cloud-storage/latest/com.google.cloud.storage.BlobInfo#com_google_cloud_storage_BlobInfo_isDirectory__) there are some limitation on this `isDirectory()` method.

Unfortunately, Spring Cloud GCP needs to be consistent in behavior with the corresponding client library. You could file an issue to the [client library repo](https://github.com/googleapis/java-storage) instead if needed.

**Comment by fiidim** [comment]
Interesting, are we saying this only happens when the bucket folder/directory is empty?

**Comment by blakeli0** [comment]
Hi @fiidim, to answer your question directly, yes we only observed this issue when the folder is empty. Also as @zhumin8 mentioned, this is a limitation on the GCS side, `isDirectory()` method only returns true only if the blob is returned by [Storage#list(String, Storage.BlobListOption...)](https://cloud.google.com/java/docs/reference/google-cloud-storage/latest/com.google.cloud.storage.Storage#com_google_cloud_storage_Storage_list_) when the [Storage.BlobListOption#currentDirectory()](https://cloud.google.com/java/docs/reference/google-cloud-storage/latest/com.google.cloud.storage.Storage.BlobListOption#com_google_cloud_storage_Storage_BlobListOption_currentDirectory__) option is used. 
Closing this issue for now and feel free to reopen if you any additional questions.
