### ISSUE TITLE
Unable to include tag option to SpTemplate.read(..., SpannerReadOptions) 

### ISSUE THREAD

**Issue by jbowmanhn** [GoogleCloudPlatform/spring-cloud-gcp#1306]
**Describe the bug**
Even though options.tag is a ReadQueryUpdateTransactionOption and valid to pass to addQueryOption() and addReadOption() in their respective Spanner{Read,Query}Options definitions, it fails when you pass a valid read option to SpannerTemplate.read.

```
java.lang.IllegalArgumentException: Can't convert com.google.cloud.spring.data.spanner.core.SpannerReadOptions@7c3d17a6 to SpannerQueryOptions 

	at com.google.cloud.spring.data.spanner.core.SpannerReadOptions.toQueryOptions(SpannerReadOptions.java:102)
	at com.google.cloud.spring.data.spanner.core.SpannerTemplate.toQueryOption(SpannerTemplate.java:240)
	at com.google.cloud.spring.data.spanner.core.SpannerTemplate.read(SpannerTemplate.java:208)
	at com.google.cloud.spring.data.spanner.core.SpannerTemplate.read(SpannerTemplate.java:188)
```

I'm pretty sure this fails because the tag isn't a member of Options.ReadAndQueryOption, which is checked in checked [in .toQueryOptions](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/core/SpannerReadOptions.java#L98) even though it implements both Read and Query options.

While I'm here complaining about tags, it'd be great to get transaction options to expose tag support as well.

**Comment by emmileaf** [comment]
@jbowmanhn Thank you for the detailed description of this issue! 

I was able to reproduce the reported behavior using `SpannerTemplate` and an entity with an eagerly loaded interleaved property to invoke the `.toQueryOptions()` check. You are right that it does not support the `ReadQueryUpdateTransactionOption` type, which should also be a valid type as it extends `ReadOption`. Will look into opening a PR for this fix.

For the side note regarding transaction options - Spring Cloud GCP does not currently support this, but you are welcome to open a new issue with the feature request template (just so it's easier to track separately and gauge community interest).

**Comment by jbowmanhn** [comment]
Thanks for throwing together a fix so fast! Do you know if this will be back ported to to 2.0.X, or will it be just slated for the next 3.X release?

**Comment by emmileaf** [comment]
It will just be a part of the next 3.X release.
