### ISSUE TITLE
FirebaseJwtTokenDecoder that implements ReactiveJwtDecoder

### ISSUE THREAD

**Issue by andreasnaess** [GoogleCloudPlatform/spring-cloud-gcp#1321]
I'm working with spring security and trying to implement firebase token verification using spring webflux. I see there is a class FirebaseJwtTokenDecoder that implements JwtDecoder. I was wondering if there a decoder that can be used for token verification with ReactiveJwtDecoder? Or if there is a way to bridge the FirebaseJwtTokenDecoder to some reactive decoder?

**Comment by elefeint** [comment]
You can't reuse it as is, so the starter won't be useful. But this repository's [Firebase Auth autoconfiguration](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/security/FirebaseAuthenticationAutoConfiguration.java) is simply a few tweaks on top of Spring Security OAuth resource server, so you should be able to create the necessary configuration in your app.

Looking at the [reactive oauth server autoconfiguration](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/reactive/ReactiveOAuth2ResourceServerAutoConfiguration.java) and its imports, it needs/creates a bean of type [`ReactiveJwtDecoder`](https://github.com/spring-projects/spring-boot/blob/7e6bc3fdca65f99d5379c22dbdf9a1f68689339e/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/security/oauth2/resource/reactive/ReactiveOAuth2ResourceServerJwkConfiguration.java#L80), not `JwtDecoder`.

You should be able to create a custom bean in your own application of type `ReactiveJwtDecoder` that simply returns a `Mono.just()` from whatever `FirebaseJwtTokenDecoder.decode()` returns. Use `FirebaseAuthenticationAutoConfiguration` as inspiration for what types of beans need to be overridden in the OAuth server -- it is likely fairly similar in the reactive OAuth server.

**Comment by andreasnaess** [comment]
Thanks for the quick reply! I will look into it :)

**Comment by andreasnaess** [comment]
I have one more question here. If I wrap FirebaseJwtTokenDecoder in a separate bean that does the following:
```
override fun decode(token: String): Mono<Jwt> {
        return Mono.just(firebaseAuthenticationJwtDecoder.decode(token))
}
```

Then I risk a blocking call from within FirebaseJwtTokenDecoder when it does a refresh with RestTemplate? Should I subscribe to this mono with the boundedElastic scheduler?
