### ISSUE TITLE
PERMISSION_DENIED when provisioning ConsumerDestination in spring-cloud-gcp-pubsub-stream-binder

### ISSUE THREAD

**Issue by kjussakov** [GoogleCloudPlatform/spring-cloud-gcp#1348]
**Describe the bug**
Spring cloud version: 2021.0.5
Spring Cloud GCP version: 3.4.0

The problem is with this line:
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/e04f755f75c98619c11fde42106cff81e95f1540/spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java#L82

It assumes the account of the pubsub consumer has permissions to fetch the topic details i.e., perform `pubSubAdmin.getTopic()`
In case the account does not have this permission the binding provisioning is stopped with "Failed to create consumer binding" due to io.grpc.StatusRuntimeException: PERMISSION_DENIED: User not authorized to perform this action. The 30 sec retry is of no use in this case.

The use case is as follow:
**Summary**: consume messages from a topic created in another GCP account through Spring cloud stream consumer binding.

**Detailed description**: GCP account 'a' provides a topic (`projects/a/topics/a-topic`) and grands create subscription permission for service account in account b. A subscription is created in GCP account 'b' for the topic `projects/a/topics/a-topic` - the subscription in 'b' is `projects/b/subscriptions/a-topic-sub`
The only permission an account in 'b' needs is consuming from the `projects/b/subscriptions/a-topic-sub` subscription.
But because of the PubSubChannelProvisioner.java#L82 an exception is thrown leaving us with no other option but to grand unnecessary permission from account 'a' to the service account in 'b' used to consume from `projects/b/subscriptions/a-topic-sub`

Note that in the case where an existing subscription is specified using `spring.cloud.stream.gcp.pubsub.bindings.{CONSUMER_NAME}.consumer.subscriptionName` fetching the topic configuration is useless.
It is being used to get the topic name and verify the subscription has the same topic name:
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/e04f755f75c98619c11fde42106cff81e95f1540/spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java#L111

but we already have the topic name defined in `spring.cloud.stream.bindings.{CONSUMER_NAME}.destination` so we can do this check without having to have the response from  `pubSubAdmin.getTopic()`

**Comment by JoeWang1127** [comment]
Hi @kjussakov, thanks for the detailed analysis. I post a demo project [here](https://github.com/JoeWang1127/pubsub-multi-acc-demo). In the project, the `Consumer` pulls messages from a topic owned by another Google account.
The screenshot below shows the 2nd subscription is from another project (i.e., joe-experimental-project). The first subscription is created as a default subscription.
![image](https://user-images.githubusercontent.com/106995533/202758854-c5edb9ae-e777-4ca2-b395-796fa80a7827.png)
The screenshot below shows that the principal only has subscriber permission.
![Screen Shot 2022-11-18 at 11 56 46](https://user-images.githubusercontent.com/106995533/202760066-48b377f0-faf5-4314-a66d-32e52eb02cfb.png)
Please let me know if you have more questions.

**Comment by JoeWang1127** [comment]
Hi @kjussakov, could you post a sample project that reproduce the issue? I can start from there.

**Comment by kjussakov** [comment]
Hi, I think your [demo app](https://github.com/JoeWang1127/pubsub-multi-acc-demo) is perfect example - it is just how you run it.
Can you please try the following steps to reproduce:

0. Make sure your have 2 GCP projects - **spring-cloud-gcp-ci** and **joe-experimental-project**
1. Make sure the topic `projects/spring-cloud-gcp-ci/topics/multi-account-topic` is created in **spring-cloud-gcp-ci**
2. Create a SA in **joe-experimental-project** - `sub-creator-sa`. Make sure it has the following permissions in **joe-experimental-project**:
```
pubsub.subscriptions.create
pubsub.subscriptions.delete
pubsub.subscriptions.get
pubsub.subscriptions.update
```

3. In project **spring-cloud-gcp-ci** grant the `sub-creator-sa` the following permissions which are needed for creating a subscription:
```
pubsub.snapshots.seek
pubsub.subscriptions.consume
pubsub.topics.attachSubscription
```
4. In project  **joe-experimental-project** and using the `sub-creator-sa` account create the subscription `sub-from-another-acc`.
The `sub-from-another-acc` is a subscription in **joe-experimental-project** which points to the topic `projects/spring-cloud-gcp-ci/topics/multi-account-topic` in **spring-cloud-gcp-ci**
5. Create another SA in **joe-experimental-project** - `consumer-sa`. Make sure it has the following permissions in **joe-experimental-project**:
```
pubsub.snapshots.seek
pubsub.subscriptions.consume
```
Note that the `consumer-sa` does not have permission `pubsub.topics.get` on `projects/spring-cloud-gcp-ci/topics/multi-account-topic` and it should not need to.
6. Now deploy and run the [demo app](https://github.com/JoeWang1127/pubsub-multi-acc-demo) using `consumer-sa` in **joe-experimental-project** - this should reproduce the error I am describing.

**Comment by JoeWang1127** [comment]
Hi @kjussakov, from your description, it seems that project spring-cloud-gcp-ci doesn't grant SA `consumer-sa` the permission to subscribe the `multi-account-topic`. In that case, it makes sense that `consumer-sa` can't create a subscription.

**Comment by kjussakov** [comment]
Yes `consumer-sa` can't and should not create any subscriptions - the subscription is there, already created by terraform or any other IaC tool which most real world projects use.
The `consumer-sa` should only consume from the subscription and not being allowed to create new ones on the fly.

**Comment by JoeWang1127** [comment]
Hi @kjussakov, sorry for the late response. 

`cosumer-sa` doesn't have any permission at all from `spring-cloud-gcp-ci`'s perspective, so the PERMISSION_DENIED makes sense.

**Comment by kjussakov** [comment]
Thank you for supporting @JoeWang1127 !
It is either some misunderstanding or I am totally missing something here but in any case we have moved away from using the spring-cloud-gcp-pubsub-stream-binder so I am no longer interested in spending more time on this.
Feel free to close the issue if you're thinking it is not relevant.

**Comment by elefeint** [comment]
@kjussakov Look into `auto-create-resources` property ([refdoc](https://googlecloudplatform.github.io/spring-cloud-gcp/3.4.0/reference/html/index.html#configuration-3)) -- turning it off for your specific streams will prevent all of the provisioning logic to be ignored.

**Comment by Manujsa** [comment]
@kjussakov  @elefeint  As this issue is already fixed by you guys for ConsumerDestination but it seems it still exists for ProducerDestination in latest 5.6.0 version in PubSubChannelProvisioner._ It uselessly enter into ensureTopicExists method and search for  this.pubSubAdmin.getTopic(topicName) while auto-create-resources=false that required additional pubsub.get.topics  permission for SA . 
Current Implementation:
  @Override
  public ProducerDestination provisionProducerDestination(
      String topic, ExtendedProducerProperties<PubSubProducerProperties> properties) {
    ensureTopicExists(topic, properties.getExtension().isAutoCreateResources());

    return new PubSubProducerDestination(topic);
  }
  Required Implementation:
    @Override
  public ProducerDestination provisionProducerDestination(
      String topic, ExtendedProducerProperties<PubSubProducerProperties> properties) {
	  
	   boolean autoCreate = properties.getExtension().isAutoCreateResources();

    // topicName may be either the short or fully-qualified version.
    String topicShortName =
        TopicName.isParsableFrom(topicName) ? TopicName.parse(topicName).getTopic() : topicName;
    if (autoCreate) {
      ensureTopicExists(topicShortName, autoCreate);
    }
    return new PubSubProducerDestination(topic);
  }
  Please fixed it and update us here !
