### ISSUE TITLE
Cloud Datastore transaction failed to commit.

### ISSUE THREAD

**Issue by beunick** [GoogleCloudPlatform/spring-cloud-gcp#1388]
Hello mate,

I have a **Contention Exception ** issue.
I am using GCP DataStore through **spring-cloud-gcp-dependencies** and **spring-cloud-gcp-starter-data-datastore**
I have an entity called "invoice" when I do a GET by ID on that entity I sometime get this error.

**Cloud Datastore transaction failed to commit.; nested exception is com.google.cloud.datastore.DatastoreException: Aborted due to cross-transaction contention. This occurs when multiple transactions attempt to access the same data, requiring Firestore to abort at least one in order to enforce serializability.**

I don't know how to solve this issue. 
Please advise. 
Thanks

**Comment by JoeWang1127** [comment]
Hi @beunick, could you post a sample that reproduces the error in a repo?

**Comment by meltsufin** [comment]
@beunick It doesn't appear to be an issue Spring Cloud GCP, but rather the behavior of Datastore/Firestore. See [documentation](https://cloud.google.com/firestore/docs/transaction-data-contention#transactions_and_data_contention). If you still believe there is something Spring Cloud GCP is doing to cause this, and able to provide a reproducer, please re-open.
