### ISSUE TITLE
Align spring.cloud.gcp.<service-name>.emulator properties

### ISSUE THREAD

**Issue by bennetelli** [GoogleCloudPlatform/spring-cloud-gcp#1391]
**Is your feature request related to a problem? Please describe.**
Right now, the emulator property for the PubSub host is: spring.cloud.gcp.pubsub.emulator-host
whereas the one for Datastore is: "spring.cloud.gcp.datastore.host". 
This property was: "spring.cloud.gcp.datastore.emulator-host" before, but since it's deprecated and should be replaced by: 
"spring.cloud.gcp.datastore.host", 
the emulator properties are drifting away between (at least) these two services. Maybe this even happened in more than these two services. I did not check this so far.

**Describe the solution you'd like**
As a user of spring-cloud-gcp, I would expect to just replace datastore with pubsub only.

**Comment by bennetelli** [comment]
@JoeWang1127 tbh I don't have a strong opinion about which property to change, as long as it's aligned :-)

**Comment by JoeWang1127** [comment]
Cool, we'll look into that.

**Comment by meltsufin** [comment]
I believe #159 already covers this feature request. So, I'm closing in favor of that one.
