### ISSUE TITLE
Missing information about Spring Cloud GCP 3.4.1

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#1399]
I noticed that Spring Cloud GCP 3.4.1 was released to Maven Central last week: https://search.maven.org/artifact/com.google.cloud/spring-cloud-gcp-dependencies

However, there is no mention of version 3.4.1 on https://github.com/GoogleCloudPlatform/spring-cloud-gcp, which still lists 3.4.0 as the current version.

Version 3.4.1 is also not mentioned in the [releases](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/releases), [tags](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tags) or [milestones](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/milestones) overviews.

Where can I find more information about version 3.4.1?

**Comment by meltsufin** [comment]
We're still completing the post-release tasks. We should have everything updated soon.
