### ISSUE TITLE
Using gcp pubsub in xml based java spring application.

### ISSUE THREAD

**Issue by shaileshexp** [GoogleCloudPlatform/spring-cloud-gcp#1400]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is and what version of Spring Cloud you are using. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by shaileshexp** [comment]
I am using activemq right now for the messaging queue and have requirement to move to gcppubsub as already aour application running in gcp cloud. I have already used the gcp pubsub programmatically in java for the pubsub.
But now i want all the responsibility for thread creation or any failure of subscriber or publisher to be though the gcp pubsub advanced library only. I want if i can get ant code base or repo where i can follow and use it.
Our application is old xml based spring application and thats that challenge i am facing to use the pubsubtemplate and all for the advance version of pubsub. i just wanted to get rid off controlling all the failures through java.

**Comment by shaileshexp** [comment]
In sort i need codebase which i referred to use the gcp pubsub in spring xml based configuration.
Need to use the 3rd party for the publisher and subscriber creation.

**Comment by meltsufin** [comment]
The project is designed to support Spring Boot and all of the samples are using Spring Boot. You can, however, wire up all of the required beans in Spring XML, but we don't have examples of that.

**Comment by ss185996** [comment]
As I can see that springbok having the @enableautoconfiguration taken care all the things of creating bean and initializing it.
How do I use the similar way of enableautoconfiguration function  for our application in xml based spring?

My simple requirement to use the pubsub in xml based spring project where developer has not do many things like  setup and configuration related to pubsub as sprinboot application had. Only minimal changes need to be done ,please suggest which approach I need to follow?
