### ISSUE TITLE
How to set GOOGLE_APPLICATION_CREDENTIALS before bean defaultGcpProjectIdProvider in xml created for pubsub

### ISSUE THREAD

**Issue by shaileshexp** [GoogleCloudPlatform/spring-cloud-gcp#1402]
I am using the pusub in our spring xml based application and defined the bean for pubsubtemplate to use in application-context.xml.
<bean id="pubsubTemplate" class="com.google.cloud.spring.pubsub.core.PubSubTemplate">
		<constructor-arg ref="pubSubPublisherTemplate"/>
		<constructor-arg  ref="pubSubSubscriberTemplate"/>
	</bean>

	<bean id="pubSubPublisherTemplate" class="com.google.cloud.spring.pubsub.core.publisher.PubSubPublisherTemplate">
	<constructor-arg ref="defaultPublisherFactory"/>
	</bean>
	<bean id="pubSubSubscriberTemplate" class="com.google.cloud.spring.pubsub.core.subscriber.PubSubSubscriberTemplate">
		<constructor-arg ref="defaultSubscriberFactory"/>
	</bean>

	<bean id="defaultPublisherFactory" class="com.google.cloud.spring.pubsub.support.DefaultPublisherFactory">
		<constructor-arg ref="defaultGcpProjectIdProvider"/>
	</bean>

	<bean id="defaultSubscriberFactory" class="com.google.cloud.spring.pubsub.support.DefaultSubscriberFactory">
		<constructor-arg ref="defaultGcpProjectIdProvider"/>
	</bean>

	<bean id="defaultGcpProjectIdProvider" class="com.google.cloud.spring.core.DefaultGcpProjectIdProvider"/>

As during the bean creation i need to provide the GOOGLE_APPLICATION_CREDENTIALS.
Our application running in GCP cloud which have different GCP projrct id and the pubsub topic created in different project ID.
How to set he GOOGLE_APPLICATION_CREDENTIALS for the pubsub projectID before the spring start to create the bean defaultGcpProjectIdProvider.

**Comment by meltsufin** [comment]
`GOOGLE_APPLICATION_CREDENTIALS` is an environment variable that can be set before the application starts, depending on the exact environment the application is running in. You can also use an explicit `CredentialsProvider` when configuration `DefaultPublisherFactory` to point to the credentials file.

**Comment by ss185996** [comment]
Can you please help me all the changes that I need to do  if I go with the manual bean definition?
As Project id, GCP credential etc need to be define somewhere before these bean creation.

**Comment by meltsufin** [comment]
Please try StackOverflow or contact [Cloud Support](https://cloud.google.com/support-hub).
