### ISSUE TITLE
[BUG] Spring boot 3.0.0 spring.factories has been removed

### ISSUE THREAD

**Issue by ivan909020** [GoogleCloudPlatform/spring-cloud-gcp#1408]
**Describe the bug**
Spring Boot 3.0.0 "spring.factories" has been removed. The automatic import of autoconfigurations is broken.

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/resources/META-INF/spring.factories

**To Reproduce**
Run the app with Spring Boot 3.0.0 and autoconfiguration will not work. Only explicit import using @ImportAutoConfiguration is working.

**Expected behavior**
The app will run without explicit @ImportAutoConfiguration({ list of autoconfiguration classes }).

**Comment by meltsufin** [comment]
The upgrade to Spring Boot 3.0 is ongoing: #1287.
cc/ @JoeWang1127
