### ISSUE TITLE
Docs: To Host or Not To Host?

### ISSUE THREAD

**Issue by ttomsu** [GoogleCloudPlatform/spring-cloud-gcp#141]
That is the question :skull: 

The Spring team has mentioned that it's better for them if the reference docs ("Reference Doc" links in https://spring.io/projects/spring-cloud-gcp#learn) contain links to documentation we can control, because it's easier for us to update our own content than for them to republish.

So.. where could we do that? One easy answer is GitHub Pages - it's all in here anyway, we might as well use it. One big requirement would be to have each docset versioned, preferably with a widget control like https://googleapis.dev/java/spring-cloud-gcp/1.2.6.RELEASE/index.html but having the version in the URL like Spring does it now is fine too (example: https://docs.spring.io/spring-cloud-gcp/docs/1.2.6.RELEASE/reference/html/)

**Comment by meltsufin** [comment]
Let's give GH Pages a try. I think we can worry about the widget later.

**Comment by ttomsu** [comment]
Done: https://googlecloudplatform.github.io/spring-cloud-gcp/
