### ISSUE TITLE
Dependency convergence error on importing spring-cloud-gcp-dependencies pom

### ISSUE THREAD

**Issue by LeeU1911** [GoogleCloudPlatform/spring-cloud-gcp#1414]
**Describe the bug**
Upon importing `spring-cloud-gcp-dependencies` pom in a multi-module maven project, `maven-enforcer-plugin` throws "Dependency convergence" error as following:
```
[WARNING] 
Dependency convergence error for org.springframework:spring-aop:jar:5.3.23:compile paths to dependency are:
+-org.example:child1:jar:1.0-SNAPSHOT
  +-com.google.cloud:spring-cloud-gcp-starter-trace:jar:3.4.1:compile
    +-org.springframework.cloud:spring-cloud-starter-sleuth:jar:3.1.5:compile
      +-org.springframework.boot:spring-boot-starter-aop:jar:2.6.13:compile
        +-org.springframework:spring-aop:jar:5.3.23:compile
and
+-org.example:child1:jar:1.0-SNAPSHOT
  +-com.google.cloud:spring-cloud-gcp-starter-trace:jar:3.4.1:compile
    +-org.springframework.cloud:spring-cloud-sleuth-brave:jar:3.1.5:compile
      +-io.zipkin.brave:brave-instrumentation-spring-rabbit:jar:5.13.9:compile
        +-org.springframework:spring-aop:jar:5.3.2:provided

[WARNING] 
Dependency convergence error for org.checkerframework:checker-qual:jar:3.28.0:compile paths to dependency are:
+-org.example:child1:jar:1.0-SNAPSHOT
  +-com.google.cloud:spring-cloud-gcp-starter-trace:jar:3.4.1:compile
    +-io.zipkin.gcp:zipkin-sender-stackdriver:jar:1.0.4:compile
      +-io.zipkin.gcp:zipkin-translation-stackdriver:jar:1.0.4:compile
        +-com.google.api.grpc:proto-google-cloud-trace-v2:jar:2.7.0:compile
          +-org.checkerframework:checker-qual:jar:3.28.0:compile
and
+-org.example:child1:jar:1.0-SNAPSHOT
  +-com.google.cloud:spring-cloud-gcp-starter-trace:jar:3.4.1:compile
    +-io.zipkin.gcp:zipkin-sender-stackdriver:jar:1.0.4:compile
      +-com.google.api.grpc:grpc-google-cloud-trace-v2:jar:2.7.0:compile
        +-org.checkerframework:checker-qual:jar:3.28.0:compile
and
+-org.example:child1:jar:1.0-SNAPSHOT
  +-com.google.cloud:spring-cloud-gcp-starter-trace:jar:3.4.1:compile
    +-com.google.cloud:google-cloud-core-grpc:jar:2.9.0:compile
      +-com.google.guava:guava:jar:31.1-jre:compile
        +-org.checkerframework:checker-qual:jar:3.12.0:compile

<Omitted further similar entries>
```

This wasn't the case for our project previously when `spring-cloud-gcp` was bundled with Spring Cloud and we imported `spring-cloud-dependencies` pom instead (See [migration guide](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#migration-guide-from-spring-framework-on-google-cloud-1-x-to-2-x))

After executing the migrating step of replacing `spring-cloud-dependencies` pom with `spring-cloud-gcp-dependencies` one, we were hit with this issue.

**Sample**
Simply check out this minimal reproducible repository: https://github.com/LeeU1911/spring-cloud-gcp-starter-dependency-convergence/blob/main/pom.xml and run `mvn install`

Will someone be able to shed some lights on why and how to fix it correctly? 

Thank you!

**Comment by meltsufin** [comment]
Can you tried adding the `spring-cloud-dependencies` as well?

```xml
<dependencyManagement>
  <dependencies>
...
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-dependencies</artifactId>
      <version>${spring-cloud.version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```

**Comment by LeeU1911** [comment]
@meltsufin Yes, it was working with `spring-cloud-dependencies` included (as it was there originally before the migration). As the [migration guide](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#migration-guide-from-spring-framework-on-google-cloud-1-x-to-2-x) instructed to remove it (see the after `pom.xml`), I wonder if it should have mentioned something about this issue, or is it very specific to my setup?

**Comment by meltsufin** [comment]
The migration guide in the past actually recommended to include the Spring Cloud BOM, but was [modified](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1068/files/51d4f39e48da3414aabdc1d05f2e0f3dd186506b#r848542143) to omit. In any case, the project does not  test for or target dependency convergence at the moment. This could be a feature request.

**Comment by suztomo** [comment]
It's too many dependencies in Spring. I don't think it's feasible to have dependency convergence.
