### ISSUE TITLE
Support `spring.config.import` for Secret Manager

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/spring-cloud-gcp#149]
Spring Boot 2.4 introduced the ability to import configuration properties from sources other than `application.properties`, using the `spring.config.import` property.

See "Supporting Additional Locations" [here](https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4).
Also see: `ConfigDataLocationResolver` and `ConfigDataLoader`.

This might be a useful feature for Secrets Manager in addition to our bootstrap properties source support.

WIP PR: #145.
Additional context: #41.

**Comment by meltsufin** [comment]
cc/ @viniciusccarvalho

**Comment by elefeint** [comment]
The release unblocked this features' development, but we have not been able to get to doing it.

**Comment by raszkiewicz** [comment]
OK. I  have added working solution to the #955  ticket

**Comment by meltsufin** [comment]
Thanks! We'll still keep this open for the "proper" fix.

**Comment by RamonaMaria** [comment]
is this bug solved in the last release? what dependencies and versions should I use so that I don't have it anymore?
thanks
