### ISSUE TITLE
`enable-iam-auth` property is ineffective for R2DBC

### ISSUE THREAD

**Issue by vy** [GoogleCloudPlatform/spring-cloud-gcp#1513]
Using Spring Cloud GCP 3.4.2, connecting to an IAM-enabled Google Cloud SQL instance over R2DBC does not work out of the box.

Using the following `application.yml`:

```yaml
spring:
  cloud:
    gcp:
      project-id: pro-tetris-f2f
      sql:
        database-name: tetris
        instance-connection-name: pro-tetris-f2f:europe-west4:tetris-csql-i
        enable-iam-auth: true
  r2dbc:
    username: tetris-sa@pro-tetris-f2f.iam
```

results in the following failure:

```
Error: SEVERITY_LOCALIZED=FATAL, SEVERITY_NON_LOCALIZED=FATAL, CODE=28000, MESSAGE=Cloud SQL IAM service account authentication failed for user "tetris-sa@pro-tetris-f2f.iam", FILE=auth.c, LINE=345, ROUTINE=auth_failed
```

It works as expected once `ENABLE_IAM_AUTH=true` is added to the R2DBC URL by means of adding

1. either `spring.r2dbc.properties.ENABLE_IAM_AUTH: true` property
2. or `spring.r2dbc.url: r2dbc:gcp:postgres://pro-tetris-f2f:europe-west4:tetris-csql-i/tetris` property

We expected this flag to be automatically set due to `spring.cloud.gcp.sql.enable-iam-auth: true` property.

**Comment by diegomarquezp** [comment]
Hi @vy, thanks for reporting this. The [documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/3.4.0/reference/html/index.html#cloud-sql-iam-database-authentication) suggests using `spring.cloud.gcp.sql.enableIamAuth`. Could you please confirm it also occurs when using `enableIamAuth` instead of `enable-iam-auth`?

**Comment by diegomarquezp** [comment]
@vy please disregard as this option should also be supported in snake-case. I will replicate and confirm

**Comment by vy** [comment]
@diegomarquezp, I don't think the property naming style (camel case, snake case, etc.) matters here thanks to [the relaxed binding in Spring Boot](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.relaxed-binding). Further, there it has been stated that

> You should always refer to property names in the placeholder using their canonical form (kebab-case using only lowercase letters).

Hence, kebab-case using lowercase letters should be supported anyway.

**Comment by diegomarquezp** [comment]
@vy, would you mind sharing a reproducible example? I'm afraid I can't proceed with replication at the moment. 
Also, please consider reaching out to our [support hub](https://cloud.google.com/support-hub) if you have a support plan for faster response times

**Comment by vy** [comment]
@diegomarquezp, I will share the project files for a minimal reproduction example below.

`pom.xml`:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.0.2</version>
  </parent>

  <groupId>com.bol.cloud.google</groupId>
  <artifactId>spring-cloud-gcp-issue-1513-demo</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>spring-cloud-gcp-issue-1513-demo</name>
  <description>Spring Cloud GCP issue #1513 reproduction</description>

  <properties>
    <java.version>17</java.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>spring-cloud-gcp-dependencies</artifactId>
        <version>3.4.2</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>spring-cloud-gcp-starter-sql-postgres-r2dbc</artifactId>
    </dependency>
  </dependencies>

</project>

```

`SpringCloudGcpIssue1513DemoApplication.java`:

```
package com.bol.cloud.google.springcloudgcpissue1513demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class SpringCloudGcpIssue1513DemoApplication {

	public static void main(String[] args) {
		SpringApplication.run(SpringCloudGcpIssue1513DemoApplication.class, args);
	}

}
```

`ConnectionCheck.java`:

```
package com.bol.cloud.google.springcloudgcpissue1513demo;

import io.r2dbc.spi.ConnectionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.context.event.ApplicationStartedEvent;
import org.springframework.context.ApplicationListener;
import org.springframework.stereotype.Component;
import reactor.core.publisher.Mono;

import java.time.Duration;

@Component
public class ConnectionCheck implements ApplicationListener<ApplicationStartedEvent> {

    @Autowired
    private ConnectionFactory connectionFactory;

    @Override
    public void onApplicationEvent(ApplicationStartedEvent ignored) {
        Mono
                .from(connectionFactory.create())
                .flatMapMany(connection -> connection.createStatement("SELECT 1").execute())
                .flatMap(result -> result.map((row, meta) -> row.get(0, Integer.class)))
                .doOnNext(updatedRowCount -> System.out.format("row: %d%n", updatedRowCount))
                .then()
                .block(Duration.ofSeconds(5));
    }

}
```

`application.yml`:

```
spring:
  r2dbc:
    username: "vyazici@bol.com"
    properties:
      ENABLE_IAM_AUTH: true
  cloud:
    gcp:
      project-id: "bolcom-stg-axlexamplecloud-d2c"
      sql:
        database-name: "examplecloud"
        instance-connection-name: "bolcom-stg-axlexamplecloud-d2c:europe-west4:examplecloud-csql-i"
        enable-iam-auth: true
```

The project successfully queries the Cloud SQL instance over IAM using the above `application.yml` configuration. But...

When I remove `r2dbc.properties.ENABLE_IAM_AUTH: true` property, I get the following error:

```
Caused by: java.lang.IllegalArgumentException: Password must not be null
	at io.r2dbc.postgresql.util.Assert.requireNonNull(Assert.java:71) ~[r2dbc-postgresql-0.8.13.RELEASE.jar:0.8.13.RELEASE]
	at io.r2dbc.postgresql.PostgresqlConnectionFactory.getAuthenticationHandler(PostgresqlConnectionFactory.java:242) ~[r2dbc-postgresql-0.8.13.RELEASE.jar:0.8.13.RELEASE]
	at io.r2dbc.postgresql.client.StartupMessageFlow.lambda$exchange$0(StartupMessageFlow.java:76) ~[r2dbc-postgresql-0.8.13.RELEASE.jar:0.8.13.RELEASE]
	at reactor.core.publisher.FluxHandle$HandleConditionalSubscriber.onNext(FluxHandle.java:326) ~[reactor-core-3.5.2.jar:3.5.2]
	... 43 common frames omitted
```

Then I add `spring.r2dbc.password: RequiredButNotUsed` property, this time I get an authentication error:

```
io.r2dbc.postgresql.ExceptionFactory$PostgresqlAuthenticationFailure: Cloud SQL IAM user authentication failed for user "vyazici@bol.com"
	at io.r2dbc.postgresql.ExceptionFactory.createException(ExceptionFactory.java:75) ~[r2dbc-postgresql-0.8.13.RELEASE.jar:0.8.13.RELEASE]
        ...
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:139) ~[reactor-core-3.5.2.jar:3.5.2]
		at reactor.core.publisher.Mono.block(Mono.java:1734) ~[reactor-core-3.5.2.jar:3.5.2]
		at com.bol.cloud.google.springcloudgcpissue1513demo.ConnectionCheck.onApplicationEvent(ConnectionCheck.java:26) ~[classes/:na]
		at com.bol.cloud.google.springcloudgcpissue1513demo.ConnectionCheck.onApplicationEvent(ConnectionCheck.java:12) ~[classes/:na]
               ...
```

Yes the error message is different than what I reported initially. It has changed after appending `--update-adc` to `gcloud auth login`. Nevertheless, my point still stands: without adding either `spring.r2dbc.properties.ENABLE_IAM_AUTH: true` or `spring.r2dbc.url`, IAM-based authentication doesn't work.

**Comment by meltsufin** [comment]
I think it's a bug. Compare the URL creation between [JDBC](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/DefaultCloudSqlJdbcInfoProvider.java#L50-L66) and [R2DBC](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/sql/R2dbcCloudSqlEnvironmentPostProcessor.java#L73-L84).
