### ISSUE TITLE
SecretManagerTemplate bean no longer auto-configured by default in 4.0.0

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#1551]
After upgrading Spring Cloud GCP from 3.4.3 to 4.0.0 a test started failing that was checking for the presence of a `SecretManagerTemplate` bean when `spring.cloud.gcp.secretmanager.enabled` is set to `true`.

In Spring Cloud GCP 3.4.3 this bean was created by the (deprecated) `com.google.cloud.spring.autoconfigure.secretmanager.GcpSecretManagerBootstrapConfiguration` class, but this class was removed in 4.0.0.

According to the [Spring Cloud GCP Secret Manager documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#secret-manager) a `SecretManagerTemplate` bean should still be created automatically. 

It looks like `com.google.cloud.spring.autoconfigure.secretmanager.SecretManagerConfigDataLocationResolver#registerSecretManagerBeans` is now the only method in Spring Cloud GCP which creates and registers a `SecretManagerTemplate` bean, but I believe that only comes into play when you have configuration property values prefixed with `sm://`, right?

**Comment by breun** [comment]
I've created a small project with a test that reproduces this issue: https://github.com/breun/secretmanagertemplate-test

**Comment by rotilho** [comment]
Even with `sm://` the secret manager doesn't lookup the secret.

**Comment by 7a8e709c** [comment]
@rotilho adding `spring.config.import=sm://` to property file helps me.

**Comment by rotilho** [comment]
@7a8e709c thanks, that definitely works!

**Comment by JoeWang1127** [comment]
Hi @breun, adding `spring.config.import=sm://` to the `application.properties` file should fix the issue.

**Comment by meltsufin** [comment]
The `SecretManagerTemplate` should always be provided by the starter. I'm not sure if the same bean can be re-used for config properties, but we should try. Adding `spring.config.import=sm://` should not be required.

**Comment by breun** [comment]
Although the [Secret Manager documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#secret-manager) doesn't mention it, I found that [the Secret Manager entry in the migration guide](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#secret-manager-2) does mention that `spring.config.import=sm://` should be set to enable an application to fetch a secret from Secret Manager. But it would be nice if this was indeed not necessary to get a `SecretManagerTemplate` bean auto-configured.

**Comment by ablx** [comment]
Workaround for application.yml
```yaml
spring:
  config:
    import: "sm://"
```
