### ISSUE TITLE
Native compile failing with spring cloud GCP 4 and spring boot 3

### ISSUE THREAD

**Issue by jmalvarezf-lmes** [GoogleCloudPlatform/spring-cloud-gcp#1559]
Hi,

I was trying to do a very simple example with pubsub and spring boot 3 with native support, but I got into this when compiling. If I execute this:

`mvn -Pnative spring-boot:build-image`

I get this
```
2023-02-01T13:31:54.082+01:00  INFO 56031 --- [           main] e.l.n.NativeServiceDemoApplication       : No active profile set, falling back to 1 default profile: "default"
Exception in thread "main" org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException: Constructor binding in a native image requires compilation with -parameters but the following classes were compiled without it:
	com.google.cloud.spring.core.Credentials
	at org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar.registerHints(BindableRuntimeHintsRegistrar.java:87)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBeanFactoryInitializationAotProcessor$ConfigurationPropertiesReflectionHintsContribution.applyTo(ConfigurationPropertiesBeanFactoryInitializationAotProcessor.java:70)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:76)
```

I'm using maven 3.6.3, GraalVM CE 22.3.1 and spring boot 3. This is my pom.xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.2</version>
		<relativePath/> 
	</parent>
	<groupId>es.leroymerlin</groupId>
	<artifactId>native-service-demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>native-service-demo</name>
	<description>Native Java service demo</description>
	<properties>
		<java.version>17</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.google.cloud</groupId>
				<artifactId>spring-cloud-gcp-dependencies</artifactId>
				<version>4.0.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<plugins>
			<plugin>
				<groupId>org.graalvm.buildtools</groupId>
				<artifactId>native-maven-plugin</artifactId>
				<configuration>
					<jvmArgs>
						<arg>Xmx8g</arg>
						<arg>Xms8g</arg>
					</jvmArgs>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<excludes>
						<exclude>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</exclude>
					</excludes>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

Any tips on how to solve this? Is it a bug?

Thank you!

**Comment by mpeddada1** [comment]
Hey @jmalvarezf-lmes thanks for reporting this issue! Please note that we don't yet have native image support in spring-cloud-gcp. Here is the umbrella issue to track this: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1565

**Comment by jmalvarezf-lmes** [comment]
Ok, its clear, thanks for the clarification!

**Comment by mpeddada1** [comment]
Yes, let's close this as a dup of #1565, thank you!

**Comment by gomezmejiam** [comment]
> Hi,
> 
> I was trying to do a very simple example with pubsub and spring boot 3 with native support, but I got into this when compiling. If I execute this:
> 
> `mvn -Pnative spring-boot:build-image`
> 
> I get this
> 
> ```
> 2023-02-01T13:31:54.082+01:00  INFO 56031 --- [           main] e.l.n.NativeServiceDemoApplication       : No active profile set, falling back to 1 default profile: "default"
> Exception in thread "main" org.springframework.boot.context.properties.bind.MissingParametersCompilerArgumentException: Constructor binding in a native image requires compilation with -parameters but the following classes were compiled without it:
> 	com.google.cloud.spring.core.Credentials
> 	at org.springframework.boot.context.properties.bind.BindableRuntimeHintsRegistrar.registerHints(BindableRuntimeHintsRegistrar.java:87)
> 	at org.springframework.boot.context.properties.ConfigurationPropertiesBeanFactoryInitializationAotProcessor$ConfigurationPropertiesReflectionHintsContribution.applyTo(ConfigurationPropertiesBeanFactoryInitializationAotProcessor.java:70)
> 	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.applyTo(BeanFactoryInitializationAotContributions.java:78)
> 	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
> 	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
> 	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
> 	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
> 	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
> 	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
> 	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
> 	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:76)
> ```
> 
> I'm using maven 3.6.3, GraalVM CE 22.3.1 and spring boot 3. This is my pom.xml:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
> 	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
> 	<modelVersion>4.0.0</modelVersion>
> 	<parent>
> 		<groupId>org.springframework.boot</groupId>
> 		<artifactId>spring-boot-starter-parent</artifactId>
> 		<version>3.0.2</version>
> 		<relativePath/> 
> 	</parent>
> 	<groupId>es.leroymerlin</groupId>
> 	<artifactId>native-service-demo</artifactId>
> 	<version>0.0.1-SNAPSHOT</version>
> 	<name>native-service-demo</name>
> 	<description>Native Java service demo</description>
> 	<properties>
> 		<java.version>17</java.version>
> 	</properties>
> 	<dependencies>
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-web</artifactId>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.projectlombok</groupId>
> 			<artifactId>lombok</artifactId>
> 			<optional>true</optional>
> 		</dependency>
> 		<dependency>
> 			<groupId>com.google.cloud</groupId>
> 			<artifactId>spring-cloud-gcp-starter</artifactId>
> 		</dependency>
> 		<dependency>
> 			<groupId>com.google.cloud</groupId>
> 			<artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-test</artifactId>
> 			<scope>test</scope>
> 		</dependency>
> 	</dependencies>
> 	<dependencyManagement>
> 		<dependencies>
> 			<dependency>
> 				<groupId>com.google.cloud</groupId>
> 				<artifactId>spring-cloud-gcp-dependencies</artifactId>
> 				<version>4.0.0</version>
> 				<type>pom</type>
> 				<scope>import</scope>
> 			</dependency>
> 		</dependencies>
> 	</dependencyManagement>
> 	<build>
> 		<plugins>
> 			<plugin>
> 				<groupId>org.graalvm.buildtools</groupId>
> 				<artifactId>native-maven-plugin</artifactId>
> 				<configuration>
> 					<jvmArgs>
> 						<arg>Xmx8g</arg>
> 						<arg>Xms8g</arg>
> 					</jvmArgs>
> 				</configuration>
> 			</plugin>
> 			<plugin>
> 				<groupId>org.springframework.boot</groupId>
> 				<artifactId>spring-boot-maven-plugin</artifactId>
> 				<configuration>
> 					<excludes>
> 						<exclude>
> 							<groupId>org.projectlombok</groupId>
> 							<artifactId>lombok</artifactId>
> 						</exclude>
> 					</excludes>
> 				</configuration>
> 			</plugin>
> 		</plugins>
> 	</build>
> </project>
> ```
> 
> Any tips on how to solve this? Is it a bug?
> 
> Thank you!

Oye tienes algún blog o anotaciones con respecto de spring nativo, estoy tratando de hacer cosas con esta tecnologia a ratos me bloqueo

**Comment by lgrousset** [comment]
`com.google.cloud.spring.core.Credentials` contructor is : 

`public Credentials(String... defaultScopes)`

however setting scope in properties does **not** do the job

`spring.cloud.gcp.credentials.scopes=DEFAULT_SCOPES`
