### ISSUE TITLE
gcip Claim in jwt not valid JSON after upgrading to Spring Boot 3 and 4.0.0

### ISSUE THREAD

**Issue by YColca** [GoogleCloudPlatform/spring-cloud-gcp#1573]
**Describe the bug**
Setup: 

- Spring Boot Version 3.0.2
- Spring Cloud Version 2022.01
- Spring Cloud GCP Version 4.0.0
- spring-cloud-gcp-security-iap-sample with minimal changes for the endpoint in the Controller:

```java
@GetMapping("/topsecret")
    public String secured() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication != null && authentication.getPrincipal() instanceof Jwt jwt) {
            return jwt.getClaimAsString("gcip");
        } else {
            return "Something went wrong; authentication is not provided by IAP/JWT.\n";
        }
    }
```
This returned before valid JSON. Now it returns **fields without double quotes and "=" signs instead of ":"**.

**Sample**
The endpoint returns something like:
{customClaim=abc, auth_time=1675668648, email=xxxx@xxxx.com, email_verified=true, firebase={identities={email=[xxxx@xxxx.com]}, sign_in_provider=password, tenant=xxxx}, sub=xxxx, user_id=xxxx}

Expecting (valid JSON in Json Web Token):
{"customClaim":"abc", "auth_time":1675668648, "email":"xxxx@xxxx.com", "email_verified":true, "firebase":{"identities":{"email":["xxxx@xxxx.com"]}, "sign_in_provider":"password", "tenant":"xxxx"}, "sub":"xxxx", "user_id":"xxxx"}

**Comment by lqiu96** [comment]
Taking a look. Let me try and reproduce this with the spring-cloud-gcp-security-iap-sample. Did you change anything with the code or dependencies that may have caused the behavior change? i.e. Spring GCP version bump from 3.x to 4.x?

**Comment by YColca** [comment]
I created a new project to reproduce the problem. You have to set `SERVICE_ACCOUNT` & `PROJECT_ID` env vars for appengineDeploy gradle task to deploy it.
https://github.com/YColca/iap-bug

My Google Cloud setup: IAP enabled for AppEngine with external Identities (Identity Platform). In the Identity Platform I enabled Multi-Tenancy.

**Comment by JoeWang1127** [comment]
I've created a relevant [issue](https://github.com/spring-projects/spring-boot/issues/34164) to Spring Boot.

**Comment by JoeWang1127** [comment]
Follow-up, created an [issue](https://github.com/spring-projects/spring-security/issues/12659) from Spring Security.

**Comment by meltsufin** [comment]
`Jwt` is a class in Spring Security and `getClaimAsString` is not documented to output JSON. Closing.
