### ISSUE TITLE
Update Secret Manager documentation

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#1588]
**Describe the bug**
As far as I understand Spring Cloud GCP 4 no longer uses the bootstrap phase for loading configuration (`SecretManagerPropertySourceLocator` was removed in 4.1.0), but the [Secret Manager documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/4.1.0/reference/html/index.html#secret-manager) and [Secret Manager Property Source section](https://googlecloudplatform.github.io/spring-cloud-gcp/4.1.0/reference/html/index.html#secret-manager-property-source) still say you can inject a bootstrap property source.

**Comment by JoeWang1127** [comment]
Hi @breun, thanks for reporting. I'll fix the docs.
