### ISSUE TITLE
BigQueryJsonDataWriter does not pass BigQueryWriteClient for build the JsonStreamWriter

### ISSUE THREAD

**Issue by circlee** [GoogleCloudPlatform/spring-cloud-gcp#1594]
Hi all.

I don't know if this is a problem.
However, there are inconveniences when using BigQueryJsonDataWriter, so I report it.

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-bigquery/src/main/java/com/google/cloud/spring/bigquery/core/BigQueryJsonDataWriter.java#L80

```
streamWriter =
        JsonStreamWriter.newBuilder(writeStream.getName(), writeStream.getTableSchema()).build();
```
in build for JsonStreamWriter, it does not pass BigQueryWriteClient into JsonStreamWriter

so , i need additional credential provider setting for JsonStreamWriter.
but BigQueryWriteClient seems already have credential provider by spring setting.

I think , it should be like below
```
streamWriter =
        JsonStreamWriter.newBuilder(writeStream.getName(), writeStream.getTableSchema(), bigQueryWriteClient).build();
```

Please check my little comment.

thanks

**Comment by mpeddada1** [comment]
@circlee Thanks for creating this ticket! To help us understand the issue better, would you be able to provide a log of the error message you are seeing? Or perhaps a reproducer of how you currently have this integration set up?

cc/ @prash-mi

**Comment by blakeli0** [comment]
Closing as no response from reporter.
