### ISSUE TITLE
Is secretmanager not supported for spring boot `2.1.8.RELEASE`?

### ISSUE THREAD

**Issue by gaurav517** [GoogleCloudPlatform/spring-cloud-gcp#1603]
I tried to use following in a spring boot 2.1.8.RELEASE project:
```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>spring-cloud-gcp-dependencies</artifactId>
                <version>2.0.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
<dependencies>
  <dependency>
          <groupId>com.google.cloud</groupId>
          <artifactId>spring-cloud-gcp-starter-secretmanager</artifactId>
    </dependency>
</dependencies>
```
but its failing with: 
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bootstrapImportSelectorConfiguration': Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/ConfigurationPropertiesBean
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
```
What would be the recommended way to use secretmanager for spring boot `2.1.8.RELEASE`? Thanks.

**Comment by mpeddada1** [comment]
@gaurav517 According to the release notes, [Spring Cloud GCP 2.0.x included support for Spring Boot 2.4 and 2.5](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/releases/tag/v2.0.0). 
However, please note that version 2.x for spring cloud gcp is quite old and [unsupported](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/README.adoc#compatibility-with-spring-project-versions). Please consider using versions 3.x or 4.x.

**Comment by gaurav517** [comment]
So we can conclude that `spring-cloud-gcp` does not support spring-boot `2.1.8.RELEASE`? As minimum support we see is `2.4.x`?

**Comment by meltsufin** [comment]
The Spring team itself doesn't support 2.1.x anymore. At a minimum, you should upgrade to Spring Boot 2.6.x and Spring Cloud GCP 3.x.
