### ISSUE TITLE
Attempting to use @ServerTimestamp on a Firestore class field, it is not updated in the database (spring-cloud-gcp-data-firestore)

### ISSUE THREAD

**Issue by ianmarxent** [GoogleCloudPlatform/spring-cloud-gcp#1604]
**Describe the bug**
When I attempt to add @ServerTimestamp to a field on my Firestore class nothing gets saved to the database. I see my object saved in Firestore, however the field is 'null'.

Using:

    <groupId>com.google.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-data-firestore</artifactId>

    <spring-cloud-gcp.version>4.0.0</spring-cloud-gcp.version>
    <spring-cloud.version>2022.0.1</spring-cloud.version>

I do see a WARNING in the terminal but not sure if it is causing it fail:
`Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: com.google.cloud.Timestamp`

**Sample**

    
    @Document(collectionName = "pim-log")
    public class LogReactive {

    @DocumentId
    private String id;

    // I have also tried Date instead of Timestamp
    @ServerTimestamp
    private Timestamp createdOn;

    // Getters and setters...

`firestoreTemplate.save(new LogReactive());`

**Comment by meltsufin** [comment]
I think it's a little confusing, but it seems like you can't use `@ServerTimestamp` here. However, [as documented](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#update-time-and-optimistic-locking) you can use `@UpdateTime`.

**Comment by ianmarxent** [comment]
Thanks, using `@UpdateTime` worked for me.
