### ISSUE TITLE
Wrong duration of spans for PubSub tracing

### ISSUE THREAD

**Issue by rafal-dudek** [GoogleCloudPlatform/spring-cloud-gcp#1629]
**Describe the bug**
Spans "publish" and "next-message" for PubSub tracing have wrong duration - 0.001ms.

It is debatable what exactly the spans should cover (when set start and finish timestamp), but even if it is not possible to make this decision right away, it would be better to have some value right now.
We would be happy to have any real value in those spans, even if not covering everything, to be able to notice some outlier spans.

**Sample**
![image](https://user-images.githubusercontent.com/32459286/221591445-dd14d86a-5cad-4f0c-a800-a78667289ef7.png)

**Comment by mpeddada1** [comment]
@rafal-dudek Do you have a reproducer or more project setup information that can help us understand how tracing is set up in your project? Is the problem that it is always setting the duration to 0.001ms?

 cc/ @meltsufin @JoeWang1127  in case you have more context into this!

**Comment by rafal-dudek** [comment]
@mpeddada1 I think it is quite straight forward if you look into the code.
"on-message" - finish time is 1 tick after start time:
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/pubsub/TracingMessageReceiver.java#L67-L69
"publish" - finish time equals start time:
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/pubsub/TraceHelper.java#L71


@meltsufin I know it is asynchronous but it takes 'some' time anyway. 
![image](https://user-images.githubusercontent.com/32459286/221837491-fa50501e-70d7-4ca5-ac56-341d1ec99d23.png)

As I understand, "publish" is Span for asynchronously publishing and pubsubpublisherthreadpool is Span for the real sending data in threadpool, "next-message" is receiving data and "on-message" is operating on it.

I believe publish makes some synchronous operations before adding it to asynchronous thread pool, like pubsub message conversion and message transformations, - it would be nice to know that time in "publish" span. In my test (screen) duration between end of "Span before publish" and start of "Span after publish" on second call is 0.487ms (first is much longer).
Without publish it is 0.184ms. With some custom message transformations and bigger messages it would be longer.

And if it comes to "next-message", it takes some time to receive a message from pubsub and that value could be stored in this span duration.

I'm not sure how important it is and how hard it would be to implement but I think the correct duration for both of these spans isn't 0.

**Comment by blakeli0** [comment]
This is working as intended as these two Spans are just to capture timestamp.

**Comment by rafal-dudek** [comment]
I'm not saying it doesn't work as intended, just that the design is not correct.
Even this comment in the code seems to confirm my words, that this is not fully correct solution and could be done in the future:
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/pubsub/TraceHelper.java#L68
> the span is just an instant, **since we don't yet track** how long it takes to publish and carry that forward
