### ISSUE TITLE
Spanner object mapping documentation doesn't explain how to map generated columns

### ISSUE THREAD

**Issue by progvb** [GoogleCloudPlatform/spring-cloud-gcp#1714]
**Is your feature request related to a problem? Please describe.**
I have [generated columns](https://cloud.google.com/spanner/docs/generated-column/how-to) in my table.

I can query the table and get the values from those generated columns without problems using `@Query` annotation.

Unfortunately I couldn't find any documentation on how to define an entity that would have those values mapped automatically.

**Describe the solution you'd like**
I'd like to be able to define an entity that would have those values mapped automatically.

**Describe alternatives you've considered**
I tried to follow the documentation on [object mapping](https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#object-mapping), but it doesn't explain how to use generated columns.

Just adding a field in my `@Entity` class with the name of the generated column results in `com.google.cloud.spanner.SpannerException: FAILED_PRECONDITION: io.grpc.StatusRuntimeException: FAILED_PRECONDITION: Cannot write into generated column`.

Is it even possible to use generated columns in `@Entity` classes?

**Comment by burkedavison** [comment]
Closing due to lack of response by OP. Please reopen if this is still an issue.
