### ISSUE TITLE
Could not autowire. no beans of type FirestoreTemplate found

### ISSUE THREAD

**Issue by yustarandomname** [GoogleCloudPlatform/spring-cloud-gcp#172]
**Describe the bug**
When trying to init firestore template, IntelliJ reports "Could not autowire. no bean of type FirestoreTemplate found". Is there a simple way to resolve this bug?

Using:
'org.springframework.boot' version '2.3.5.RELEASE'
"org.springframework.cloud:spring-cloud-gcp-data-firestore:1.2.6.RELEASE"
"org.springframework.cloud:spring-cloud-gcp-starter-data-firestore:1.2.6.RELEASE"

**Sample**
![Screenshot 2020-12-10 at 16 48 11](https://user-images.githubusercontent.com/25432790/101795226-f966b600-3b07-11eb-882b-db29a648efce.png)

**Comment by yustarandomname** [comment]
tried to copy: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/master/spring-cloud-gcp-samples/spring-cloud-gcp-data-firestore-sample/src/main/java/com/example/UserController.java

**Comment by meltsufin** [comment]
Is this just an issue with the IDE, or the app doesn't work?

**Comment by meltsufin** [comment]
Please re-open if you're still having this issue.
