### ISSUE TITLE
Google Secret Manager secrets aren't resolved

### ISSUE THREAD

**Issue by falk-stefan** [GoogleCloudPlatform/spring-cloud-gcp#1762]
## Versions

```none
Spring Boot:       3.0.6
Spring Cloud GCP:  4.1.4
```

More details see [pom.xml](https://github.com/falk-stefan/spring-boot-gcp-secret-manager/blob/main/pom.xml).

## Description

There appears to be an issue with my setup as I am not able to load secrets from GCPs Secret Manager in my Spring Boot application. 

I have followed the example from https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1229 without success.

I would assume that this could be a simple IAM Policy issue but it appears as if there's no attempt to even resolve the variable. It looks as if the Spring Boot application interprets ${sm://SECRET_NAME} simply as a environment variable name and its default value. If `spring-cloud-gcp-starter-secretmanager` attempted to resolve the variable, I'd expect an exception coming from there.

Hence, to me this looks like as if the Spring Boot application is not configured correctly on my end.

## Logging

After some further testing I noticed the following log-output (see complete log https://github.com/GoogleCloudPlatform/spring-cloud-gcp/files/11294854/output.log).

It's not clear to me whether or not this is actually related to my issue but it is coming from somewhere in `GrpcSecretManagerServiceStub`.

```none
java.lang.ClassNotFoundException: com.google.auth.appengine.AppEngineCredentials
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:390) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:381) ~[na:na]
	at io.grpc.auth.GoogleAuthLibraryCallCredentials.loadAppEngineCredentials(GoogleAuthLibraryCallCredentials.java:254) ~[grpc-auth-1.54.0.jar:1.54.0]
	at io.grpc.auth.GoogleAuthLibraryCallCredentials.<clinit>(GoogleAuthLibraryCallCredentials.java:57) ~[grpc-auth-1.54.0.jar:1.54.0]
	at io.grpc.auth.MoreCallCredentials.from(MoreCallCredentials.java:35) ~[grpc-auth-1.54.0.jar:1.54.0]
	at com.google.api.gax.grpc.GrpcCallContext.withCredentials(GrpcCallContext.java:160) ~[gax-grpc-2.24.0.jar:2.24.0]
	at com.google.api.gax.grpc.GrpcCallContext.withCredentials(GrpcCallContext.java:67) ~[gax-grpc-2.24.0.jar:2.24.0]
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:206) ~[gax-2.24.0.jar:2.24.0]
	at com.google.cloud.secretmanager.v1.stub.GrpcSecretManagerServiceStub.create(GrpcSecretManagerServiceStub.java:248) ~[google-cloud-secretmanager-2.14.0.jar:2.14.0]
	at com.google.cloud.secretmanager.v1.stub.SecretManagerServiceStubSettings.createStub(SecretManagerServiceStubSettings.java:349) ~[google-cloud-secretmanager-2.14.0.jar:2.14.0]
	at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.<init>(SecretManagerServiceClient.java:180) ~[google-cloud-secretmanager-2.14.0.jar:2.14.0]
	at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.create(SecretManagerServiceClient.java:162) ~[google-cloud-secretmanager-2.14.0.jar:2.14.0]
	at com.google.cloud.spring.autoconfigure.secretmanager.GcpSecretManagerAutoConfiguration.secretManagerClient(GcpSecretManagerAutoConfiguration.java:71) ~[spring-cloud-gcp-autoconfigure-4.1.4.jar:4.1.4]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.8.jar:6.0.8]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:655) ~[spring-beans-6.0.8.jar:6.0.8]
```

## Sample

https://github.com/falk-stefan/spring-boot-gcp-secret-manager

@JoeWang1127

**Comment by ivanzhujunwei** [comment]
I also cannot retrieve the value from secret manager. tried different ways from 
1. https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-secret-manager#4
2. https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#secret-manager
3. https://github.com/spring-attic/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/java/com/example
I am using the following:

> <parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.6-SNAPSHOT</version>
		<relativePath/> 
	</parent>

> <properties>
		<java.version>17</java.version>
		<spring-cloud-gcp.version>4.1.3</spring-cloud-gcp.version>
		<spring-cloud.version>2022.0.1</spring-cloud.version>
	</properties>

> <dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-secretmanager</artifactId>
		</dependency>

**Comment by ivanzhujunwei** [comment]
> I did not see the error as mentioned above. but I just cannot retrieve the value from secret manager and it appears as a null value. tried the different ways from links below but neither of them works.
> 
> 1. https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-secret-manager#4
> 2. https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#secret-manager
> 3. https://github.com/spring-attic/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample/src/main/java/com/example
> 
> I am using the following config:
> 
> ```
> <groupId>org.springframework.boot</groupId>
> <artifactId>spring-boot-starter-parent</artifactId>
> <version>3.0.6-SNAPSHOT</version>
> <relativePath/> 
> 
> <java.version>17</java.version>
> <spring-cloud-gcp.version>4.1.3</spring-cloud-gcp.version>
> <spring-cloud.version>2022.0.1</spring-cloud.version>
> 
> <groupId>com.google.cloud</groupId>
> <artifactId>spring-cloud-gcp-starter-secretmanager</artifactId>
> ```

Sorry, when I am digging deeper, it seems something wrong to get the value from the application.properties file, it always shows NULL. not related to the library or dependency yet. Can ignore the post above for now.

**Comment by ivanzhujunwei** [comment]
ok, I've resolved the issue loading values from application.properties file. Now, still cannot get the value from secret manager in GCP, here is the piece of code:
`
private final String secret;
public backUpService(@Value("${sm://secret}") String secret) {
        this.secret = secret;
}
public void test(){
       System.out.println("load value:   " + this.secret);
}
`
It always pints this: load value:   //secret

**Comment by meltsufin** [comment]
Please note that you need `spring.config.import=sm://` in your `application.properties`. This is required after upgrade to `4.x`.
Also, please refer to the [secretsmanager-sample](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-secretmanager-sample) which shows the correct configuration, which I just manually tested to ensure that it works.

**Comment by falk-stefan** [comment]
(╯°□°)╯︵ ┻━┻

This is all I have to say about this.

@JoeWang1127 from my side the issue can be closed.

@meltsufin thanks man.. :sweat_smile:

**Comment by ivanzhujunwei** [comment]
Thanks @meltsufin it works for me as well.

**Comment by ivanzhujunwei** [comment]
Hello guys, I know this ticket was closed, but any idea about the following would be appreciated! 
@JoeWang1127 @meltsufin @falk-stefan 

I can run the following successfully in LOCAL.
- application.properties file:
`spring.config.import=sm://`
`secret=${sm://secret}`

- service file: 
`private final String secret;`
`public SecretService(@Value("${secret}") String secret) {`
`         this.secret = secret;`
`}`
`...`
`System.out.println("load value:   " + secret);`

I can get the value which is set in Secret Manager.

However, when this is running in Cloud Build based on the Dockerfile, it always fails in the step of:
`mvn package`. The error messages are:

> Suppressed: com.google.api.gax.rpc.AsyncTaskException: Asynchronous task failed
Step #0 - "Build Docker Image": 		at com.google.api.gax.rpc.ApiExceptions.callAndTranslateApiException(ApiExceptions.java:57) ~[gax-2.23.3.jar:2.23.3]
Step #0 - "Build Docker Image": 		at com.google.api.gax.rpc.UnaryCallable.call(UnaryCallable.java:112) ~[gax-2.23.3.jar:2.23.3]
Step #0 - "Build Docker Image": 		at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1396) ~[google-cloud-secretmanager-2.13.0.jar:2.13.0]
Step #0 - "Build Docker Image": 		at com.google.cloud.secretmanager.v1.SecretManagerServiceClient.accessSecretVersion(SecretManagerServiceClient.java:1326) ~[google-cloud-secretmanager-2.13.0.jar:2.13.0]
Step #0 - "Build Docker Image": 		at com.google.cloud.spring.secretmanager.SecretManagerTemplate.getSecretByteString(SecretManagerTemplate.java:189) ~[spring-cloud-gcp-secretmanager-4.1.3.jar:4.1.3]
Step #0 - "Build Docker Image": 		at com.google.cloud.spring.secretmanager.SecretManagerPropertySource.getProperty(SecretManagerPropertySource.java:47) ~[spring-cloud-gcp-secretmanager-4.1.3.jar:4.1.3]
Step #0 - "Build Docker Image": 		at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:85) ~[spring-core-6.0.8.jar:6.0.8]
> ...
> Step #0 - "Build Docker Image": Caused by: com.google.api.gax.rpc.DeadlineExceededException: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 16.926342891s. [closed=[], open=[[buffered_nanos=16943672210, waiting_for_connection]]]

> Step #0 - "Build Docker Image": Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'secretBackupService' defined in file [/build/target/classes/monash/gcpwizard/services/SecretService.class]: Unexpected exception during bean creation

I went through the source libraries, but it seems the answer is not straightforward to me. 

![iShot_2023-05-03_17 16 58](https://user-images.githubusercontent.com/14146339/235853294-9148fd6d-eba2-47d7-9746-09f602e9ab3c.png)

![iShot_2023-05-03_16 29 52](https://user-images.githubusercontent.com/14146339/235846054-c54c6bba-d091-43ee-8c8f-d536a5a2b9c5.png)

**Comment by meltsufin** [comment]
@ivanzhujunwei Like @JoeWang1127 said, let's open a new issue for this, and if you can, please provide a reproducer. It seems odd that the application would run during build, unless you have some tests that are trying to execute. In that case, you might want to change the command to `mvn package -DskipTests`. Note that Cloud Build runs under a different service account, probably without access to the Secrets Manager API.

**Comment by ivanzhujunwei** [comment]
Thanks @meltsufin `mvn package -DskipTests` works. 
However, those test cases are still required to run before build, I have added this step into the cloud build by the following:
`- name: maven:3.9.1-amazoncorretto-17`
`   args:`
`          - mvn`
`          - test`
`   id: Run tests`

**Comment by ivanzhujunwei** [comment]
Thank you very much @meltsufin 

 `mvn package -DskipTests` works in my dockerfile for image build. 
However, those test cases are still required to run, I have added this step into the cloud build before the image build, by the following:
`- name: maven:3.9.1-amazoncorretto-17`
`   args:`
`          - mvn`
`          - test`
`   id: Run tests`

So I assume during the image building, if Secret Manager is triggered somehow (in my case, the SM is injected in one of the constructors.), it will fail as the building process itself does not have access to the Secret Manager.
