### ISSUE TITLE
Pub/Sub Trace Support for Push-Subscription

### ISSUE THREAD

**Issue by campfireman** [GoogleCloudPlatform/spring-cloud-gcp#1763]
Hey guys,
I was wondering about a feature:

**Is your feature request related to a problem? Please describe.**
We primarily use push subscriptions in our projects. At the moment we have to pass trace-ids manually between services to preserve the trace context. Using the experimental `spring.cloud.gcp.trace.pubsub.enabled=true` does not help, as it only works through the pubSubTemplate. Push-Subscriptions are received via HTTP requests.

**Describe the solution you'd like**
`spring.cloud.gcp.trace.pubsub.enabled=true` automagically maintains the trace context in push-subscriptions for beautiful tracing waterfalls.

**Describe alternatives you've considered**
Doing it manually by ourselves.

Maybe something you have considered before? Would love to hear your thoughts :)

**Comment by meltsufin** [comment]
#893 is related.

**Comment by campfireman** [comment]
Awesome, thanks! That is enough context for me, closing the issue.
