### ISSUE TITLE
Add reactive support for Spring Cloud GCP PubSub Stream Binder

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#179]
Spring Cloud GCP PubSub Stream Binder currently doesn't fully support reactive programming with non-blocking I/O. `PubSubMessageChannelBinder` uses `PubSubTemplate` instead of `PubSubReactiveFactory `, and makes use of the `org.springframework.cloud.gcp.pubsub.integration.[inbound,outbound]` packages from Spring Cloud GCP PubSub, which currently don't support reactive types.

**Comment by meltsufin** [comment]
I think that a reactive variant of the Pub/Sub Stream Binder absolutely could be useful. It might be possible to make it an option in the `spring-cloud-gcp-pubsub-stream-binder` module or to just create a new one `spring-cloud-gcp-pubsub-stream-binder-reactive`.

Would you be interested in contributing the support?

**Comment by breun** [comment]
We are currently evaluating Spring Cloud Stream as a basis for using PubSub. The lack of reactive support in the PubSub stream binder would currently be a blocker for us. But maybe implementing this reactive support would be less work than building what we envision on top of Spring Cloud GCP PubSub. We’ll be investigating Spring Cloud Stream a bit more first.

**Comment by ttomsu** [comment]
So I've been looking into all things Reactive since I accepted this bug, and I'm not quite sure what problem exactly you're asking to solve. If you look under the hood at `PubSubReactiveFactory`, it too uses the same building blocks as the `PubSubTemplate`.

Can you help me understand what you'd like to see from the library or samples?

**Comment by elefeint** [comment]
Spring Cloud Stream natively supports reactive streams for both [producing](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_suppliers_sources) and [consuming](https://docs.spring.io/spring-cloud-stream/docs/current/reference/html/spring-cloud-stream.html#_consumer_reactive) data starting at version 3.0. Even though the binder SPI is not itself reactive, the incoming data binding is based on a streaming Spring Integration adapter, and so Spring Cloud Stream framework can easily convert incoming messages into a `Flux` (albeit without ability to propagate backpressure back to the Pub/Sub server).

The functional sample in this repo [demonstrates](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/aefa67da1f7c0f219b203c0ba21c73b3a8cf08a3/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-binder-functional-sample/spring-cloud-gcp-pubsub-stream-binder-functional-sample-source/src/main/java/com/example/Source.java#L49) the use of a reactive data source. While its counterpart sink [is not reactive](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/aefa67da1f7c0f219b203c0ba21c73b3a8cf08a3/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-binder-functional-sample/spring-cloud-gcp-pubsub-stream-binder-functional-sample-sink/src/main/java/com/example/Sink.java#L41), it can be easily modified to operate on a `Flux` like this:

```
@Bean
public Function<Flux<UserMessage>, Mono<Void>> logUserMessage() {
	return userMessages ->
		userMessages
				.log() // any intermediate operations go here
				.doOnNext(userMessage ->
						LOGGER.info(String.format("New message received from %s: %s at %s",
							userMessage.getUsername(), userMessage.getBody(), userMessage.getCreatedAt()))
		).then();
}
``` 

Would this usage pattern satisfy your requirement?

**Comment by breun** [comment]
Me and my colleagues were trying out `org.springframework.cloud:spring-cloud-gcp-pubsub-stream-binder:1.2.6.RELEASE` (we're currently still on Spring Cloud Hoxton), so maybe things have changed in version 2, but we saw that `PubSubInboundChannelAdapter` uses the streaming pull `subscribeAndConvert` method, which is async, but not reactive, because backpressure does not get propagated and you can only use the flow control settings to limit the flow of messages, which is not what you'd expect in a reactive programming environment. In a reactive scenario we'd expect the client to pull messages and respect backpressure all the way down.

**Comment by elefeint** [comment]
@olegz Spring Cloud Stream does an amazing job supporting reactive streams out of the box by constructing reactive objects in the framework. For the future, are there plans to allow binders to return custom reactive streams that would then be propagated to customer sinks? In our case, the streaming Pub/Sub does not support backpressure for a host of historical reasons, but we have a workaround that tracks cumulative subscriber demand and polls the server as needed. There does not seem a way to plug this ready-to-go `Flux` into the binder API though.

More generally, have you seen customer interest in backpressure-supporting streams in other binders like Kafka?

**Comment by vy** [comment]
> ```java
> @Bean
> public Function<Flux<Message>, Mono<Void>> messageConsumer() {
> 	return messages -> messages.concatMap(this::consumeMessage).then();
> }
> ```

@elefeint, in the above example you shared (I have simplified it further), the completion happens, i.e., `then()` executes, when the entire stream is consumed. There how do you gradually `ack` the progress? For instance, say `messages` is a `Flux` composed of 10 messages, `consumeMessage()` successfully consumed the first 9, and then failed on the last 10th. In this case, will you `nack` all the 10 messages? Do you see my point? This function footprint doesn't allow progress tracking. As a developer I would rather have something as follows:

```java
@Bean
public Function<Flux<Message>, Flux<Consumption<Message>>> messageConsumer() {
	return messages -> messages.concatMap(this::consumeMessage);
}
```

This way one can also intercept the consumption and have a word on what to do next. Batch `ack`ing? Check. Retry on failures? Check. Complete database transaction? Check.

I hope my point is clear. It is not just that backpressure propagation is missing, the exposed API is not designed with a reactive mind set, IMHO.

**Comment by elefeint** [comment]
`.then()` triggers the reactive pipeline, but the pipeline itself can be as complex as you need. To address the batching usecase, I'd probably turn a stream of messages into a stream of batches with a Reactor operator, and then feed it into the batch-based business logic:

```
@Bean
public Function<Flux<UserMessage>, Mono<Void>> logUserMessage() {
	return userMessages ->
		userMessages
				.bufferTimeout(5, Duration.ofSeconds(5))
				.doOnNext(batchOfUserMessages ->
						LOGGER.info(String.format("Received %s messages", batchOfUserMessages.size())
				)).then();

	}
```

**Comment by vy** [comment]
(@elefeint, I have deleted my comment to avoid distracting the conversation from its actual point. Mine is more of a Spring Cloud Streams issue, not really particularly tied to Spring Cloud GCP. That said, thanks for your prompt response.)
