### ISSUE TITLE
spring.cloud.gcp.project-id is not honored when using spring-cloud-gcp-starter-secretmanager

### ISSUE THREAD

**Issue by wleese** [GoogleCloudPlatform/spring-cloud-gcp#1793]
**Describe the bug**
Spring Cloud GCP 3.4.9
Spring Cloud 2022.0.2

Previously a GcpProjectIdProvider bean was provided by com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration based on the value of spring.cloud.gcp.project-id.

However, now, when including the spring-cloud-gcp-starter-secretmanager dependency, a GcpProjectIdProvider bean is provided by spring-cloud-gcp-starter-secretmanager which ignores spring.cloud.gcp.project-id and instead uses spring.cloud.gcp.secretmanager.project-id with a fallback to ServiceOptions.getDefaultProjectId().

**Sample**
```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT, classes = [Shortname1Application::class])
@TestPropertySource(
    properties = [
        "spring.cloud.gcp.project-id=abc",
//        "spring.cloud.gcp.secretmanager.project-id=abc",
        "spring.config.import=sm://",
    ],
)
class Shortname1ApplicationTests {

    @Autowired
    private lateinit var projectIdProvider: GcpProjectIdProvider
  
    // Returns null
    @Test
    fun `with spring import config property enabled then expect correct project id`() {
        AssertionsForClassTypes.assertThat(projectIdProvider.projectId).isEqualTo("abc")
    }

}
```

**Comment by JoeWang1127** [comment]
After an initial investigation, I think we need to modify this part: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/b444fcbbdd57984ac7304263490546219ec41c86/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/secretmanager/GcpSecretManagerAutoConfiguration.java#L54-L57

**Comment by meltsufin** [comment]
It looks like a bug. The project ID should be determined like in Datastore autoconfig.
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/0c7d56acede530e4ecfbac5ce6a9ffa341b7306c/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/datastore/GcpDatastoreAutoConfiguration.java#L83-L87
