### ISSUE TITLE
spring.cloud.gcp.secretmanager.enabled=false still results in the creation of GcpProjectIdProvider

### ISSUE THREAD

**Issue by wleese** [GoogleCloudPlatform/spring-cloud-gcp#1794]
**Describe the bug**
Spring Cloud GCP 3.4.9
Spring Cloud 2022.0.2

When troubleshooting https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/1793, I was surprised to find that even though spring.cloud.gcp.secretmanager.enabled=false, a GcpProjectIdProvider (and other beans) is still being created, resulting in the GcpProjectIdProvider bean in GcpContextAutoConfiguration not being provided.

**Comment by JoeWang1127** [comment]
Hi @wleese, could you share more rational why this is an issue? `GcpProjectIdProvider` is needed in other modules as well, it is not only set for secret manager.

**Comment by wleese** [comment]
Due to a GcpProjectIdProvider being created via secretmanager, the linked bug is triggered. Of course a default GcpProjectIdProvider should be provided for other modules :)

My issue strictly lies with the one provided that has the issue I linked to. If they both have the same implementation, then I’m fine either way :)
