### ISSUE TITLE
Ability to provide ConsumerEndpointCustomizer for PubSubMessageChannelBinder

### ISSUE THREAD

**Issue by poznachowski** [GoogleCloudPlatform/spring-cloud-gcp#182]
I'm evaluating pub/sub emulator for development purposes (using dedicated `@Profile`). I'm unable to force the emulator to stop redelivering messages (retry policies are not supported), which is undermining the whole concept. What I want to achieve is to **ack** all messages regardless whether exception is being thrown or not. 

As, there is no `AckMode` supporting this case - I'd like to be able to provide my implementation of `ConsumerEndpointCustomizer` to the `PubSubMessageChannelBinder`.
Due to the different behaviour of bootstrapping Spring Cloud binders (then any other Spring Boot / Cloud components), I'm not able to get the Binder bean in my `Configuration` class and simply invoking `setConsumerEndpointCustomizer` on that.

The only way I was able to achieve my goal was to duplicate whole `PubSubBinderConfiguration` and due to the `@ConditionalOnMissingBean(Binder.class)` I could provide my own version of `PubSubMessageChannelBinder` instantiation, where I set up different error handler (via mentioned `ConsumerEndpointCustomizer`) and swallow any exception that my `@StreamListener` gets.

I'm using **spring-cloud-gcp-pubsub-stream-binder:1.2.5.RELEASE**

**Comment by elefeint** [comment]
Would setting up an error handler, such as in [this sample app](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/2c78357734bd1bf9914e9e88ab486a7d0c0bcf84/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-binder-sample/src/main/java/com/example/SinkExample.java#L53), address your usecase? The error handler could manually ack() the message, but even if the error handler does nothing, the message will get acked because successful completion of an error handler is considered successful message processing. This is documented under [Spring Integration](https://github.com/spring-cloud/spring-cloud-gcp/blob/master/docs/src/main/asciidoc/spring-integration-pubsub.adoc#user-content-acknowledging-messages-and-handling-failures), so it's a bit hard to find.

**Comment by poznachowski** [comment]
That would address the issue, if I had a single `@StreamListener` in the application. Use case is I have plenty of them (>10) and it would be sensitive on the topic names. 

> The error handler could manually ack() the message, but even if the error handler does nothing, the message will get acked because successful completion of an error handler is considered successful message processing.

That is exactly what I want to do. In the documentation link you provided that is an example without Binder usage. In my case I'm using the Binder which creates multiple `PubSubInboundChannelAdapter` instances and creating dedicated error channels to them (per subscription / consumer)

Let me show you my modification to the original code to explicitly present you my intention:

```
@Slf4j
@Configuration
@Profile("local")
@EnableConfigurationProperties(PubSubExtendedBindingProperties.class)
public class LocalConfiguration {

    @Bean
    public PubSubChannelProvisioner pubSubChannelProvisioner(PubSubAdmin pubSubAdmin) {
        return new PubSubChannelProvisioner(pubSubAdmin);
    }

    @Bean
    public PubSubMessageChannelBinder pubSubBinder(
            PubSubChannelProvisioner pubSubChannelProvisioner,
            PubSubTemplate pubSubTemplate,
            PubSubExtendedBindingProperties pubSubExtendedBindingProperties) {

        var binder = new PubSubMessageChannelBinder(null,
                pubSubChannelProvisioner,
                pubSubTemplate,
                pubSubExtendedBindingProperties
        );
        binder.setConsumerEndpointCustomizer((endpoint, destinationName, group) -> {
            var channelAdapter = (PubSubInboundChannelAdapter) endpoint;
            var channel = new PublishSubscribeChannel();
            channel.subscribe(m -> log.error("Error handled: ", ((ErrorMessage)m).getPayload()));
            channelAdapter.setErrorChannel(channel);
        });
        return binder;
    }

    @Bean
    public BindingHandlerAdvise.MappingsProvider pubSubExtendedPropertiesDefaultMappingsProvider() {
        return () -> Collections.singletonMap(
                ConfigurationPropertyName.of("spring.cloud.stream.gcp.pubsub.bindings"),
                ConfigurationPropertyName.of("spring.cloud.stream.gcp.pubsub.default"));
    }
}
```
This is a substitution of `PubSubBinderConfiguration` when local profile is used. Here for all Binders (all subscriptions) I am able to provide the `ConsumerEndpointCustomizer` that allow me to set errorHandling of the underlying `PubSubInboundChannelAdapter`. Error handling does exactly what you said, just log the error and complete successfully allowing the framework to ack() the message for me.

I am looking for this kind of modification without pulling back original `PubSubBinderConfiguration` configuration.

**Comment by meltsufin** [comment]
@poznachowski I proposed a PR (#186) to add the support. Please see if it would address your needs.

**Comment by poznachowski** [comment]
@meltsufin that would do. Thank you for taking care of this so quickly!
