### ISSUE TITLE
Inconsecutive GCP PubSub delivery_attempt 

### ISSUE THREAD

**Issue by lawrence-telus** [GoogleCloudPlatform/spring-cloud-gcp#1885]
**Describe the bug**
I ran into a production issue when use spring cloud gcp pubsub API to receive messages with stream pull. I notice  delivery_attempt  attribute had inconsecutive value when redelivery happened.  Here are 3 examples I collected from the service log.

1. Received 2 and 3(final) delivery. Missed the first one.
2. Received 6(final) delivery. Missed 1-5.
3. Received 1,4,6,10 and 13(final). Missed others in between.

For all above scenarios, messages were consumed and acked successfully. NO message loss. The subscription in use is the only one of the PubSub topic.  There are 4 pods of the same microservice with that subscription running on GKE. The message consuming code is developed by Spring Integration IntegrationFlow.
What could happened to those unreceived redeliveries? Is it related to ack or unack logic?

**Sample code**
```java
  @Bean
  @Autowired
  public IntegrationFlow usageFlow(
      PubSubTemplate pubSubTemplate,
      EligibilityHandler eligibilityHandler,
      UsageEventHandler usageEventHandler,
      DeliveryHandler deliveryHandler) {
    var usageEventInbound = new PubSubInboundChannelAdapter(pubSubTemplate, subscription);
    usageEventInbound.setAckMode(AckMode.MANUAL);
    usageEventInbound.setErrorChannel(usageErrorChannel());
    // @formatter:off
    return IntegrationFlows.from(usageEventInbound)
        .handle(
            Message.class,
            (message, messageHeaders) -> {
              BasicAcknowledgeablePubsubMessage originalMessage =
                  messageHeaders.get(ORIGINAL_MESSAGE, BasicAcknowledgeablePubsubMessage.class);
              String messageId = messageHeaders.get(USAGE_EVENT_ID, String.class);
              String policyMessageId = originalMessage.getPubsubMessage().getMessageId();
              String payload = originalMessage.getPubsubMessage().getData().toStringUtf8();
              String deliveryAttempt =
                  messageHeaders.get(DELIVERY_ATTEMPT, String.class) != null
                      ? messageHeaders.get(DELIVERY_ATTEMPT, String.class)
                      : "0";
              MDC.put(TRACE, messageId);
              log.info(
                  "Received a message with id [{}], policy message id [{}], delivery attempt(s)"
                      + " [{}] and attributes [{}]. Payload: {}",
                  messageId,
                  policyMessageId,
                  deliveryAttempt,
                  messageHeaders,
                  payload);
				  
              if (eligibilityHandler.isMessageAlreadyProcessed(
                  messageId + CACHE_PUBSUB_MESSAGE_ID_KEY_SEPARATOR + policyMessageId)) {
                originalMessage.ack();
                return null;
              }
              eligibilityHandler.cacheMessageStatus(
                  messageId + CACHE_PUBSUB_MESSAGE_ID_KEY_SEPARATOR + policyMessageId,
                  CACHE_PUBSUB_MESSAGE_ID_STATUS_PENDING);
              return message;
            })
        .transform(Transformers.fromJson(UsageEvent.class))
        .handle(UsageEvent.class, eligibilityHandler::checkEligibility)
        .handle(
            Message.class,
            (message, messageHeaders) -> {
              var originalMessage =
                  messageHeaders.get(ORIGINAL_MESSAGE, BasicAcknowledgeablePubsubMessage.class);
              String messageId = messageHeaders.get(USAGE_EVENT_ID, String.class);
              if (originalMessage != null) {
                // Save message's status in cache to avoid being processed again.
                String policyMessageId = originalMessage.getPubsubMessage().getMessageId();
                eligibilityHandler.cacheMessageStatus(
                    messageId + CACHE_PUBSUB_MESSAGE_ID_KEY_SEPARATOR + policyMessageId,
                    CACHE_PUBSUB_MESSAGE_ID_STATUS_SENT);
                originalMessage.ack();
              }
              return message;
            })
        .split()
        .handle(deliveryHandler, "sendMessage")
        .get();
    // @formatter:on
  }

  @Bean
  public MessageChannel usageErrorChannel() {
    return new DirectChannel();
  }

  @Bean
  public IntegrationFlow errorFlow(ErrorHandler errorHandler) {
    return IntegrationFlows.from(usageErrorChannel()).handle(errorHandler, "handleError").get();
  }
```
spring-cloud-gcp-dependencies: 1.2.2.RELEASE

**Comment by meltsufin** [comment]
Are you collating the logs from all 4 pods? Redeliveries happen when the application is not ack'ing the messages within the configured time period. Are you ack'ing the messages before the redeliveries happen?
I would suggest filing a ticket with Google Cloud Support, where they can analyze what's going on with your Pub/Sub subscriptions on the back-end.

**Comment by lawrence-telus** [comment]
GKE provides a centralized view of logs of all pods. It does not look like it could miss logs. 
I did file a GCP support ticket and provides the log and pubsub subscription monitoring metrics data. BTW. The issue only happened at early May for 2 days. It does not appear since then. 
What Google found at the server is the  com.google.cloud.pubsub.v1.Subscriber.ModifyAckDeadline was called with not zero value. They suspect it could be the reason that caused inconsecutive deliveries. You can see from the above code, BasicAcknowledgeablePubsubMessage does not support any Mod Ack operations. But they had difficulty to figure out which pod triggered the Ack Mod. Could Spring Cloud modify Ack under certain circumstances without client application involvement?

**Comment by meltsufin** [comment]
Spring Cloud GCP would not be automatically modifying ack deadline to non-zero values, but the Cloud Pub/Sub client library that is used by Spring Cloud GCP might, depending on the configuration.

**Comment by burkedavison** [comment]
Closing issue since OP states this isn't repeatable, and the issue has gone stale.
