### ISSUE TITLE
ExistBy does not work on subclasses

### ISSUE THREAD

**Issue by Alos** [GoogleCloudPlatform/spring-cloud-gcp#1894]
**Describe the bug**
Spring Datastore `existBy` queries are not working with subclasses. 

![CatClassDiagram](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/25460/4fde6a6f-59b1-43a9-acc6-a736a41a197d)
```java
    Cat cat = new Cat();
    cat.setAge(2).setName("bob");
    Cat savedCat = animalRepository.save(cat);
    assertNotNull(savedCat); //pass savedCat has an id
    boolean isCatThere = animalRepository.existsByName("bob");
    assertTrue(isCatThere); //fails
```

**Sample**
https://github.com/Alos/SpringCloudGCPExistByIssue

**Comment by meltsufin** [comment]
I think the issue is that Datastore doesn't support polymorphism. Each entity can have one and only one Kind. The `cat` is stored with a `cat` Kind. Are you expecting it be stored under the `animal` Kind because you're using `DatastoreRepository<Animal, Long>` repository?

**Comment by Alos** [comment]
I would have multiple kinds of animals, I would have to implement multiple repositories (one per subclass). I think this would not be an elegant solution, please tell me there is another way?

**Comment by meltsufin** [comment]
If you think in terms of the underlying entities in Datastore, what should the data look like?

**Comment by Alos** [comment]
I don't think I particularly care either way. It can be all an Animal kind with discriminator property or multiple entities. I've also confirmed that the existById and the existByExample are also not working. For now I will try to use multiple repositories and see if that fixes the issue :(

**Comment by meltsufin** [comment]
I would just get rid of the polymorphism and have a single entity `Animal` with the union of all the fields of all subclasses of animal. I think having interfaces for `Dog` and `Cat` that `Animal` implements might work, but you would have to use `Animal` kind for storing in the Datastore.

**Comment by Alos** [comment]
Ended up creating multiple Repositories per subclass. Aggregating all my subclasses into an `Animal` was not great.
