### ISSUE TITLE
Spring boot controllers + Google cloud function + gradle

### ISSUE THREAD

**Issue by Chuckame** [GoogleCloudPlatform/spring-cloud-gcp#1916]
After a lot of research, I didn't succeed on how to make compatible a rest api with the invoker with gradle, because spring adds some logic to generates its own jar launcher, so the main class responsible of mapping the httpFunction from the gcf trigger to internal routes using a WebServer proxy is not accessible.

Anyone have some insight, idea or solution to make it work? I don't want to use the HttpFunction, but more using the annotation framework of spring

**Comment by Chuckame** [comment]
It's the same issue as https://github.com/spring-cloud/spring-cloud-function/issues/665, while here I know that it's linked to the custom spring packaging

**Comment by meltsufin** [comment]
Have you tried the official [sample](https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-gcp-http).

**Comment by Chuckame** [comment]
@meltsufin it's maven, not gradle

**Comment by meltsufin** [comment]
Have you tried translating to Gradle? What's missing on the Gradle side vs. Maven?

**Comment by Chuckame** [comment]
I'm sorry if it wasn't clear. For the moment, the spring boot gradle plugin is not taking into account the GcfJarLauncher app layout. It is done on the maven side by adding the gcf adapter like this:
```xml

			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>org.springframework.cloud</groupId>
						<artifactId>spring-cloud-function-adapter-gcp</artifactId>
						<version>${spring-cloud-function.version}</version>
					</dependency>
				</dependencies>
			</plugin>
```

**Comment by Chuckame** [comment]
What I want is to still try using gradle instead of maven, even with manual steps

**Comment by meltsufin** [comment]
I think it's more of a question for the Spring Boot project. Can you file a question there?

**Comment by burkedavison** [comment]
Closing issue due to lack of response by OP. Please reopen if this is determined to be a Spring Cloud GCP specific issue.

**Comment by svachmic** [comment]
How did this end? @Chuckame were you ever able to deploy? I'm trying to achieve the same thing with no luck. All examples are in Maven...

**Comment by Chuckame** [comment]
Hello, sadly no success on it. I used maven, then totally moved to typescript for better native experience (the tooling is well made on js/ts stacks, while a bit poor on the Java side).
