### ISSUE TITLE
Build for JsonStreamWriter, it does not pass BigQueryWriteClient into JsonStreamWriter.

### ISSUE THREAD

**Issue by Mikksrund** [GoogleCloudPlatform/spring-cloud-gcp#1924]
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

**Comment by meltsufin** [comment]
@prash-mi PTAL.
