### ISSUE TITLE
Create a changelog like in the old repo

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/spring-cloud-gcp#194]
https://github.com/spring-cloud/spring-cloud-gcp/blob/master/CHANGELOG.adoc

**Comment by kioie** [comment]
Hey @meltsufin what do you think should be included here? The changelog in the old repo looks detailed enough and we can build on it.

**Comment by meltsufin** [comment]
I was thinking of creating a new one with updates since `1.2.6` and linking to the old one at the bottom.
Thanks for you interest in helping!
