### ISSUE TITLE
Add support for Logstash Markers

### ISSUE THREAD

**Issue by nhmarujo** [GoogleCloudPlatform/spring-cloud-gcp#198]
**Is your feature request related to a problem? Please describe.**
I am trying `spring-cloud-gcp-starter-logging` (Spring Cloud 2.2.5.RELEASE) and it works great on GKE. Everything is included properly in the JSON payload, except for the **Logstash Markers** I'm using when logging.

**Describe the solution you'd like**
I would like `StackdriverJsonLayout` to be enhanced, so it would also consider **Logstash Markers** to be included on the JSON payload.

I think this could be easily achieved if the method `toJsonMap` in `StackdriverJsonLayout` is changed to look for **Logstash Markers** and add them to the map if present. Something like (this code is inspired on `net.logstash.logback.composite.loggingevent.LogstashMarkersJsonProvider`):
```
(...)

@Override
protected Map<String, Object> toJsonMap(ILoggingEvent event) {
    (...)

    addLogstashMarkerIfNecessary(event.getMarker());

    return map;
}

private void addLogstashMarkerIfNecessary(Map<String, Object> jsonMap, Marker marker) {
    if (marker == null) {
        return;
    }

    if (marker instanceof ObjectAppendingMarker) {
        ObjectAppendingMarker objectAppendingMarker = (ObjectAppendingMarker) marker;
        jsonMap.put(objectAppendingMarker.getFieldName(), objectAppendingMarker.getFieldValue());
    }

    if (marker.hasReferences()) {
        for (Iterator<?> i = marker.iterator(); i.hasNext(); ) {
            Marker next = (Marker) i.next();
            addLogstashMarkerIfNecessary(jsonMap, next);
        }
    }
}

(...)
```
**Note:** I created a Layout that extends `org.springframework.cloud.gcp.logging.StackdriverJsonLayout` and overrides the `toJsonMap` method, just adding that piece of logic, and it works as expected:
```
(...)

@Override
protected Map<String, Object> toJsonMap(ILoggingEvent event) {
    Map<String, Object> jsonMap = super.toJsonMap(event);
    addLogstashMarkerIfNecessary(jsonMap, event.getMarker());
    return jsonMap;
}

(...)
```

So, technically, it is possible. I do understand this adds Logstash as a dependency, but I think is worth it (not sure if there is a way to do it generically or in a more decoupled way).

**Note:** maybe it would also be good to add a property to control whether or not these should be added (just like it happens with MDC, for instance)

**Describe alternatives you've considered**
I did try setting up `logback-spring.xml` in some way that would combine the behaviours of `org.springframework.cloud.gcp.logging.StackdriverJsonLayout` and `net.logstash.logback.composite.loggingevent.LogstashMarkersJsonProvider`. Had no success in any combination I tried, which lead me to look for a solution at a lower level.

**Comment by dzou** [comment]
@nhmarujo - Thanks for the feature request. Yes we can definitely consider adding this.

I'm not too familiar with Logstash though, is it a commonly-used framework? Regarding adding a new dependency, we probably can add a dependency at `provided` scope and maybe do some work to check if a class is on the classpath so users don't get a new transitive dependency.

Also, is there something special about Logstash Markers in particular? Or are logging markers in general something that we should be supporting in general? Right now I'm doing some research as to [what logging markers are](https://stackoverflow.com/questions/16813032/what-are-markers-in-java-logging-frameworks-and-what-is-a-reason-to-use-them).

**Comment by nhmarujo** [comment]
Hi @dzou . Thank you for the prompt answer.

Yes, **logstash** is widely known https://www.elastic.co/logstash. Although we are not using it for any log ingestion, we were using their logback encoder (`net.logstash.logback.encoder.LogstashEncoder`), which already produces a JSON formatted output.

This lib also provides Markers, that can be used to add context to each log line. Example:
```
logger.info(append("field1", "value1")
                .and(append("field2", "value2")),
                "Some log message");
```
The 2 key/value pairs for the example above would then be added as fields of the resulting JSON payload.

Right now I'm considering moving away from that encoder in favour of yours. Everything works perfectly, but our code already uses those markers everywhere and I would like to keep them.

**Comment by dzou** [comment]
I see, thanks for the info. I'll do some experimentation and set up a sample app to try it out.

So for your project, you're using these dependencies right?

```
<dependency>
    <groupId>net.logstash.logback</groupId>
    <artifactId>logstash-logback-encoder</artifactId>
    <version>6.6</version>
</dependency>
<!-- Your project must also directly depend on either logback-classic or logback-access.  For example: -->
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.2.3</version>
</dependency>

**Comment by nhmarujo** [comment]
Yes. Not exactly on that version (I'm using logstash-logback-encoder v6.4), but shouldn't make any difference.

**Comment by nhmarujo** [comment]
One additional information. I was looking at my code snippet and realised it may be a bit simplistic, since it is assuming all **Logstash Markers** would be of type `ObjectAppendingMarker`. But apparently there are more https://appdoc.app/artifact/net.logstash.logback/logstash-logback-encoder/3.0/net/logstash/logback/marker/Markers.html, so might be a good idea to look at them as a whole.

**Comment by dzou** [comment]
@nhmarujo - Hey, I did some research on this today and have a _tentative_ solution, I ended up extending the `StackdriverJsonLayout ` class and overriding the `addCustomDataToJsonMap(..)` method. Then referencing this custom layout class in my logback.xml.

Here is my sample code: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/compare/logging-markers-example

This is what I would recommend for now.
_____

Regarding adding built-in Markers support, I did some research into understanding where markers are used and their variations. One of the tricky things is, while the ObjectAppendingMarker is straightforward, the whole class of logstash & logback markers is very general. It can be used to represent arbitrary data structures (graphs, lists of metadata, etc.)

If we were to add built-in support for markers in our library, we would have to make too many assumptions about what the user wants. (i.e. whether they want to render the full key-value pair in JSON versus only including the keys or only including a subset of the fields of a complex object, etc).

I feel it'd just be better if we could offer easy ways of letting users augment the JSON or `LogEntry` representation of the logs in Stackdriver.

If you feel good about this, I think we can probably do some more work at adding some more docs/samples around log metadata augmentation.

**Comment by nhmarujo** [comment]
Hi @dzou

Regarding your code example, it is somehow similar to mine, although I preferred to override `toJsonMap` (still calling `super`). The advantage I see with my approach is that you don't lose the ability to use the `customJson` tag (which I'm currently using to add `<customJson>{"logType": "application"}</customJson>`, for instance).

---

Can you please elaborate a bit on this statement?
> I feel it'd just be better if we could offer easy ways of letting users augment the JSON or LogEntry representation of the logs in Stackdriver.

Honestly I'm not sure I'm picturing correctly what you are suggesting.

I do understand that **logback ,arkers** are a very wide concept (which can be about anything). What I would like to see is support for the **logstash markers** (which are a specification of **logback markers**) if they are present. Here is some documentation that shows a bit better how they can be used https://github.com/logstash/logstash-logback-encoder#event-specific-custom-fields

Thanks

**Comment by dzou** [comment]
> Can you please elaborate a bit on this statement?
> 
> > I feel it'd just be better if we could offer easy ways of letting users augment the JSON or LogEntry representation of the logs in Stackdriver.

This is what I had in mind: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/compare/logging-markers-example

In the sample code I introduce a new interface called `StackdriverJsonLayoutEnhancer` which allows users to add whatever additional metadata they want to the JSON representation ([example](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/compare/logging-markers-example#diff-3a062f21a9c8f1d6094a6bb4b1b5c3aa316f8c1828d18f9b3a0db726b261dc53)). You can specify which enhancers you want to use using the `<enhancer>` tag in logback [like this](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/compare/logging-markers-example#diff-27840b66978ba490ebbe35a0a63805c2f127b3611a7204607dee8effdcb16edd). This copies the convention of using "enhancers" in the logging appender as well.

We can consider also adding an additional package in our logging module called `extensions` which can be the [home of these enhancers](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/compare/logging-markers-example#diff-3a062f21a9c8f1d6094a6bb4b1b5c3aa316f8c1828d18f9b3a0db726b261dc53) in the future.

Does this make sense? I think this is a good way of supporting logstash while still being flexible enough to let the user customize how they want markers (or other metadata) to be printed.

**Comment by nhmarujo** [comment]
Hi @dzou. Yes, I think it is a way to achieve the same in a more decoupled and flexible way.

**Comment by dzou** [comment]
Ok, if you're happy with this direction I've created https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/208 to incorporate these changes.

**Comment by nhmarujo** [comment]
Hi @dzou. Thank you this. Looks like a good move 😄

**Comment by dzou** [comment]
Cool. I just merged it in; the feature will be available in our SNAPSHOT shortly or you can wait for the `2.0.1` release.

**Comment by nhmarujo** [comment]
Thank you so much for all the effort 😉

**Comment by dzou** [comment]
No problem.
