### ISSUE TITLE
Precision of timestampNanos in logs is miliseconds instead of nanoseconds

### ISSUE THREAD

**Issue by rafal-dudek** [GoogleCloudPlatform/spring-cloud-gcp#1996]
**Describe the bug**
StackdriverJsonLayout sets value of 'timestampNanos' log field as 
`TimeUnit.MILLISECONDS.toNanos(event.getTimeStamp() % 1_000)`  which has precision of miliseconds.
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java#L276
Proper value should be `event.getNanoseconds()`

This is causing out-of-order logs in GCP Logs Explorer in some cases.

**Sample**
```
    Logger log = LoggerFactory.getLogger(GenericSpringBootApplication.class);
    log.info("1");
    log.info("2");
    log.info("3");
    log.info("4");
    log.info("5");
```
Result in kubectl logs:

> {"timestampSeconds":1688547662,"timestampNanos":662000000,"severity":"INFO","thread":"scheduling-1","message":"1"}
{"timestampSeconds":1688547662,"timestampNanos":663000000,"severity":"INFO","thread":"scheduling-1","message":"2"}
{"timestampSeconds":1688547662,"timestampNanos":663000000,"severity":"INFO","thread":"scheduling-1","message":"3"}
{"timestampSeconds":1688547662,"timestampNanos":663000000,"severity":"INFO","thread":"scheduling-1","message":"4"}
{"timestampSeconds":1688547662,"timestampNanos":663000000,"severity":"INFO","thread":"scheduling-1","message":"5"}

Result in GCP Logs Explorer:
![image](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/32459286/86346ebf-20fd-4a66-8c5f-33560c5267b1)

**Comment by meltsufin** [comment]
Would you mind submitted a fix?
