### ISSUE TITLE
Trace publish does not stop even if the configuration is disabled

### ISSUE THREAD

**Issue by adirepo** [GoogleCloudPlatform/spring-cloud-gcp#2023]
Hi, I am using spring boot 2.7.12 with spring cloud 2021.0.7 and spring cloud gcp 3.5.0. I am running this spring boot app as a backend service on Google Cloud Run platform. I want to disable the trace collection on Strackdriver Trace as I no longer want them to be collected.

As per the configuration [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/5a6078ff71b560f1512f45460040e1cd1960f226/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/trace/StackdriverTraceAutoConfiguration.java#L69) and spring documentation, I am trying to use `spring.cloud.gcp.trace.enabled` this property from application.yml to disable the trace collection. However, despite of setting this property to `false`, the traces are still getting collected as shown in below image. Could you please help?

![1fElA](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/30016801/c9f2794a-8a8e-4600-b169-abd1f87baf6f)

Note: I am able to reproduce this issue even with spring boot 2.6.6, but with spring boot 2.3.2.RELEASE I do not see this problem.

**Comment by meltsufin** [comment]
This is strange as you can see that the auto-configuration class is conditioned on this property. Have you tried removing trace dependencies from you pom.xml?

**Comment by adirepo** [comment]
I just tried removing the `spring-cloud-gcp-starter-trace` dependency and re-deployed the module. Sadly, the traces are still getting published.

**Comment by adirepo** [comment]
Below is the dependency tree for my module:
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.7.12:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.7.12:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.7.12:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.7.12:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.7.12:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.12:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.17.2:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.36:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.30:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.7.12:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.5:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.5:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.13.5:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.5:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.5:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.5:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.7.12:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.75:compile
[INFO] |  |  +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.75:compile
[INFO] |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.75:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.27:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.3.27:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.27:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.3.27:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.27:compile
[INFO] +- com.google.cloud:spring-cloud-gcp-starter-pubsub:jar:3.5.0:compile
[INFO] |  +- com.google.cloud:spring-cloud-gcp-starter:jar:3.5.0:compile
[INFO] |  |  \- com.google.cloud:spring-cloud-gcp-autoconfigure:jar:3.5.0:compile
[INFO] |  +- com.google.cloud:spring-cloud-gcp-pubsub:jar:3.5.0:compile
[INFO] |  |  \- com.google.cloud:google-cloud-pubsub:jar:1.123.11:compile
[INFO] |  |     \- com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:1.105.11:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] +- com.google.cloud:spring-cloud-gcp-data-firestore:jar:3.5.0:compile
[INFO] |  +- com.google.cloud:google-cloud-firestore:jar:3.10.0:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core-grpc:jar:2.16.0:compile
[INFO] |  |  +- com.google.http-client:google-http-client:jar:1.43.1:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.14:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.16:compile
[INFO] |  |  +- io.opencensus:opencensus-contrib-http-util:jar:0.31.1:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-cloud-firestore-v1:jar:3.10.0:compile
[INFO] |  |  +- com.google.cloud:proto-google-cloud-firestore-bundle-v1:jar:3.10.0:compile
[INFO] |  |  +- com.google.auto.value:auto-value-annotations:jar:1.10.1:compile
[INFO] |  |  +- io.opencensus:opencensus-contrib-grpc-util:jar:0.31.1:compile
[INFO] |  |  +- io.grpc:grpc-core:jar:1.54.0:compile
[INFO] |  |  +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  |  +- org.codehaus.mojo:animal-sniffer-annotations:jar:1.23:runtime
[INFO] |  |  +- io.perfmark:perfmark-api:jar:0.26.0:runtime
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  +- com.google.api:api-common:jar:2.9.0:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.18.0:compile
[INFO] |  |  +- io.grpc:grpc-protobuf:jar:1.54.0:compile
[INFO] |  |  +- io.grpc:grpc-protobuf-lite:jar:1.54.0:compile
[INFO] |  |  +- io.grpc:grpc-context:jar:1.54.0:compile
[INFO] |  |  +- com.google.protobuf:protobuf-java:jar:3.21.12:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:2.17.0:compile
[INFO] |  |  +- com.google.api:gax:jar:2.26.0:compile
[INFO] |  |  +- com.google.auth:google-auth-library-oauth2-http:jar:1.16.0:compile
[INFO] |  |  +- io.grpc:grpc-api:jar:1.54.0:compile
[INFO] |  |  +- com.google.api:gax-grpc:jar:2.26.0:compile
[INFO] |  |  +- io.grpc:grpc-alts:jar:1.54.0:compile
[INFO] |  |  +- io.grpc:grpc-grpclb:jar:1.54.0:compile
[INFO] |  |  +- org.conscrypt:conscrypt-openjdk-uber:jar:2.5.2:compile
[INFO] |  |  +- io.grpc:grpc-auth:jar:1.54.0:compile
[INFO] |  |  +- io.grpc:grpc-netty-shaded:jar:1.54.0:compile
[INFO] |  |  +- io.grpc:grpc-googleapis:jar:1.54.0:runtime
[INFO] |  |  +- io.grpc:grpc-xds:jar:1.54.0:runtime
[INFO] |  |  +- io.opencensus:opencensus-proto:jar:0.2.0:runtime
[INFO] |  |  +- io.grpc:grpc-services:jar:1.54.0:runtime
[INFO] |  |  +- com.google.re2j:re2j:jar:1.6:runtime
[INFO] |  |  +- com.google.api:gax-httpjson:jar:0.111.0:compile
[INFO] |  |  +- com.google.http-client:google-http-client-gson:jar:1.43.1:compile
[INFO] |  |  +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.32.0:compile
[INFO] |  |  +- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  |  +- org.threeten:threetenbp:jar:1.6.8:compile
[INFO] |  |  +- io.grpc:grpc-stub:jar:1.54.0:compile
[INFO] |  |  +- io.opencensus:opencensus-api:jar:0.31.1:compile
[INFO] |  |  +- com.google.auth:google-auth-library-credentials:jar:1.16.0:compile
[INFO] |  |  +- com.google.cloud:google-cloud-core:jar:2.16.0:compile
[INFO] |  |  +- com.google.api.grpc:proto-google-iam-v1:jar:1.12.0:compile
[INFO] |  |  +- com.google.code.gson:gson:jar:2.9.1:compile
[INFO] |  |  \- com.google.protobuf:protobuf-java-util:jar:3.21.12:compile
[INFO] |  +- com.google.api.grpc:grpc-google-cloud-firestore-v1:jar:3.10.0:compile
[INFO] |  +- org.springframework:spring-core:jar:5.3.27:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.27:compile
[INFO] |  +- org.springframework.data:spring-data-commons:jar:2.7.12:compile
[INFO] |  +- org.springframework:spring-context:jar:5.3.27:compile
[INFO] |  +- org.springframework:spring-tx:jar:5.3.27:compile
[INFO] |  +- com.google.cloud:spring-cloud-gcp-core:jar:3.5.0:compile
[INFO] |  \- io.projectreactor:reactor-core:jar:3.4.29:compile
[INFO] |     \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] +- com.google.cloud:spring-cloud-gcp-starter-logging:jar:3.5.0:compile
[INFO] |  \- com.google.cloud:spring-cloud-gcp-logging:jar:3.5.0:compile
[INFO] |     +- ch.qos.logback.contrib:logback-json-classic:jar:0.1.5:compile
[INFO] |     |  \- ch.qos.logback.contrib:logback-json-core:jar:0.1.5:compile
[INFO] |     \- com.google.cloud:google-cloud-logging-logback:jar:0.130.11-alpha:compile
[INFO] |        +- ch.qos.logback:logback-core:jar:1.2.12:compile
[INFO] |        +- com.google.cloud:google-cloud-logging:jar:3.14.9:compile
[INFO] |        +- com.google.api.grpc:proto-google-cloud-logging-v2:jar:0.103.9:compile
[INFO] |        \- org.jspecify:jspecify:jar:0.2.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.7.12:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.7.12:compile
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.7:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.7.12:compile
[INFO] |  |  +- com.zaxxer:HikariCP:jar:4.0.3:compile
[INFO] |  |  \- org.springframework:spring-jdbc:jar:5.3.27:compile
[INFO] |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  +- jakarta.persistence:jakarta.persistence-api:jar:2.2.3:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.6.15.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.4.3.Final:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.12.23:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.4.2.Final:compile
[INFO] |  |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.8:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.8:compile
[INFO] |  |     +- com.sun.istack:istack-commons-runtime:jar:3.0.12:compile
[INFO] |  |     \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
[INFO] |  +- org.springframework.data:spring-data-jpa:jar:2.7.12:compile
[INFO] |  |  \- org.springframework:spring-orm:jar:5.3.27:compile
[INFO] |  \- org.springframework:spring-aspects:jar:5.3.27:compile
[INFO] +- com.google.cloud:spring-cloud-gcp-starter-sql-postgresql:jar:3.5.0:compile
[INFO] |  +- com.google.cloud.sql:postgres-socket-factory:jar:1.11.1:compile
[INFO] |  |  \- com.google.cloud.sql:jdbc-socket-factory-core:jar:1.11.1:compile
[INFO] |  |     +- dev.failsafe:failsafe:jar:3.3.1:compile
[INFO] |  |     +- com.github.jnr:jnr-unixsocket:jar:0.38.19:compile
[INFO] |  |     |  +- com.github.jnr:jnr-ffi:jar:2.2.13:compile
[INFO] |  |     |  |  +- com.github.jnr:jffi:jar:1.3.10:compile
[INFO] |  |     |  |  +- com.github.jnr:jffi:jar:native:1.3.10:runtime
[INFO] |  |     |  |  +- org.ow2.asm:asm-commons:jar:9.2:compile
[INFO] |  |     |  |  +- com.github.jnr:jnr-a64asm:jar:1.0.0:compile
[INFO] |  |     |  |  \- com.github.jnr:jnr-x86asm:jar:1.0.2:compile
[INFO] |  |     |  +- com.github.jnr:jnr-constants:jar:0.10.4:compile
[INFO] |  |     |  +- com.github.jnr:jnr-enxio:jar:0.32.14:compile
[INFO] |  |     |  \- com.github.jnr:jnr-posix:jar:3.1.16:compile
[INFO] |  |     +- org.ow2.asm:asm-util:jar:9.5:compile
[INFO] |  |     |  +- org.ow2.asm:asm:jar:9.5:compile
[INFO] |  |     |  +- org.ow2.asm:asm-tree:jar:9.5:compile
[INFO] |  |     |  \- org.ow2.asm:asm-analysis:jar:9.5:compile
[INFO] |  |     +- com.google.api-client:google-api-client:jar:2.2.0:compile
[INFO] |  |     |  \- com.google.http-client:google-http-client-apache-v2:jar:1.43.1:compile
[INFO] |  |     +- org.checkerframework:checker-compat-qual:jar:2.5.5:compile
[INFO] |  |     +- com.google.apis:google-api-services-sqladmin:jar:v1beta4-rev20230403-2.0.0:compile
[INFO] |  |     \- com.google.oauth-client:google-oauth-client:jar:1.34.1:compile
[INFO] |  \- org.postgresql:postgresql:jar:42.3.8:compile
[INFO] +- org.springframework.retry:spring-retry:jar:1.3.4:compile
[INFO] +- org.projectlombok:lombok:jar:1.18.26:compile
[INFO] +- com.opencsv:opencsv:jar:5.2:compile
[INFO] |  +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] |  +- org.apache.commons:commons-text:jar:1.8:compile
[INFO] |  +- commons-beanutils:commons-beanutils:jar:1.9.4:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  \- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  \- org.apache.commons:commons-pool2:jar:2.11.1:compile
[INFO] +- com.h2database:h2:jar:2.1.214:test
[INFO] +- org.springframework.boot:spring-boot-starter-data-redis-reactive:jar:2.7.12:compile
[INFO] |  \- org.springframework.boot:spring-boot-starter-data-redis:jar:2.7.12:compile
[INFO] |     +- org.springframework.data:spring-data-redis:jar:2.7.12:compile
[INFO] |     |  +- org.springframework.data:spring-data-keyvalue:jar:2.7.12:compile
[INFO] |     |  +- org.springframework:spring-oxm:jar:5.3.27:compile
[INFO] |     |  \- org.springframework:spring-context-support:jar:5.3.27:compile
[INFO] |     \- io.lettuce:lettuce-core:jar:6.1.10.RELEASE:compile
[INFO] |        +- io.netty:netty-common:jar:4.1.92.Final:compile
[INFO] |        +- io.netty:netty-handler:jar:4.1.92.Final:compile
[INFO] |        |  +- io.netty:netty-resolver:jar:4.1.92.Final:compile
[INFO] |        |  +- io.netty:netty-buffer:jar:4.1.92.Final:compile
[INFO] |        |  +- io.netty:netty-transport-native-unix-common:jar:4.1.92.Final:compile
[INFO] |        |  \- io.netty:netty-codec:jar:4.1.92.Final:compile
[INFO] |        \- io.netty:netty-transport:jar:4.1.92.Final:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.7.12:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.7.12:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.7.12:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.7.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.11:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.11:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.22.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.8.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.8.2:test
[INFO] |  +- org.mockito:mockito-core:jar:4.5.1:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.23:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:4.5.1:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.1:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-test:jar:5.3.27:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.1:test
[INFO] +- org.springframework.security:spring-security-test:jar:5.7.8:test
[INFO] |  +- org.springframework.security:spring-security-core:jar:5.7.8:test
[INFO] |  |  \- org.springframework.security:spring-security-crypto:jar:5.7.8:test
[INFO] |  \- org.springframework.security:spring-security-web:jar:5.7.8:test
[INFO] \- junit:junit:jar:4.13.2:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:2.2:test

**Comment by adirepo** [comment]
Also attaching here the autoconfiguration output. Do you happen to see anything suspicious here? 🤔

[autoconfiguratio_debug.txt](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/files/12063589/autoconfiguratio_debug.txt)

**Comment by burkedavison** [comment]
Closing this issue due to lack of OP response. Please reopen if necessary.
