### ISSUE TITLE
Autoconfigure R2DBC support for Cloud SQL

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#205]
When using the Spring Cloud GCP Cloud SQL PostgreSQL starter (`spring-cloud-gcp-starter-sql-postgresql`) you get a JDBC-based stack using `org.springframework.boot:spring-boot-starter-jdbc` and the `org.postgresql:postgresql` JDBC driver.

For Spring WebFlux applications I would like to be able to use Cloud SQL via [R2DBC](https://r2dbc.io) instead of JDBC.

I can use R2DBC with Spring Boot and a plain PostgreSQL database via `org.springframework.boot:spring-boot-starter-data-r2dbc` and the `io.r2dbc:r2dbc-postgresql` R2DBC driver for PostgreSQL.

I have found https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/master/r2dbc-postgres and an example project at https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/cloud-sql/r2dbc that shows what dependencies to add and how to create a `ConnectionFactory` bean, but it would be great if Spring Cloud GCP would have a starter and auto-configuration for this, so Spring Cloud GCP users don't need to manage and configure these dependencies.

**Comment by ttomsu** [comment]
Sounds like a great idea. I don't think we have the bandwidth to support it at the moment but once https://github.com/GoogleCloudPlatform/cloud-spanner-r2dbc maybe @elefeint would want to take a stab at Cloud SQL :stuck_out_tongue_winking_eye:

**Comment by olaf-2** [comment]
That would be great. Currently I use an authorized static outgoing IP address for my Cloud Run services as a workaround.

**Comment by elefeint** [comment]
@olaf-2 Have you tried using https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory ? This issue is to simplify setting it up, but the mechanism is there already.

**Comment by olaf-2** [comment]
Yes, did not work. Now I retried with this little :gcp: in the URL I had overlooked and it works. (⌒_⌒;)
Thanks.

**Comment by chanseokoh** [comment]
@elefeint with https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory, I guess then the issue no longer stands?

**Comment by elefeint** [comment]
It does in that we can make the correct `ConnectionFactory` creation automatic given a dependency on R2DBC and socket factory.
I'll update the issue title to reflect that.
