### ISSUE TITLE
The spring-cloud-gcp-pubsub-stream-dead-letter-sample 

### ISSUE THREAD

**Issue by mayur-solace** [GoogleCloudPlatform/spring-cloud-gcp#2061]
I'm running below sample in the Google Cloud Shell as per the instruction in the README.adoc of the sample. 
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-dead-letter-sample

The sample application runs, however as expected the message is not moved to dead letter topic after 6 attempts. 
Refer the screenshot below.

<img width="1792" alt="image" src="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/81177023/001aa7cf-4570-49bf-b5a2-029ba989c0f3">

Tried running the sample on my local too and I see behaviour as Google Cloud Shell.

**Comment by meltsufin** [comment]
It's working in our CI:
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/5657976387/job/15328261647#step:11:8386

**Comment by mayur-solace** [comment]
Thanks for pointing me to the integration tests. 

I don't understand step# 4 in the https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-samples/spring-cloud-gcp-pubsub-stream-dead-letter-sample/README.adoc 

I will try to learn more about it and then give it a shot again. Closing this issue.
