### ISSUE TITLE
Provide helper classes to make it easer to write custom serializers for FirestoreTemplate

### ISSUE THREAD

**Issue by PojahnM** [GoogleCloudPlatform/spring-cloud-gcp#209]
Spring Cloud GCP already provide a way to write custom mappers to `FirestoreTemplate`(`FirestoreClassMapper`). This feature is partially important if you use data classes in Kotlin(or records in Java 14) because the default deserializer works poorly with these.  

It's however hard to write custom converters, mostly because all convenient util-methods in Google libs are package private(which makes sense because Googles API does not support custom mappers AFAIK). 
Currently, all we have is `public Map<String, Value> getFieldsMap()` in class `Document`. `Value` can be 11 different types and can contain nested maps. To sum up, here's what every developer using spring and want to write a custom serializer have to do:
- Sub string the document name to get the id
- Use reflection to find the id field name
- Traverse the map(returned by `getFieldsMap`)
- Decode `Value`(11 different types)

Also worth noting that it's not possible to copy googles decode function fully because it uses objects that we can't create or don't have access to.

**Comment by dzou** [comment]
@PojahnM -- Thanks for the report. Yeah sure, we can add support for this.

Just want to make sure I understand, are you interested in writing custom converters for how the values in `Map<String, Value> getFieldsMap()` get converted into the fields of an entity?

Or if I am misunderstanding could you provide an example? It sounds like you would like to customize the conversion behavior in the `FirestoreClassMapper` and plug in custom converters to be used when `Documents` are mapped to your user-defined entities/objects?

**Comment by PojahnM** [comment]
Hm... You know I am not sure what kind if util methods I wanted when I wrote this. I implemented something after I wrote this and they turned out too specific to my use case. 

But the initial problem is general. The built-in converter by Google requires a no-arg constructor or else it fails. For example, in Kotlin, you have to create a data class that look could look like this:

```kotlin
data class User(
    val id: String = "",
    val username: String = "",
    val state: SomeEnum = SomeEnum.SomeValue,
    val nestedObject: SomeNestedObject("", "", 0, listOf())
)
```

And something similar with Java 14 records(https://stackoverflow.com/a/61152747). 
This is not ideal because you can have large objects with nested fields and some objects such as enums do not have a default value. Also in Kotlin, the compiler will go easy on you. In theory, this will compile: `val user = User("id")` because of the default values.

So with the default Firestore converter, the code becomes harder to maintain, more error prone and unintuitive. 

I have no idea what sort of utils methods would be needed to help this. I wrote a custom converter that uses Jackson to convert a document to an entity which works great but have other issues.

I will close this because I feel like it's incomplete.

**Comment by dzou** [comment]
Gotcha I see, thanks for the update. Let us know if something comes up again.

You may also consider opening a request in the [Standard Java Firestore Client libraries](https://github.com/googleapis/java-firestore) (not targeting Spring framework). This is the core library we depend on and certain changes may need to be made upstream there.
