### ISSUE TITLE
PathResourceResolver can't resolve a GoogleStorageResource due to no Google Storage UrlStreamHandler

### ISSUE THREAD

**Issue by jhordies** [GoogleCloudPlatform/spring-cloud-gcp#210]
When trying to use a Google Storage Resource as the spring static resource location the PathResourceResolver calls the method isResourceUnderLocation that calls the GoogleStorageResource.toURL() that throws a MalformedURLException because no URL stream handler is registered for the gs protocol (as stated by the documentation)

**Sample**
Add the following dependecy to your project:
```xml
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-gcp-starter-storage</artifactId>
		</dependency>
```
Set the following property in you project:
spring.resources.static-locations=gs://[YOUR_GCS_BUCKET]/

If this is a public bucket (allUsers with Storage read permission) and no credentials are needed, use the following config class:
```java
@Configuration
public class BucketResourceConfig {

    @Bean
    public Storage storage() throws IOException {
        return StorageOptions.newBuilder()
                .setHeaderProvider(
                        new UserAgentHeaderProvider(GcpStorageAutoConfiguration.class))
                .build().getService();
    }

    @Bean
    public CredentialsProvider googleCredentials() throws Exception {
        return new NoCredentialsProvider();
    }
}
```
Assuming the root of the bucket contains a index.html
Call your server with http://host:port/index.html 
Put a breakpoint in PathResourceResolver.isResourceUnderLocation(...)
and see it fail to call resource.getURL() even though resource.getInputStream() would return the index.html

**Comment by ttomsu** [comment]
Can you provide more details of your environment, specifically which version of Spring Cloud GCP, which Spring Cloud version, and which Spring Boot version you're using?

**Comment by ttomsu** [comment]
Could you also point me to what documentation you're referring?

**Comment by jhordies** [comment]
Hi,
> Could you also point me to what documentation you're referring?
I meant the javadoc of GoogleStorageResource
	/**
	 * Since the gs: protocol will normally not have a URL stream handler registered,
	 * this method will always throw a {@link java.net.MalformedURLException}.
	 * @return the URL for the GCS resource, if a URL stream handler is registered for the gs protocol.
	 */
	@Override
	public URL getURL() throws IOException {
		return getURI().toURL();
	}


> Can you provide more details of your environment, specifically which version of Spring Cloud GCP, which Spring Cloud version, and which Spring Boot version you're using?

       <groupId>org.springframework.cloud</groupId>
       <artifactId>spring-cloud-gcp-dependencies</artifactId>
       <version>1.2.6.RELEASE</version>

      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>2.3.4.RELEASE</version>

Thanks

**Comment by ttomsu** [comment]
And to what documentation are you looking at and following?

**Comment by jhordies** [comment]
> And to what documentation are you looking at and following?

None in particular,
I just read 
https://cloud.spring.io/spring-cloud-gcp/multi/multi__spring_resources.html
https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.2.0.RELEASE/reference/html/

And as the GoogleStorageResource should be of type Spring Resources (abstraction for a number of low-level resources, such as file system files, classpath files, servlet context-relative files, etc.)
I expected to use it as a a spring.resources.static-locations without any customization in Spring.

I made it work by overriding checkResource/isReourceUnderLocation from the PathResourceResolver as follows to treat the GoogleStorageResource specifically by returning resource.exists() and so avoid calling resource.getURL().getPath() that would trigger the exception : 

`
    private class SinglePageAppResourceResolver extends PathResourceResolver
    {
        @Override
        protected boolean checkResource(Resource resource, Resource location) throws IOException {
            if (isResourceUnderLocation(resource, location)) {
                return true;
            }
            Resource[] allowedLocations = getAllowedLocations();
            if (allowedLocations != null) {
                for (Resource current : allowedLocations) {
                    if (isResourceUnderLocation(resource, current)) {
                        return true;
                    }
                }
            }
            return false;
        }

        private boolean isResourceUnderLocation(Resource resource, Resource location) throws IOException {
            if (resource.getClass() != location.getClass()) {
                return false;
            }

            String resourcePath;
            String locationPath;

            if (resource instanceof UrlResource) {
                resourcePath = resource.getURL().toExternalForm();
                locationPath = StringUtils.cleanPath(location.getURL().toString());
            }
            else if (resource instanceof ClassPathResource) {
                resourcePath = ((ClassPathResource) resource).getPath();
                locationPath = StringUtils.cleanPath(((ClassPathResource) location).getPath());
            }
            else if (resource instanceof ServletContextResource) {
                resourcePath = ((ServletContextResource) resource).getPath();
                locationPath = StringUtils.cleanPath(((ServletContextResource) location).getPath());
            }
            else if(resource instanceof GoogleStorageResource){
                return resource.exists();
            }
            else {
                resourcePath = resource.getURL().getPath();
                locationPath = StringUtils.cleanPath(location.getURL().getPath());
            }

            if (locationPath.equals(resourcePath)) {
                return true;
            }
            locationPath = (locationPath.endsWith("/") || locationPath.isEmpty() ? locationPath : locationPath + "/");
            return (resourcePath.startsWith(locationPath) && !isInvalidEncodedPath(resourcePath));
        }

        private boolean isInvalidEncodedPath(String resourcePath) {
            if (resourcePath.contains("%")) {
                // Use URLDecoder (vs UriUtils) to preserve potentially decoded UTF-8 chars...
                try {
                    String decodedPath = URLDecoder.decode(resourcePath, "UTF-8");
                    if (decodedPath.contains("../") || decodedPath.contains("..\\")) {
                        logger.warn("Resolved resource path contains encoded \"../\" or \"..\\\": " + resourcePath);
                        return true;
                    }
                }
                catch (IllegalArgumentException ex) {
                    // May not be possible to decode...
                }
                catch (UnsupportedEncodingException ex) {
                    // Should never happen...
                }
            }
            return false;
        }
    }
`

The use it like this:

`@Configuration
public class SinglePageAppWebMvcConfigurer extends WebMvcConfigurerAdapter
{
    @Autowired
    private ResourceProperties resourceProperties;

    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry)
    {
        registry.addResourceHandler("/**")
                .addResourceLocations(resourceProperties.getStaticLocations())
                .resourceChain(true)
                .addResolver(new SinglePageAppResourceResolver());
    }
}`

**Comment by jhordies** [comment]
Thanks for the fix.
Regards
