### ISSUE TITLE
spring.cloud.gcp.sql.enabled is ignored if specified in application.properties

### ISSUE THREAD

**Issue by Dattish** [GoogleCloudPlatform/spring-cloud-gcp#215]
**Describe the bug**
Introduced in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/131

The `spring.cloud.gcp.sql.enabled` variable is ignored if it's set using `application.properties`.
I'm not sure if this is a deliberate design choice since `EnvironmentPostProcessor` runs before those properties are applied.

**Comment by dzou** [comment]
Thanks for the report. Interesting, I didn't realize that the settings were be overridden; I don't think this was an intentional design choice.

So when you say

> The spring.cloud.gcp.sql.enabled variable is ignored if it's set using application.properties.

Did you mean to imply you found somewhere else to set it where it is not ignored? Or is it simply not working altogether?

**Comment by Dattish** [comment]
> So when you say
> 
> > The spring.cloud.gcp.sql.enabled variable is ignored if it's set using application.properties.
> 
> Did you mean to imply you found somewhere else to set it where it is not ignored? Or is it simply not working altogether?

Ah yes sorry, looks like my last paragraph went missing. I managed to set the variable using OS environment variables as well as using `bootstrap.properties` while a configuration class with `@PropertySource` didn't work.

**Comment by meltsufin** [comment]
@Dattish I'm not able to reproduce this issue. I've just tried modifying [our MySQL sample](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-sql-mysql-sample), and if I add `spring.cloud.gcp.sql.enabled=false` to `application.properties`, it breaks for me, as expected.

Can you provide a repro?

**Comment by Dattish** [comment]
> Can you provide a repro?
@meltsufin 
After trying to reproduce it with a clean project for a bit I've realized that this is probably some strange interaction between the different spring dependencies we use in the project where the bug occurred.

When we test database stuff at my workplace we usually use [testcontainers](https://github.com/Playtika/testcontainers-spring-boot) to spin up docker containers for databases, which is also why we want to disable spring cloud gcp sql. That dependency requires spring-cloud-starter-bootstrap if you usually don't use spring-cloud.

Here's an [example](https://github.com/Dattish/spring-bug-repro), you can just run the test to make it crash if you have docker installed. The issue seems to arise whenever you have both spring-cloud-starter-bootstrap and a spring-cloud-gcp-starter dependency in the classpath. If you replace the spring-cloud-gcp-starter dependency with the ones commented out below it it works.

I feel like this might not be a usual (or intended) usecase so perhaps we should just close the issue since the workarounds might be good enough if you really want to do this.

**Comment by meltsufin** [comment]
@Dattish I think you're right that this has something to do with using bootstrap dependencies. In your setup, when Spring invokes the `CloudSqlEnvironmentPostProcessor` it doesn't see properties from `application.properties`. Of course, if you remove `spring-cloud-gcp-starter-sql-postgresql` from your `pom.xml` `CloudSqlEnvironmentPostProcessor` will be disabled because it won't be on the classpath anymore.

cc/ @snicoll In case you have some insight on why an `EnvironmentPostProcessor` might not be able to see `application.properties` when `boostrap.properties` is in the picture.

**Comment by snicoll** [comment]
If the `EnvironmentPostProcessor` runs in the bootstrap context, it can only see what Spring Cloud has initiated. At that point, the application actually hasn't even started and none of the usual environment preparation has happened yet. 

This is unfortunately a limitation of how the bootstrap context was designed and that lead to significant issues when using this feature with Spring Cloud Config Server (see https://github.com/spring-cloud/spring-cloud-commons/issues/737 for instance). The good news is that Spring Cloud `2020.0` has deprecated the bootstrap context in favour of a new mechnism introduced in Spring Boot 2.4 that makes this problem go away, see https://github.com/spring-cloud/spring-cloud-commons/issues/608#issuecomment-626340364.

**Comment by dzou** [comment]
@meltsufin -- To fix this this probably means we need to revisit how to implement the `spring.config.import` thing for Secret Manager and our Runtime Config: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/149
