### ISSUE TITLE
Failing to connect to MySQL DB deployed as PCF service

### ISSUE THREAD

**Issue by rohithkk** [GoogleCloudPlatform/spring-cloud-gcp#2153]
We have PCF deployed on GCP. I have configured MySQL Database as a PCF service and refer to that service in our app manifest file.
This application was working as expected with Springboot 2.7.x version. I'm trying to upgrade this to Springboot 3.x so I changed the spring-cloud-gcp-starter dependencies to 4.5.x version. 

When the application tries to start, it is failing to connect to the Database. I see following error in the logs.

`DEBUG HikariConfig.logConfiguration:1132 - jdbcUrl.........................jdbc:mysql://google/pcf-sb-3-1617999200207369658?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=pcf02-235316:us-central1:public-member-experience-mysql-dev
`
`Caused by: java.lang.ClassCastException: class com.google.cloud.sql.mysql.SocketFactory cannot be cast to class javax.net.SocketFactory (com.google.cloud.sql.mysql.SocketFactory is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @13c78c0b; javax.net.SocketFactory is in module java.base of loader 'bootstrap')
`

the jdbcUrl looks weird. Why is there a socketFactory added as part of the connection string? Is that expected? What do I need to change to connect to the service?

**application.properties**
```
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.database=mysql
spring.sql.init.platform=mysql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true
spring.jpa.show-sql=true
```

**Comment by meltsufin** [comment]
The socket factory is expected if you are trying to use integrated authentication. I think you want to just disable the Cloud SQL auto-configuration and use the database directly. Try adding `spring.cloud.gcp.sql.enabled=false`.

**Comment by burkedavison** [comment]
Closing as resolved due to lack of response. Please reopen if there is still an issue.
