### ISSUE TITLE
Can't read secrets from Secret Manager when deployed from docker container in Cloud Run.

### ISSUE THREAD

**Issue by bondar-artem** [GoogleCloudPlatform/spring-cloud-gcp#2281]
**Description:** 
When application is built with Docker container using "spring-cloud-gcp-starter-secretmanager" to read secrets from Secret Manager, application not able to get access to secrets. The primary reason is that Secret Manager uses path to secret in the format `"projects/{PROJECT NUMBER}/secrets/{SECRET NAME}"`, but application during the deployment trying to access path `"projects/{PROJECT ID}/secrets/{SECRET NAME}"`. Since this path does not exist, application is not able to read secrets from the Secret Manager.
When the same application deployed without a Docker container - everything is working fine.

**Demo Examples**
For this demo was used a sample Spring Boot application described in this guide: [URL](https://codelabs.developers.google.com/codelabs/cloud-spring-cloud-gcp-secret-manager#0)
The ready-to-use sample can be found in this repo: [URL](https://github.com/bondar-artem/test-cloud-red)

**Steps to reproduce**

No-container flow:
1. Login to Gcloud, create a new project. Navigate to secret manager and create a new secret with name "greeting" and value "Hello"
2. Open a new gcloud terminal
3. Clone the repo: `git clone https://github.com/bondar-artem/test-cloud-red.git`
4. Navigate to the project folder: `cd test-cloud-red`
5. Export JAVA_HOME: `export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/`
6. Run application: `./mvnw -DskipTests spring-boot:run`
7. Click on "Web Preview" button in the terminal. Application is opened on port 8080 with displayed message "Hello World!". The text "Hello" was obtained from a Secret Manager which was saved under a key "greeting" in the step 1. Everything is working as expected.

Deploy with Docker Container:
1. Navigate to the project folder: `cd test-cloud-red`
2. Make sure that docker is configured on glcoud: `gcloud auth configure-docker`
3. Build a new Docker image with Jib and push to container registry: `mvn compile jib:build`
_Note: you may need to change property `google-project-id` in pom.xml to your Project ID. Project ID should be the same in step 4 as well._
4. Deploy container to Cloud Run: `gcloud run deploy demo-app --image=gcr.io/test-secret-402616/demo:latest --platform managed --region us-central1`
5. Application build fails. Navigate to "Cloud Run", select "demo-app" project, click "Logs". Scroll down to see the error message: `PERMISSION_DENIED: Permission 'secretmanager.versions.access' denied for resource 'projects/test-secret-402616/secrets/greeting/versions/latest' (or it may not exist).`

<img width="1408" alt="Logs – demo-app – Cloud Run – Test-secret – Google Cloud console 🔊 2023-10-21 10-49-13" src="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/21285622/46aaa2de-dec6-425f-8d55-b2a6d21bcec0">

At first it may seem that problem is the user permission. But it's not. The scenario was executed as OWNER so it has a higher level permissions. The problem is the path application trying to reach to a Secret Manager, because actual path is different:
<img width="515" alt="Security – Test-secret – Google Cloud console 🔊 2023-10-21 10-51-31" src="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/21285622/ae312147-f4a1-4773-9843-3d370af5eca6">

During the debugging process I clearly saw in the logs, that when application deployed without a Docker, it's reaching secret value based on Project Number. For some reason, when ran in Docker, its trying to use Proejct ID instead.

Also I was thinking that Jib plugin causing his, so I tried the build with just a Dockerfile, and received the same error.

Demo repo also have Github action workflow. Feel free to try it out. Only need to set up the service account on Gcloud side.
Follow the steps 1 to 10 in this guide to set it up: [URL](https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)

**Comment by burkedavison** [comment]
Hello @bondar-artem ,

How have you verified that the docker container contains correct credentials?  In the no-container workflow, the Cloud Shell terminal prompts for credentials which allows gcloud application-default to provide them during the client library request. By contrast, the docker setup described contains no credentials.

If no credentials are provided in the docker container, the error message received would make sense: the server would be unable to find the project --> so it would mean it's unable to find the project number --> so it would not be able to find the secret --> so it produces an error that states that either permissions don't exist, or the secret doesn't exist.

**Comment by bondar-artem** [comment]
@burkedavison thank you for the reply.
How the credentials should be provided in the container?
If I build the container in the Cloud Shell, so it means that I build in on behalf of the user who authorized in that shell, isnt it?

Server is actually able to find the project. You can see in the log, it reaches the project by Project-ID, so it understands what kind of project it's trying to reach.

**Comment by burkedavison** [comment]
Hey @bondar-artem ,

I replicated the error and resolved it by assigning the "Secret Manager Secret Accessor" role to the compute engine service account that is used by Cloud Run. You can find the compute engine service account's name by going to the [Service Account page](https://pantheon.corp.google.com/iam-admin/serviceaccounts), then assigning it the accessor role from the [IAM page](https://pantheon.corp.google.com/iam-admin/iam).

This allowed the container to correctly start up.

If you then have issues with the *.run.app link working, take a look at https://cloud.google.com/run/docs/authenticating/public

**Comment by bondar-artem** [comment]
@burkedavison 
Thanks for looking into that!
I am surprised to hear how it could work for you?
I have assigned to my service account the role of "Owner" which is the role that can perform anything.
Also I tried the "Secret Manager Secret Accessor" account for my GitHub Actions service account and no luck, it didn't work.

Could you try to reproduce it on your end?
The repo that I have provided have already configured GitHub actions yml file that uses GitHub workload identity provider. You just need to configure your own service and replace it in yaml file.

**Comment by burkedavison** [comment]
I was able to replicate both the error and resolve it by assign the role.

When you say you've assigned "your service account the role of Owner", is it the compute engine's service account for your project? It should be `<project-number>-compute@developer.gserviceaccount.com` that you've assigned this permission to.

**Comment by bondar-artem** [comment]
I am talking about IAM & Admin tab. Here is how it looks for me:
<img width="1446" alt="IAM – IAM   Admin – Test-secret – Google Cloud console 2023-10-23 16-47-09" src="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/21285622/6e0f69e9-ea16-4887-a572-e9517c3623df">

Under the "Service account" I have account used to authorize with GitHub. It also have "Owner" permissions

<img width="1800" alt="my-service-account@test-secret-402616 iam gservice" src="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/21285622/602655ce-4121-4e3b-86f7-ee826b3504f0">

I don't use Compute Engine. I use Cloud Run.

**Comment by burkedavison** [comment]
[By default, Cloud Run services or jobs run as the default Compute Engine service account.](https://cloud.google.com/run/docs/configuring/jobs/service-accounts)

To [deploy using a user-managed service account](https://cloud.google.com/run/docs/securing/service-identity#gcloud), the gcloud command would need to include a `--service-account` parameter.

**Comment by bondar-artem** [comment]
Oh my god! Thank you @burkedavison !!!
That `--service-account` flag did the magic! :) It's finally working :)

**Comment by jankos11** [comment]
> I was able to replicate both the error and resolve it by assign the role.
> 
> When you say you've assigned "your service account the role of Owner", is it the compute engine's service account for your project? It should be `<project-number>-compute@developer.gserviceaccount.com` that you've assigned this role to.

This solution also resolve my problem, thanks a lot @burkedavison
