### ISSUE TITLE
Compatibility with upcoming Spring Boot 3.2 / Spring Cloud 2023.0

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#2301]
[Compatibility with Spring Project Versions](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/new?assignees=&labels=waiting-for-triage&projects=&template=bug_report.md&title=#compatibility-with-spring-project-versions) currently shows that Spring Cloud GCP 4.x is compatible with Spring Boot 3.x.

Spring Boot 3.2 (based on Spring Framework 6.1) will be released next month, and if you want to use that with Spring Cloud, as far as I know that will require an update to the upcoming Spring Cloud 2023.0.

Am I correct in thinking that Spring Cloud GCP 4.x won't be compatible with Spring Boot 3.2, and that the compatibility of Spring Cloud GCP 4.x should be changed from `3.x` to `3.0.x, 3.1.x`, and the compatibility of Spring Framework from `6.x` to `6.0.x`?

**Comment by meltsufin** [comment]
@burkedavison We should check if we're compatible with Spring Boot 3.2. Our preference would be not to introduce a new major version, and skimming through release notes, it doesn't look we will need to.

**Comment by breun** [comment]
If Spring Cloud GCP 4.x is (or can be made) compatible with both Spring Cloud 2022.0 and 2023.0, and Spring Boot 3.2, that would be great of course.

[Spring Boot 3.2.0-RC1 is out](https://spring.io/blog/2023/10/20/spring-boot-3-2-0-rc1-available-now), and 3.2.0-RC2 will be released on November 2nd. Final release on November 23rd. https://github.com/spring-projects/spring-boot/milestones

Spring Cloud 2023.0.0-RC1 was scheduled to be released 3 days ago, but is still pending. Spring Cloud 2023.0.0 is scheduled for release on November 28th. https://github.com/spring-cloud/spring-cloud-release/milestones

**Comment by Harmelodic** [comment]
Heyo so, both [Spring Boot 3.2.0](https://spring.io/blog/2023/11/23/spring-boot-3-2-0-available-now) is out, and [Spring Cloud 2023.0.0](https://spring.io/blog/2023/12/06/spring-cloud-2023-0-0-aka-leyton-is-now-available) is out.

Is there an idea/ETA for when Spring Cloud GCP's compatibility will be available?

**Comment by sleicht** [comment]
Looks like this is resolved with #2397, or is something still missing?

**Comment by Harmelodic** [comment]
Indeed! Looks like #2397 got merged and [4.9.0 got released](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/releases/tag/v4.9.0) which includes the point in the release note:

> - backport Spring Boot 3.2 compatibility updates to Spring Cloud GCP 4.x

Haven't tested it myself, but I suspect this is resolved.

**Comment by anbusampath** [comment]
> Looks like this is resolved with #2397, or is something still missing?

Looks like Spring Boot 3.2/Spring Cloud 2023 compatibility tested and reverted to Spring Boot 3.1.5 and Spring Cloud 2022.0.4. May be next minor release(4.10) will have proper dependency updates.

**Comment by anbusampath** [comment]
> May be next minor release(4.10) will have proper dependency updates.

We got major release - https://github.com/GoogleCloudPlatform/spring-cloud-gcp/releases/tag/v5.0.0

**Comment by burkedavison** [comment]
Major release 5.0.0 is still building and will be available in Maven soon.

**Comment by anbusampath** [comment]
> Major release 5.0.0

is it compatible with Java 21?

**Comment by breun** [comment]
Closing this issue due to the release of [5.0.0](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/releases/tag/v5.0.0), which is compatible with Spring Boot 3.2 and Spring Cloud 2023.0.

**Comment by burkedavison** [comment]
> is it compatible with Java 21?

We currently verify compatibility with Java 21 in our unit test CI: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/.github/workflows/unitTests.yaml#L23
