### ISSUE TITLE
Spring Cloud Stream Unable to setup subscription to a topic in a different GCP project

### ISSUE THREAD

**Issue by maganv** [GoogleCloudPlatform/spring-cloud-gcp#232]
Our application is consuming messages from a topic that is setup in another team's GCP project.
Example topic name: "projects/team-a/topics/topic-1". Our application runs in "team-b" project. Since the projects are different we need to use the full topic name in the "destination" otherwise the `PubSubChannelProvisioner`
does not find the topic (`makeSureTopicExists`-method). But then the subscription name will be "illegal" since the expected subscription name is `<topicName>.<group>`.

`spring-cloud-gcp-pubsub-stream-binder` version: 2.0.0
This is the configuration:
```
spring.cloud.stream.bindings.input.destination=projects/team-a/topics/topic-1
spring.cloud.stream.bindings.input.group=my-event-handler
```

Is there a way to set it up that I am missing?

If is not possible today, a solution could be that if the topic name contains "/" the right-most value could be used when getting the subscription. 
In the above case the expected subscription name would be "topic-1.my-event-handler".

**Comment by meltsufin** [comment]
@maganv This is a really good question. Looking at it, our `PubSubChannelProvisioner#provisionConsumerDestination` is not aware of fully-qualified topic names. So, it composes something like `projects/team-a/topics/topic-1.my-event-handler` which is invalid both as a short name and as a fully qualified name of a subscription. We can probably fix it, but I'm wondering what you would expect the subscription name to be? Would you want it to be created in project `team-a` or where application is running under `team-b`?

**Comment by maganv** [comment]
In our case we would create the subscription manually in project `team-b` i.e. the same project as the application is running. So if the topic's fully qualified name is `projects/team-a/topics/topic-1` we want to use the subscription with id/short-name `topic-1.my-event-handler` in project `team-b`, fully qualified name would be `projects/team-b/subscriptions/topic-1.my-event-handler`

If the topic was created in the same project as the application is using, i.e. `projects/team-b/topics/topic-1` the configuration would be like this:
```
spring.cloud.stream.bindings.input.destination=topic-1
spring.cloud.stream.bindings.input.group=my-event-handler
```
And it would use the subscription `projects/team-b/subscriptions/topic-1.my-event-handler`. We would like to achieve the same naming convention of the subscription even if the topic is in a different project. The naming convention of the subscription: `<topicName>.<group>` is fine if the `<topicName>` is the short name and not the fully qualified name even when the topic is in another project.
