### ISSUE TITLE
Pubsub subscriber config

### ISSUE THREAD

**Issue by ValdasK** [GoogleCloudPlatform/spring-cloud-gcp#2386]
Can you use spring boot config file to define individual subscriber settings (e.g. number of threads, thread name) for subscriptions that are added via PubSubInboundChannelAdapter?

If not, how such settings could be changed via code?

I cannot figure out if this is supported (if yes, then it's undocumented?)

What I want to change is that instead of default 4 threads that perform whole pubsub execution is to split several topics which take long to process into their own threads so they do not block processing of fast messages, is this doable?

We are using `spring-cloud-gcp-starter-pubsub` with defaults

**Comment by meltsufin** [comment]
If you are using the starter, the relevant [config properties](https://googlecloudplatform.github.io/spring-cloud-gcp/4.8.4/reference/html/index.html#publishersubscriber-configuration) do apply.

**Comment by ValdasK** [comment]
Thank you, I somehow have missed part about `spring.cloud.gcp.pubsub.subscription.[subscription-name].executor-threads`

Correct me if I am wrong, setting this to something like `4` would mean that there would be 4 generic message threads coming from global config, processing all messages; and 4 threads dedicated for [subscription-name] messages? Can I somehow exclude [subscription-name] messages from global execution threads?

**Comment by meltsufin** [comment]
I believe there will be two thread pools, each with 4 threads. Only one of them, the subscription-specific one, will be used for [subscription-name].
