### ISSUE TITLE
Datastore projection returns empty list

### ISSUE THREAD

**Issue by k8kim** [GoogleCloudPlatform/spring-cloud-gcp#2387]
**Describe the bug**
Spring cloud gcp version: 4.8.3
Spring cloud version: 2022.0.4

Querying datastore with closed-interface projection to get a list of objects back always return an empty list.

**Sample**
Repository: https://github.com/k8kim/spring-gcp-data-projection-demo

In the repository, there is a rest controller (CatController.java), datastore repository (CatRepository), and some entities (Cat.java, LightCat.java, Person.java). LightCat is an interface for projecting Cat object.

The rest controller contains 4 endpoints, but the ones that are related here are:
- {POST} /cats : add a cat with name and ownerName from request parameters and some default values.
- {GET} /cats: returns a list of Cats in the datastore
- {GET} /light-cats: returns a list of LightCats in the datastore

Steps to reproduce:
1. Clone and run the spring application
2. Check if the cats are added at the bootup through the GET endpoint `/cats`
Expected response:
```
 [
    {
        "id": 5768659410616320,
        "referenceId": 100,
        "name": "Coco",
        "found": "2023-11-28T17:43:35.690Z",
        "breed": "AMERICAN_SHORTHAIR",
        "owner": {
            "name": "Alice",
            "address": "Canada"
        }
    },
    {
        "id": 5643462120570880,
        "referenceId": 100,
        "name": "Honey",
        "found": "2023-11-28T17:43:35.403Z",
        "breed": "ABYSSINIAN",
        "owner": {
            "name": "Bob",
            "address": "US"
        }
    },
    {
        "id": 5637781690777600,
        "referenceId": 100,
        "name": "Kitty",
        "found": "2023-11-28T17:43:35.088Z",
        "breed": "RAGDOLL",
        "owner": {
            "name": "Jason",
            "address": "Canada"
        }
    }
]
```
- If there are no cats returned, you can try restarting the application or use `{POST} /cats` to add cats manually
3. If cats are returned successfully, try to grab light cats through the GET endpoint `/light-cats`

The return of `/light-cats` is always empty.

**Comment by meltsufin** [comment]
@k8kim Where is the "bootup" code that adds the default set of cats?

**Comment by meltsufin** [comment]
This seems more like a limitation of Datastore in how it handles `EntityValue` properties, such as `Person`, in projection queries.

WORKS:
```java
    Query<ProjectionEntity> query =
        Query.newProjectionEntityQueryBuilder()
            .setKind("cat")
            .setProjection("__key__","name", "breed", "found")
            .build();
```

DOESN'T WORK:
```java
    Query<ProjectionEntity> query =
        Query.newProjectionEntityQueryBuilder()
            .setKind("cat")
            .setProjection("__key__","name", "breed", "owner", "found")
            .build();
```

Spring Data Dastastore correctly genrates the second query, and it doesn't work.

I think that a way to work around it is to register a converter that converts `Person` to a `String`. That way it will be a basic string type in Datastore, and then it should work.

**Comment by meltsufin** [comment]
Closing. Please, re-open, if you still think it's an issue in Spring Cloud GCP.

**Comment by meltsufin** [comment]
@k8kim If you just put a breakpoint on Line 253 in PartTreeDatastoreQuery.java `getEntityOrProjectionQueryBuilder()`, you should be able to inspect the query that is generated, when you run the app in debug mode.

**Comment by k8kim** [comment]
@meltsufin I have tried, looks like the QueryBuilder's projections are the ones that you've pasted above ("__key__","name", "breed", "owner", "found"). However, because I specified to get `Owner.name`, should it send the query like `SELECT owner.name, name, breed, found FROM cat WHERE referenceId=100`? That returns some stuff to me through GQL.

**Comment by meltsufin** [comment]
How did you specify to get `Owner.name`? If you want to use GQL, you can just annotate the method with `@Query`. See: https://googlecloudplatform.github.io/spring-cloud-gcp/4.8.4/reference/html/index.html#custom-gql-query-methods.

**Comment by k8kim** [comment]
I tried to query through Pantheon. So would spring-cloud-data query the whole `Owner` object when the closed interface has the interface for the Owner to only get `name`?

`LightCat.java` contains
```
package com.example.projectiontest.models;

import java.time.Instant;

public interface LightCat {
  Long getId();

  String getName();
  Breed getBreed();

  Person getOwner();

  Instant getFound();

  interface Person {
    String getName();
  }
}
```
I would expect it to try to get `id, name, breed, found, owner.name` not the whole `Person` and then filter out `name`.

**Comment by meltsufin** [comment]
@k8kim Spring Data Datastore does not flatten the projection in this way for nested entities. You can argue that it's a limitation. So, feel free to file a feature request for this in the repo.
