### ISSUE TITLE
Block a pull request if it breaks updateDocs job

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/spring-cloud-gcp#2477]
**Describe the bug**

Block a pull request if it breaks updateDocs job. We had to revert a build-related artifact version last Friday https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2473. That version upgrade should not have merged.

**Comment by burkedavison** [comment]
updateDocs now required for 3.x, 4.x, and main branches.

For this repository, required tests are configured in the GitHub settings under 'Branches'.

**Comment by burkedavison** [comment]
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2488

This PR enables the check for PRs and ensures the updateDocs test works correctly by cherry-picking the fix for 5.0.0

**Comment by burkedavison** [comment]
Verified functional
