### ISSUE TITLE
How to disable stackdriver logging in a spring application for a GCP project without creating a new docker image

### ISSUE THREAD

**Issue by mehulparmariitr** [GoogleCloudPlatform/spring-cloud-gcp#2492]
**Describe the bug**
I have a spring application packaged inside a docker image and running in GKE pods. I want to disable stackdriver logging but only for this application in gke. Is there any env variable/property I can change in my spring application to disable this? I am using these two jars - 

```
<dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-logging</artifactId>
        </dependency>
```

i thought these two variables will work but they are not.
```
spring.cloud.gcp.logging.enabled=false
stackdriver.log.level=OFF
```

Also for this I will have to create a new docker image and redeploy. Is there any way I can do directly in my kubernetes yaml/env variable?

**Comment by meltsufin** [comment]
You have to stop generating logs.
Have you tried:
```
logging.level.root=OFF
```

**Comment by mehulparmariitr** [comment]
> You have to stop generating logs. Have you tried:
> 
> ```
> logging.level.root=OFF
> ```

That is still printing to console. So I am getting this permission error while logging. I want to stop logging to stackdriver so this error goes away. 

Error - 
`ERROR: onFailure exception: com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'logging.logEntries.create' denied on resource (or it may not exist).
ERROR: onFailure exception: com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'logging.logEntries.create' denied on resource (or it may not exist).
ERROR: onFailure exception: com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'logging.logEntries.create' denied on resource (or it may not exist).
ERROR: onFailure exception: com.google.cloud.logging.LoggingException: io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission 'logging.logEntries.create' denied on resource (or it may not exist).`

This is my config - https://github.com/googleapis/java-logging-logback/issues/1233

**Comment by mehulparmariitr** [comment]
Not required now. We can close the issue.
