### ISSUE TITLE
LoggingAppender getting `projectId` from service account key json instead of env variable `GOOGLE_CLOUD_PROJECT`

### ISSUE THREAD

**Issue by mehulparmariitr** [GoogleCloudPlatform/spring-cloud-gcp#2496]
I have these two variables set in intellij `GOOGLE_CLOUD_PROJECT` and `SPRING_CLOUD_GCP_LOGGING_PROJECT_ID` but still `LoggingAppender` class is getting projectId null in `ServiceOptions.class` and ultimately reading from service account Json file. What is the issue?

I realised in `LoggingAppender` class LoggingOptions are null, but super.getLoggingOptions() has values. Why is the case?

my logback-appender-custom.xml

`<?xml version="1.0" encoding="UTF-8"?>
<included>
    <property name="STACKDRIVER_LOG_NAME" value="${STACKDRIVER_LOG_NAME:-spring.log}"/>
    <property name="STACKDRIVER_LOG_FLUSH_LEVEL" value="${STACKDRIVER_LOG_FLUSH_LEVEL:-WARN}"/>
    <appender name="STACKDRIVER_CUSTOM" class="com.google.cloud.spring.logging.LoggingAppender">
        <log>${STACKDRIVER_LOG_NAME}</log>
        <loggingEventEnhancer>com.google.cloud.spring.logging.TraceIdLoggingEnhancer</loggingEventEnhancer>
        <loggingEventEnhancer>com.avc.xyz.asd.logger.CustomLoggingEventEnhancer</loggingEventEnhancer>
        <writeSynchronicity>ASYNC</writeSynchronicity>
        <flushLevel>${STACKDRIVER_LOG_FLUSH_LEVEL}</flushLevel>
        <logbackBatchingSettings>
            <elementCountThreshold>50</elementCountThreshold>
            <requestByteThreshold>1000</requestByteThreshold>
            <delayThreshold>100</delayThreshold>
            <maxOutstandingElementCount>1000</maxOutstandingElementCount>
            <maxOutstandingRequestBytes>10000</maxOutstandingRequestBytes>
            <limitExceededBehavior>Ignore</limitExceededBehavior>
        </logbackBatchingSettings>
    </appender>
</included>`

my logback-spring.xml

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <springProperty scope="context" name="STACKDRIVER_LOG_NAME" source="stackdriver.log.name"
                    defaultValue="abc.log"/>
    <springProperty scope="context" name="STACKDRIVER_LOG_FLUSH_LEVEL" source="stackdriver.log.level"
                    defaultValue="INFO"/>
    <include resource="com/google/cloud/spring/logging/logback-json-appender.xml"/>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="logback-appender-custom.xml"/>
    <appender name="ASYNC_STACKDRIVER" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="STACKDRIVER_CUSTOM"/>
    </appender>
    <root level="INFO">
        <appender-ref ref="ASYNC_STACKDRIVER"/>
        <appender-ref ref="CONSOLE_JSON"/>
    </root>
</configuration>`

version of dependencies

`<properties>
        <java.version>1.8</java.version>
        <spring-cloud-gcp.version>3.4.5</spring-cloud-gcp.version>
        <spring-cloud.version>2021.0.5</spring-cloud.version>
    </properties>`

**Comment by meltsufin** [comment]
Have you tried setting the `logDestinationProjectId` property of the `LoggingAppender`?

**Comment by mehulparmariitr** [comment]
@meltsufin  Yes I tried if reads the property but when it is calling this - `super.getLoggingOptions()`
`LoggingOptions.newBuilder();` is not reading any projectID and returning null. For some reason both the logging objects are completely different.

<img width="1548" alt="image" src="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/11155969/b1647ee4-9bc2-4400-a77f-5746480c4234">

**Comment by mehulparmariitr** [comment]
I tried the default config also 

`<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="true">
    <include resource="org/springframework/cloud/gcp/autoconfigure/logging/logback-appender.xml"/>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>

    <root level="INFO">
        
        <appender-ref ref="CONSOLE"/>
        <appender-ref ref="STACKDRIVER"/>
    </root>
</configuration>`


There I am getting all these errors. I am suspecting its a dependency issue.

`12:47:13,365 |-WARN in ch.qos.logback.core.joran.action.IncludeAction - Could not find resource corresponding to [org/springframework/cloud/gcp/autoconfigure/logging/logback-appender.xml]
12:47:13,365 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@4d722ac9 - Adding [jar:file:/Users/mehparmar/.m2/abc2/org/springframework/boot/spring-boot/2.5.3/spring-boot-2.5.3.jar!/org/springframework/boot/logging/logback/defaults.xml] to configuration watch list.
12:47:13,365 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@53f0a4cb - URL [jar:file:/Users/mehparmar/.m2/abc2/org/springframework/boot/spring-boot/2.5.3/spring-boot-2.5.3.jar!/org/springframework/boot/logging/logback/defaults.xml] is not of type file
12:47:13,367 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word clr with class [org.springframework.boot.logging.logback.ColorConverter]
12:47:13,368 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wex with class [org.springframework.boot.logging.logback.WhitespaceThrowableProxyConverter]
12:47:13,368 |-INFO in ch.qos.logback.core.joran.action.ConversionRuleAction - registering conversion word wEx with class [org.springframework.boot.logging.logback.ExtendedWhitespaceThrowableProxyConverter]
12:47:13,369 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.catalina.startup.DigesterFactory] to ERROR
12:47:13,369 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53142455 - Propagating ERROR level on Logger[org.apache.catalina.startup.DigesterFactory] onto the JUL framework
12:47:13,370 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.catalina.util.LifecycleBase] to ERROR
12:47:13,370 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53142455 - Propagating ERROR level on Logger[org.apache.catalina.util.LifecycleBase] onto the JUL framework
12:47:13,370 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.coyote.http11.Http11NioProtocol] to WARN
12:47:13,370 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53142455 - Propagating WARN level on Logger[org.apache.coyote.http11.Http11NioProtocol] onto the JUL framework
12:47:13,370 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.sshd.common.util.SecurityUtils] to WARN
12:47:13,370 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53142455 - Propagating WARN level on Logger[org.apache.sshd.common.util.SecurityUtils] onto the JUL framework
12:47:13,370 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.tomcat.util.net.NioSelectorPool] to WARN
12:47:13,370 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53142455 - Propagating WARN level on Logger[org.apache.tomcat.util.net.NioSelectorPool] onto the JUL framework
12:47:13,371 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.jetty.util.component.AbstractLifeCycle] to ERROR
12:47:13,371 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53142455 - Propagating ERROR level on Logger[org.eclipse.jetty.util.component.AbstractLifeCycle] onto the JUL framework
12:47:13,371 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.hibernate.validator.internal.util.Version] to WARN
12:47:13,371 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53142455 - Propagating WARN level on Logger[org.hibernate.validator.internal.util.Version] onto the JUL framework
12:47:13,371 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework.boot.actuate.endpoint.jmx] to WARN
12:47:13,371 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53142455 - Propagating WARN level on Logger[org.springframework.boot.actuate.endpoint.jmx] onto the JUL framework
12:47:13,371 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@4d722ac9 - Adding [jar:file:/Users/mehparmar/.m2/raptor2/org/springframework/boot/spring-boot/2.5.3/spring-boot-2.5.3.jar!/org/springframework/boot/logging/logback/console-appender.xml] to configuration watch list.
12:47:13,371 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@53f0a4cb - URL [jar:file:/Users/mehparmar/.m2/raptor2/org/springframework/boot/spring-boot/2.5.3/spring-boot-2.5.3.jar!/org/springframework/boot/logging/logback/console-appender.xml] is not of type file
12:47:13,372 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
12:47:13,372 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
12:47:13,376 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
12:47:13,390 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
12:47:13,390 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@53142455 - Propagating INFO level on Logger[ROOT] onto the JUL framework
12:47:13,390 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
12:47:13,391 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [STACKDRIVER]. Did you define it below instead of above in the configuration file?
12:47:13,391 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
12:47:13,391 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
12:47:13,391 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@784b990c - Registering current configuration as safe fallback point
2023-12-26 12:47:13.409 ERROR 3078 --- [           main] o.s.boot.SpringApplication               : Application run failed`

**Comment by mehulparmariitr** [comment]
okay I realized it should be 
```
<include resource="com/google/cloud/spring/logging/logback-appender.xml"/>
```
and not

```
    <include resource="org/springframework/cloud/gcp/autoconfigure/logging/logback-appender.xml" />
```

**Comment by mehulparmariitr** [comment]
But still it is reading project ID from service file and not ebv variables. I am not sure whats the issue?

**Comment by meltsufin** [comment]
What makes you think that it should be reading the project ID from the environment variables? I don't see that anywhere in the code.
That being said, `logDestinationProjectId` should work, but it doesn't because we actually do not call `super.getLoggingOptions()` in the Spring Cloud GCP `LoggingAppender`.

**Comment by mehulparmariitr** [comment]
https://googlecloudplatform.github.io/spring-cloud-gcp/3.7.5/reference/html/index.html#cloud-logging

Its clearly mentioned here that `GOOGLE_CLOUD_PROJECT` and `GOOGLE_APPLICATION_CREDENTIALS` environment variables are for project ID and credentials private key location. For me credentials key is being identified but not projectId.

`super.getLoggingOptions()` is being called to get credentials and its working fine. I dont see anything same for projectID. Can you explain how `LoggingOptions` are getting initialized. Right now I am using default config with no custom appender.  Still its not identifying the projectId. 

```
<configuration debug="true">

    <include resource="com/google/cloud/spring/logging/logback-appender.xml"/>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml"/>

    <root level="INFO">
        <appender-ref ref="STACKDRIVER"/>
    </root>
</configuration>
```

**Comment by meltsufin** [comment]
It looks like the documentation is incorrect. In any case, using the `GOOGLE_CLOUD_PROJECT` environment variable should be handled in the https://github.com/googleapis/java-logging-logback/ library to which we delegate. So, please file an issue there regarding that. As far as Spring Cloud GCP is concerned, we need to fix correct delegation to `super. getLoggingOptions` so that settings like `logDestinationProjectId` work properly.

**Comment by mehulparmariitr** [comment]
For default config(not using a custom appender) in logback-spring.xml how would anyone pass `logDestinationProjectId` ?

I see another environment variable for projectid - `SPRING_CLOUD_GCP_LOGGING_PROJECT_ID` but that is also not working - https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#logback-support

What is the recommended way to pass project id?

**Comment by meltsufin** [comment]
At this point, you would need to configure a custom appender.

**Comment by mehulparmariitr** [comment]
What is the expected ETA of release of new 3.x spring-cloud-gcp-starter-logging library with this fix?
