### ISSUE TITLE
spring.cloud.gcp.sql properties getting ignored in application.yml

### ISSUE THREAD

**Issue by gabalmat** [GoogleCloudPlatform/spring-cloud-gcp#252]
**Describe the bug**
It seems that when I add `spring-cloud-gcp-starter-secretmanager` to my Spring Boot project, the `spring.cloud.gcp.sql` properties (`database-name` and `instance-connection-name`) defined in application.yml are ignored.  When I run the app, I see the following error in the logs even though I've defined database-name in application.yml:

`18:06:06.369 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalArgumentException: A database name must be provided.`

If I move these properties to bootstrap.yml, my app will start again without any errors.  I'm using `spring-cloud-gcp-starter-sql-postgresql` and this issue only occurs once I add `spring-cloud-gcp-starter-secretmanager` to my project.

Spring Cloud version: 2020.0.0
Spring Cloud GCP version: 2.0.0

**Sample**
Here's a minimal [example](https://github.com/gabalmat/spring-cloud-gcp-bug-reporoduce) reproducing the issue.  If you run the app with `./gradlew bootRun` you can see the error mentioned above.  If you un-comment out the configuration in bootstrap.yml, you'll see the error no longer appears.

**Comment by meltsufin** [comment]
@snicoll We're seeing some issues now when `CloudSqlEnvironmentPostProcessor` is used in combination with bootstrap config. It looks like all of the environment post-processors are invoked during bootstrap phase and then again after `application.properties` are loaded. Is there any way to detect that the `CloudSqlEnvironmentPostProcessor` is being invoked from the bootstrap phase, and skip it? Thanks!

Ref: #131

**Comment by snicoll** [comment]
> Is there any way to detect that the CloudSqlEnvironmentPostProcessor is being invoked from the bootstrap phase, and skip it? Thanks!

Unfortunately, the way the bootstrap context is designed makes it quite hard to do that. It really depends what decisions you need to make in the BPP but if you need the configuration from a config server, I am afraid there's no way around that. 

I managed to skip the BPP in the bootstrap phase as described [here](https://github.com/spring-cloud/spring-cloud-commons/issues/737#issuecomment-616643295). Here is [an example](https://github.com/wavefrontHQ/wavefront-spring-boot/blob/94f828d344ebbfb7632eee402f9ef775fc41fae2/wavefront-spring-boot/src/main/java/com/wavefront/spring/autoconfigure/AccountManagementEnvironmentPostProcessor.java#L83-L85).

**Comment by artembilan** [comment]
Thanks, @snicoll , for sharing your experience!

@meltsufin ,

looking to the Stéphane's sample and what you have so far in the `CloudSqlEnvironmentPostProcessor`, it sounds like we all are on the same page:

```
private DatabaseType getEnabledDatabaseType(ConfigurableEnvironment environment) {
		if (Boolean.parseBoolean(environment.getProperty("spring.cloud.gcp.sql.enabled", "true"))
				&& isOnClasspath("javax.sql.DataSource")
				&& isOnClasspath("org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType")
				&& isOnClasspath("com.google.cloud.sql.CredentialFactory")) {
```

So, how that can happen we post-process in Bootstrap env if we don't have there that `spring.cloud.gcp.sql.enabled = true`?

**Comment by meltsufin** [comment]
@snicoll Thanks for your suggestions!
 
> So, how that can happen we post-process in Bootstrap env if we don't have there that `spring.cloud.gcp.sql.enabled = true`?

@artembilan that `"true"` parameter is the default value.

**Comment by artembilan** [comment]
Maybe it must not be enabled by default?..
At least that is what I see with many other Spring Cloud features.
On the other hand has `@ConfigurationProperties` already contributed to environment when we are on this `EnvironmentPostProcessor` phase? I thought it happens a bit later.

Anyway: if you think it OK so far, let's fix it same way as Stéphane suggest!

**Comment by meltsufin** [comment]
>Anyway: if you think it OK so far, let's fix it same way as Stéphane suggest!

Agreed! He provided exactly what I was asking. So, we'll go with that for now. 😃 

```java
 if (environment.getPropertySources().contains("bootstrap")) {
      // Do not run in the bootstrap phase as the user configuration is not available yet
      return false;
 }
```

**Comment by mathiasbosman** [comment]
(sorry to boast this).. 

is there a current workaround or snapshot available with this fix?

**Comment by dzou** [comment]
Hey @mathiasbosman - Yes, you can use the fix in our snapshot version.

Add this repository to your project:

```
<repository>
  <id>snapshots-repo</id>
  <url>https://oss.sonatype.org/content/repositories/snapshots</url>
  <releases><enabled>false</enabled></releases>
  <snapshots><enabled>true</enabled></snapshots>
</repository>
```

Then you can depend on version `2.0.2-SNAPSHOT` of the SQL starter which should have the fix.
