### ISSUE TITLE
Collaboration manual link is broken in the README.adoc file.

### ISSUE THREAD

**Issue by ThusithaDJ** [GoogleCloudPlatform/spring-cloud-gcp#256]
Recently I noticed that [collaboration manual](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/master/CONTRIBUTING.adoc) link in the [README.adoc](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/master/README.adoc) giving a 404 error. Is this expected, or are you guys working on something new?

**Comment by elefeint** [comment]
Good catch! We've renamed the doc to `CONTRIBUTING.md`, but it's still at the top level of the project. Will fix the link.

**Comment by ThusithaDJ** [comment]
Awesome, Thanks @elefeint
