### ISSUE TITLE
Property spring.cloud.gcp.credentials.encoded-key not works in a Graalvm compiled app

### ISSUE THREAD

**Issue by mmuniz75** [GoogleCloudPlatform/spring-cloud-gcp#2569]
Set a valid GCP token in property spring.cloud.gcp.credentials.encoded-key.
The JVM version works fine.
The compiled version with Graalvm not able to get the credentials from the property spring.cloud.gcp.credentials.encoded-key

**Comment by czp3009** [comment]
Also meet this problem

it seems to be Graalvm not detect Credentials class used in GcpConfigProperties, even though Credentials has been maked by @NestedConfigurationProperty

Additional findings: properties in Credentials also can't be hinted by IDEA code completion(properties file or yaml file)

Workaround:
```kotlin
class GoogleCredentialsHints : RuntimeHintsRegistrar {
    override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
        hints.reflection().registerType(Credentials::class.java, *MemberCategory.entries.toTypedArray())
    }
}

@AutoConfiguration
@ConditionalOnClass(Credentials::class)
@ImportRuntimeHints(GoogleCredentialsHints::class)
class GoogleCredentialsAutoConfiguration
```

**Comment by mmuniz75** [comment]
The app starts but when I try acess the Big Query I got :
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
POST https://www.googleapis.com/bigquery/v2/projects/lclz-dados/queries
{
  "code": 403,
  "errors": [
    {
      "domain": "global",
      "message": "Access Denied: Project lclz-dados: User does not have bigquery.jobs.create permission in project lclz-dados.",
      "reason": "accessDenied"
    }
  ],
  "message": "Access Denied: Project lclz-dados: User does not have bigquery.jobs.create permission in project lclz-dados.",
  "status": "PERMISSION_DENIED"
}
]

if I set GOOGLE_APPLICATION_CREDENTIALS to a json with the same content of spring.cloud.gcp.credentials.encoded-key without  the base64 encode it works fine
