### ISSUE TITLE
Spanner - PK fields which can be null - Save entity with @Interleaved field

### ISSUE THREAD

**Issue by agustintabarez** [GoogleCloudPlatform/spring-cloud-gcp#2621]
**Describe the bug**
The error occurs when inserting an entity that has an interleaved relationship with another table, and at least one shared primary key is null.

**Versions:**
spring-cloud-gcp-dependencies: 5.0.3
spring-boot: 3.2.2

**Sample**
```
@Table
public class Parent { 

  @PrimaryKey
  @Column
  private String keyOne;

  @PrimaryKey(keyOrder = 2)
  @Column
  private Long keyTwo;

  @Interleaved
  private List<Child> children;

  // More fields
}

@Table
public class Child { 

  @PrimaryKey
  @Column
  private String keyOne;

  @PrimaryKey(keyOrder = 2)
  @Column
  private Long keyTwo;

  @PrimaryKey(keyOrder = 3)
  @Column
  private Long keyThree;

  // More fields
}

var keyOne = "keyOne";
var keyTwo = null;
var keyThree = "keyThree";
List<Child> children = List.of(new Child(keyOne, keyTwo, keyThree));

Parent parent = new Parent(keyOne, keyTwo, children);
parentRepository.save(parent) // extends SpannerRepository
```

**Error:**

`Cannot invoke "Object.equals(Object)" because the return value of "java.util.Iterator.next()" is null`

![Screenshot 2024-02-20 at 14 10 25](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/32047325/0816fce9-70e2-4a36-b31c-3c406e366b24)

**Comment by ldetmer** [comment]
resolved in commit [42c69b](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/commit/42c69b6298ea06b8043811b4048eaf9a6b9cba19).  Will be included in next spring-cloud-gcp release 5.6.1.
