### ISSUE TITLE
RE: @Transactional Annotation not working

### ISSUE THREAD

**Issue by patrickpannn** [GoogleCloudPlatform/spring-cloud-gcp#2627]
**Describe the bug**
Hi, I try to use the @Transactional Annotation, but it doesn't seem to work. Any help would appreciate!!!

**Sample**
**---- the config class**
```
@Configuration(proxyBeanMethods = false)
@EnableTransactionManagement
@ConditionalOnClass(DatastoreTransactionManager.class)
@AutoConfigureBefore(TransactionAutoConfiguration.class)
public class TransactionConfig {

    @Bean
    DatastoreTransactionManager datastoreTransactionManager(DatastoreProvider datastore) {
        return new DatastoreTransactionManager(datastore);
    }
}
```

**--- the function annotated with @Transactional**
```
@Transactional
    public Mono<ServerResponse> updateRepo(ServerRequest serverRequest) {
        var identifier = serverRequest.pathVariable("identifier");
        return serverRequest.bodyToMono(RepositoryDto.class)
                .flatMap(repositoryDto -> {
                        log.info("Start transaction");
                        var existingRepo = repoService.findByIdentifier(identifier)
                                .orElseThrow(() -> new RuntimeException("not found"));

                        checkRepoNotModified(existingRepo, repositoryDto);
                        log.info("======= " + TransactionSynchronizationManager.isActualTransactionActive());

                        updateRepoWhenNotNull(existingRepo, repositoryDto);

                        existingRepo.setVersion(existingRepo.getVersion()+1L);


                        var newRepo = repoService.save(existingRepo);
                        log.info("Intermediate state");

                        var testRepo = repoService.findByIdentifier(identifier);

                        log.info("End transaction");
                        return ok(newRepo);
                }).doOnError(error -> log.error("Error occur when update", error))
                .onErrorResume(error -> ServerResponse.status(BAD_REQUEST).bodyValue(error.getMessage()));
    }
```

**--- The logs show that the transaction immediately close at the very beginning of the function.**

2024-02-23T00:26:27.209+11:00 TRACE 29754 --- [ctor-http-nio-3] o.s.t.i.TransactionInterceptor           : Getting transaction for [com.example.transactiondatastore.RepoHandler.updateRepo]
2024-02-23T00:26:27.236+11:00 TRACE 29754 --- [ctor-http-nio-3] o.s.t.i.TransactionInterceptor           : Completing transaction for [com.example.transactiondatastore.RepoHandler.updateRepo]
2024-02-23T00:26:27.476+11:00  INFO 29754 --- [ctor-http-nio-3] c.e.transactiondatastore.RepoHandler     : Start transaction
2024-02-23T00:26:28.461+11:00  INFO 29754 --- [ctor-http-nio-3] c.e.transactiondatastore.RepoHandler     : ======= false
2024-02-23T00:26:28.711+11:00  INFO 29754 --- [ctor-http-nio-3] c.e.transactiondatastore.RepoHandler     : Intermediate state
2024-02-23T00:26:29.579+11:00  INFO 29754 --- [ctor-http-nio-3] c.e.transactiondatastore.RepoHandler     : End transaction

**Comment by patrickpannn** [comment]
@meltsufin , it doesn't work. Is `(DatastoreProvider datastore)` right in the config? 
BTW, the trace was enabled by this `logging.level.org.springframework.transaction.interceptor = TRACE`

**Comment by meltsufin** [comment]
I suggest you compare you configuration against the [sample](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample). The sample uses `@Transactional` and it works there.

**Comment by patrickpannn** [comment]
@meltsufin , I wonder if google datastore supports reactive transaction in springboot?

**Comment by meltsufin** [comment]
@patrickpannn No, but we do have reactive transaction manager support for Firestore.

**Comment by patrickpannn** [comment]
@meltsufin , right! Would "DatastoreOperations.performTransaction" sort of mimic the reactive way to do the transaction?

**Comment by meltsufin** [comment]
I'm not sure, but wouldn't you still need to implement the reactive transaction manager using it?

**Comment by patrickpannn** [comment]
Do you mean adding a reactive-transaction-manager bean in the configuration class? I am not sure why myDatastoreOperations.performTransaction does not work in this case. I am using "DatastoreOperations myDatastoreOperations;". Can you shed some lights on this? 

RepoHandler:
`public Mono<ServerResponse> updateRepo(ServerRequest serverRequest) {
        var identifier = serverRequest.pathVariable("identifier");
        return serverRequest.bodyToMono(RepositoryDto.class)
                .flatMap(repositoryDto -> ok(repoService.doWorkInsideTransaction(identifier, repositoryDto)))
                .doOnError(error -> log.error("Error occur when update", error))
                .onErrorResume(error -> ServerResponse.status(BAD_REQUEST).bodyValue(error.getMessage()));
    }`


RepoService: 
`public String doWorkInsideTransaction(String identifier, RepositoryDto repositoryDto) {
        return myDatastoreOperations.performTransaction(
                transactionDatastoreOperations -> {
                    // Work with transactionDatastoreOperations here.
                    // It is also a DatastoreOperations object.
                    updateRepo(identifier, repositoryDto);
                    return "transaction completed";
                }
        );
    }

    Repository updateRepo(String identifier,RepositoryDto repositoryDto) {
        log.info("Start transaction");
        var existingRepo = findByIdentifier(identifier)
                .orElseThrow(() -> new RuntimeException("not found"));

        checkRepoNotModified(existingRepo, repositoryDto);
        log.info("======= " + TransactionSynchronizationManager.isActualTransactionActive());

        updateRepoWhenNotNull(existingRepo, repositoryDto);

        existingRepo.setVersion(existingRepo.getVersion()+1L);


        var newRepo = save(existingRepo);
        log.info("Intermediate state");

        var testRepo = findByIdentifier(identifier);

        log.info("End transaction");
        return newRepo;
    }`

**Comment by meltsufin** [comment]
We would have to dig into this more, but for now you can seek the help of the community, since reactive support for Datastore is not prioritized currently.

**Comment by patrickpannn** [comment]
@meltsufin , I switched to @Transactional annotation, which works. Thanks for that. I am using Pessimistic concurrency mode and I wonder if two concurrent read-write transactions read/write the same data, how does Datastore assign the lock to the transaction? Would it be transaction1 or transaction2?

**Comment by burkedavison** [comment]
https://cloud.google.com/datastore/docs/concepts/transactions provides more information about Datastore concurrency modes. Please consider opening a support ticket to get specific help with Datastore service behavior from an expert in that matter. Since the Spring Cloud GCP part of this ticket has been resolved, I'm closing this ticket.
