### ISSUE TITLE
In Datastore, saving and loading a LocalDate varies depending on time zone

### ISSUE THREAD

**Issue by stjasink** [GoogleCloudPlatform/spring-cloud-gcp#2641]
**Describe the bug**

Using version 5.0.4

I save a LocalDate in a a model class using a DatastoreRepository.  When I load the date back again, it can vary based on the time zone.  A LocalDate is a date only, with no time or time zone data, so its value should remain the same.

I can see that this gets stored as a Timestamp with time of midnight, and timezone of the timezone the application is running in.  So if I save a LocalDate of "21 July 2023" when running in time zone UTC+1, this is saved as Timestamp of "21 July 2023 at 00:00:00.000 UTC+1".  Reading this back when running in time zone UTC will return "20 July 2023", which is the previous day and not what I expect.  Loading this as a Timestamp with time zone and then doing the truncation to date only afterwards, causes this.

Having a quick look at the conversions, it looks like this is a two-step conversion of LocalDate -> Date -> Timestamp when writing and then Timestamp -> Date -> LocalDate when reading.  The Date -> LocalDate conversion is from the standard Spring JSR310 conversions and uses the current default time zone, which makes sense in most cases, but not in this one.  

So I don't know what the right solution would be here.  Maybe to have a custom LocalDate -> Timestamp and Timestamp -> LocalDate conversion that sticks to UTC all the time so as not to let time zones affect it?  Or storing date-only types as a string to avoid the question of Timestamp time zones, but that feels like it would lose some useful data type information and functionality in the saved record for sorting, comparing, etc.

**Sample**

I have an example with a failing test here:  https://github.com/stjasink/gcp-datastore-dates

I have copied the main classes here for easy reference:

Model class

```
@Entity
data class ThingWithDate(
    @Id
    val id: String,
    val date: LocalDate
)
```

Repository

```
interface ThingWithDateRepository: DatastoreRepository<ThingWithDate, String>
```

Test - the second assertion fails

```
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class DatastoreDateTest {

    @Autowired
    private var repository: ThingWithDateRepository? = null

    @Test
    fun `loading LocalDate gives the same answer when running in different time zones`() {
        val myDate = LocalDate.of(2023, Month.JULY, 21)
        val id = UUID.randomUUID().toString()

        TimeZone.setDefault(TimeZone.getTimeZone("Europe/London"))

        val thing = ThingWithDate(id, myDate)
        repository!!.save(thing)

        val loadedThingSameTZ  = repository!!.findById(id).get()
        println(loadedThingSameTZ)
        // this assertion passes, was loaded in the same time zone it was saved
        assertEquals(myDate, loadedThingSameTZ.date)

        TimeZone.setDefault(TimeZone.getTimeZone("UTC"))

        val loadedThingUTC  = repository!!.findById(id).get()
        println(loadedThingUTC)
        // this assertion fails, was loaded in a different time zone
        assertEquals(myDate, loadedThingUTC.date)
    }

}

```

**Comment by meltsufin** [comment]
The datatypes that are supported out of the box are listed [here](https://googlecloudplatform.github.io/spring-cloud-gcp/5.0.4/reference/html/index.html#supported-types-2).
You can use,`com.google.cloud.Timestamp` or custom conversion.

I suggest your register your own converter for `LocalDate`, if that's what you want to use in your entity.

**Comment by stjasink** [comment]
Thanks, I added a custom converter and it works as I need.

I had assumed that since all the `Jsr10Converters` are included that they were supported, but as they are not mentioned in the link that you posted then that's probably not the case.  I'll close this, thanks.
