### ISSUE TITLE
Issue on passing Array Of Struct and List of Struct in Spring Data spanner repository query parameter

### ISSUE THREAD

**Issue by manideeps** [GoogleCloudPlatform/spring-cloud-gcp#2694]
**Description**

I have a spanner repository and its custom query methods.
If parameter type is Struct[] , its not treated as iterable instead first value of the array to passed spanner. 

If parameter type is List of Struct, its failing in binding parameter. Exception is .
`java.lang.IllegalArgumentException: Could not convert to an ARRAY of compatible type: java.util.List<com.google.cloud.spanner.Struct> statesAndStatues`  

Below is the spanner repository

```
public interface UserRepository extends SpannerRepository<User, String> {

  @Query(" SELECT * FROM user WHERE (state,status) IN ( @statesAndStatues ) ")
  List<User> getUsersBasedOnState(Struct[] statesAndStatues);

  @Query(" SELECT * FROM user WHERE (state,status) IN unnest ( @statesAndStatues ) ")
  List<User> getUsersBasedOnStateStructList(List<Struct> statesAndStatues);

}
```

Library versions:
Spring Boot : 3.2.3
Spring GCP Cloud : 5.0.4

**Sample**
Sample code repo : https://github.com/deepak-mani-exa/spannersample

**Comment by meltsufin** [comment]
Does `List<Struct>` work?
The full list of supported types is here:
https://googlecloudplatform.github.io/spring-cloud-gcp/5.1.0/reference/html/index.html#custom-types

**Comment by manideeps** [comment]
> Does `List<Struct>` work? The full list of supported types is here: https://googlecloudplatform.github.io/spring-cloud-gcp/5.1.0/reference/html/index.html#supported-types

When using the List<Struct> its exception thrown
`java.lang.IllegalArgumentException: Could not convert to an ARRAY of compatible type: java.util.List<com.google.cloud.spanner.Struct>`

I think only in the where clause parameters its not working

**Comment by meltsufin** [comment]
Does Spanner allow structs in the where clause? Have you tried just running the query manually?
cc: @olavloite

**Comment by olavloite** [comment]
> Does Spanner allow structs in the where clause? Have you tried just running the query manually? cc: @olavloite

Yes, it is allowed, but the syntax that is used in the query in this issue seems to be wrong. The following works:

```sql
select *
from (select 'Hello World!') t
where struct<num INT64, name STRING>(1, 'One') in unnest (
  array(
    select as struct 1 as num, 'One' as name
    union all
    select as struct 2 as num, 'Two' as name
  )
)
```

The above query returns `Hello World!`.

If you change the `(1, 'One')` literal into something that is not in the list, then the query returns no rows.

Removing the `struct<num INT64, name STRING>` in the query causes an error that is similar to the one reported above:

```
select *
from (select 'Hello World!') t
where (1, 'One') in unnest (
  array(
    select as struct 1 as num, 'One' as name
    union all
    select as struct 2 as num, 'Two' as name
  )
)

Statement failed: Casting between arrays with incompatible element types is not supported: Invalid cast from ARRAY<STRUCT<num INT64, name STRING>> to ARRAY<STRUCT<INT64, STRING>>.
```

@manideeps Would you mind changing your query to match the working query above?

**Comment by manideeps** [comment]
For the first method, array of struct parameter, logically query is invalid. But its executed successfully because parameter is not treated as array instead first value of the array is bind to parameter and without the unnest it works. Let say, there are 3 values in array and 3 rows in table and all should match. But only one row is returned because spring data spanner binds only first value of the array.

For the second method , problem is exception thrown spring data parameter binding layer itself and query was not sent to spanner db due to query building and parameter binding failure.

My aim is to pass a array of tuple from java to spanner using Spring data SpannerRepositories. Values of array are user provided not a static.

I achieved the same by passing array of Json string and converting the json into array of struct in spanner query but its not a cleaner one. Please let me know if there is any simple alternative way.

```
SELECT *
FROM user
where (state, next_action) in UNNEST (
          ARRAY(SELECT AS STRUCT
                JSON_VALUE(state_and_next_action, '$.state') ,
                JSON_VALUE(state_and_next_action, '$.nextAction')
                -- statesAndNextActions passed as array Of Json String
                -- Ex. Json value is {"status": "Draft", "nextAction": "enable"}
               FROM UNNEST( @statesAndNextActions ) AS state_and_next_action)
              )

```

Spring Data SpannerRepository for the above query is 
@Query(value="""
    SELECT *
    FROM user
    where (state, next_action) in UNNEST (
              ARRAY(SELECT AS STRUCT
                    JSON_VALUE(state_and_next_action, '$.state') ,
                    JSON_VALUE(state_and_next_action, '$.nextAction')
                    -- statesAndNextActions passed as array Of Json String
                    -- Ex. Json value is {"status": "Draft", "nextAction": "enable"}
                   FROM UNNEST( @statesAndNextActions ) AS state_and_next_action)
                  )
""")
public List<User> getUsers(@Param("statesAndNextActions") List<String> statesAndNextActions);

**Comment by burkedavison** [comment]
Closing this issue as it has been resolved.
