### ISSUE TITLE
migrate PubSubMessageChannelBinderTests to junit 5 Assertions

### ISSUE THREAD

**Issue by zhumin8** [GoogleCloudPlatform/spring-cloud-gcp#2695]
Context in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2672#issuecomment-1991761527. - this is in 3.x branch.
newer dependabot upgrade pr: #2689

Migrate `Assert` used in this test to junit 5 `org.junit.jupiter.api.Assertions` instead should solve issue occurred in upgrading error_prone.

Consider moving away from `org.junit.Assert` ([search](https://github.com/search?q=repo%3AGoogleCloudPlatform%2Fspring-cloud-gcp%20org.junit.Assert&type=code)) for the whole repo.

**Comment by mothmane** [comment]
Hi,

maybe moving away also from junit 4 Assume in favor of junit jupiter Assumptions,

**Comment by zhumin8** [comment]
Thanks @mothmane for your PR that addressed junit 4 Assert and Assume in main branch. (#2733)

But I should have been more precise in the issue description, the original intend for this issue is for 3.x branch, which have more occurrences of junit 4 syntax that blocks an errorprone upgrade.

Keeping this issue open.

**Comment by mothmane** [comment]
Hi,


You can assign it to me I will do it

**Comment by burkedavison** [comment]
Thank you @mothmane
