### ISSUE TITLE
Auto-Config targeting incorrect project?

### ISSUE THREAD

**Issue by storresdiaz** [GoogleCloudPlatform/spring-cloud-gcp#2698]
Hi! The auto config for MySQL is targeting a deleted project, I cannot seem to find any information on how to override the project and sql server instance I'm trying to target - though I would still like to keep the rest of the auto-config enabled. Can anyone point me in the right direction?

To be more precise the following is from the Spring docs, but it does not override the project (https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.1.0.RC2/multi/multi_spring-cloud-gcp-core.html) : 

The Spring Cloud GCP starter auto-configures a GcpProjectIdProvider. If a spring.cloud.gcp.project-id property is specified, the provided GcpProjectIdProvider returns that property value.

spring.cloud.gcp.project-id=my-gcp-project-id

**Comment by burkedavison** [comment]
You could implement your own GcpProjectIdProvider bean, as the default is set to only instantiate `@ConditionalOnMissingBean`.

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/adb57c6165a384b0236d8599598f8c699fccc6d3/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/core/GcpContextAutoConfiguration.java#L59-L78

**Comment by zhumin8** [comment]
Also this may not relate to your issue directly, but noticing that you are referencing old documentation from an outdated version. Please try to use newer versions of spring-cloud-gcp if possible and refer to our up-to-date documentation at:
https://googlecloudplatform.github.io/spring-cloud-gcp/5.1.0/reference/html/index.html

**Comment by storresdiaz** [comment]
> Also this may not relate to your issue directly, but noticing that you are referencing old documentation from an outdated version. Please try to use newer versions of spring-cloud-gcp if possible and refer to our up-to-date documentation at: https://googlecloudplatform.github.io/spring-cloud-gcp/5.1.0/reference/html/index.html

This is the one I initially used which resulted in exactly the same scenario. In my application.properties I also set the instance connection name to <ProjectID>:<Region>:<InstanceID> . Still, it picks up a deleted projectID and attempts to connect. Looking into @burkedavison's solution now - will respond with the result soon. Thank you!

**Comment by storresdiaz** [comment]
@burkedavison Perhaps I'm doing something wrong, but a custom implementation still causes the incorrect project ID to be called. 

`public class CustomGcpProjectIdProvider implements GcpProjectIdProvider {
    @Override
    public String getProjectId() {
        return "myprojectid";
    }

}`

```
@Configuration
public class GcpConfiguration {

    @Bean
    @Primary
    public GcpProjectIdProvider gcpProjectIdProvider() {
        return new CustomGcpProjectIdProvider();
    }

}
```

**Comment by meltsufin** [comment]
Cloud SQL starter uses a different mechanism than other starters. It uses `EnvironmentPostProcessor` that doesn't have access to beans. So, overriding the `GcpProjectIdProvider` won't help. Currently, what you have to use is `spring.cloud.gcp.sql.instance-connection-name=my-project-id:my-region:my-instance-name`, as described in the documentation. It's a required property and it contains the project ID. What are you setting this to?

**Comment by storresdiaz** [comment]
> Cloud SQL starter uses a different mechanism than other starters. It uses `EnvironmentPostProcessor` that doesn't have access to beans. So, overriding the `GcpProjectIdProvider` won't help. Currently, what you have to use is `spring.cloud.gcp.sql.instance-connection-name=my-project-id:my-region:my-instance-name`, as described in the documentation. It's a required property and it contains the project ID. What are you setting this to?

This is exactly what I am doing within application.properties, as an example : 

`spring.cloud.gcp.sql.instance-connection-name=test-project:us-central1:testsqlserverinstancename`

Here is what my dependencies look like : 

```
  // https://mvnrepository.com/artifact/com.google.cloud/spring-cloud-gcp-starter
  implementation 'com.google.cloud:spring-cloud-gcp-starter:5.1.0'
  // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-jpa
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa:3.2.3'
  // https://mvnrepository.com/artifact/com.google.cloud/spring-cloud-gcp-starter-sql-mysql
  implementation 'com.google.cloud:spring-cloud-gcp-starter-sql-mysql:5.1.0'
```

**Comment by meltsufin** [comment]
Are you saying that somehow it's still not targeting `testsqlserverinstancename` on `test-project`?

If so, try starting you Spring app with `debug=true` to see what autoconfiguration is kicking in.

**Comment by storresdiaz** [comment]
Upon further reading the error logs, it appears that a proper POST is being made to the provided instance-connection-name property, **however** a previously deleted project is halting the process and throwing a 403 forbidden error.

**Comment by meltsufin** [comment]
Can you explain "a previously deleted project is halting the process and throwing a 403 forbidden error"?

**Comment by storresdiaz** [comment]
> Can you explain "a previously deleted project is halting the process and throwing a 403 forbidden error"?

```
java.sql.SQLNonTransientConnectionException: Could not create connection to database server.
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
POST https://sqladmin.googleapis.com/sql/v1beta4/projects/correctProjectName/instances/correctSQLInstance':generateEphemeralCert
{
  "code": 403,
  "details": [
    {
      "@type": "type.googleapis.com/google.rpc.ErrorInfo",
      "reason": "USER_PROJECT_DENIED",
      "domain": "googleapis.com",
      "metadata": {
        "service": "sqladmin.googleapis.com",
        "consumer": "projects/crafty-airfoil-numbers"
      }
    }
  ],
  "errors": [
    {
      "domain": "global",
      "message": "Project crafty-airfoil-numbers has been deleted.",
      "reason": "forbidden"
    }
  ],
  "message": "Project crafty-airfoil-numbers has been deleted.",
  "status": "PERMISSION_DENIED"
}
```

**Comment by storresdiaz** [comment]
@meltsufin 
Also, the GCP plugin for IntelliJ is properly connecting to the MySQL instance so I do not believe this to be a problem with my permissions.

**Comment by meltsufin** [comment]
Is this deleted project `crafty-airfoil-numbers` mentioned anywhere in your code or configuration?

**Comment by storresdiaz** [comment]
> Is this deleted project `crafty-airfoil-numbers` mentioned anywhere in your code or configuration?

Not at all. In the POST where it says _correctProjectName_ , as it says - the correct project name is being requested but the incorrect deleted project is being returned.

**Comment by meltsufin** [comment]
Can you make sure that you're using the correct credentials and that your environment variables don't contain the old project name?

**Comment by storresdiaz** [comment]
> Can you make sure that you're using the correct credentials and that your environment variables don't contain the old project name?

I believe this is the answer. The command line tools generated a credentials file under ~/.config that included the deleted project name. My initial assumption was that I would be able to use my main account to authenticate across all projects locally. Instead, It appears that I will have to containerize all applications, and authenticate them with their own service accounts to be able to work locally. 

If this is not the best way to handle this please correct me, otherwise I believe there is sufficient evidence to mark this question as closed. Thank you all for the help!

**Comment by meltsufin** [comment]
I believe it should work with user credentials. Did you use "gcloud auth login"?
https://cloud.google.com/docs/authentication/gcloud

**Comment by storresdiaz** [comment]
> I believe it should work with user credentials. Did you use "gcloud auth login"? https://cloud.google.com/docs/authentication/gcloud

I deleted the original config and used `gcloud auth application-default login` as `gcloud auth login` did not generate the default credentials. It works perfectly. I also have just found out about `gcloud config set project PROJECT_ID` which I believe to be the key to swap between projects.

-------- For future readers scrolling to the bottom (Spring Boot)  -------------------

1. Delete your default credentials under .config/gcloud in your home directory.
2. Run `cloud auth application-default login` to generate new default credentials.
3. In application.properties put spring.cloud.gcp.sql.instance-connection-name=[instanceConnectionName]. This will be in your admin panel, it is in [name]:[region]:[sql-instance-name] format.
4. In application.properties put spring.cloud.gcp.sql.database-name=yourDBName. This is the DB within your SQL instance.
5. In application.properties spring.datasource.password=password . This is of course your password for generally your root user you set. This is also managed within the google admin console. 
6. If you have multiple projects possibly use `gcloud config set project PROJECT_ID` to swap between them and properly connect to your instances [Un-tested so don't quote me on it].
