### ISSUE TITLE
Issue with @Unindexed Annotation on java.util.Collections in Spring Data Cloud Datastore - Not Working as Expected

### ISSUE THREAD

**Issue by Rajkumar061299** [GoogleCloudPlatform/spring-cloud-gcp#2699]
**Describe the bug**

We've been utilising Objectify for data persistence in Google Cloud Datastore, where the `Unindexed` annotation works seamlessly across all value types. However, upon transitioning to Spring Cloud Data Datastore, we expected similar functionality. Unfortunately, we've encountered an issue where `Unindexed` annotations within **Map or List<Ref<?>>** fields are not producing the expected outcome.

**Environment Details:**
* Java 17 
* Spring Boot 3.2.3
* Gradle 8.5

**build.gradle:**

```
ext {
    set('springCloudGcpVersion', "5.0.4")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.google.cloud:spring-cloud-gcp-starter'
    implementation 'com.google.cloud:spring-cloud-gcp-starter-data-datastore'
}

dependencyManagement {
    imports {
        mavenBom "com.google.cloud:spring-cloud-gcp-dependencies:${springCloudGcpVersion}"
    }
}
```

**Entity Classes:**

```
import com.google.cloud.spring.data.datastore.core.mapping.*;
import org.springframework.data.annotation.Id;

@Entity(name = "Library")
public class Library {
  @Id private String id = UUID.randomUUID().toString();
  @Unindexed private Map<String, Set<String>> attributes; // Unsuccessful unindexing
  @Unindexed private Set<Integer> sets; // Successfully unindexed
  @Unindexed @LazyReference private List<Book> bookRefs; // Unsuccessful unindexing
}

import com.google.cloud.datastore.Key;
import com.google.cloud.spring.data.datastore.core.mapping.*;
import org.springframework.data.annotation.Id;

@Entity
public class Book {
  @Id Key id;
  private String title;
}

```
We're seeking resolution to ensure consistent @Unindexing functionality across all relevant data types within Spring Cloud Data Datastore.

<img width="1436" alt="Datastore Table Screenshot" src="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/85780710/2075c57e-401a-4e3f-9cb2-edbbc0c166bd">

**Comment by meltsufin** [comment]
I think this is a valid issue.
Some context for investigation: https://github.com/spring-attic/spring-cloud-gcp/issues/1832.

**Comment by burkedavison** [comment]
Hello @Rajkumar061299 , can you clarify what is the behavior you're seeing with Objectify that you're expecting with the Spring Cloud GCP Data Datastore module?

When I have a entity defined like this:
```java
@Entity
public class ObjectifyLibrary {
  @Id private String id = UUID.randomUUID().toString();
  @Unindex private String primitive;
  @Unindex private Set<String> collectionOfPrimitive;
  @Unindex private Map<String, String> mapOfPrimitives;
  @Unindex private ObjectifyBook ref;
  @Unindex private List<ObjectifyBook> refs;
  @Unindex private Map<String, ObjectifyBook> mapOfRefs;
```
The resulting entity in the console looks like this:
![image](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/40617934/e6db9f65-c6e7-4fcc-85fb-f0ea9dba94e0)

The above matches the current behavior of Spring Cloud GCP Data Datastore, when I modify an existing example of the have the same set of field types:
![image](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/40617934/02afe3d9-ab9a-4343-a237-bc666ca1e282)

In an attempt to see what would happen, I modified the logic to mark the list or map as "exclude from indexes", I get an error from the server:
> ```
> com.google.datastore.v1.client.DatastoreException: Exclude from indexes cannot be set on a list value
>     at com.google.datastore.v1.client.RemoteRpc.makeException(RemoteRpc.java:184) ~[datastore-v1-proto-client-2.18.5.jar:2.18.5]
> ```

So based on the above, I am not currently seeing a difference in behavior, and I also don't see that there's an available modification to the way the library is marking "exclude from indexes" given that it would result in an exception.

**Comment by Rajkumar061299** [comment]
Hi @burkedavison, I was trying to Unindex the map in Objectify version 5.1.22, and it got unindexed properly. 

```
import com.googlecode.objectify.annotation.*;
import java.io.Serializable;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import lombok.Data;

@Entity
@Index
@Data public class Library implements Serializable {
  @Id private String id = UUID.randomUUID().toString();
  @Unindex private Map<String, Set<String>> attributes;
}
```


<img width="1440" alt="Screenshot 2024-04-06 at 12 50 05 PM" src="https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/85780710/101f4857-d242-4abd-88d0-b5d9bd7e1458">


Could you please share the GitHub link for the Objectify example you tried?

**Comment by burkedavison** [comment]
Here's the example I was using - now updated to also have a Map<String, Set<String>>:
https://github.com/burkedavison/objectify-datastore-example/tree/main

I'm still getting the same behavior - not what you're seeing in your screenshot.
![image](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/assets/40617934/d9d9f26d-46b9-41a1-a0b4-8bd66f9e058b)

**Comment by Rajkumar061299** [comment]
Hi @burkedavison , In our application, we are currently using Objectify version 5.1.22, which allows us to Unindex lists or sets of objects, as well as maps. However, after further investigation, we discovered that newer versions of Objectify and Google Datastore client libraries do not support these types. Thank you for your assistance with this issue. We can close this issue.

**Comment by burkedavison** [comment]
Sounds good - thank you for your patience and best wishes on your application.
