### ISSUE TITLE
TransportChannelProvider bean overwrites maxInboundMetadataSize with null

### ISSUE THREAD

**Issue by ivan-zaitsev** [GoogleCloudPlatform/spring-cloud-gcp#2785]
**Describe the bug**
[TransportChannelProvider](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java#L437) bean overwrites `maxInboundMetadataSize` with null by not setting it. It causes `io.grpc.netty.shaded.io.netty.handler.codec.http2.Http2Exception: Header size exceeded max allowed size (10240)` error because it fallbacks to default 10KiB instead of 4MiB.

**Sample**
The library has default 4MB:
https://github.com/googleapis/java-pubsub/blob/main/google-cloud-pubsub/src/main/java/com/google/cloud/pubsub/v1/Subscriber.java#L487

**Comment by diegomarquezp** [comment]
Hi @ivan-zaitsev, thanks for reporting this issue. Would you mind sharing how you are using the bean and any properties file you are working with? Thanks!

@burkedavison @meltsufin shouldn't a config file override this default setting?

**Comment by ivan-zaitsev** [comment]
Hello @diegomarquezp, default config.

```
spring:
  cloud:
    gcp:
      project-id: ...
      credentials:
        encoded-key: ...
```

You can trace bean [TransportChannelProvider](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/pubsub/GcpPubSubAutoConfiguration.java#L437) usage and will find that it will overwrite default 4MB value with null.

**Comment by meltsufin** [comment]
@diegomarquezp I agree that we should keep the defaults set by Pub/Sub, unless they are overwritten by configuration or we intentionally want to change them in Spring Cloud GCP. In this particular case, we are unintentionally overriding the defaults and should fix it.
