### ISSUE TITLE
spring-cloud-gcp-dependencies BOM forces to use specific version of depenencies

### ISSUE THREAD

**Issue by ivan-zaitsev** [GoogleCloudPlatform/spring-cloud-gcp#2786]
**Describe the bug**
When BOM is used in maven `dependencyManagement` section it will manage dependencies. It is good for the libraries which are provided by this repository, but for example such library as [opentelemetry-bom](https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-bom) is not managed by this repository. When `spring-cloud-gcp-dependencies` is added to `dependencyManagement` section it overwrites parent `opentelemetry` version. 

**Sample**
https://mvnrepository.com/artifact/com.google.cloud/spring-cloud-gcp-dependencies/5.1.2
Managed Dependencies section

**Comment by suztomo** [comment]
Is this dependency management preventing you from using certain feature of OpenTelemetry?

**Comment by ivan-zaitsev** [comment]
The thing is here not about using certain feature, by using `spring-cloud-gcp-dependencies` in `dependencyManagement` I don't expect that it will manage additionally `opentelemetry` or other dependencies that Spring parent manages already. This creates implicit dependency override.

**Comment by suztomo** [comment]
> opentelemetry or other dependencies that Spring parent manages already

That's interesting. I didn't know that Spring parent manages OpenTelemetry version already. Thanks.

**Comment by ivan-zaitsev** [comment]
I think that `r2dbc-postgresql` also managed by Spring.

**Comment by JoeWang1127** [comment]
OpenTelemetry is no longer managed by spring-cloud-gcp-dependencies starting from [5.4.0](https://mvnrepository.com/artifact/com.google.cloud/spring-cloud-gcp-dependencies/5.4.0).

https://github.com/googleapis/sdk-platform-java/pull/2736 fixed this issue.
