### ISSUE TITLE
Configure Spring Initialzr (start.spring.io)

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/spring-cloud-gcp#28]
Before the release of spring-cloud-gcp 2.0, we need to make some edits to our spring.io initialzr page.

Edits are capture in this repo:
https://github.com/spring-io/start.spring.io

**Comment by dzou** [comment]
Tasks:

- [ ] Update the intializr to point to new repo
- [ ] Don't forget to update the new group/packages when updating initailzr configs

**Comment by ttomsu** [comment]
https://github.com/spring-io/start.spring.io/pull/577

**Comment by ttomsu** [comment]
Done in https://github.com/spring-io/start.spring.io/issues/578
