### ISSUE TITLE
Flaky alloydb integration test

### ISSUE THREAD

**Issue by burkedavison** [GoogleCloudPlatform/spring-cloud-gcp#2830]
Check the main branch build history, and alloydb integration tests are consistently failing.

Investigate and resolve.

Examples: 
* https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/8911762444/job/24473758084
* https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/8910786581/job/24470730025

**Comment by meltsufin** [comment]
cc: @ttosta-google

**Comment by ttosta-google** [comment]
I will investigate this issue.

**Comment by enocom** [comment]
This appears to be a misconfigured on the server-side. The certificate should have a public IP in its server certificate SANs. That value is now gone.
