### ISSUE TITLE
Reference documentation for release 5.4.1 isn't published

### ISSUE THREAD

**Issue by wleese** [GoogleCloudPlatform/spring-cloud-gcp#2969]
It seems that https://googlecloudplatform.github.io/spring-cloud-gcp/5.4.1/reference/html/index.html is not available, but https://googlecloudplatform.github.io/spring-cloud-gcp/5.4.0/reference/html/index.html is.

Perhaps this is intentional, if so I'd love to know as we link to the docs pretty often.

**Comment by JoeWang1127** [comment]
Thanks for reporting this issue.

https://googlecloudplatform.github.io/spring-cloud-gcp/5.4.1/reference/html/index.html is back on.
