### ISSUE TITLE
Sprinboot 3.2 + jdk 21 + spring gcp verion 5.4.1, causes  java.lang.NoSuchMethodError: 'com.google.api.gax.rpc.StubSettings$Builder 

### ISSUE THREAD

**Issue by aravinths** [GoogleCloudPlatform/spring-cloud-gcp#2972]
com.google.cloud.pubsub.v1.stub.SubscriberStubSettings$Builder.setBackgroundExecutorProvider(com.google.api.gax.core.ExecutorProvider)'"},"stackTrace":[{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doDispatch","fileName":"DispatcherServlet.java","lineNumber":1104,"className":"org.springframework.web.servlet.DispatcherServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doService","fileName":"DispatcherServlet.java","lineNumber":979,"className":"org.springframework.web.servlet.DispatcherServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"processRequest","fileName":"FrameworkServlet.java","lineNumber":1014,"className":"org.springframework.web.servlet.FrameworkServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doGet","fileName":"FrameworkServlet.java","lineNumber":903,"className":"org.springframework.web.servlet.FrameworkServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"service","fileName":"HttpServlet.java","lineNumber":564,"className":"jakarta.servlet.http.HttpServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"service","fileName":"FrameworkServlet.java","lineNumber":885,"className":"org.springframework.web.servlet.FrameworkServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"service","fileName":"HttpServlet.java","lineNumber":658,"className":"jakarta.servlet.http.HttpServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":206,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"WsFilter.java","lineNumber":51,"className":"org.apache.tomcat.websocket.server.WsFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"CorsFilter.java","lineNumber":54,"className":"com.macys.rcs.returncommoncore.web.filter.CorsFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilterInternal","fileName":"RequestContextFilter.java","lineNumber":100,"className":"org.springframework.web.filter.RequestContextFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":116,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilterInternal","fileName":"FormContentFilter.java","lineNumber":93,"className":"org.springframework.web.filter.FormContentFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":116,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilterInternal","fileName":"ServerHttpObservationFilter.java","lineNumber":109,"className":"org.springframework.web.filter.ServerHttpObservationFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":116,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilterInternal","fileName":"CharacterEncodingFilter.java","lineNumber":201,"className":"org.springframework.web.filter.CharacterEncodingFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":116,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"StandardWrapperValve.java","lineNumber":167,"className":"org.apache.catalina.core.StandardWrapperValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"StandardContextValve.java","lineNumber":90,"className":"org.apache.catalina.core.StandardContextValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"AuthenticatorBase.java","lineNumber":482,"className":"org.apache.catalina.authenticator.AuthenticatorBase","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"StandardHostValve.java","lineNumber":115,"className":"org.apache.catalina.core.StandardHostValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"ErrorReportValve.java","lineNumber":93,"className":"org.apache.catalina.valves.ErrorReportValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"StandardEngineValve.java","lineNumber":74,"className":"org.apache.catalina.core.StandardEngineValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"RemoteIpValve.java","lineNumber":731,"className":"org.apache.catalina.valves.RemoteIpValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"service","fileName":"CoyoteAdapter.java","lineNumber":344,"className":"org.apache.catalina.connector.CoyoteAdapter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"service","fileName":"Http11Processor.java","lineNumber":391,"className":"org.apache.coyote.http11.Http11Processor","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"process","fileName":"AbstractProcessorLight.java","lineNumber":63,"className":"org.apache.coyote.AbstractProcessorLight","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"process","fileName":"AbstractProtocol.java","lineNumber":896,"className":"org.apache.coyote.AbstractProtocol$ConnectionHandler","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doRun","fileName":"NioEndpoint.java","lineNumber":1736,"className":"org.apache.tomcat.util.net.NioEndpoint$SocketProcessor","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"SocketProcessorBase.java","lineNumber":52,"className":"org.apache.tomcat.util.net.SocketProcessorBase","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"runWorker","fileName":"ThreadPoolExecutor.java","lineNumber":1191,"className":"org.apache.tomcat.util.threads.ThreadPoolExecutor","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"ThreadPoolExecutor.java","lineNumber":659,"className":"org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"TaskThread.java","lineNumber":63,"className":"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable","nativeMethod":false},{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"21-ea","methodName":"run","fileName":"Thread.java","lineNumber":1583,"className":"java.lang.Thread","nativeMethod":false}],"rootCause":{"cause":null,"stackTrace":[{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"buildSubscriberStubSettings","fileName":"DefaultSubscriberFactory.java","lineNumber":393,"className":"com.google.cloud.spring.pubsub.support.DefaultSubscriberFactory","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"createSubscriberStub","fileName":"DefaultSubscriberFactory.java","lineNumber":339,"className":"com.google.cloud.spring.pubsub.support.DefaultSubscriberFactory","nativeMethod":false},{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"21-ea","methodName":"computeIfAbsent","fileName":"ConcurrentHashMap.java","lineNumber":1708,"className":"java.util.concurrent.ConcurrentHashMap","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"getSubscriberStub","fileName":"PubSubSubscriberTemplate.java","lineNumber":537,"className":"com.google.cloud.spring.pubsub.core.subscriber.PubSubSubscriberTemplate","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"pullAsync","fileName":"PubSubSubscriberTemplate.java","lineNumber":208,"className":"com.google.cloud.spring.pubsub.core.subscriber.PubSubSubscriberTemplate","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"pullAsync","fileName":"PubSubSubscriberTemplate.java","lineNumber":258,"className":"com.google.cloud.spring.pubsub.core.subscriber.PubSubSubscriberTemplate","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"pullAsync","fileName":"PubSubTemplate.java","lineNumber":147,"className":"com.google.cloud.spring.pubsub.core.PubSubTemplate","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"pullMessage","fileName":"PubSubHealthIndicator.java","lineNumber":121,"className":"com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doHealthCheck","fileName":"PubSubHealthIndicator.java","lineNumber":100,"className":"com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doHealthCheck","fileName":"PubSubHealthIndicator.java","lineNumber":95,"className":"com.google.cloud.spring.autoconfigure.pubsub.health.PubSubHealthIndicator","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"health","fileName":"AbstractHealthIndicator.java","lineNumber":82,"className":"org.springframework.boot.actuate.health.AbstractHealthIndicator","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"getHealth","fileName":"HealthIndicator.java","lineNumber":37,"className":"org.springframework.boot.actuate.health.HealthIndicator","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"getHealth","fileName":"HealthEndpointWebExtension.java","lineNumber":94,"className":"org.springframework.boot.actuate.health.HealthEndpointWebExtension","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"getHealth","fileName":"HealthEndpointWebExtension.java","lineNumber":47,"className":"org.springframework.boot.actuate.health.HealthEndpointWebExtension","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"getLoggedHealth","fileName":"HealthEndpointSupport.java","lineNumber":172,"className":"org.springframework.boot.actuate.health.HealthEndpointSupport","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"getContribution","fileName":"HealthEndpointSupport.java","lineNumber":145,"className":"org.springframework.boot.actuate.health.HealthEndpointSupport","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"getAggregateContribution","fileName":"HealthEndpointSupport.java","lineNumber":156,"className":"org.springframework.boot.actuate.health.HealthEndpointSupport","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"getContribution","fileName":"HealthEndpointSupport.java","lineNumber":141,"className":"org.springframework.boot.actuate.health.HealthEndpointSupport","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"getHealth","fileName":"HealthEndpointSupport.java","lineNumber":110,"className":"org.springframework.boot.actuate.health.HealthEndpointSupport","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"getHealth","fileName":"HealthEndpointSupport.java","lineNumber":81,"className":"org.springframework.boot.actuate.health.HealthEndpointSupport","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"health","fileName":"HealthEndpointWebExtension.java","lineNumber":80,"className":"org.springframework.boot.actuate.health.HealthEndpointWebExtension","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"health","fileName":"HealthEndpointWebExtension.java","lineNumber":69,"className":"org.springframework.boot.actuate.health.HealthEndpointWebExtension","nativeMethod":false},{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"21-ea","methodName":"invoke","fileName":"DirectMethodHandleAccessor.java","lineNumber":103,"className":"jdk.internal.reflect.DirectMethodHandleAccessor","nativeMethod":false},{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"21-ea","methodName":"invoke","fileName":"Method.java","lineNumber":580,"className":"java.lang.reflect.Method","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invokeMethod","fileName":"ReflectionUtils.java","lineNumber":281,"className":"org.springframework.util.ReflectionUtils","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"ReflectiveOperationInvoker.java","lineNumber":74,"className":"org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"AbstractDiscoveredOperation.java","lineNumber":60,"className":"org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"handle","fileName":"AbstractWebMvcEndpointHandlerMapping.java","lineNumber":327,"className":"org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$ServletWebOperationAdapter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"handle","fileName":"AbstractWebMvcEndpointHandlerMapping.java","lineNumber":434,"className":"org.springframework.boot.actuate.endpoint.web.servlet.AbstractWebMvcEndpointHandlerMapping$OperationHandler","nativeMethod":false},{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"21-ea","methodName":"invoke","fileName":"DirectMethodHandleAccessor.java","lineNumber":103,"className":"jdk.internal.reflect.DirectMethodHandleAccessor","nativeMethod":false},{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"21-ea","methodName":"invoke","fileName":"Method.java","lineNumber":580,"className":"java.lang.reflect.Method","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doInvoke","fileName":"InvocableHandlerMethod.java","lineNumber":255,"className":"org.springframework.web.method.support.InvocableHandlerMethod","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invokeForRequest","fileName":"InvocableHandlerMethod.java","lineNumber":188,"className":"org.springframework.web.method.support.InvocableHandlerMethod","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invokeAndHandle","fileName":"ServletInvocableHandlerMethod.java","lineNumber":118,"className":"org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invokeHandlerMethod","fileName":"RequestMappingHandlerAdapter.java","lineNumber":926,"className":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"handleInternal","fileName":"RequestMappingHandlerAdapter.java","lineNumber":831,"className":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"handle","fileName":"AbstractHandlerMethodAdapter.java","lineNumber":87,"className":"org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doDispatch","fileName":"DispatcherServlet.java","lineNumber":1089,"className":"org.springframework.web.servlet.DispatcherServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doService","fileName":"DispatcherServlet.java","lineNumber":979,"className":"org.springframework.web.servlet.DispatcherServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"processRequest","fileName":"FrameworkServlet.java","lineNumber":1014,"className":"org.springframework.web.servlet.FrameworkServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doGet","fileName":"FrameworkServlet.java","lineNumber":903,"className":"org.springframework.web.servlet.FrameworkServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"service","fileName":"HttpServlet.java","lineNumber":564,"className":"jakarta.servlet.http.HttpServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"service","fileName":"FrameworkServlet.java","lineNumber":885,"className":"org.springframework.web.servlet.FrameworkServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"service","fileName":"HttpServlet.java","lineNumber":658,"className":"jakarta.servlet.http.HttpServlet","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":206,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"WsFilter.java","lineNumber":51,"className":"org.apache.tomcat.websocket.server.WsFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"CorsFilter.java","lineNumber":54,"className":"com.macys.rcs.returncommoncore.web.filter.CorsFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilterInternal","fileName":"RequestContextFilter.java","lineNumber":100,"className":"org.springframework.web.filter.RequestContextFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":116,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilterInternal","fileName":"FormContentFilter.java","lineNumber":93,"className":"org.springframework.web.filter.FormContentFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":116,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilterInternal","fileName":"ServerHttpObservationFilter.java","lineNumber":109,"className":"org.springframework.web.filter.ServerHttpObservationFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":116,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilterInternal","fileName":"CharacterEncodingFilter.java","lineNumber":201,"className":"org.springframework.web.filter.CharacterEncodingFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":116,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":175,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":150,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"StandardWrapperValve.java","lineNumber":167,"className":"org.apache.catalina.core.StandardWrapperValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"StandardContextValve.java","lineNumber":90,"className":"org.apache.catalina.core.StandardContextValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"AuthenticatorBase.java","lineNumber":482,"className":"org.apache.catalina.authenticator.AuthenticatorBase","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"StandardHostValve.java","lineNumber":115,"className":"org.apache.catalina.core.StandardHostValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"ErrorReportValve.java","lineNumber":93,"className":"org.apache.catalina.valves.ErrorReportValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"StandardEngineValve.java","lineNumber":74,"className":"org.apache.catalina.core.StandardEngineValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"invoke","fileName":"RemoteIpValve.java","lineNumber":731,"className":"org.apache.catalina.valves.RemoteIpValve","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"service","fileName":"CoyoteAdapter.java","lineNumber":344,"className":"org.apache.catalina.connector.CoyoteAdapter","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"service","fileName":"Http11Processor.java","lineNumber":391,"className":"org.apache.coyote.http11.Http11Processor","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"process","fileName":"AbstractProcessorLight.java","lineNumber":63,"className":"org.apache.coyote.AbstractProcessorLight","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"process","fileName":"AbstractProtocol.java","lineNumber":896,"className":"org.apache.coyote.AbstractProtocol$ConnectionHandler","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"doRun","fileName":"NioEndpoint.java","lineNumber":1736,"className":"org.apache.tomcat.util.net.NioEndpoint$SocketProcessor","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"SocketProcessorBase.java","lineNumber":52,"className":"org.apache.tomcat.util.net.SocketProcessorBase","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"runWorker","fileName":"ThreadPoolExecutor.java","lineNumber":1191,"className":"org.apache.tomcat.util.threads.ThreadPoolExecutor","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"ThreadPoolExecutor.java","lineNumber":659,"className":"org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker","nativeMethod":false},{"classLoaderName":null,"moduleName":null,"moduleVersion":null,"methodName":"run","fileName":"TaskThread.java","lineNumber":63,"className":"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable","nativeMethod":false},{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"21-ea","methodName":"run","fileName":"Thread.java","lineNumber":1583,"className":"java.lang.Thread","nativeMethod":false}],"message":"'com.google.api.gax.rpc.StubSettings$Builder com.google.cloud.pubsub.v1.stub.SubscriberStubSettings$Builder.setBackgroundExecutorProvider(com.google.api.gax.core.ExecutorProvider)'","suppressed":[],"localizedMessage":"'com.google.api.gax.rpc.StubSettings$Builder com.google.cloud.pubsub.v1.stub.SubscriberStubSettings$Builder.setBackgroundExecutorProvider(com.google.api.gax.core.ExecutorProvider)'"},"message":"Handler dispatch failed: java.lang.NoSuchMethodError: 'com.google.api.gax.rpc.StubSettings$Builder com.google.cloud.pubsub.v1.stub.SubscriberStubSettings$Builder.setBackgroundExecutorProvider(com.google.api.gax.core.ExecutorProvider)'","suppressed":[],"localizedMessage":"Handler dispatch failed: java.lang.NoSuchMethodError: 'com.google.api.gax.rpc.StubSettings$Builder com.google.cloud.pubsub.v1.stub.SubscriberStubSettings$Builder.setBackgroundExecutorProvider(com.google.api.gax.core.ExecutorProvider)'"}"}}"

**Comment by aravinths** [comment]
any help would be helpful added latest gax jar , causes same issue

**Comment by mpeddada1** [comment]
Hey @aravinths thanks for filing this issue. Could you provide us with a reproducible sample?

**Comment by zhumin8** [comment]
This sounds like dependency version misalignment issue, we usually recommend using BOM `spring-cloud-gcp-dependencies` to avoid similar issues. See our [guide](https://googlecloudplatform.github.io/spring-cloud-gcp//reference/html/index.html#bill-of-materials).

That said, closing this issue due to lack of response from user. Please feel free to reopen if the above did not work for you and provide  a reproducible sample.
