### ISSUE TITLE
Logging: warning level is incorrectly reported to Cloud Logging

### ISSUE THREAD

**Issue by pedro-carneiro** [GoogleCloudPlatform/spring-cloud-gcp#299]
Following the [documentation](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#LogSeverity), the `severity` field of a log entry must be one of the possbile nine options described.

However, this is being reported as a [direct translation](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/0fe8d71268da4fd1def6c02868b25ecafe6855c4/spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/StackdriverJsonLayout.java#L216) of the `Level` enumeration.

As such, the following happens:

| `Level` | `LogSeverity` | Effect in Cloud Logging |
|---------------|--------|------------------------|
| TRACE | ? | DEFAULT ❌ |
| DEBUG | DEBUG | DEBUG ✅ |
| INFO | INFO | INFO ✅ |
| WARN | WARNING | DEFAULT ❌ |
| ERROR | ERROR | ERROR ✅ |

I guess the most pressing of these is the warning level translation.

**Comment by dzou** [comment]
Thanks for catching this. Yeah I can add the correct Cloud Logging level mappings.

**Comment by dzou** [comment]
Fixed in #314 -- We are preparing a `2.0.2` release soon and this fix will be in there.
