### ISSUE TITLE
OpenTelemetry version not defined in version management leads to NoSuchMethodException

### ISSUE THREAD

**Issue by Carst-Tankink** [GoogleCloudPlatform/spring-cloud-gcp#3011]
**Describe the bug**
Opening a JDBC connection to a spanner database throws the exception:

```
java.lang.NoSuchMethodError: 'io.opentelemetry.api.metrics.LongHistogramBuilder io.opentelemetry.api.metrics.LongHistogramBuilder.setExplicitBucketBoundariesAdvice(java.util.List)'
	at com.google.cloud.spanner.jdbc.Metrics.<init>(Metrics.java:46) ~[google-cloud-spanner-jdbc-2.19.3.jar:2.19.3]
	at com.google.cloud.spanner.jdbc.JdbcConnection.<init>(JdbcConnection.java:105) ~[google-cloud-spanner-jdbc-2.19.3.jar:2.19.3]
	at com.google.cloud.spanner.jdbc.JdbcDriver.connect(JdbcDriver.java:208) ~[google-cloud-spanner-jdbc-2.19.3.jar:2.19.3]
```

It looks like `google-cloud-spanner-jdbc 2.19.3` uses the `setExplicitBucketBoundariesAdvice` which is only available since version `1.32.0` of `opentelemetry-api` (see javadoc at https://javadoc.io/doc/io.opentelemetry/opentelemetry-api/latest/io/opentelemetry/api/metrics/LongHistogramBuilder.html), but Spring boot 3.2 provides `opentelemetry-api` version `1.31.0` (see https://github.com/spring-projects/spring-boot/blob/3.2.x/spring-boot-project/spring-boot-dependencies/build.gradle#L1103).

I am not 100% sure if spanner-jdbc is intended to be part of the spring-cloud-gcp offering or if it is included in my dependency chain, but I am worried about version divergence in case I start managing spanner-jdbc myself (because we do use other spanner modules from the spring-cloud-gcp project).

_Versions:_

- spring-cloud-gcp 5.4.2 
- spring-boot 3.2.7
 
I observed the problem in spring-cloud-gcp 5.4.1 as well,  but went to the latest available to make sure it wasn't fixed already.

**Sample**
See https://github.com/Carst-Tankink/spanner-jdbc-incompatible-example for a self-contained example, based on existing spanner-JDBC sample code and the spring-cloud-gcp starter.

I expect this application to start up and the `/timestamp` endpoint to properly connect to spanner and execute the query (provided a spanner database is created).

**Comment by burkedavison** [comment]
As an immediate workaround: the OpenTelemetry version can be explicitly defined in the application's pom.xml, and will take precedence over the version being provided by Spring Boot.

---

Although opentelemetry is defined in java-shared-dependencies' third-party-dependencies for use by projects like spanner-jdbc, the libraries-bom does not include third-party-dependencies and opentelemetry is also not listed in spring-cloud-gcp-dependencies. The result is that Spring Boot's dependency management controls the opentelemetry version.

Some options:
* Define opentelemetry in spring-cloud-gcp-dependencies
* Include third-party-dependencies with libraries-bom

CC @suztomo, @blakeli0

**Comment by Carst-Tankink** [comment]
Thanks for looking at this! 

I forgot to add the workaround, indeed. For me this is not immediately blocking because of it, but a report seemed like a good idea regardless :)

**Comment by zhumin8** [comment]
This is resolved in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3146
