### ISSUE TITLE
Incorrect latest documentation links

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#3020]
https://github.com/GoogleCloudPlatform/spring-cloud-gcp currently contains these links:

* [Spring Framework on Google Cloud 5.1.0 (Latest)](https://googlecloudplatform.github.io/spring-cloud-gcp/5.4.3/reference/html/index.html) - [Javadocs 5.1.0](https://googleapis.dev/java/spring-cloud-gcp/5.1.0/index.html)

The link target for the reference docs is for Spring Cloud GCP 5.4.3, which is indeed currently the latest version, but the link text mentions version 5.1.0. The link text should match the link target.

For the Javadoc link both the link text and the link target are not for the latest version. https://googleapis.dev/java/spring-cloud-gcp/5.4.3/index.html does exist, so I would expect a link to that.

**Comment by lqiu96** [comment]
Thanks for reporting this. We'll have to look into why it's not updating properly. For now, I'll raise a PR to manually update the links.

CC: @burkedavison I also found this older issue regarding not having the other Spring branches being kept up to date: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/2697

**Comment by zhumin8** [comment]
closing and tracking in #2697
