### ISSUE TITLE
Is this repo active now

### ISSUE THREAD

**Issue by kioie** [GoogleCloudPlatform/spring-cloud-gcp#31]
Hey guys, is this repo now active? if not, any chance you'd let us know what the plans are for the repo?

**Comment by meltsufin** [comment]
It's active, and it is the main repo for the project starting with version 2.0 forward (Ilford base).
We're still working out the CI/CD stuff for the repo, among other minor things.
The Spring Cloud org repo will also continue to live on for the 1.2.x (Hoxton base).

Do you have a specific question about the plans though?

**Comment by kioie** [comment]
No question really, just checking in to see if I can start contributing here.
