### ISSUE TITLE
Multiple active namespaces for datastore 

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/spring-cloud-gcp#317]
See: https://github.com/spring-cloud/spring-cloud-gcp/issues/2640

**Comment by meltsufin** [comment]
So, is the solution proposed in https://github.com/spring-cloud/spring-cloud-gcp/issues/2204#issuecomment-780524911 not sufficient?

**Comment by dzou** [comment]
I think it should work for the user but I'm not sure. I mentioned it to them in the previous thread. I think we should document the approach and make it easier to use (i.e. user mentioned having to set a default when it might not make sense).

**Comment by meltsufin** [comment]
I don't think there is sufficient description of the issue from the customer. I'm closing, but please reopen if you feel that something here still needs to be addressed.
