### ISSUE TITLE
Issues with one microservice with multiple subscriptions

### ISSUE THREAD

**Issue by Vitor-Bittencourt-Rentalmatics** [GoogleCloudPlatform/spring-cloud-gcp#3182]
Hello.

First of all, sorry for the lack of details, but it's exactly a request for help in raising details that I am looking for.

I've noticed that in when we replay DLQs there seems to be a spike in the "live" subscription far above what would make sense.
An example from today, we had 157 messages in the DLQ.
When I replayed those (using Dataflow), the number of messages in the subscription I pushed those to spiked to 9645.

And when the microservice subscribes to more than 1 subscription, when replaying DLQs in one subscription, the number of messages in other subscriptions spike, and sometimes we even get some going to DLQs. Which can cause a "fun" Whac-A-Mole game trying to get all DLQs zeroed.

Our services can handle a quite high number of messages. At peak times we have 3Mi+/hour, so a mere 157 shouldn't even tickle it, especially because I never re-run DLQs during busy times.

The basic simplified dependencies used would be:

```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.18</version>
        <relativePath/>
    </parent>

    <properties>
        <java.version>17</java.version>
        <spring-cloud-gcp.version>3.8.6</spring-cloud-gcp.version>
        <lombok.version>1.18.24</lombok.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.google.cloud</groupId>
                <artifactId>spring-cloud-gcp-dependencies</artifactId>
                <version>${spring-cloud-gcp.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>spring-cloud-gcp-starter-pubsub</artifactId>
        </dependency>
    </dependencies>
```

We have a few microservices which are using more recent dependencies, and running on Java 21.
Same behaviour is seen on those.

**Comment by mpeddada1** [comment]
@Vitor-Bittencourt-Rentalmatics Thanks for creating this issue! Are you able to reproduce this problem with just the Pub/Sub client  library? Alternatively, please reach out to cloud.google.com/support.

**Comment by Vitor-Bittencourt-Rentalmatics** [comment]
Hello @mpeddada1 

The problem only happens in our production environment, where the loads are high.

I could potentially try to recreate in a non-production environment, but it would be costly both in terms of my time, and resources.
I'd have to create a new separate isolated environment that we don't have now.

Do you have a theory?
If I am to request company time and resources to go looking for the issue myself, I'd have to be able to explain what I am doing and why.

Thank you,
Vitor.

**Comment by mpeddada1** [comment]
@Vitor-Bittencourt-Rentalmatics As this doesn't seem to be a Spring Cloud GCP specific bug, the best way to get support is through [cloud.google.com/support](http://cloud.google.com/support) where subject matter experts can work with you to diagnose what is happening. If the issue is later determined to be due to a behavior in Spring Cloud GCP, please reopen this ticket.
