### ISSUE TITLE
Update to Cloud SQL Factory 1.20.1 to fix issue with token refresh

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#3248]
Google Cloud SQL Socket Factory [1.20.1](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases/tag/v1.20.1) was released on September 5th with a fix for a token refresh issue which causes database connectivity problems.

I noticed that last week's Spring Cloud GCP 5.6.1 release [still comes with version 1.20.0](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/v5.6.1/spring-cloud-gcp-dependencies/pom.xml#L38).

**Comment by blakeli0** [comment]
Hey @breun, I just updated Google Cloud SQL Socket Factory to 1.20.1 in all release branches. It should be released in the next cycle within ~2 weeks.

**Comment by breun** [comment]
Not important for the token refresh fix, but I just wanted to note that in the meantime version [1.21.0](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases/tag/v1.21.0) has been released.

Do you have some kind of automatic process set up to create pull requests for dependency updates (Dependabot, Renovate, etc.) for Spring Cloud GCP?

**Comment by burkedavison** [comment]
We've now updated to 1.21.0
