### ISSUE TITLE
Update Zipkin GCP to 2.2.5 to fix NPE

### ISSUE THREAD

**Issue by ccudennec-otto** [GoogleCloudPlatform/spring-cloud-gcp#3256]
Hi everyone!

It would be great to see Zipkin GCP 2.2.5 as a dependency as it fixes a Null Pointer Exception that happens really frequently if you're using Cloud Run:
* https://github.com/openzipkin/zipkin-gcp/pull/225
* https://github.com/openzipkin/zipkin-gcp/releases/tag/2.2.5

I noticed that you already have PRs from Dependabot and Renovate but don't know how your process is to merge them:
* #3189
* #3187

Thanks for your effort! 😃

**Comment by burkedavison** [comment]
This likely should have been included in the last release. Thank you for bringing this to our attention. I've merged the upgrade, and it will be included in the next release due in ~1 week. (We're on a 2 week release rotation.)

**Comment by ccudennec-otto** [comment]
That's great! Thanks a lot! 🥳
