### ISSUE TITLE
Provide additional configuration properties for Cloud SQL JDBC

### ISSUE THREAD

**Issue by hessjcg** [GoogleCloudPlatform/spring-cloud-gcp#3285]
The auto-config library for Cloud SQL does not include all of the possible configuration parameters provided by the Cloud SQL Java Connector. Particularly those related to the refresh strategy, universe domain, and service account impersonation.

**Is your feature request related to a problem? Please describe.**
Cloud Run and Cloud Functions benefit greatly from using the "lazy" refresh strategy. Customers in Cloud Run experience connection problems that can only be mitigated by configuring "lazy refresh".

**Describe the solution you'd like**
Add all supported Cloud SQL Java Connector configuration properties to the spring auto-config.

**Comment by mieseprem** [comment]
I just looked on my custom datasource url and found more parameter you don't mention:
* cloudSqlInstance
* socketFactory
* enableIamAuth
* ipTypes
I'm not sure if those parameter are used by the SQL connector but I have them all along with `cloudSqlTargetPrincipal`

Or am I wrong and your enhancement is not about configure cloudsql conector via datasource?

**Comment by burkedavison** [comment]
Resolved with #3286
