### ISSUE TITLE
sonar started to fail in main after Nov 6

### ISSUE THREAD

**Issue by zhumin8** [GoogleCloudPlatform/spring-cloud-gcp#3376]
The last successful run was nightly on Nov 6 ([log](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/11698141113)).
Started to fail consistently starting https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/11705520637. 

Error:  Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:5.0.0.4389:sonar (default-cli) on project spring-cloud-gcp: Error status returned by url [https://api.sonarcloud.io/analysis/jres?os=linux&arch=x86_64]: 401 -> [Help 1]

**Comment by zhumin8** [comment]
@burkedavison does this seems related to recent changes?

**Comment by ldetmer** [comment]
Fixed in #3381
