### ISSUE TITLE
Propagate `storeOnDisk` property to the configuration

### ISSUE THREAD

**Issue by artemptushkin** [GoogleCloudPlatform/spring-cloud-gcp#342]
### Problem.

Some Datastore emulator runs require `--no-store-on-disk` start-up property, but currently, there is no way to pass it

### Solution

I would suggest to create an additional property for `org.springframework.cloud.gcp.autoconfigure.datastore.EmulatorSettings` and pass it to `LocalDatastoreHelper`

**Comment by meltsufin** [comment]
Sounds like a good idea.

**Comment by artemptushkin** [comment]
I will take this
