### ISSUE TITLE
Issue with @Entity inheritance updating datastore from 1.2.1.RELEASE to 2.0.0 (com.google.cloud) 

### ISSUE THREAD

**Issue by lucasoares** [GoogleCloudPlatform/spring-cloud-gcp#353]
Hello.

I just updated my project to use this new project (com.google.cloud) instead of the spring one and I had several integration tests that are now failing.

I have three classes (using lombok):

```java
@Data
@Accessors(chain = true)
public class BaseEntity {
  private Long companyId;
  private Long creatorId;
  private Long updatedUserId;

  private Date createdAt;
  private Date updatedAt;
}
```

```java
@Data
@Accessors(chain = true)
@Entity(name = "TicketStatus")
@EqualsAndHashCode(callSuper = false)
public class TicketStatus extends BaseEntity {
  @Id private Long id;
  private int value;
  @NotEmpty private String name;

  @Pattern(regexp = "#[0-9A-Fa-f]{6}")
  private String hexColor;

  @Pattern(regexp = "#[0-9A-Fa-f]{6}")
  private String iconHexColor;
}
```

```java
public class PendingStatus extends TicketStatus {
  private static final String NAME = "Pendente";
  private static final int VALUE = 1;
  private static final String HEX_COLOR = "#3a78b6";
  private static final String ICON_HEX_COLOR = "#ffffff";

  public PendingStatus(long companyId) {
    setId(IdUtils.getFixedId(companyId, VALUE));
    setCompanyId(companyId);
    setName(NAME);
    setValue(VALUE);
    setHexColor(HEX_COLOR);
    setIconHexColor(ICON_HEX_COLOR);
  }
```

The logic behind attributes doesn't matter here.

I just notice that PendingStatus class is not using the same `@Entity` as its parent class `TicketStatus` anymore. Creating this entity using the `PendingStatus` class will save a different entity than creating directly from the `TicketStatus` class.

For example, the following test now fails:
```
PendingStatus pendingStatus = new PendingStatus(4816908371099648L);
this.datastoreTemplate.save(pendingStatus);

Collection<TicketStatus> result = this.datastoreTemplate.findAll(TicketStatus.class);
Assertions.assertNotNull(result);
Assertions.assertEquals(1, result.size());
```

Before upgrading the dependency version this would work as expected.

Something we should know? Thanks!

**Comment by ttomsu** [comment]
Hi @lucasoares - 

There wasn't too much done in the 1.2 -> 2.0 upgrade related to actually _changing_ behavior, beyond removing some `@Deprecated` stuff, so I can't explain right-off-the-bat what may be going wrong. What _did_ change was a lot of dependencies and the underlying Spring versions, so my hunch is the culprit is somewhere buried deep in the stack.

So lets try to debug a bit - can you first try to pull in the latest of the 1.2.x branch - `1.2.7.RELEASE` is our latest release, which corresponds to the `Hoxton.SR10` release of Spring Cloud.

If the tests all pass, then it may be related to an update in Spring Data. Let us know and we'll try to help dig into it.

**Comment by meltsufin** [comment]
@lucasoares I've just tested this kind of scenario and it still works on the current version. Did you check the Datastore console to see if the entity is actually saved? This looks more like an issue with the test. You might be checking for the existence of the entity too soon after saving. Remember that Datastore is eventually consistent. So, it may take some time before the entity can be read back from Datastore.

In our own integration tests, we use Awaitility to deal with this, like so:
```java
		this.testEntityRepository.saveAll(this.allTestEntities);
		await().atMost(20, TimeUnit.SECONDS).untilAsserted(() ->
			assertThat(this.testEntityRepository.countBySize(1L)).isEqualTo(3)
		);
```

**Comment by lucasoares** [comment]
Hello, @meltsufin and @ttomsu how you guys are doing?

I was just writing here the test case but I found out what I was doing wrong.

For some reason, I still had the old dependency on my classpath coming from another library and this @Entity was the only thing in my code using the library using old import.

Sorry for wasting your time! Thank you for the all-time support.
