### ISSUE TITLE
Datastore - When there is an Entity B extend A that contains a @Reference it doesn't get resolved

### ISSUE THREAD

**Issue by Stomrage** [GoogleCloudPlatform/spring-cloud-gcp#356]
I found a problem inside the entity resolving pattern. You can find the use case below:

Class A
```
@Entity(name = "A")  
public class A {
}
```
Class B
```
@Entity(name= "A")
public class B extends A {
  @Reference
  private C c; (also extend from A)
}
```
Repository of A
```
@Repository
public ARepository extend DatastoreRepository<A, Key>{}
```
Use case

```
A a = this.aRepository.findById("a_id");
B b = (B) a;
b.getC() => NULL
```

## Solution 1 (Not compatible with @ LazyReference)

Moving the reference of C inside B into A.
`C getC() { return (C) this.a;}`
It work when working with @ Reference but not with @ LazyReference. (Cannot cast from A into C)

## Solution 2

Create a repository of B with different kind of entity for each class

## Solution 3

In the function `private <T> T convertEntityResolveDescendantsAndReferences(Class<T> entityClass,
			DatastorePersistentEntity datastorePersistentEntity,
			BaseKey key, ReadContext context)`
https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/5229e6f4d265b0db4e1cf00b841f77417e907660/spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/core/DatastoreTemplate.java#L625

```
// Possible fix
// Modify the type of datastorePersistentEntity to be the type given by the @ DiscriminatorValue
// It seems like the framework already does that for backed properties inside the entity converter
// End possible fix
BaseEntity readEntity = context.getReadEntity(key);
convertedObject = this.datastoreEntityConverter.read(entityClass, readEntity);
context.putConvertedEntity(key, convertedObject);
context.removeReadEntity(key);
if (convertedObject != null) {
	resolveDescendantProperties(datastorePersistentEntity, readEntity, convertedObject, context);
        // datastorePersistentEntity is of type A. When it should be of type B to access the associations properties of B
	resolveReferenceProperties(datastorePersistentEntity, readEntity, convertedObject, context);
}
```

**Comment by Stomrage** [comment]
Coming back to this issue with a test case inside spring-cloud-gcp-data-datastore.

Repository + Entities
```
@Entity(name = "A")
@DiscriminatorField(field = "type")
public class EntityA {
    @Id
    private Key id;

    public Key getId() {
        return id;
    }
}

@Entity(name = "A")
@DiscriminatorValue("B")
public class EntityB extends EntityA{
}

@Entity(name = "A")
@DiscriminatorValue("C")
public class EntityC extends EntityA {

    @Reference
    EntityB entityB;

    public EntityC(EntityB entityB){
        this.entityB = entityB;
    }

    public EntityB getEntityB() {
        return entityB;
    }
}

@Repository
public interface EntityARepository extends DatastoreRepository<EntityA, Long> {}
```

The test case

```
@RunWith(SpringRunner.class)
@ContextConfiguration(classes = { DatastoreIntegrationTestConfiguration.class })
public class ReferenceResolvingntegrationTest extends AbstractDatastoreIntegrationTests{

    @Autowired
    EntityARepository entityARepository;

    @SpyBean
    private DatastoreTemplate datastoreTemplate;

    @BeforeClass
    public static void checkToRun() {
        assumeThat(
                "Datastore integration tests are disabled. Please use '-Dit.datastore=true' "
                        + "to enable them. ",
                System.getProperty("it.datastore"), is("true"));
    }

    @After
    public void deleteAll(){
        datastoreTemplate.deleteAll(EntityA.class);
        datastoreTemplate.deleteAll(EntityB.class);
        datastoreTemplate.deleteAll(EntityC.class);
    }

    @Test
    public void TestMyRepository(){
        EntityB entityB_1 = new EntityB();
        entityARepository.save(entityB_1);
        EntityC entityC_1 = new EntityC(entityB_1);
        entityARepository.save(entityC_1);
        EntityC fetchedC = (EntityC) entityARepository.findById(entityC_1.getId().getId()).get();
        //EntityC shouldn't be null and need to be resolve inside the template
        assertThat(fetchedC.getEntityB()).isNotNull();
    }
}
```

When fetching for EntityC inside the repository, inside DatastoreTemplate.convertEntityResolveDescendantsAndReferences

- EntityC is correctly translated from EntityA to EntityC thanks to the discriminator value
- convertedObject:EntityC => OK
- resolveReferenceProperties(datastorePersistentEntity, readEntity, convertedObject, context) => NOT OK
- The datastorePersistentEntity is of type EntityA

Maybe I misunderstood the goal of framework and this is a use case that souldn't be handled.

**Comment by Stomrage** [comment]
Fixed the issue with a simple and raw solution

DefaultDatastoreEntityConverter -> Give back the true entity behind the default one of the repository
```
	@Override
	public DatastorePersistentEntity getTruePersistentEntity(Class<?> aClass, BaseEntity entity) {
		DatastorePersistentEntity ostensiblePersistentEntity = (DatastorePersistentEntity) this.mappingContext
				.getPersistentEntity(aClass);
		EntityPropertyValueProvider propertyValueProvider = new EntityPropertyValueProvider(entity, this.conversions);

		return  getDiscriminationPersistentEntity(ostensiblePersistentEntity,
				propertyValueProvider);
	}
```

Inside the DatastoreTemplate -> Use this True entity to check for references
```
			if (convertedObject != null) {
				DatastorePersistentEntity trueEntity = this.datastoreEntityConverter.getTruePersistentEntity(entityClass, readEntity);
				resolveDescendantProperties(datastorePersistentEntity, readEntity, convertedObject, context);
				resolveReferenceProperties(trueEntity, readEntity, convertedObject, context);
			}
```

**Comment by dzou** [comment]
Thanks for the report @Stomrage and for looking into the issue. I think the use-case should be supported, seems like an issue on our end if we are not handling a complex entity relationship correctly.

```
@Entity(name = "A")
@DiscriminatorField(field = "type")
public class EntityA {
    @Id
    private Key id;

    public Key getId() {
        return id;
    }
}

@Entity(name = "A")
@DiscriminatorValue("B")
public class EntityB extends EntityA{
}

@Entity(name = "A")
@DiscriminatorValue("C")
public class EntityC extends EntityA {

    @Reference
    EntityB entityB;

    public EntityC(EntityB entityB){
        this.entityB = entityB;
    }

    public EntityB getEntityB() {
        return entityB;
    }
}

@Repository
public interface EntityARepository extends DatastoreRepository<EntityA, Long> {}
```

Just want to make sure I understand the problem: So in your example, this repository would return all `EntityA`, `EntityB`, and `EntityC` right? Because `B` and `C` are both subclasses of `A`?

And when you get an `EntityC` from the repository and then call `EntityC.getEntityB()`, this returns null?

**Comment by Stomrage** [comment]
> this repository would return all EntityA, EntityB, and EntityC right? 

- I forgot to mention that EntityA should be abstract but this is not relevant.
- The repository should return everything that extend from EntityA

> Because B and C are both subclasses of A?

- EntityA, EntityB, EntityC are of the same "Kind" which mean the same fetching group for the repository
- EntityA define a "DiscriminatorField"  and EntityB,EntityC define a "DiscriminatorValue" to cast from EntityA to subclasses of EntityA

> And when you get an EntityC from the repository and then call EntityC.getEntityB(), this returns null?

You have everything right.

**Comment by meltsufin** [comment]
@Stomrage I would suggest you open a PR with your proposed solution. Are the test failures due to real breakage, or they just need to be adjusted to accommodate for the change?

**Comment by Stomrage** [comment]
> Are the test failures due to real breakage, or they just need to be adjusted to accommodate for the change?

Seems like simple failure from Mocking issues, I'll dive deeper into the tests to ensure that everything is working correctly.

> I would suggest you open a PR with your proposed solution

Yep I'll do that when I find the time to so. (Currently using my modification for business purposes)

I also need to review the contribution guideline.

**Comment by THCoulon** [comment]
See: #377 for the pull request
