### ISSUE TITLE
Spring Native support

### ISSUE THREAD

**Issue by joeyslalom** [GoogleCloudPlatform/spring-cloud-gcp#379]
Spring Native has announced its beta release: https://spring.io/blog/2021/03/11/announcing-spring-native-beta

There is support for it at start.spring.io, but using it with GCP Support returns a project with its `HELP.md` saying 
```The following dependency is not known to work with Spring Native: 'GCP Support'. As a result, your application may not work as expected.```

Native Image support is very interesting for us, especially for our deployments to GKE and Cloud Run.

**Comment by meltsufin** [comment]
@dzou 
We're working on general GraalVM Native Image support for GCP here: https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support

**Comment by meltsufin** [comment]
@dzou Is there something we can do in this project to integrate `google-cloud-graalvm-support`? Maybe a starter and a sample? Docs?

**Comment by dzou** [comment]
> @dzou Is there something we can do in this project to integrate `google-cloud-graalvm-support`? Maybe a starter and a sample? Docs?

Yeah good idea. Let me try out some more code samples with different Spring Cloud GCP modules and then I can add this.

**Comment by joeyslalom** [comment]
Got a Kotlin project from the initializer running on Cloud Build: https://github.com/joeyslalom/upgraded-garbanzo

Everything builds fine (I used Cloud Build) but at runtime I got a `BeanDefinitionStoreException`.  Here's my workaround:
```kt
import com.google.cloud.spring.autoconfigure.datastore.GcpDatastoreEmulatorAutoConfiguration
import org.springframework.context.annotation.Configuration
import org.springframework.nativex.hint.TypeHint


@TypeHint(types = [GcpDatastoreEmulatorAutoConfiguration::class])
@Configuration
class GcpDatastoreEmulatorAutoConfigurationHint
```

The next runtime error I got was a `BeanInstantiationException`.  This required a workaround in `build.gradle.kts`:
```kts
tasks.withType<BootBuildImage> {
	builder = "paketobuildpacks/builder:tiny"
	environment = mapOf("BP_NATIVE_IMAGE" to "true",
		"BP_NATIVE_IMAGE_BUILD_ARGUMENTS" to "--enable-url-protocols=http")
}
```

Some notes:
* I tried including `google-cloud-graalvm-support`, but that had no effect.
* I also tried including `spring-cloud-gcp-starter-logging`, but could not use it due to https://github.com/spring-projects-experimental/spring-native/issues/625
* Very fast startup: `SpringApplication : Started application in 0.675 seconds (JVM running for 1.09)`
* GCR reports virtual size: 32.7 MB

**Comment by joeyslalom** [comment]
Got a Kotlin project from the initializer running on Cloud Run: https://github.com/joeyslalom/upgraded-garbanzo

Everything builds fine (I used Cloud Build) but at runtime I got a `BeanDefinitionStoreException`.  Here's my workaround:
```kt
import com.google.cloud.spring.autoconfigure.datastore.GcpDatastoreEmulatorAutoConfiguration
import org.springframework.context.annotation.Configuration
import org.springframework.nativex.hint.TypeHint


@TypeHint(types = [GcpDatastoreEmulatorAutoConfiguration::class])
@Configuration
class GcpDatastoreEmulatorAutoConfigurationHint
```

The next runtime error I got was a `BeanInstantiationException`.  This required a workaround in `build.gradle.kts`:
```kts
tasks.withType<BootBuildImage> {
	builder = "paketobuildpacks/builder:tiny"
	environment = mapOf("BP_NATIVE_IMAGE" to "true",
		"BP_NATIVE_IMAGE_BUILD_ARGUMENTS" to "--enable-url-protocols=http")
}
```

Some notes:
* I tried including `google-cloud-graalvm-support`, but that had no effect.
* I also tried including `spring-cloud-gcp-starter-logging`, but could not use it due to https://github.com/spring-projects-experimental/spring-native/issues/625
* Very fast startup: `SpringApplication : Started application in 0.675 seconds (JVM running for 1.09)`
* GCR reports virtual size: 32.7 MB

**Comment by dzou** [comment]
@joeyslalom -- Thanks for sharing your findings, this is very helpful. Sorry I've been delayed from doing this, we've been prioritizing just getting the base GCP client libraries and will move onto supporting Spring Cloud GCP soon. Adding the autoconfigurations for example is something we'll add on our end so you won't need to add your own native hints.

Regarding `google-cloud-graalvm-support`, I think you may need to add this eventually when you begin to interact with the Datastore client and start reading/writing documents.

Great to hear that you were able to get something working.

**Comment by joeyslalom** [comment]
With the new releases of Spring Native, I updated my project to also include Cloud SQL support and Spring Data (this required a lot more `@TypeHint`).  However, I also noticed there is another incompatibility using start.spring.io's Spring Native + GCP Support; incompatibility with Spring Native and also incompatibility with Spring Boot 2.5.x.

@dzou `google-cloud-graalvm-support` seems less useful as the sample uses even older releases:
```
<properties>
    <spring-boot.version>2.4.0-M3</spring-boot.version>
    <spring-cloud-gcp.version>1.2.8.RELEASE</spring-cloud-gcp.version>
</properties>
```

**Comment by elefeint** [comment]
Spring Framework 6 includes native configurations without spring-native project. We won't be adding native compilation facilities to Spring Cloud GCP until the project moves to Spring Framework 6 next year. Once that happens, we'll be building native support on top of the existing client library support, which moved from the standalone repo to the individual client libraries.
