### ISSUE TITLE
Linkage checker failing after recent deluge of Dependabot updates

### ISSUE THREAD

**Issue by ttomsu** [GoogleCloudPlatform/spring-cloud-gcp#389]
Builds 47-50 as of this writing, but check her for the latest: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions?query=branch%3Amain+workflow%3A%22Linkage+Check%22+is%3Afailure

**Comment by suztomo** [comment]
Linkage Checker 1.5.7 fixed a bug where Linkage Checker was not working for spring-cloud-gcp. Now it work as designed but it reports too many. I created an issue on me to investigate these errors.

https://github.com/GoogleCloudPlatform/cloud-opensource-java/issues/1983#issuecomment-800303299

**Comment by elefeint** [comment]
Obsolete; we decided not to use linkage checker on this project.
