### ISSUE TITLE
The CI does not appear to run all the tests of a module

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/spring-cloud-gcp#39]
The github actions CI is not running all the tests. See logs: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/runs/945379936

Typically you will see something like this: `0 tests run` in modules with tests. Will investigate what is going on.

```
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ spring-cloud-gcp-logging ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
```

**Comment by dzou** [comment]
Seems to have started happening after I updated the versions: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/35

**Comment by meltsufin** [comment]
I suspect that the surefire and/or failsafe plugin configuration changed in the parent, which is `spring-cloud-build` for us.

**Comment by dzou** [comment]
Thanks for the tip, and thanks @elefeint for pointing out that by default JUnit4 tests do not get run if a project is configured to use JUnit 5.

Looks like we have to add this snippet to get it to work:

```
		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<scope>test</scope>
		</dependency>
```
