### ISSUE TITLE
Is the commons-logging dependency of pubsub wanted?

### ISSUE THREAD

**Issue by markusheiden** [GoogleCloudPlatform/spring-cloud-gcp#394]
**Describe the bug**
Is the commons-logging:commons-logging dependency of com.google.cloud:google-cloud-pubsub wanted?

As of the prior commit https://github.com/GoogleCloudPlatform/spring-cloud-gcp/commit/a5b648bdfbfd0cda190b5d91296b2db8a1555e2c that should have been removed.

**Comment by meltsufin** [comment]
@markusheiden Can you please clarify a bit more? Are you saying that we are pulling this dependency transitively through Pub/Sub lib? Is it causing some issue?

**Comment by markusheiden** [comment]
Yes it is pulled transitively (compile scope) by pubsub. Try mvn dependency:tree in a maven project.

We have a check (maven enforcer plugin) for unwanted dependencies in our project, which fails with the new pubsub dependency. We use jcl-over-slf4j for logging which clashes with commons-logging. That does not cause any compile time problems, but may lead to incorrect logging.

**Comment by meltsufin** [comment]
It looks like Pub/Sub client library is pulling it in transitively.
```
[INFO] com.google.cloud:google-cloud-pubsub:jar:1.112.0
[INFO] \- com.google.http-client:google-http-client:jar:1.39.0:compile
[INFO]    \- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO]       \- commons-logging:commons-logging:jar:1.2:compile
```
It's probably best to ask the question there: https://github.com/googleapis/java-pubsub.

Have you tried just excluding the dependency in your pom to see if everything still works fine?

**Comment by markusheiden** [comment]
Yes, I excluded it and it works. But I just tried it in local development and not in production yet.

Anyway the Spring Boot logging dependencies should include support for commons-logging (but not the commons-logging implementation itself), because Spring itself relies on commons-logging.

mvn dependency:tree shows for me, that google-cloud-pubsub includes commons-logging directly:
```
[INFO] |  |  +- com.google.cloud:spring-cloud-gcp-starter-pubsub:jar:2.0.1:compile
[INFO] |  |  |  \- com.google.cloud:spring-cloud-gcp-pubsub:jar:2.0.1:compile
[INFO] |  |  |     \- com.google.cloud:google-cloud-pubsub:jar:1.108.6:compile
[INFO] |  |  |        +- io.grpc:grpc-api:jar:1.33.0:compile
[INFO] |  |  |        +- org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime
[INFO] |  |  |        +- io.grpc:grpc-stub:jar:1.33.0:compile
[INFO] |  |  |        +- io.grpc:grpc-protobuf:jar:1.33.0:compile
[INFO] |  |  |        +- io.grpc:grpc-protobuf-lite:jar:1.32.2:compile
[INFO] |  |  |        +- com.google.api.grpc:proto-google-cloud-pubsub-v1:jar:1.90.6:compile
[INFO] |  |  |        +- org.checkerframework:checker-compat-qual:jar:2.5.5:compile
[INFO] |  |  |        +- com.google.api:gax-grpc:jar:1.60.0:compile
[INFO] |  |  |        +- io.grpc:grpc-auth:jar:1.33.0:compile
[INFO] |  |  |        +- io.grpc:grpc-netty-shaded:jar:1.33.0:compile
[INFO] |  |  |        +- io.grpc:grpc-alts:jar:1.33.0:compile
[INFO] |  |  |        +- io.grpc:grpc-grpclb:jar:1.33.0:compile
[INFO] |  |  |        +- org.apache.commons:commons-lang3:jar:3.11:compile
[INFO] |  |  |        +- org.conscrypt:conscrypt-openjdk-uber:jar:2.2.1:compile
[INFO] |  |  |        +- io.grpc:grpc-core:jar:1.33.0:compile
[INFO] |  |  |        +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  |  |        +- io.perfmark:perfmark-api:jar:0.19.0:runtime
[INFO] |  |  |        \- commons-logging:commons-logging:jar:1.2:compile
```

The google-cloud-pubsub pom of version 1.112.0 proves that:
```
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <version>1.2</version>
      <scope>compile</scope>
      <exclusions>
        <exclusion>
          <artifactId>log4j</artifactId>
          <groupId>log4j</groupId>
        </exclusion>
        <exclusion>
          <artifactId>logkit</artifactId>
          <groupId>logkit</groupId>
        </exclusion>
        <exclusion>
          <artifactId>avalon-framework</artifactId>
          <groupId>avalon-framework</groupId>
        </exclusion>
        <exclusion>
          <artifactId>servlet-api</artifactId>
          <groupId>javax.servlet</groupId>
        </exclusion>
      </exclusions>
      <optional>false</optional>
    </dependency>
```

**Comment by meltsufin** [comment]
I don't see it in the source. Can you point me to it?
https://github.com/googleapis/java-pubsub/blob/v1.112.0/google-cloud-pubsub/pom.xml

**Comment by markusheiden** [comment]
Some plugin (maven-dependency-plugin?) seems to rewrite the pom. Maybe the plugin comes from the parent pom.

You can see the final result here: https://search.maven.org/artifact/com.google.cloud/google-cloud-pubsub/1.112.0/jar

**Comment by meltsufin** [comment]
I suspect that the flatten plugin is doing it. So, it's just obscures the fact that it's a transitive dependency.
```
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
      </plugin>
```

Either way, I think it's really a question for the Pub/Sub Client library.
