### ISSUE TITLE
Upgrade to Spring Cloud Sleuth version that is Ilford

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/spring-cloud-gcp#4]
Currently, we're overwriting the version of Sleuth in the parent POM.
This overwrite should be removed and the `-Dit.trace=true` integration tests need to be made to pass with the latest version.

Follow-up to #3.

Also look at https://github.com/spring-cloud/spring-cloud-gcp/issues/2268.

**Comment by meltsufin** [comment]
Also change `B3Propagation.Format.MULTI` to `B3Propagation.Format.SINGLE_NO_PARENT` as mentioned in https://github.com/spring-cloud/spring-cloud-gcp/pull/2290#issuecomment-630510628`

**Comment by elefeint** [comment]
There are a few more changes requred:
* the sampler config is defaulting to NEVER again, so we'll need to reimport it manually in trace autoconfig. 
* SleuthProperties is now package private, so we can't override `supportsJoin` and `setTraceId128` in properties anymore. We'll likely need to provide the whole `SpanHandler` bean`.
* There is an old version of brave coming from somewhere again...
