### ISSUE TITLE
Workload identity isnt supported?

### ISSUE THREAD

**Issue by lechen26** [GoogleCloudPlatform/spring-cloud-gcp#403]
Hi

when using spring app with GKE workload identity enabled the 'Default compute engine credentials' is still in action although gcloud recognize service account is being used.

SpringCloudVersion 2020.0.1
SpringGCPVersion 2.0.0

before GKE workload identity feature, when no service account was set on the workload, and no env for encoded_key set, the credentials that were automatically retrieved was the ComputeEngineCredentials one.

on the log we could see the messages:
`Default credentials provider for Google Compute Engine`

now, when GKE workload identity is enabled, and serviceAccount set on the GKE workload, when issuing gcloud auth list i do see the right service account but on the spring application i still see the same message where thee Default credentials being used. 

is it expected? wasnt it supposed to show the service account that were injected to the workload?
I dont want to set an env variable that points to json cause that's the all idea of the workload identity...

Thanks

**Comment by meltsufin** [comment]
We simply delegate handling of default credentials to the client libraries. So, it should work. You can even try just connecting to the library directly without Spring Cloud GCP. There should be no difference.

Do you have the GKE metadata service available? See explanation here: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#gke_mds.

**Comment by lechen26** [comment]
Yes i do.
when doing the same with NodeJS library , it works as expected.
gcloud command and the application has the same permissions.

when using the spring-cloud-gcp packages i always see the Default credentials message.

based on the code i see its the 'CompuneEngineCredentials'. how does it retrieve it?

thanks

**Comment by lechen26** [comment]
Ok, i think only the printing is wrong.

as mentioned when using Workload identity by providing serviceAccount attribute on the workload, 
while starting the service i see the default Credentials of compute message appear on the log:
```
Default credentials provider for Google Compute Engine.
Scopes in use by default credentials: [https://www.googleapis.com/auth/pubsub, https://www.googleapis.com/auth/spanner.admin, https://www.googleapis.com/auth/spanner.data, https://www.googleapis.com/auth/datastore, https://www.googleapis.com/auth/sqlservice.admin, https://www.googleapis.com/auth/devstorage.read_only, https://www.googleapis.com/auth/devstorage.read_write, https://www.googleapis.com/auth/cloudruntimeconfig, https://www.googleapis.com/auth/trace.append, https://www.googleapis.com/auth/cloud-platform, https://www.googleapis.com/auth/cloud-vision, https://www.googleapis.com/auth/bigquery, https://www.googleapis.com/auth/monitoring.write]
```


BUT, when the service account of the workload does not includes the needed permissiosn for GCP, such as for Cloud Storage in my case, i do get an exception saying my service account does not have the right permissions.
and the error does includes the right service account:

```
com.google.cloud.storage.StorageException: 403 Forbidden
{ "code": 403, "message": "storage-service-account@myproject.iam.gserviceaccount.com does not have storage.objects.create access to mybucket/files/71233c.txt." }
```

so it does identify right the service account of Workload identity and acts upon it, its just wrongly prints the 'Using Default compute service account'.

thanks

**Comment by meltsufin** [comment]
I see. Well, workload identity becomes the default credentials provider for compute engine. So, I don't know if the log is really incorrect. Take a look at the `DefaultCredentialsProvider` class. The message is coming from there.
