### ISSUE TITLE
Updates needed for Secret Manager Bootstrap Configuration

### ISSUE THREAD

**Issue by dzou** [GoogleCloudPlatform/spring-cloud-gcp#41]
In a change in `spring-cloud-context`, we will now need to set a property in order to enable secret bootstrap initialization: `spring.config.use-legacy-processing=true`

https://github.com/spring-cloud/spring-cloud-commons/pull/703

@meltsufin - Should we ask users to set this themselves? Or I was thinking - we could add this setting in our secret-manager-starter `application.properties` file? You could say that the addition of our starter implies they want to enable this...

**Comment by elefeint** [comment]
Hmm, the presence of `use-legacy-processing` implies that there is a new way of getting properties into the bootstrap phase. Maybe document this as workaround, and get the new way into 1.2.5?

**Comment by meltsufin** [comment]
+1 on what @elefeint said regarding adoption of the new non-legacy bootstrap initialization method, if possible.
Does this changes in `spring-cloud-commons` apply to Hoxton as well, or just Ilford?

**Comment by dzou** [comment]
For now going to simply use the property in the tests to unblock ourselves. I've added the `p0` label as a reminder to ask for the recommended solution from the Spring team to find a proper solution before we release.

Note I think this only affects the Ilford release; the spring-cloud-gcp 1.2.x is relying on the Hoxton snapshots and should be OK.

**Comment by eddumelendez** [comment]
The new way is using `spring.config.import` property key. Read `Importing Additional Configuration` and `Supporting Additional Locations` https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4

You can use `gcp-secretmanager:` as a prefix

**Comment by dzou** [comment]
Followed up with Spencer and his response:

> spring.config.import bypasses some of the edge cases with bootstrap that can cause problems for folks
> By far the easiest way is to use the bootstrap starter. Just document that folks will use bootstrap still.

Seems like this should be OK for now until a user runs into issue.

Notes on how to implement `spring.config.import`: 

Eddu's PR: https://github.com/spring-cloud/spring-cloud-aws/pull/721

Some Spring Gitter Q/A:
![image](https://user-images.githubusercontent.com/3209274/100002656-e37c9580-2d92-11eb-9340-badeb96d5a81.png)

**Comment by dzou** [comment]
Gonna re-open this - I think we have to do this at some point eventually anyway. And it seems like bootstrap can co-exist with the new property source loading method.

@eddumelendez - Hey I got a question, I saw that you create a new instance of your secret manager client object in the `AwsSecretsManagerConfigDataLocationResolver`. We have a situation where we offer the secrets property source but also allow users to `@Autowire` the secret manager client in their autoconfiguration.

Is this how you would do it? I.e. can standard autoconfiguration classes access the bootstrap registry where you create the client bean?

**Comment by dzou** [comment]
Based on discussions today sounds like we will just keep the bootstrap pattern and avoid introducing this for now (since it will increase complexity by requiring users to manually add the bootstrap starter).

I'll leave my PR up as a reference for the future if it is needed.

**Comment by eddumelendez** [comment]
@dzou sorry for the delay

> @eddumelendez - Hey I got a question, I saw that you create a new instance of your secret manager client object in the `AwsSecretsManagerConfigDataLocationResolver`. We have a situation where we offer the secrets property source but also allow users to @Autowire the secret manager client in their autoconfiguration.

The SecretsManager client is created and then registered as a bean at `AwsSecretsManagerConfigDataLocationResolver` and as such can be resolved by the application using `@Autowired` but if you mean create their own client and that one used in the `ConfigDataLocationResolver` then I think the approach is similar to the one for [Vault](https://github.com/spring-cloud/spring-cloud-vault/blob/0355f153b1f02a3d143a654ded3c55063dcdbb26/spring-cloud-vault-config/src/main/java/org/springframework/cloud/vault/config/VaultConfigDataLocationResolver.java#L80) 

This should be added manually

```
application.addBootstrapper(registy -> register(VaultConfigurer.class, context -> configurer));
```

and then the ConfigDataLocationResolver can look for it, but yeah it will need an extra step.

```
private static Collection<VaultConfigurer> getVaultConfigurers(ConfigurableBootstrapContext bootstrapContext) {
	Collection<VaultConfigurer> vaultConfigurers = new ArrayList<>(1);
	if (bootstrapContext.isRegistered(VaultConfigurer.class)) {
		vaultConfigurers.add(bootstrapContext.get(VaultConfigurer.class));
	}
	return vaultConfigurers;
}
```
