### ISSUE TITLE
CloudSqlEnvironmentPostProcessor not compatible with Spring Cloud Bootstrap PropertySourceLocator mechanism

### ISSUE THREAD

**Issue by mzeijen** [GoogleCloudPlatform/spring-cloud-gcp#433]
I discovered that the new `CloudSqlEnvironmentPostProcessor` within Spring Cloud GCP 2.x causes issues when you combine it with properties that are being loaded via a [`PropertySource`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/context/annotation/PropertySource.html) that is created via the [Spring Cloud Bootstrap `PropertySourceLocator`](https://docs.spring.io/spring-cloud-commons/docs/current/reference/html/#customizing-bootstrap-property-sources). The reason is that the properties loaded via  a `PropertySource` that is created by a `PropertySourceLocator` are loaded after the `CloudSqlEnvironmentPostProcessor` is executed.

The case in which we discovered this is as follows:
 - In the `application.yml`, on the classpath, the property `spring.cloud.gcp.sql.enabled` is set to `false` 
 - When the application is deployed to a GKE environment, [Spring Cloud Kubernetes](https://docs.spring.io/spring-cloud-kubernetes/docs/current/reference/html/#configmap-propertysource) is used to load a Kubernetes ConfigMap, via the Kubernetes API so the ConfigMap is not mounted in the container, and this ConfigMap contains the same `spring.cloud.gcp.sql.enabled` property but it set to `true`
 - The intention is to have CloudSQL disabled when developing locally, but it is used when running the application within GKE.
 - When deploying in GKE with the ConfigMap, the `spring.cloud.gcp.sql.enabled=true` is never picked up by the `CloudSqlEnvironmentPostProcessor` and thus it doesn't do its thing to setup the required correct `Datasource` for CloudSQL. The application fails to startup.
 - The issue is that Spring Cloud Kubernetes uses the Spring Cloud Bootstrap `PropertySourceLocator` mechanism to create a `PropertySource` for the ConfigMap but this happens when the `ApplicationContextInitializers` are executed, which is after the `EnvironmentPostProcessor` have been executed in the normal application context startup phase (so the `PropertySourceLocator` is only created in the bootstrap contact startup phase and executed in the application context startup phase). Because of that the `CloudSqlEnvironmentPostProcessor` never sees the properties from the ConfigMap PropertySource.

To figure out what was going on took some time. In the end, there are plenty workaround like simply mounting the ConfigMap and loading via one of the ways that Spring Boot has to load configuration, but it would be best if the CloudSQL support mechanism in Spring Cloud GCP would simply be compatible with Spring Cloud Bootstrap and it all works as expected.

I am not sure what a good solution is. Maybe go back to the mechanism from Spring Cloud GCP 1.x?

**Sample**
I have not provided a code sample, as this is requires fairly complicated setup to demonstrate the issue. I hope that the explanation above suffices to make the issue clear.

**Comment by dzou** [comment]
Thanks for the report. Unfortunately we migrated from the old way of doing things due to some issues that emerged in the ilford releases [(context here)](https://github.com/spring-cloud/spring-cloud-gcp/issues/272). I don't think we can switch back.

Do you know if the `CloudSqlEnvironmentPostProcessor` gets executed once or twice?

We had a bootstrap [issue here before](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/252) which sounds like it might have solved a similar problem? Perhaps we can add your property source to that `if-condition` we had:

```
if (environment.getPropertySources().contains("bootstrap") || /* Your property source name here */) {
      // Do not run in the bootstrap phase as the user configuration is not available yet
      return false;
}
```

**Comment by mzeijen** [comment]
Thanks for the background information. It will be a hard one to fix then. A possibly ugly solution would be to create a `ApplicationContextInitializer` that does the work instead?
At least it would be good to add some kind of warning to the documentation that the current implementation doesn't play nice with `PropertySourceLocators` like those from Spring Cloud Kubernetes?

Regarding your other question. The `CloudSqlEnvironmentPostProcessor ` is indeed executed twice, once in the bootstrap startup phase and once in the application startup phase, but that conditional indeed ensures it only does work on the application startup phase. But at that point the `PropertySourceLocators` haven't created the `PropertySources` yet. 
TBH, I believe the `PropertySourceLocator` mechanism is actually the problem here. In my opinion it should have resolved all the properties in the bootstrap phase and then have injected the `PropertySources` into the application startup phase even before or at the start of the execution of the `EnvironmentPostProcessors`. But I guess the `PropertySourceLocator` mechanism is something that is going to be removed over time (and the bootstrap phase as a whole) now that Spring Boot has improved mechanism to read properties from external sources.

**Comment by dzou** [comment]
I see. Yeah we can do something to update the docs. I would still be interested to see if it's possible to reproduce the issue -- Is the overall idea to set the `spring.cloud.gcp.sql.enabled=false` and to be able to override that to `true` with a bootstrap configuration?

**Comment by meltsufin** [comment]
Notice that `EnvironmentPostProcessor`s can be ordered. We did not provide a specific order for `CloudSqlEnvironmentPostProcessor`, and maybe that doesn't play way with the Kubernates `PropertySourceLocators`. I'd be happy to look into this issue, but we need some kind of repro for it. Can the Cloud SQL sample be modified to illustrate this issue?

**Comment by mzeijen** [comment]
@meltsufin Changing the order of the `EnvironmentPostProcessors` won't help because the `PropertySourceLocator` is executed in another phase, as a `ApplicationContextInitializer`, and that always comes after the `EnvironmentPostProcessor` phase.

I will create a todo for me to see if I can create a simple reproduction somewhere next week.

**Comment by meltsufin** [comment]
@snicoll Do you have any insight into this kind of issue?

**Comment by snicoll** [comment]
I thought we already discussed this, didn't we? See https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/215#issuecomment-774958577

**Comment by mzeijen** [comment]
This problem indeed occurs due to limitations in the deprecated bootstrap mechanism. I am not sure if you should try to fix this issue. Adding a warning to the documentation regarding which properties should not be configured via property sources that require the legacy bootstrap methods, should suffice in my opinion.

**Comment by meltsufin** [comment]
I'm confused on this because we specifically skip the `CloudSqlEnvironmentPostProcessor` in the bootstrap phase since #273. So, bootstrap should not interfere with it. The `CloudSqlEnvironmentPostProcessor` then actually runs during the normal application context init phase which should have all the property sources available at that point.

**Comment by snicoll** [comment]
That's a different problem with the same cause. Even if your BPP runs in the right "context" it runs before Spring Cloud Config Server has loaded the remote config, see https://github.com/spring-cloud/spring-cloud-commons/issues/608#issuecomment-626340364

**Comment by mzeijen** [comment]
Indeed, but in this case it is not the Spring Cloud Config Server but a Spring Cloud Kubernetes ConfigMap PropertySource, but the mechanism is the same.

**Comment by snicoll** [comment]
Right. Same design issue yeah.

**Comment by meltsufin** [comment]
@limkinZero Are you able to use the setting in `application.yaml`? `CloudSqlEnvironmentPostProcessor` is not part of the bootstrap phase.

**Comment by limkinZero** [comment]
I couldn't. I tried configue the property in the application.properties
with the same error.

**Comment by meltsufin** [comment]
@limkinZero That's interesting. You might have something else going on in your application configuration. Would you be able to provide a reproducible example of this issue?

**Comment by limkinZero** [comment]
Mmm, you can check this branch:
https://gitlab.com/aweframework/awe/-/tree/380-configure-cloud-sql-for-awe-boot-project-on-the-cloud

but you have to add the dependency to pom.xml file in awe-boot project
（awe-test module）and configure the bootstrap.yaml to disable gpc.

**Comment by meltsufin** [comment]
@limkinZero Would you be able to make the necessary changes in a fork and provide exact instructions on how to reproduce the issue?

**Comment by elefeint** [comment]
I wonder if we should try implementing the Cloud SQL configuration as a custom `ConfigDataResource`, similarly to what @JoeWang1127 is doing with Secret Manager now. This would allow the datasource properties to be truly ordered together with the other `spring.config.import` property sources.

This would not help with refreshing credentials and such because of GoogleCloudPlatform/cloud-sql-jdbc-socket-factory#776 / #1204, but it may be an improvement. 

@mzeijen What are you doing as a workaround in the meantime -- maven profiles?

**Comment by JoeWang1127** [comment]
@mzeijen @limkinZero @elefeint I created a demo project in [here](https://github.com/JoeWang1127/demo-sql-kube). It can be treated as a workaround of this issue.

**Comment by JoeWang1127** [comment]
Close this issue as no response, please reopen the issue if needed.
