### ISSUE TITLE
Upgrade to Spring Boot 2.5

### ISSUE THREAD

**Issue by meltsufin** [GoogleCloudPlatform/spring-cloud-gcp#472]
Spring Boot 2.5 is a major version upgrade, and so cannot be done automatically.

## Changes to address for 2.5:

New method in `CrudRepository`: [`deleteAllById()`](https://github.com/spring-projects/spring-data-commons/pull/476). Since we support both Spring Boot 2.4 and 2.5, this means we'll have to omit `@Overrides` annotation to maintain ability to compile against 2.4.
- [ x] Implement in `SimpleDatastoreRepository`  (#565)
- [ x] Implement in `SimpleFirestoreReactiveRepository` (#566)
- [ x] Implement in `SimpleSpannerRepository` (#567)

Return types for `previous()` and `next()` were restricted from generic `Pageable` to `PageRequest`.
- [ x] Update `DatastorePageable` with the new return types. Slight complication that we pass some non-paged pageables into `DatastorePageable` static methods (#564).  

Ref: #471

**Comment by elefeint** [comment]
Spring Cloud tracks Spring Boot 2.5 migration in [3.1.x branch](https://github.com/spring-cloud/spring-cloud-build/blob/3.1.x)

**Comment by spencergibb** [comment]
@elefeint the 3.1.x branch will only be 2.5 until 2.6 starts. 2.5 support is on the 3.0 branch but as forwards compatible. So spring cloud 2020.0.3 supports both boot 2.4 and 2.5. Spring cloud 2021.0 will support 2.6

**Comment by elefeint** [comment]
@spencergibb That's good to know, thank you -- I remember that the original Illford announcement was for both, 2.4 and 2.5 Boot support, but then I saw that Spring Cloud Build main is [still on 2.4.6](https://github.com/spring-cloud/spring-cloud-build/blob/6ff762f675d6c8302dcab435a4e984dd86a65605/pom.xml#L31).

Out of curiosity, how will Spring Cloud train test compatibility with both, 2.4 and 2.5 -- will you be running parallel builds with a different Spring Boot dependency? We would face the same issue if we support both versions simultaneously...

**Comment by spencergibb** [comment]
We run all of our builds with boot 2.5. We actually change the version of boot in spring cloud build, build it locally, then run the project build

**Comment by meltsufin** [comment]
Thanks for the clarification!

**Comment by elefeint** [comment]
One of the changes will be in Spring Data -- crud repositories and the reactive variants added a [new `deleteAllById()` method](https://github.com/spring-projects/spring-data-commons/blob/fb3e50951eb73e70edcf0dda17aa1b7ba4454d03/src/main/java/org/springframework/data/repository/CrudRepository.java#L120).
