### ISSUE TITLE
Support for IAM database authentication

### ISSUE THREAD

**Issue by breun** [GoogleCloudPlatform/spring-cloud-gcp#474]
Cloud SQL supports IAM logins: https://cloud.google.com/sql/docs/postgres/iam-logins

Support for this has recently been added to the Cloud SQL Java socket factory library: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/350

Could Spring Cloud GCP expose support for this?

**Comment by meltsufin** [comment]
This is blocked on the release of the Cloud SQL Java socket factory library. Once that's done, we'll take a look at what's involved, but otherwise we also welcome external contributions.

**Comment by meltsufin** [comment]
The release has arrived: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/releases/tag/v1.3.0

**Comment by meltsufin** [comment]
I started looking into this, but having some issues getting it to work.
See: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/515

**Comment by mzeijen** [comment]
Thanks Mike!
