### ISSUE TITLE
Error on Testing

### ISSUE THREAD

**Issue by jofre62** [GoogleCloudPlatform/spring-cloud-gcp#481]
**Describe the bug**
I am using spring-cloud-gcp and pubsub as follows :

<version>2.4.5</version>
<spring-cloud.version>2020.0.2</spring-cloud.version>
<spring-cloud-gcp.version>2.0.0</spring-cloud-gcp.version>

Everything runs well until I run the tests.

On tests I always get an error on Sleuth, as follows :

No qualifying bean of type 'org.springframework.cloud.sleuth.instrument.web.servlet.TracingFilter' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}

Removing springboot gcp everything goes allright.

**Comment by meltsufin** [comment]
Is there any reason you're not using `2.0.2` of Spring Cloud GCP?
Can you share a simple example where the issue is reproduced?
Thanks!

**Comment by meltsufin** [comment]
Closing due to no response from OP.
