### ISSUE TITLE
spring-cloud-gcp-storage add meta data when writing to GoogleStorageResource

### ISSUE THREAD

**Issue by michaelmok2021** [GoogleCloudPlatform/spring-cloud-gcp#483]
I am trying to figure how to specify the metadata for the file I am writing to google storage. I am using GoogleStorageResource to wrote the contents.  see example below. 

```java
 public void writeToStorage(byte[] contents, String fileName) throws IOException {
        GoogleStorageResource childResource = getChildResource(fileName);
        try (OutputStream os = childResource.getOutputStream()) {
            os.write(contents);
        }
        log.info("it works");
    }
```
Is there a way or function to set the metadata properties of the GoogleStorageResource? Thanks.

**Comment by elefeint** [comment]
@michaelmok2021 There is no ability to set ACL when automatically creating a file through `GoogleStorageResource`. However, you can inject the lower level `com.google.cloud.storage.Storage` object, and then use its `create(Blob, BlobTargetOption)` variant to set up permissions.

This looks like a good feature request for the `GoogleStorageResource` object to acquire an overridden `createBlob(BlobTargetOption...)` variant. Would you be interested in contributing the code to the project?

**Comment by michaelmok2021** [comment]
@elefeint I figure how to add the meta data using existing functions. See below the solution.
` 
public void writeToStorage(byte[] contents, String fileName, Map<String, String> metadata) throws IOException {
        GoogleStorageResource childResource = getChildResource(fileName);
        try (OutputStream os = childResource.getOutputStream()) {
            os.write(contents);
        }
        // set meta data
        Blob blob = childResource.getBlob();
        // Does an upsert operation, if the key already exists it's replaced by the new value, otherwise
        // it's added.
        blob.toBuilder().setMetadata(metadata).build().update();
        log.info("file written to GCP storage");
    }
`
