### ISSUE TITLE
Custom PubSub subscription name delimiter

### ISSUE THREAD

**Issue by artemptushkin** [GoogleCloudPlatform/spring-cloud-gcp#487]
### Problem

It might be quite an often case, as for me, when you migrate to an existent topic and/or follow company naming conventions and have a different pattern for subscription name than it is supposed to be by `spring-cloud-gcp`.

Currently, you have "." as the delimiter

> Subscription name must be matched by convention `<destinationName>.<consumerGroup>` where `destinationName` is a topic name

The problem is that it is a case when someone needs another delimiter.

### Suggestion

Have dot as the default delimiter and make it customizable through the app properties, for instance:
```yaml
spring.cloud.stream.gcp.pubsub.bindings.<channel-name>.consumer.subscription-delimeter='-'
```

### Alternatives

Unfortunately, there is no way to have a workaround against the hardcoded value.

### Comments

I believe it can be done in a neat way as you use _subscriptionName_ only for indeed subscription creation [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-pubsub-stream-binder/src/main/java/com/google/cloud/spring/stream/binder/pubsub/provisioning/PubSubChannelProvisioner.java#L95), i.e. I see this as a backward compatible change.

**Comment by elefeint** [comment]
@artemptushkin Pub/Sub consumer configuration allows for a completely custom subscription name to be used. So you could specify your company's correct naming convention as follows:
```
spring.cloud.stream.gcp.pubsub.bindings.<channel-name>.consumer.subscriptionName=<destinationName>-<consumerGroup>
```
See [property documentation](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/docs/src/main/asciidoc/spring-stream.adoc#consumer-destination-configuration) for the full order of subscription name resolution.

Would this meet your requirement?

**Comment by artemptushkin** [comment]
It does indeed, really missed that part, thanks!
