### ISSUE TITLE
Use Emulator Credentials when using Firestore Emulator

### ISSUE THREAD

**Issue by cjenkscybercom** [GoogleCloudPlatform/spring-cloud-gcp#501]
**describe the problem** 
When trying to run CI/CD against a Firestore emulator instance (e.g. in GitHub Actions), tests were failing due to not finding the GOOGLE_APPLICATION_CREDENTIALS location. This was unexpected since we'd configured emulator=true, and it ofc wasn't caught because we all have this already set on our local machines.
```
spring.cloud.gcp.firestore.emulator.enabled=true
spring.cloud.gcp.firestore.host-port=localhost:1234
spring.cloud.gcp.project-id=emulator
```

So, the workaround was to override the CredentialsProvider to explicitly use `FirestoreOptions.EmulatorCredentials()`:
```
import com.google.api.gax.core.CredentialsProvider;
import com.google.auth.Credentials;
import com.google.cloud.firestore.FirestoreOptions;
//

@Configuration
public class SomeConfiguration {

  @Profile("integration-test")
  @Primary
  @Bean
  CredentialsProvider credentialsProvider() {
    return new CredentialsProvider() {
      @Override
      public Credentials getCredentials() throws IOException {
        return new FirestoreOptions.EmulatorCredentials();
      }
    };
  }
}
```

**Describe the solution you'd like**
It'd be nice if this worked without further configuration; e.g. if CredentialsProvider used emulator credentials when emulator is enabled.

**Describe alternatives you've considered**
 I see in the source that CredentialsProvider always pulls from the location on the Credentials object, which makes sense since a lot of the GCP components don't have emulator support. Might be tricky, if you don't want to add some lines to check typeof Credentials.

**Additional context**
None

**Comment by meltsufin** [comment]
I think it's a bug because I see that `GcpFirestoreEmulatorAutoConfiguration` does not actually provide an emulator `CredentialsProvider` bean that would override the `CredentialsProvider` bean created in `GcpFirestoreAutoConfiguration`. I think it's an easy fix. We may even want to run the `GcpFirestoreEmulatorAutoConfigurationIntegrationTests` as part of the unit tests, to verify the fix.

**Comment by garywg04** [comment]
Hi @meltsufin @cjenkscybercom, when I try to reproduce the issue using the Firestore sample project found that. 
- The IOException were from `GcpContextAutoConfiguration`, which is executed before `GcpFirestoreEmulatorAutoConfiguration` even we did add the `CredentialsProvider` bean likely it will still occur. 

- I can CRUD data on the Emulator even without the override. You may need to ensure the project-id is setup correctly on `application.properties` and the Emulator. make sure using `spring.cloud.gcp.firestore.project-id=emulator` instead of `spring.cloud.gcp.project-id=emulator`

**Comment by meltsufin** [comment]
@garywg04 Thanks for looking into this issue. Have you tried putting `@AutoConfigureBefore({GcpFirestoreAutoConfiguration.class, GcpContextAutoConfiguration.class })` on `GcpFirestoreEmulatorAutoConfiguration` to force the order?

**Comment by garywg04** [comment]
@meltsufin, yes, forcing the order can fix this issues; however other GCP service's may pickup the wrong credentials when the emulator is enabled.

Maybe we can use `spring.cloud.gcp.core.enabled = false` and provide GcpProjectIdProvider and CredentialsProvider from the `GcpFirestoreEmulatorAutoConfiguration` when the bean is missing. In that way user able run test with/without the credentials simply toggle the `spring.cloud.gcp.core.enabled` flag. 

Is that make sense to you? Also would like to check anyone already working in this issues, if not i would love to work on it.

**Comment by meltsufin** [comment]
Great point about impacting other services! You're welcome to work on it. I just realized that we have already solved this problem in Pub/Sub. So, we don't have to reinvent the solution. In Pub/Sub, we made `GcpPubSubAutoConfiguration` aware of the emulator setting. See this snippet:

```java
	public GcpPubSubAutoConfiguration(GcpPubSubProperties gcpPubSubProperties,
			GcpProjectIdProvider gcpProjectIdProvider,
			CredentialsProvider credentialsProvider) throws IOException {
		this.gcpPubSubProperties = gcpPubSubProperties;
		this.finalProjectIdProvider = (gcpPubSubProperties.getProjectId() != null)
				? gcpPubSubProperties::getProjectId
				: gcpProjectIdProvider;

		if (gcpPubSubProperties.getEmulatorHost() == null
				|| "false".equals(gcpPubSubProperties.getEmulatorHost())) {
			this.finalCredentialsProvider = gcpPubSubProperties.getCredentials().hasKey()
					? new DefaultCredentialsProvider(gcpPubSubProperties)
					: credentialsProvider;
		}
		else {
			// Since we cannot create a general NoCredentialsProvider if the emulator host is enabled
			// (because it would also be used for the other components), we have to create one here
			// for this particular case.
			this.finalCredentialsProvider = NoCredentialsProvider.create();
		}
	}
```

A similar approach should work in the Firestore module. WDYT?

**Comment by garywg04** [comment]
Cool, look good to me. Let me try to follow the `GcpPubSubAutoConfiguration` and add the same handling to Firestore emulator.

**Comment by meltsufin** [comment]
Sound good! Looking forward to the PR.

**Comment by garywg04** [comment]
Hi @meltsufin created [PR](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/555) that follow the `GcpPubSubAutoConfiguration` to aware of the emulator setting. Would you mind have a look ?

**Comment by meltsufin** [comment]
@garywg04 Thanks! I submitted my review!

**Comment by chjeningka** [comment]
Thanks for your contributions on this! 
I can confirm at least on my side that the work in the PR resolves the issue here.

**Comment by cjenkscybercom** [comment]
Thank you for your contributions here! I can at least confirm on my side the changes in the PR resolves the problems here.

**Comment by garywg04** [comment]
@meltsufin thanks for the review! pushed new commits with your suggestions.

**Comment by garywg04** [comment]
@cjenkscybercom thanks for the verify and glad to hear the PR did address your problems.
