### ISSUE TITLE
Remove workaround nulling out Pub/Sub error channel on shutdown

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/spring-cloud-gcp#505]
Remove workaround for spring-cloud/spring-cloud-gcp#2615 now that spring-projects/spring-integration#3450 has been long merged.

1) Remove the overridden method [here](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/939df3ed563e672621a60bb7bb77bf3b86a8e773/spring-cloud-gcp-pubsub/src/main/java/com/google/cloud/spring/pubsub/integration/inbound/PubSubInboundChannelAdapter.java#L152-L162)
2) Verify what `requireSubscribers` option introduced in Spring Integration fix is set to; change to `true` if necessary
3) validate that exceptions are not disappearing on application shutdown.

**Comment by garywg04** [comment]
HI, @elefeint. I am new to the community and would like to work on this. 

I checked the default error channel on spring-cloud-gcp-pubsub-stream-binder are using BinderErrorChannel and already set requireSubscribers to true on the constructor.

**Comment by garywg04** [comment]
Created [PR](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/527) here looking for review, please feel free to let me know if anything i missed thanks.

**Comment by elefeint** [comment]
@garywg04 Thank you for the PR!
