### ISSUE TITLE
Support for Spring Native in spring-cloud-gcp-data-firestore

### ISSUE THREAD

**Issue by amirmv2006** [GoogleCloudPlatform/spring-cloud-gcp#507]
Trying to take advantage of recently introduced Spring native, I was applying their changes into my pet project which is using `FirestoreReactiveRepository`. But of course it doesn't work just yet.

**Describe the solution you'd like**
I'd like to compile my project into graalvm native executable without any changes in the code.

**Describe alternatives you've considered**
I already tried to see what is done for Spring Data Repositories and trying to mimic that for firestore repositories. I found out these steps are needed:
* A couple of Type Hints
* a ComponentProcessor finding firestore Documents and adding reflection config for them
* Another ComponentProcessor finding the repository interfaces and add proxy config for them

**Additional context**
Will try to add a sample project here

**Comment by amirmv2006** [comment]
- A couple of Type Hints
    - https://gist.github.com/amirmv2006/e9eb826d3037354be379b62f0f75dfa8 
- a ComponentProcessor finding firestore Documents and adding reflection config for them
    - This needs knowledge of which classes are annotated with @Document. In order to do that, @Indexed should be added to the Document annotation, then consumer modules should use `spring-context-indexer` to index their Docuemtns
    - https://gist.github.com/96b44ad700f022b6a35637a4df6bc6c4
- Another ComponentProcessor finding the repository interfaces and add proxy config for them
    - https://gist.github.com/d22a39add52a861c9b98229437e50438

**Comment by dzou** [comment]
Thanks for reporting this. Yes this can certainly be done; we have Firestore supported through [`google-cloud-graalvm-support`](https://github.com/GoogleCloudPlatform/google-cloud-graalvm-support).

With your Spring native hints + graalvm support, I think we can probably produce a sample relatively easily. I see you have a [commit referenced here](https://github.com/amirmv2006/spring-cloud-gcp/commit/8c0805572eb435a31c7927b1429c05ed2ab53e61) and we will reference the notes you made in the thread.
