### ISSUE TITLE
datastore.host is not used

### ISSUE THREAD

**Issue by PeterUlb** [GoogleCloudPlatform/spring-cloud-gcp#514]
As per documentation, I use the property spring.cloud.gcp.datastore.host
```
The hostname:port of the datastore service or emulator to connect to. Can be used to connect to a manually 
started Datastore Emulator. If the autoconfigured emulator is enabled, this property will be ignored 
and localhost:<emulator_port> will be used.
```

`System.getProperty("spring.cloud.gcp.datastore.host") => http://localhost:49343`

Now I'm using the Autowired Storage and call `var blob = storage.get(myConfig.getBucket(), imageKey);`

This fails with the following exception:

```
com.google.cloud.storage.StorageException: The project to be billed is associated with an absent billing account.

com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
GET https://storage.googleapis.com/storage/v1/b/mock-bucket/o/images%2FBVXErLFEgv?projection=full
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "location" : "Authorization",
    "locationType" : "header",
    "message" : "The project to be billed is associated with an absent billing account.",
    "reason" : "accountDisabled"
  } ],
  "message" : "The project to be billed is associated with an absent billing account."
}
```

I'm now wondering why `https://storage.googleapis.com/` is called, since spring.cloud.gcp.datastore.host is set to a different url.

**Comment by meltsufin** [comment]
Are you trying to use Storage or Datastore? I know the names could be confusing, but those are two very different products. Storage is for storing files and Datastore is a NoSQL database.

**Comment by PeterUlb** [comment]
> 
> 
> Are you trying to use Storage or Datastore? I know the names could be confusing, but those are two very different products. Storage is for storing files and Datastore is a NoSQL database.

Oh well, I expected there's a configuration option for the endpoint and basically skimmed through the properties for anything host/endpoint related. You are totally right. There's simply no endpoint override for Storage.

I'll write my own Bean in the test context with endpoint config then. Thanks for the pointer!
