### ISSUE TITLE
Could not find an appender named [STACKDRIVER]

### ISSUE THREAD

**Issue by ShaimaaSabry** [GoogleCloudPlatform/spring-cloud-gcp#517]
my dependency:
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-logging</artifactId>
    <version>1.2.1.RELEASE</version>
</dependency>
```

my logback-spring.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <!-- With 1.2 release, replace with: include resource="org/springframework/cloud/gcp/logging/logback-appender.xml" /-->
    <include resource="org/springframework/cloud/gcp/logging/logback-appender.xml" />
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />

    <root level="INFO">
        <!-- If running in GCP, remove the CONSOLE appender otherwise logs will be duplicated. -->
        <!--appender-ref ref="CONSOLE"/-->
        <appender-ref ref="STACKDRIVER" />
    </root>
</configuration>
```

The error:
```
 Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [STACKDRIVER]
```

**Comment by suztomo** [comment]
Let me find the appender configuration location.

If you read some documentation for writing configuration, can you share the URL?

**Comment by suztomo** [comment]
@ShaimaaSabry  Would you share the result of `mvn dependency:tree -Dincludes=org.springframework.cloud:spring-cloud-gcp-logging`? I suspect you have an unexpected spring-cloud-gcp-logging version.

spring-cloud-gcp-logging 1.2.1.RELEASE has the STACKDRIVER appender in org/springframework/cloud/gcp/logging/logback-appender.xml:

```
suztomo-macbookpro44% unzip ~/Downloads/spring-cloud-gcp-logging-1.2.1.RELEASE.jar 
Archive:  /Users/suztomo/Downloads/spring-cloud-gcp-logging-1.2.1.RELEASE.jar
  inflating: META-INF/MANIFEST.MF    
   creating: org/
   creating: org/springframework/
   creating: org/springframework/cloud/
   creating: org/springframework/cloud/gcp/
   creating: org/springframework/cloud/gcp/logging/
   creating: org/springframework/cloud/gcp/logging/extractors/
   creating: META-INF/maven/
   creating: META-INF/maven/org.springframework.cloud/
   creating: META-INF/maven/org.springframework.cloud/spring-cloud-gcp-logging/
  inflating: org/springframework/cloud/gcp/logging/logback-json-appender.xml  
  inflating: org/springframework/cloud/gcp/logging/LoggingAppender.class  
  inflating: org/springframework/cloud/gcp/logging/extractors/TraceIdExtractor.class  
  inflating: org/springframework/cloud/gcp/logging/TraceIdLoggingWebMvcInterceptor.class  
  inflating: META-INF/maven/org.springframework.cloud/spring-cloud-gcp-logging/pom.xml  
  inflating: org/springframework/cloud/gcp/logging/StackdriverTraceConstants.class  
  inflating: org/springframework/cloud/gcp/logging/TraceIdLoggingEnhancer.class  
  inflating: org/springframework/cloud/gcp/logging/LoggingWebMvcConfigurer.class  
  inflating: META-INF/maven/org.springframework.cloud/spring-cloud-gcp-logging/pom.properties  
  inflating: org/springframework/cloud/gcp/logging/StackdriverErrorReportingServiceContext.class  
  inflating: org/springframework/cloud/gcp/logging/extractors/XCloudTraceIdExtractor.class  
  inflating: org/springframework/cloud/gcp/logging/StackdriverJsonLayout.class  
  inflating: org/springframework/cloud/gcp/logging/logback-appender.xml  
suztomo-macbookpro44% cat org/springframework/cloud/gcp/logging/logback-appender.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
Stackdriver appender logback configuration provided for import.
-->

<included>
  <property name="STACKDRIVER_LOG_NAME" value="${STACKDRIVER_LOG_NAME:-spring.log}"/>
  <property name="STACKDRIVER_LOG_FLUSH_LEVEL" value="${STACKDRIVER_LOG_FLUSH_LEVEL:-WARN}"/>

  <appender name="STACKDRIVER" class="org.springframework.cloud.gcp.logging.LoggingAppender">
    <log>${STACKDRIVER_LOG_NAME}</log> <!-- Optional : default java.log -->
    <enhancer>org.springframework.cloud.gcp.logging.TraceIdLoggingEnhancer</enhancer>
    <flushLevel>${STACKDRIVER_LOG_FLUSH_LEVEL}</flushLevel> <!-- Optional : default ERROR -->
  </appender>
</included>
```

Also when I use logback, I often use `<configuration debug="true"> ` to confirm the configurations are applied as expected. See http://logback.qos.ch/manual/configuration.html#dumpingStatusData.

**Comment by ShaimaaSabry** [comment]
@suztomo 
The results of running mvn dependency:tree:
```
[INFO] com.hawaya.services:payment-service:jar:1.0.0
[INFO] \- org.springframework.cloud:spring-cloud-gcp-starter-logging:jar:1.2.1.RELEASE:compile
[INFO]    \- org.springframework.cloud:spring-cloud-gcp-logging:jar:1.2.1.RELEASE:compile
```

**Comment by suztomo** [comment]
With `<configuration debug="true">`, does your process show anything suspicious when it starts up?

**Comment by elefeint** [comment]
@ShaimaaSabry Definitely try `<configuration debug="true">` shows, like @suztomo suggested -- it will say which appender files it finds.

What might also be helpful is comparing your project to this minimal reproducer, which finds the custom appender configuration correctly: https://github.com/elefeint/examples/tree/master/stackdriver-logging-121

**Comment by ShaimaaSabry** [comment]
I am getting these messages after adding <configuration debug="true">:
```
23:17:23,538 |-WARN in ch.qos.logback.core.joran.action.IncludeAction - Could not find resource corresponding to [org/springframework/cloud/gcp/logging/logback-appender.xml]
23:17:23,539 |-INFO in ch.qos.logback.core.joran.util.ConfigurationWatchListUtil@b8d749e - Adding [jar:file:/Users/shimo/.m2/repository/org/springframework/boot/spring-boot/2.5.2/spring-boot-2.5.2.jar!/org/springframework/boot/logging/logback/defaults.xml] to configuration watch list.
23:17:23,539 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@7a95d1d2 - URL [jar:file:/Users/shimo/.m2/repository/org/springframework/boot/spring-boot/2.5.2/spring-boot-2.5.2.jar!/org/springframework/boot/logging/logback/defaults.xml] is not of type file
```

**Comment by suztomo** [comment]
The error seems similar to https://jira.qos.ch/browse/LOGBACK-470. Would you try upgrading the logback to the latest version (The latest stable logback is version 1.2.3)?

**Comment by ShaimaaSabry** [comment]
The error is fixed. Thank you. However, now after I deploy to GCP, the logs are not grouped together by request as I expected. Can you please advice?

**Comment by elefeint** [comment]
@ShaimaaSabry How did you fix the issue?

For grouping, you may find [this explanation](https://github.com/spring-cloud/spring-cloud-gcp/issues/2573#issuecomment-729972081) useful.

**Comment by ShaimaaSabry** [comment]
@elefeint I think this exclusion fixed it:
```        
<dependency>
      <groupId>com.google.cloud.sql</groupId>
      <artifactId>mysql-socket-factory</artifactId>
      <version>1.0.2</version>
      <exclusions>
          <exclusion>
              <groupId>com.google.api-client</groupId>
              <artifactId>google-api-client</artifactId>
          </exclusion>
      </exclusions>
  </dependency>
```

**Comment by elefeint** [comment]
For grouping log entries, the previous issue is for a more complicated scenario. To go back to the basics: in a deployed environment, request grouping will work out of the box. If you are testing it locally, make sure to invoke your endpoint with a `x-cloud-trace-context` header, which will then be used to group log entries in that request. For example: 

````
curl --header "x-cloud-trace-context: ABCD1234" http://localhost:8080/
````

**Comment by elefeint** [comment]
I've tested `com.google.cloud.sql:mysql-socket-factory:1.0.2` in combination with `org.springframework.cloud:spring-cloud-gcp-starter-logging:1.2.1.RELEASE` and could not reproduce the issue with appender configuration missing from classpath. There must be something else that is contributing to the issue.

However, `com.google.cloud.sql:mysql-socket-factory:1.0.2` is a 5 year old version of the dependency, so you may want to upgrade it to a newer version in any case.

**Comment by ShaimaaSabry** [comment]
@elefeint Thank you. Is there a way to nest the logs of each request under the parent request log without clicking the icon, similar to how GCP arranges the logs when you are using servlets. Similar to the below screenshot:
<img width="1680" alt="Screen Shot 2021-07-15 at 10 57 16 PM" src="https://user-images.githubusercontent.com/32084062/125857473-13a5067b-3b9a-45b6-b6d3-20f1f5b0333f.png">

**Comment by elefeint** [comment]
Please try not to duplicate the same question across multiple issues. This thread is in #518.
