### ISSUE TITLE
Logs Not Grouped By Request On GCP

### ISSUE THREAD

**Issue by ShaimaaSabry** [GoogleCloudPlatform/spring-cloud-gcp#518]
I am trying to group logs by request on GCP.

My logback-spring.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="true">
    <!-- With 1.2 release, replace with: include resource="org/springframework/cloud/gcp/logging/logback-appender.xml" /-->
    <include resource="org/springframework/cloud/gcp/logging/logback-appender.xml" />
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <include resource="org/springframework/boot/logging/logback/console-appender.xml" />
    <include resource="org/springframework/cloud/gcp/logging/logback-json-appender.xml"/>

    <root level="INFO">
        <!-- If running in GCP, remove the CONSOLE appender otherwise logs will be duplicated. -->
        <appender-ref ref="CONSOLE_JSON"/>
    </root>
</configuration>
```

I am not using any spring filters but the logs are still not grouped by request.

<img width="1410" alt="Screen Shot 2021-07-03 at 12 40 17 AM" src="https://user-images.githubusercontent.com/32084062/124334455-62db0e80-db97-11eb-84c5-36efd8fecf41.png">

**Comment by elefeint** [comment]
Click this icon to see logs grouped by request: 
![image](https://user-images.githubusercontent.com/41136058/124336545-6d33e300-db6c-11eb-997e-0315eaefbaf3.png)

**Comment by ShaimaaSabry** [comment]
Worked. Thank you.

**Comment by ShaimaaSabry** [comment]
@elefeint Is there a way to nest the logs of each request under the parent request log without clicking the icon, similar to how GCP arranges the logs when you are using servlets.
<img width="1680" alt="Screen Shot 2021-07-15 at 10 57 16 PM" src="https://user-images.githubusercontent.com/32084062/125856644-aaac3a5f-6fdf-4656-a710-9a6f1c13aaa1.png">

**Comment by elefeint** [comment]
What logging library were you using with servlets? 

I suspect that the difference in presentation is between setting `operation` vs `trace` fields in the [LogEntry](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry) object.

**Comment by ShaimaaSabry** [comment]
@elefeint java util logging. I tried using java util logging with spring boot but it didn't work.
