### ISSUE TITLE
Spring Data Cloud Spanner @Column(spannerCommitTimestamp = true) Behaves Unexpectedly

### ISSUE THREAD

**Issue by MusikPolice** [GoogleCloudPlatform/spring-cloud-gcp#526]
**Describe the bug**
Our project is using `spring-cloud-gcp-starter-data-spanner:2.0.0`. We decided to try using Spanner Commit Timestamps as a sort of audit trail, hoping to track when each object that we persist was created with an immutable timestamp that is set at object creation time.

Unfortunately, we've found that Spring Data Cloud Spanner's implementation of this feature does not treat fields that are annotated with `@Column(spannerCommitTimestamp = true)` as immutable.

**Sample**
We can define a simple object that will be stored in Spanner:
```
@Table(name = "Foo")
data class Foo (

    @PrimaryKey
    val id: String,

    val someValue: String,

    // the value of this column will be overwritten by Spanner whenever an INSERT operation is committed
    @Column(spannerCommitTimestamp = true)
    val createdTimestamp: Timestamp? = null
)
```

as well as a repository to go with the object:
```
@Repository
interface FooRepository : SpannerRepository<Foo, String>
```

and the corresponding database table that will contain instances of this object that are persisted to Spanner:
```
CREATE TABLE Foo (
  id STRING(255) NOT NULL,
  someValue STRING(32) NOT NULL,
  createdTimestamp TIMESTAMP NOT NULL OPTIONS (
    allow_commit_timestamp = true
  ),
) PRIMARY KEY(id);
```

Now, we can use these objects to write a unit test that demonstrates two issues with the Spanner Commit Timestamp implementation:
```
@Test
fun testCreatedTimestamp() {
    // create a simple object
    val expected = Foo(UUID.randomUUID().toString(), UUID.randomUUID().toString())

    // Issue 1: createdTimestamp is null because fooRepository.save(...) is returning the provided object, as opposed to the committed object
    val saved = fooRepository.save(expected)
    assertThat(saved.createdTimestamp).isNotNull    // this assert will fail

    // if we fetch the object from the database, we'll find that the createdTimestamp was populated as expected
    val actual = fooRepository.findById(expected.id).get()
    assertThat(actual.createdTimestamp).isNotNull

    // next, we'll make a meaningless change to force an update to the object
    fooRepository.save(actual.copy(someValue = UUID.randomUUID().toString()))

    // Issue 2: createdTimestamp should be idempotent even if other fields are updated
    val updated = fooRepository.findById(expected.id).get()
    assertThat(updated.createdTimestamp).isEqualTo(actual.createdTimestamp)    // this assert will fail
}
```

As demonstrated above, there are two issues with this implementation, one minor, and one decidedly not so:

1. `SpannerRepository::save(...)` returns the object specified in the first parameter, as opposed to the object that was actually persisted to the database
    * In our case, this means that the value of the returned object's `createdTimestamp` attribute is `null`, because that attribute is populated by Spanner when the transaction that contains the `INSERT` operation is committed
    * Ideally, this method would query the database for the newly inserted object and return the result, so as to reflect any changes that were made to the object by the database, and in this case capturing the correct value of `createdTimestamp`
    * This issue is related to existing issue https://github.com/spring-cloud/spring-cloud-gcp/issues/1622
    * In my mind, this is a minor issue - we can work around it by overriding [the `save(...)` method in `SimpleSpannerRepository.java`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/support/SimpleSpannerRepository.java#L85) if necessary

2. The value of `createdTimestamp` changes when an existing object is updated. 
    * This is a big problem, because it implies that `createdTimestamp` is not immutable, and is of no use as an audit mechanism
    * I would expect the value of this field to only be updated by a `save(...)` operation if it has not yet been set by a previous operation

**Comment by elefeint** [comment]
@MusikPolice You are correct that part 1 is an unimplemented enhancement requested in spring-cloud/spring-cloud-gcp#1622

However, part 2 works as intended and is not unique to the Spring Data implementation. The disconnect is that your requirement is for " an immutable timestamp that is set at object creation time.", while Cloud Spanner's commit timestamp is "a commit timestamp for each insert and update operation" ([docs](https://cloud.google.com/spanner/docs/commit-timestamp)). It is not meant for auditing, but instead for replaying events with consistent results.

A workaround for your requirement would be to programmatically set a timestamp only at object creation time.

**Comment by MusikPolice** [comment]
Thanks for explaining my misunderstanding @elefeint. Since the issue that can be fixed is already covered by another ticket, I'll close this one for the time being.
