### ISSUE TITLE
How can I make a reference between two different entities?

### ISSUE THREAD

**Issue by aukhatov** [GoogleCloudPlatform/spring-cloud-gcp#541]
I have a two entities: EntityA, EntityB (like a table in SQL).
And I would like to make a reference between them, like a foreign key in SQL.
`EntityA {id, title}`
`EntityB {id, description, entityA_id}`

How can I make that?

**Comment by meltsufin** [comment]
You probably looking for this: https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.3/reference/html/index.html#ancestor-descendant-relationships.
