### ISSUE TITLE
Insert One Row Into BigQuery

### ISSUE THREAD

**Issue by ShaimaaSabry** [GoogleCloudPlatform/spring-cloud-gcp#544]
I am following the big query sample trying to insert one row into a table in big query. 
```
ListenableFuture<Job> loadJob = this.bigQueryFileGateway.writeToBigQueryTable("user_id,created_time,action\nx,2021-07-11 06:40:00 UTC,x".getBytes(), "scammer_table");
loadJob.get();
```
I am getting an error that my data does not match the table schema:
```
java.util.concurrent.ExecutionException: com.google.cloud.spring.bigquery.core.BigQueryException: Provided Schema does not match Table harmonica-dev:Analytics.scammer_table. Field user_id is missing in new schema
```
What's wrong with my string format? I copied the format from the test in the sample.

**Comment by meltsufin** [comment]
Can you check the schema of your `scammer_table`? Does it have a field called `user_id`?

**Comment by meltsufin** [comment]
Please re-open if you're still having an issue with this.
