### ISSUE TITLE
GqlDatastoreQuery works differently depending on whether the entity has a single-string constructor

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/spring-cloud-gcp#547]
`GqlDatastoreQuery` [cycles through available conversions](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/c8faf7ad1ff8a6018785dac155f26e8651c93270/spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/query/GqlDatastoreQuery.java#L237-L240) to determine whether an object is "not an entity" if a conversion is found.

However, Spring provides `FallbackObjectToStringConverter` that activates if the [source object has a single-String constructor](https://github.com/spring-projects/spring-framework/blob/d034a1f26d0ea3782f53b8ff7a2a0cea7c825b71/spring-core/src/main/java/org/springframework/core/convert/support/FallbackObjectToStringConverter.java#L31-L33).

This leads to different behavior depending on whether the entity has a single-String constructor (there are other conditions in `FallbackObjectToStringConverter` that will trigger this, but this is the most obvious one).

To reproduce, add a constructor like the below to `com.google.cloud.spring.data.datastore.it.TestEntity`, and run `DatastoreIntegrationTests.testWithCustomQuery()`

```
public TestEntity(String triggerConversionSideEffect) {}
```

Observe this error:
```
com.google.cloud.spring.data.datastore.core.mapping.DatastoreDataException: The query method returns non-entity types, but the query result has more than one column. Use a Projection entity type instead.
```

This happens because `isNonEntityReturnType()` returns true, causing [this conditional](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/c8faf7ad1ff8a6018785dac155f26e8651c93270/spring-cloud-gcp-data-datastore/src/main/java/com/google/cloud/spring/data/datastore/repository/query/GqlDatastoreQuery.java#L144-L146) in `GqlDatastoreQuery.execute()` falls into the wrong (`queryIterable()`) path.

As a matter of personal taste, I would also like the negative in `isNonEntityReturnType` to go away in favor of `isEntityReturnType`. The negative is hard to reason about, especially in the ternary context.

I would solve this is to make the new `isEntityReturnType` simply check whether `@Entity` annotation is present, instead of doing an exhaustive check on conversions to decide if the type is something other than entity.

**Comment by elefeint** [comment]
cc: @zhumin8 -- the rabbit hole was totally worth it, since it's a bug in our code.

**Comment by meltsufin** [comment]
AFAIK JPA requires every entity to have a no-arg constructor. I didn't know that adding a single String arg constructor is an option and there is special behavior for it in Spring Data.

**Comment by elefeint** [comment]
That test entity already has a no-arg constructor; the new constructor is in addition to, not instead of:
```
	public TestEntity() {
	}

	public TestEntity(String triggerConversionSideEffect) {
	}
```

The issue is that we are using conversion service to determine whether something is an entity.

Spring data allows non-no-arg as well as multiple constructors: https://docs.spring.io/spring-data/commons/docs/current/reference/html/#mapping.object-creation

**Comment by blakeli0** [comment]
Closing as not planned
