### ISSUE TITLE
Add cloudsql proxy health indicator

### ISSUE THREAD

**Issue by eddumelendez** [GoogleCloudPlatform/spring-cloud-gcp#557]
**Is your feature request related to a problem? Please describe.**
-

**Describe the solution you'd like**
it would be great to add a health indicator which can be enabled or disabled via configuration property when cloudsql proxy is used.

**Describe alternatives you've considered**
Create a custom health indicator for cloudsql proxy.

**Additional context**
See [this](https://github.com/GoogleCloudPlatform/cloudsql-proxy/pull/859)

**Comment by elefeint** [comment]
Thanks, @eddumelendez ! 
We don't currently have additional health indicators on the roadmap, but I would like to leave the issue open, so people can upvote it.

**Comment by elefeint** [comment]
Closing due to lack of community interest.
