### ISSUE TITLE
feat: support setting timeout in SpannerTemplate

### ISSUE THREAD

**Issue by pravsingh** [GoogleCloudPlatform/spring-cloud-gcp#570]
**Is your feature request related to a problem? Please describe.**
would like to set deadline/timeout when calling APIs in SpannerTemplate.
ref: https://github.com/googleapis/java-spanner/pull/379/files

**Describe the solution you'd like**
introduce SpannerOptions accepting timeout/deadline.

**Describe alternatives you've considered**
I have tried setting up a context key as mentioned in https://github.com/googleapis/java-spanner/pull/379/files however that sounds like a mixing of two different frameworks.

**Additional context**
add feature mentioned at https://github.com/googleapis/java-spanner/pull/379/files

**Comment by elefeint** [comment]
Starting with version 2.0.3, you can customize the `SpannerOptions` object by providing a `com.google.cloud.spring.autoconfigure.spanner.SpannerOptionsCustomizer` bean. It can be a lambda that takes a `SpannerOptions.Builder` and modifies it as necessary.

Let us know if this works for you!
