### ISSUE TITLE
Split spring-cloud-gcp-data-spanner-sample into two separate sample apps

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/spring-cloud-gcp#588]
Right now, the Spanner sample contains two completely distinct flows, with the following message printed if you try to just run the app:
`To run the Spanner example, please specify  -Dspring-boot.run.arguments=--spanner_repository to run the Spanner repository example or -Dspring-boot.run.arguments=--spanner_template to run the Spanner template example`

Sample applications should be simple and demonstrate one layer of integration. We have separate samples for template and higher level abstractions for other samples (pubsub, firestore).

**Comment by elefeint** [comment]
@ddixit14 This is the sample we've looked at yesterday. Try separating it into two separate sample applications, one for `SpannerTemplate`, and the other for the Spring Data repositories.

**Comment by ddixit14** [comment]
Closing this issue.
