### ISSUE TITLE
Find why TraceSampleApplicationIntegrationTests flakes consistently

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/spring-cloud-gcp#597]
After #548 was merged, `TraceSampleApplicationIntegrationTests` started flaking. The scheduled daily test run often fails on the weekend -- I usually re-run on Monday, and the same run succeeds.

Some diagnostic information is added in #587.

If the test succeeds, it succeeds quickly. Otherwise it keeps pinging the backend trying to find the 25th span. The span that is missing is one of the final "send" spans on publish. In related news, the successful runs have both subscriber threads outputting "Overriding default instance of MessageHandlerMethodFactory with provided one.", while the failed runs only have one of the threads printing this out.

Bad run:
```
13:00:52.234 [http-nio-auto-1-exec-1] INFO  com.example.WorkService - starting busy work
13:00:52.901 [http-nio-auto-1-exec-2] INFO  com.example.ExampleController - meeting took 658ms
13:00:53.614 [http-nio-auto-1-exec-3] INFO  com.example.ExampleController - meeting took 650ms
13:00:54.224 [http-nio-auto-1-exec-4] INFO  com.example.ExampleController - meeting took 589ms
13:00:54.229 [http-nio-auto-1-exec-1] INFO  com.example.WorkService - finished busy work
13:00:55.522 [gcp-pubsub-subscriber2] INFO  o.s.i.h.s.MessagingMethodInvokerHelper - Overriding default instance of MessageHandlerMethodFactory with provided one.
13:00:55.527 [gcp-pubsub-subscriber1] INFO  o.s.i.h.s.MessagingMethodInvokerHelper - Overriding default instance of MessageHandlerMethodFactory with provided one.
13:00:55.570 [gcp-pubsub-subscriber1] INFO  com.example.Application - Message arrived! Payload: All work is done via PubSubTemplate.
13:00:55.574 [gcp-pubsub-subscriber2] INFO  com.example.Application - Message arrived! Payload: All work is done via SI.
```

Good run:

```
13:09:18.827 [http-nio-auto-1-exec-1] INFO  com.example.WorkService - starting busy work
13:09:19.408 [http-nio-auto-1-exec-2] INFO  com.example.ExampleController - meeting took 571ms
13:09:19.998 [http-nio-auto-1-exec-3] INFO  com.example.ExampleController - meeting took 528ms
13:09:20.518 [http-nio-auto-1-exec-4] INFO  com.example.ExampleController - meeting took 501ms
13:09:20.521 [http-nio-auto-1-exec-1] INFO  com.example.WorkService - finished busy work
13:09:20.699 [gcp-pubsub-subscriber1] INFO  o.s.i.h.s.MessagingMethodInvokerHelper - Overriding default instance of MessageHandlerMethodFactory with provided one.
13:09:20.728 [gcp-pubsub-subscriber1] INFO  com.example.Application - Message arrived! Payload: All work is done via SI.
13:09:20.731 [gcp-pubsub-subscriber2] INFO  com.example.Application - Message arrived! Payload: All work is done via PubSubTemplate.
```

**Comment by elefeint** [comment]
@meltsufin if you have time at some point.

**Comment by meltsufin** [comment]
So, the bad runs essentially never succeed regardless of the wait? "Overriding default instance of MessageHandlerMethodFactory with provided one" could be a good lead indeed. I'll try to look at this later in the week.

**Comment by elefeint** [comment]
Right -- they sit there at 24 spans found for however long you give them.

**Comment by elefeint** [comment]
The missing span stays missing. Sent you links and screenshots.

**Comment by meltsufin** [comment]
This span is supposed to be created by the built-in Spring Integration Sleuth instrumentation.
Specifically in `TracingChannelInterceptor.preSend()`. Since this span is placed into a thread-local and then used as a parent for the `handle` span, I suspect there might be a race condition there, where two `handle` spans are assigned the same `send` parent.

I'm thinking of just recommending disabling `TraceSpringIntegrationAutoConfiguration` via the `spring.sleuth.messaging.enabled=false` property, since it doesn't add much utility on top of our Pub/Sub instrumentation.

**Comment by elefeint** [comment]
Sounds good.
