### ISSUE TITLE
Add documentation detailing support for subscription-specific properties

### ISSUE THREAD

**Issue by mpeddada1** [GoogleCloudPlatform/spring-cloud-gcp#602]
Follow-up to  [#562(comment)](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/562#discussion_r700514823) 

As a result of the addition of subscription-specific properties, a custom bean take precedence over auto-configured properties. If one wishes to use subscription-specific properties then they will need to avoid using a custom bean. Additionally, if a subscription-specific property is not specified then the global (if specified) or default configuration will be taken into account as a fallback.

This change needs to be documented.

**Comment by elefeint** [comment]
This is not a release blocker in technical terms, but we should document before release.

**Comment by elefeint** [comment]
Fixed in #728
