### ISSUE TITLE
Extractors for Traceparent / Tracestate From Request

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/spring-cloud-gcp#627]
**Is your feature request related to a problem? Please describe.**

Similar to:

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-logging/src/main/java/com/google/cloud/spring/logging/extractors/XCloudTraceIdExtractor.java

I'm requesting an extractor for the 'traceparent' and `tracestate` field. See: https://www.w3.org/TR/trace-context/

**Describe the solution you'd like**

2 extractors for HTTP request headers `traceparent` and `tracestate`.

**Comment by meltsufin** [comment]
Supporting `traceparent` seems to make sense. I'm not sure what we would do with `tracestate` though because `TraceIdExtractor` is just for the trace id currently.

**Comment by grant** [comment]
Just `traceparent` would work forme.

**Comment by elefeint** [comment]
@grant Does https://github.com/openzipkin-contrib/brave-propagation-w3c/tree/master/tracecontext meet this requirement? 

Spring Cloud GCP's tracing support modifies built-in Spring Cloud Sleuth / Brave processing with Google Cloud-specific bits, but the W3C headers are standard. Do you know of anything Google Cloud specific that would require customization?

**Comment by grant** [comment]
@elefeint I no longer work at the company, deferring to @matthewrobertson.

But that seems to meet the req, yes.
