### ISSUE TITLE
Transaction refresh option for idle transaction of Spanner

### ISSUE THREAD

**Issue by toyopilgrim** [GoogleCloudPlatform/spring-cloud-gcp#628]
**Is your feature request related to a problem? Please describe.**

Related to the issue previously raised on https://github.com/spring-cloud/spring-cloud-gcp/issues/2453, support of idle transaction handling is in hold after the conclusion of no plan to support the feature in google client library side. 

I wonder if this could still be supported in ORM side. But no discussion was made after that in the old repository issue.

As the official doc says, the workaround to refresh transaction is suggested in a particular scenario where it requires avoiding commit failure by idle transaction.

>Idle Transactions: A transaction is considered idle if it has no outstanding reads or SQL queries and has not started a read or SQL query within the last 10 seconds. Idle transactions can be aborted by Cloud Spanner so that they don't hold on to locks indefinitely. If an idle transaction is aborted, the commit will fail with error ABORTED.
>If this behavior is undesirable, periodically executing a simple SQL query in the transaction (for example, SELECT 1) prevents the transaction from becoming idle.

I encountered a situation that an external API call took more than 10s exceptionally to respond while RW transaction was opened.

**Describe the solution you'd like**

Enable refresh transaction option with timeout to avoid idle transaction abortion for a certain period

**Describe alternatives you've considered**
Make a conclusion that this feature should be up to each developer not Spring because this is probably considered not really highly recommended situation to make it happen.

**Additional context**
Here's a case scenario.

--begin trx 

* Read & update DB
* Call external API (update external persistence) - took over 10s but successful
* Got rolled back

--end trx

```
org.springframework.transaction.UnexpectedRollbackException: Transaction Got Rolled Back; nested exception is com.google.cloud.spanner.AbortedException: ABORTED: com.google.api.gax.rpc.AbortedException: io.grpc.StatusRuntimeException: ABORTED: Transaction was aborted. Idle for over 10 seconds.
```

**Comment by elefeint** [comment]
@toyopilgrim, the Spanner team consensus was that building auto-extending transactions would cause problems more frequently than it would solve them. Spring Cloud GCP's goal is to integrate the existing GCP client libraries with the Spring ecosystem, but not to change their behavior. As such, we won't consider adding this feature.

So I am afraid that we are taking the route of your Alternatives Considered section. In your own application, you may use the same Spanner transaction to send scheduled pings in a different thread. From the architectural standpoint, distributed transactions between microservices  will always be a bottleneck and any restructuring that avoids this situation is worth doing.

**Comment by toyopilgrim** [comment]
It makes sense. I’ve wanted to clarify if it could be supported or not in Spring Cloud because  I found no finalized discussion related to this topic in the pj. So thx. 

In my case, in order to avoid such situation, I am refactoring it to make non-blocking API call asynchronously and have eventual consistency in the persistences between the microserivice and the external service. This is pretty close to what you suggest. 

No objection to your conclusion.
