### ISSUE TITLE
Health Indicator for Cloud Spanner

### ISSUE THREAD

**Issue by suztomo** [GoogleCloudPlatform/spring-cloud-gcp#640]
Copied from https://github.com/spring-cloud/spring-cloud-gcp/issues/2680 (old repository) by @ikeyat

---

I think Spring Boot's DataSourceHealthIndicator does not work for spring-cloud-gcp-data-spanner because it does not use JDBC DataSource.
A custom health indicator Such as SpannerHealthIndicator and its auto configures should be added into spring-cloud-gcp-data-spanner to avoid boilerplate.

https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health.writing-custom-health-indicators

**Comment by suztomo** [comment]
My memo:

DatastoreHealthIndicator and PubSubHealthIndicator exist

**Comment by elefeint** [comment]
@ikeyat If you already have an implementation in mind, we are happy to accept a pull request. One thing to keep in mind is that Kubernetes restarts unhealthy pods, so we need to make sure the indicators don't bubble up to the [`liveness` probe](https://docs.spring.io/spring-boot/docs/2.5.5/reference/html/actuator.html#actuator.endpoints.kubernetes-probes.external-state)

**Comment by ikeyat** [comment]
@elefeint 
Actually not yet. But I'd like to do soon.

**Comment by elefeint** [comment]
Thank you!
