### ISSUE TITLE
Security Firebase: NoSuchMethodError: 'java.util.Map com.nimbusds.jose.Header.toJSONObject()'

### ISSUE THREAD

**Issue by zhumin8** [GoogleCloudPlatform/spring-cloud-gcp#657]
**Describe the bug**
Upgrading to Spring Boot 2.6(#599), running `FirebaseJwtTokenDecoder.decode` leads to `NoSuchMethodError: 'java.util.Map com.nimbusds.jose.Header.toJSONObject()'`

This breaks a couple of test in `FirebaseJwtTokenDecoderTests.java`
Error trace:
```
java.lang.AssertionError: 
Expecting actual throwable to be an instance of:
  org.springframework.security.oauth2.jwt.JwtException
but was:
  java.lang.NoSuchMethodError: 'java.util.Map com.nimbusds.jose.Header.toJSONObject()'
	at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.createJwt(NimbusJwtDecoder.java:155)
	at org.springframework.security.oauth2.jwt.NimbusJwtDecoder.decode(NimbusJwtDecoder.java:137)
	at com.google.cloud.spring.security.firebase.FirebaseJwtTokenDecoder.decode(FirebaseJwtTokenDecoder.java:89)
```
Suspect to be dependency version incompatibility related to Nimbus. Needs further investigation.

**Comment by elefeint** [comment]
Does spring-cloud-gcp-security-iap have a similar issue? They both use the same spring-security infrastructure.

**Comment by zhumin8** [comment]
This was original tested against the `Spring Boot 2.6.0 Milestone 2` release. Now that we are on `spring-boot:2.6.0-RC1` in 3.x branch, this error is gone.
