### ISSUE TITLE
Storage emulator support

### ISSUE THREAD

**Issue by mateuszsokolski** [GoogleCloudPlatform/spring-cloud-gcp#674]
Firestore has property `spring.cloud.gcp.firestore.emulator.enabled`. Is there a way to configure spring app, that could let it know, to not use `GOOGLE_APPLICATION_CREDENTIALS` path variable, but connect to storage emulator on localhost?

**Comment by ddixit14** [comment]
Hi @mateuszsokolski, currently the storage emulator (which is a part of the firebase emulator suite) is not supported by non-firebase storage clients. 
For further reference, please have a look at https://github.com/googleapis/java-storage/issues/875, https://github.com/googleapis/nodejs-storage/issues/1473 and https://github.com/firebase/firebase-tools/issues/3508
