### ISSUE TITLE
NullPointerException in StackdriverJsonLayout

### ISSUE THREAD

**Issue by mirehasfun** [GoogleCloudPlatform/spring-cloud-gcp#687]
**Describe the bug**
Hi, I think i stumbled over a NullPointerException happening in StackdriverJsonLayout's `formatMessage` method, when the logged message passed is `null`. 

This happens in my case, when my catch-all exception handler processes an instance of a `NullPointerException`. The logging code looks like this: 
```
// This leads to another `NullPointerException` in StackdriverJsonLayout and results in swallowed logs for my application.
LOGGER.error(e.getMessage(), e);
```

A solution would be, to initialize the StringBuilder without a constructor argument and then `append` the formattedMessage: 

```
// instead
StringBuilder message = new StringBuilder(event.getFormattedMessage());

// do this
StringBuilder message = new StringBuilder();
message.append(event.getFormattedMessage());
```

Note:  This happens only when using StackdriverJsonLayout / CONSOLE_JSON appender provided in logback-json-appender.xml. When using a regular console appender, the same code works. 

**Sample**
The issue can easily be reproduced with the following code: 

```
@Test
public void logtest() {
    //Using slf4j
    Logger log = LoggerFactory.getLogger(getClass());

    try {
        throw new NullPointerException();
    } catch (Exception e) {
        log.error(e.getMessage(), e);
    }
}
```

**Comment by suztomo** [comment]
Thank you for reporting the issue. Would you share the stacktrace you observed? It would tell which line of the code is having the problem.

Further, it seems that you know where/how to fix it. Would you be willing to create a pull request?

**Comment by mirehasfun** [comment]
The problem is, the stacktrace gets swallowed, so I cannot provide one. However, I'll gladly provide a pull request.
