### ISSUE TITLE
Migrate tests from JUnit4 to JUnit5

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/spring-cloud-gcp#688]
JUnit5 adoption was slow at first, but at this point there is no reason not to upgrade. R2DBC repo is already on JUnit5.

- [ ] Run all current unit tests (mvn test) and note how many were ran vs skipped.
- [ ] Replace test dependency on junit with one on JUnit5 (Jupiter)
- [ ] If you run the tests at this point, 0 tests will be run! Introduce backwards compatibility for JUnit4 tests (hint: pom.xml plugin configuration -- vintage engine)
- [ ] Run all unit tests, validate that exactly as many tests run now as did in the first step.
- [ ] Pick a test, any test. Migrate to JUnit5 (import packages will change; `@BeforeClass` becomes `@BeforeAll` etc. All junit tests can then become package private. Repeat until all tests are JUnit5.

Reference:
https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4

**Comment by ddixit14** [comment]
Done hence closing.
