### ISSUE TITLE
Remove custom PubSubEmulator rule; replace with testcontainers

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/spring-cloud-gcp#710]
PubSubEmulator is a JUnit4 rule that relies too much on the linux-sh filesystem (so would not even work on Windows) and on process manipulation. It was the best I could do at the time, but it's not worth supporting -- thanks to @eddumelendez there is now [Testcontainers support](https://github.com/testcontainers/testcontainers-java/blob/master/modules/gcloud/src/main/java/org/testcontainers/containers/PubSubEmulatorContainer.java).

@saturnism had an [example of an integration test](https://github.com/saturnism/testcontainers-gcloud-examples/blob/main/springboot/pubsub-example/src/test/java/com/example/springboot/pubsub/PubSubIntegrationTests.java) using Pub/Sub emulator testcontainer.

**Comment by eddumelendez** [comment]
@elefeint should we enough for now to add a deprecation of PubSubEmulator and update docs pointing to testcontainers' gcloud module? I think this can be a good first issue and I can help with that.

**Comment by elefeint** [comment]
`PubSubEmulator` was never available to users; it was an internal test utility. 
It might be useful to link to Testcontainers' documentation in Spring Cloud GCP refdoc, showing how to use the different emulators.

**Comment by elefeint** [comment]
I am going to close this issue since we are not planning to change test infrastructure.
