### ISSUE TITLE
Prevent unit tests from trying to acquire Application Default Credentials

### ISSUE THREAD

**Issue by elefeint** [GoogleCloudPlatform/spring-cloud-gcp#740]
A number of unit tests trigger autoconfiguration of `DefaultCredentialsProvider`. The symptom of it is "java.io.IOException: The Application Default Credentials are not available" output, plus the test takes longer than it should (because interacting with file system is relatively expensive).

1) In an environment that does not have ADC, run `mvn test`, which will run unit tests only, and inventory all tests that complain about credentials. Hint: you can cheat here and take any JUnit output from GitHubActions, as credentials are unavailable there.
2) Pick a test from your list. Figure out what needs to be done in test setup to override credentials, so that autoconfigured `DefaultCredentialsProvider` is never instantiated. Hint: it's going to be a matter of either making a `@Bean` of type `CredentialsProvider` available in test configuration, or in using `.withBean()` to do the same in programmatically generated context. There are examples of both in the codebase. Some instances use a `mock(CredentialsProvider.class)`, while others return a new credentials provider as a lambda `() ->  NoCredentialsProvider.create()`.

Bonus: measure how long all unit tests take to run before you start making changes, and measure the same after all changes are done. How much faster have our unit tests gotten?

**Comment by elefeint** [comment]
@ddixit14 This is for after JUnit migration. It will take you through different styles of overriding autoconfiguration.

**Comment by ddixit14** [comment]
This is completed so closing the issue.

**Comment by Mowee** [comment]
@ddixit14 @elefeint Can you provide me with some more informations. Because I seem to be unable to solve this issue. I've thought by manually providing a NoCredentialsProvider for my via a TestConfiguration this issue could be solved but this does not seems to be the case. Even providing a custom SecretManagerServiceClient does not solve my issue.

I've created a sample repository: https://github.com/Mowee/gcp-no-credentials-provider

**Comment by elefeint** [comment]
@Mowee please open a new issue describing what you are trying to achieve. This issue was for an internal test infrastructure, which should not affect you unless you are working on Spring Cloud GCP project.

**Comment by Mowee** [comment]
@elefeint Thank you, I will do.
