### ISSUE TITLE
Logback CONSOLE_JSON appender. Customize pattern

### ISSUE THREAD

**Issue by debrutal** [GoogleCloudPlatform/spring-cloud-gcp#744]
**Is your feature request related to a problem? Please describe.**
When analysing errors in the Cloud Run Logs i am used to see `thread` and `package/class` information within the logged message of the log. For me it is important to have those informations at the first glance to associate logs to the same execution. This is the default behaviour with logback.

When i use a provided appender e.g.
`  <include resource="com/google/cloud/spring/logging/logback-json-appender.xml"/>`
those informations are not visible within cloud log run. 

To have a better Analysis i then have to switch to the GCP Logs Explorer and then use correct filters to find that message, which costs time and is quite annoying. Luckily this tool then provides me with additional related logs, which is not the first place to go for, since it technically covers all imaginable logs.

**Describe the solution you'd like**

I want to customize the pattern which is used at the given appender. Maybe this is a non existing feature in Logback. I cannot tell.

**Describe alternatives you've considered**
I could use a self written Appender, but as a developer i try to keep things in a default state if possible. IMHO Conventions are a huge productivity boost.

**Additional context**

A more comprehensive description is at [Stackoverflow](https://stackoverflow.com/questions/70017929/google-spring-cloud-logback-json-appender-hides-information-like-thread-or-loggi?noredirect=1#comment123909329_70017929)

**Comment by debrutal** [comment]
editid missing end of a sentence

**Comment by elefeint** [comment]
@debrutal Cloud Logging converts a JSON field with key `message` into the text that you see in logging overview. With `StackdriverJsonLayout` (which is what powers `logback-json-appender.xml`), you can customize all aspects of the logged JSON with an implementation of `com.google.cloud.spring.logging.JsonLoggingEventEnhancer` referenced as `<loggingEventEnhancer>` field of the encoder.

Here is an example enhancer implementation that would do what you are looking for:
```
public class MessageLoggingEventEnhancer implements JsonLoggingEventEnhancer  {
	@Override
	public void enhanceJsonLogEntry(Map<String, Object> jsonMap, ILoggingEvent event) {

		String originalMessage = (String) jsonMap.get(JsonLayout.FORMATTED_MESSAGE_ATTR_NAME);
		String messageWithExtraInformation = event.getThreadName() + " - " + event.getLoggerName() + " - " + originalMessage;
		jsonMap.put(JsonLayout.FORMATTED_MESSAGE_ATTR_NAME, messageWithExtraInformation);
	}
}
```

And here is how you would get it picked up by the layout:

```
<root level="INFO">
		<appender name="CONSOLE_JSON" class="ch.qos.logback.core.ConsoleAppender">
			<encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
				<layout class="com.google.cloud.spring.logging.StackdriverJsonLayout">
					<projectId>${projectId}</projectId>
					<loggingEventEnhancer>com.example.MessageLoggingEventEnhancer</loggingEventEnhancer>
				</layout>
			</encoder>
		</appender>
    </root>
```

**Comment by dinvlad** [comment]
Is there an example on how to use it with `PatternLayoutEncoder` (which supports other information not seemingly available in `JsonLoggingEventEnhancer`, like method name etc)?

**Comment by zhumin8** [comment]
Closing as part of cleanup. Please re-open if it's still relevant.
