### ISSUE TITLE
BeforeSaveEvent doesn't include all the entities

### ISSUE THREAD

**Issue by psinghbay1** [GoogleCloudPlatform/spring-cloud-gcp#746]
**Describe the bug**
We are leveraging this event to update some common attributes in entity classes. We noticed that The event includes the entities which are saved only using SpannerTemplate.save() calls. If we have parent-child related entities e.g. School & Students and call SpannerTemplate.save(new Student()), then the BeforeSaveEvent includes Student object. However if we have code something like:
```java
School sch = new School(...);
Student std = new Student(sch);
spTmpl.save(std);
```
then the BeforeSaveEvent doesn't include School. Same issue occurs even if we call spTmpl.save(sch).
However the transaction log mentions that it got to update both entities:

```txt
Applying Mutation: [insert_or_update(school{}), insert_or_update(student{})]
```

changing the code to something like this fixes the issue:

```java
```java
School sch = new School(...);
Student std = new Student(sch);
spTmpl.save(std);
spTmpl.save(sch);
```

**Sample**

**Comment by elefeint** [comment]
@psinghbay1 Thank you for reporting! 

@ddixit14 Could you reproduce the issue and look into the cause? This is higher priority than the testing work.

**Comment by ddixit14** [comment]
Hi @psinghbay1, could you please provide more information on the entities that you have defined, if you're using spanner-template or spanner-repository and the version of spring-cloud-gcp you're using?
