### ISSUE TITLE
Add `Spring Boot` version compatibility matrix to documentation & README

### ISSUE THREAD

**Issue by michaeldlfx** [GoogleCloudPlatform/spring-cloud-gcp#789]
**Is your feature request related to a problem? Please describe.**
Currently, it's quite difficult to verify the compatibility of `Spring Boot` versions with `Spring Cloud GCP` versions. It's only possible by
1. Noticing that the application won't start, and looking up the [`SpringBootVersionVerifier.java`](https://github.com/spring-cloud/spring-cloud-commons/blob/8807b4dac035c2247987d22065ac03b8c86777e3/spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/SpringBootVersionVerifier.java#L36-L40) file in the `Spring Cloud` project, which `Spring Cloud GCP` transitively includes. [Here's a link the most recent commit to that file](https://github.com/spring-cloud/spring-cloud-commons/commit/f8f549cc72de4c42f376af379bed5876207529e3#diff-573b4a5eeec352ae13a1ed5df6391bd67d458954e8220638c6f14aed8bea67c3).

2. Having a look at the [`Spring Initializr`](https://start.spring.io), by selecting a Spring Boot version and looking up GCP dependencies.

**Describe the solution you'd like**
It would be great to display a version compatibility matrix both on the [official `Spring Cloud GCP` documentation page](https://spring.io/projects/spring-cloud-gcp) and the `README` of this repository.

_Note_: The [official `Spring Cloud` documentation page](https://spring.io/projects/spring-cloud) does have a `Spring Boot` version compatibility matrix in the [Getting Started section](https://spring.io/projects/spring-cloud#getting-started). I've attached a screenshot below as a reference.

**Describe alternatives you've considered**
As mentioned, I did some digging through the dependencies until I came across the [`SpringBootVersionVerifier.java`](https://github.com/spring-cloud/spring-cloud-commons/blob/8807b4dac035c2247987d22065ac03b8c86777e3/spring-cloud-commons/src/main/java/org/springframework/cloud/configuration/SpringBootVersionVerifier.java#L36-L40) file to find the version incompatiblity. I've then also had a look at the [`Spring Initializr`](https://start.spring.io), by selecting the current Spring Boot version and then looking for GCP dependencies.

**Additional context**

Here's a screenshot from the [official `Spring Cloud` documentation page `Spring Boot` compatibility matrix](https://spring.io/projects/spring-cloud#getting-started)

<img width="847" alt="Screenshot 2021-12-12 at 15 04 28" src="https://user-images.githubusercontent.com/24497482/145715587-8086173c-b781-4759-aac3-5d55b153877c.png">

**Comment by elefeint** [comment]
@michaeldlfx Thank you; this is a good idea. 
To summarize quickly up front:
* Spring Boot 2.6 / Spring Cloud 2021.0 are not yet supported in Spring Cloud GCP. We are working on this compatibility for the next release.
* Spring Boot 2.4/2.5 and Spring Cloud 2020.x are supported in Spring Cloud GCP 2.0.x.
