### ISSUE TITLE
firestore cannot handle field names with leading and trailing __ as it breaks a constraint in firestore if created

### ISSUE THREAD

**Issue by PhilipAshworth** [GoogleCloudPlatform/spring-cloud-gcp#820]
**Describe the bug**
When using the https://cloud.spring.io/spring-cloud-static/Greenwich.RC2/multi/multi__spring_data_cloud_datastore.html and Entity data is created, it causes firestore / google cloud datastore fields to be created using a naming convention of __<field name>__ for example `__type__ = "__legacy_entity__"`

This clashes with a firestore restriction where double underscores at the start and end of a fieldname are restricted. This means that the firebase console cannot add these fields and that any field in a map with a field containing a field named this way cannot be updated from the firestore console. The error given is  "unable to save field". The same applies if you try to do this in the google cloud console for the datastore.

There is no way to change the leading and trailing __ to another value to work around this problem for firestore. This also breaks existing tools that developers have to import data back in to firestore where these fields exist.

This applies to all firestore projects so to reproduce this, go to the firebase console and create a new firestore database if one does not exist. Try to add a new field called __newfield__
**Sample**
![image](https://user-images.githubusercontent.com/86660422/147354143-35c65a41-3497-4409-96aa-51ea72c325b5.png)

![image](https://user-images.githubusercontent.com/86660422/147354177-39a37733-f132-49cf-ab96-0ae307dd994e.png)
![image](https://user-images.githubusercontent.com/86660422/147354609-db53ae58-c400-4405-aae1-3933826c5d1e.png)

**Comment by elefeint** [comment]
Datastore and Firestore have separate modules in Spring Cloud GCP. Try using the [Firestore integration](https://googlecloudplatform.github.io/spring-cloud-gcp/2.0.7/reference/html/index.html#spring-data-cloud-firestore) to interact with Firestore in native mode.

**Comment by emmileaf** [comment]
Closing as resolved, please re-open if needed.
