### ISSUE TITLE
R2DBC in Cloud SQL : Enable support for IAM database authentication

### ISSUE THREAD

**Issue by mpeddada1** [GoogleCloudPlatform/spring-cloud-gcp#821]
This seems to be blocked as described below:

Currently holding off on adding support for enabling IAM auth through the url as this doesn't seem to be working as expected for the R2DBC workflow. Extra options parsed from the url are automatically typed as `String` so  when [GcpConnectionFactoryProvider#createFactory](https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/blob/20881af5ec8669fcb97899f232810ed03138ebfa/r2dbc/core/src/main/java/com/google/cloud/sql/core/GcpConnectionFactoryProvider.java#L103) in the Cloud SQL Java socket factory library calls `(Boolean)connectionFactoryOptions.getValue(ENABLE_IAM_AUTH)` this results in an error.

_Originally posted by @mpeddada1 in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/772#discussion_r769133534_

**Comment by elefeint** [comment]
I think this will have to be a change in `GcpConnectionFactoryProvider`.
Even when [the limitation in R2DBC](https://github.com/r2dbc/r2dbc-spi/issues/206) gets addressed with some new API, the socket factory will still have to switch to using the new API.

**Comment by mpeddada1** [comment]
Thanks for the link to the limitation. Create an issue at https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/686.
