### ISSUE TITLE
Support "Annotate File" endpoint

### ISSUE THREAD

**Issue by gabac** [GoogleCloudPlatform/spring-cloud-gcp#844]
**Is your feature request related to a problem? Please describe.**
Google Vision also offers an API to annotate files, specifically PDFs. In my use case I have many file types and I would like not to convert a PDF to an image on my side

- https://cloud.google.com/vision/docs/reference/rest/v1/files/annotate
- https://cloud.google.com/vision/docs/reference/rpc/google.cloud.vision.v1#google.cloud.vision.v1.BatchAnnotateFilesRequest

**Describe the solution you'd like**
Support this additional endpoint as well.

**Describe alternatives you've considered**
Convert the file in my custom service

**Additional context**
Would be happy to provide a PR if you think this is a sensible addition

**Comment by meltsufin** [comment]
I think this could make sense, especially if it's a simple addition to the `VisionTemplate`. @dzou @elefeint What do you think?

**Comment by gabac** [comment]
That would have been my idea 💡

**Comment by elefeint** [comment]
@gabac Have you tried using `CoudVisionTemplate.analyzeImage()` on the PDFs? PDF is [considered one of the supported "image" types](https://cloud.google.com/vision/docs/supported-files).

**Comment by gabac** [comment]
I tried, it's not 😉
That's why I opened up the feature request in the first place

**Comment by gabac** [comment]
That would be the error message I receive
```
code: 13
message: "Internal server error. Failed to process features."
```

**Comment by elefeint** [comment]
We've tested this a bit with the existing Vision sample. Could not reproduce this exact error, but did get "bad image" response codes for every PDF tried. 
I've reached out to Vision team for guidance on whether the "annotate-image" set of APIs is expected to work on PDFs, or if "annotate-files" should be used instead.

**Comment by gabac** [comment]
This is my mistake. I copied in an internal error message from my service. The error message by the API would be the same as you just mentioned
```
{
  "responses": [
    {
      "error": {
        "code": 3,
        "message": "Bad image data."
      }
    }
  ]
}

```
I appreciate that you reached out to the Vision team to clarify things.

Independent of the outcome, would you be interested in supporting the `annotate-files` endpoint in this library?

**Comment by elefeint** [comment]
@gabac I've confirmed that PDF, TIFF and GIF files are expected to use `BatchAnnotateFiles` endpoint. 

If you are interested in sending a PR, we'll be happy to review and accept it.

**Comment by meltsufin** [comment]
@florian-3ap I'm wondering whether the `DocumentOcrTemplate` is relevant to your use-case? It does operate asynchronously via Google Storage. So, there's that difference.
See: https://googlecloudplatform.github.io/spring-cloud-gcp/reference/html/index.html#cloud-vision-ocr-dependencies

**Comment by florian-3ap** [comment]
@meltsufin We do not store the document in a bucket before the OCR extraction. Therefore this `DocumentOcrTemplate` is not a possible option for us.
