### ISSUE TITLE
[pubsub] Graceful shutdown for underlying Publisher

### ISSUE THREAD

**Issue by njkevlani** [GoogleCloudPlatform/spring-cloud-gcp#864]
Hello,

Does [`PubSubPublisherTemplate`](https://docs.spring.io/spring-cloud-gcp/docs/1.1.0.M2/api/org/springframework/cloud/gcp/pubsub/core/publisher/PubSubPublisherTemplate.html) provide functionality to call [`.shutdown`](https://googleapis.dev/java/google-cloud-pubsub/latest/com/google/cloud/pubsub/v1/Publisher.html#shutdown--) and [`.awaitTermination`](https://googleapis.dev/java/google-cloud-pubsub/latest/com/google/cloud/pubsub/v1/Publisher.html#awaitTermination-long-java.util.concurrent.TimeUnit-) methods from underlying [`com.google.cloud.pubsub.v1.Publisher`](https://googleapis.dev/java/google-cloud-pubsub/latest/com/google/cloud/pubsub/v1/Publisher.html)?

We have a use case where we want to be able to control the shutdown for the underlying publisher.

> **Describe the solution you'd like**

We would want to be able to have a method in PubSubPublisherTemplate that shuts down underlying Publishers. Or to have an API to access underlying Publishers.

**Comment by elefeint** [comment]
It's a valid feature request. In fact, it's a bug/omission that we don't shut down publishers on Spring context shutdown ourselves.

@njkevlani Is your usecase related to application shutdown issues, or do you want to clean up publishers throughout the application lifespan?

**Comment by njkevlani** [comment]
Hey @elefeint,

Yes, our usecase is about application's graceful shutdown.
