### ISSUE TITLE
Tracing context derived from PubSub messages that are delivered through push subscriptions

### ISSUE THREAD

**Issue by hfgbarrigas** [GoogleCloudPlatform/spring-cloud-gcp#893]
Although there is tracing support for pubsub template leveraging spring-cloud-sleuth, when using pubsub push subscriptions message attributes are not used as http headers but instead, the whole message is delivered in the body of an http post.

**Describe the solution you'd like**
Ideally, propagating tracing context should be transparent and users of spring-cloud-sleuth and gcp could opt-in via configuration property.
The solution should support servers that are using spring-webflux or spring-web.

**Comment by meltsufin** [comment]
Thank you for submitting the enhancement request @hfgbarrigas!

**Comment by hfgbarrigas** [comment]
sure thing. while this isn't supported, could you point me in the right direction to come up with something? I was looking at `org.springframework.cloud.sleuth.instrument.web.TraceWebFilter` but would have to make adjustment to inspect the body and get the message attributes. Is there anything that I could re-use from https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/548 to extract and populate the tracing context?

**Comment by elefeint** [comment]
Here is a sample showing one way to get this done: 
https://github.com/elefeint/examples/tree/master/pubsub-push

In the sample, `HttpTracingCustomizer` is used to exclude the Pub/Sub Push endpoint from being instrumented by turning sampling off. Then a new span with the correct trace context is created in the REST controller, where the request body is already available.

My original approach of extracting the trace context in `HttpTracingCustomizer` worked; however it's not very elegant, since a servlet request can normally only be read once, and all kind of cludgy code is needed to make the request body cacheable. From the user application perspective, it's much better to get the context at the point where request body is available without difficulties.

For implementing something like that more generally, we have two choices:
1)  Extract context `HttpTracingCustomizer`, cache request InputStream in a subclass of Request.
2) Do something more similar to the sample above, but also for a URL path matching a new "pushEndpoint" property, set up a HTTP filter or request callback after the body is available but before the request is sent to the controller.

**Comment by hfgbarrigas** [comment]
@elefeint thanks for your example.

I took a stab at doing this in a Webfilter but felt too soon in the chain (raw DataBuffer and no de-serialisation) and didn't like subscribing or wrapping the body (or caching). Here's what I came up with:

```Java
public class PubSubBodyTracingExtractor {
    private static final String B3_CONTEXT_KEY = "b3";
    private static final String SPAN_NAME = "pubsub-push";
    private static final String PUBSUB_MESSAGE_ID_TAG = "pubsub.message.id";
    private static final String PUBSUB_SUBSCRIPTION_TAG = "pubsub.subscription";

    private Tracer tracer;
    private Tracing tracing;
    private BaggageField myBaggage;

    public PubSubBodyTracingExtractor(Tracer tracer, Tracing tracing, BaggageField myBaggage) {
        this.tracer = tracer;
        this.tracing = tracing;
        this.myBaggage = myBaggage;
    }

    public <T> Mono<T> fromMessage(PubSubMessage body, Mono<T> execution) {
        final Span newSpan = getSpan(body);
        return execution
                .contextWrite(ctx -> ReactorSleuth.wrapContext(ctx.put(TraceContext.class, new BraveTraceContext(newSpan.context()))))
                .doOnTerminate(newSpan::finish);
    }

    public <T> Flux<T> fromMessage(PubSubMessage body, Flux<T> execution) {
        final Span newSpan = getSpan(body);
        return execution
                .contextWrite(ctx -> ReactorSleuth.wrapContext(ctx.put(TraceContext.class, new BraveTraceContext(newSpan.context()))))
                .doOnComplete(newSpan::finish);
    }

    private Span getSpan(PubSubMessage message) {
        final Propagation propagation = this.traceContextFromMessage(message);

        final TraceContextOrSamplingFlags flags = B3SingleFormat.parseB3SingleFormat(propagation.b3);

        final Span newSpan = this.tracer.nextSpan(flags);

        newSpan.name(SPAN_NAME);
        newSpan.kind(Span.Kind.CONSUMER);
        Optional.ofNullable(message.getSubscription())
                .ifPresent(s -> newSpan.tag(PUBSUB_SUBSCRIPTION_TAG, s));
        Optional.ofNullable(message.getMessage())
                .filter(mm -> !StringUtils.isEmpty(mm.getMessageId()))
                .ifPresent(mm -> newSpan.tag(PUBSUB_MESSAGE_ID_TAG, mm.getMessageId()));

        // we can play with baggage with the span context
        //this.myBaggage.updateValue(newSpan.context(), propagation.myBaggage());

        final long timestamp = this.tracing.clock(newSpan.context()).currentTimeMicroseconds();

        newSpan.start(timestamp);
        return newSpan;
    }

    private Propagation traceContextFromMessage(final PubSubMessage message) {
        //  {"subscription":".../pushsubscription",
        //   "message":{"data":"dGVzdCttZXNzYWdlKzE9","messageId":"1",
        //     "attributes":{"b3":"61e98ba6abdecbfb47188242d3f9398e-ec36907be1b2501e-1"}}}
        final Map<String, String> msgAttrs = Optional.ofNullable(message.getMessage())
                .map(PubSubMessage.Message::getAttributes)
                .orElse(Collections.emptyMap());

        LOGGER.debug("Message attributes: {}", msgAttrs);

        final String b3 = Optional.ofNullable(msgAttrs.get(B3_CONTEXT_KEY))
                .orElseGet(() -> {
                    brave.propagation.TraceContext traceContext = Optional.ofNullable(this.tracing.currentTraceContext())
                            .map(CurrentTraceContext::get)
                            .orElseGet(() -> this.tracer.newTrace().context());

                    return B3SingleFormat.writeB3SingleFormat(traceContext);
                });

        String myBaggage = Optional.ofNullable(msgAttrs.get("myBaggage"))
                .orElse("");

        LOGGER.debug("Using b3: {}, myBaggage: {}", b3, myBaggage);

        return Propagation.builder()
                .b3(b3)
                .myBaggage(myBaggage)
                .build();
    }

    @Getter
    @Builder
    private static class Propagation {
        private String upc;
        private String myBaggage;
    }
}
```
Maybe it's useful for someone else. Let me know if you spot anything wrong or worth changing.

**Comment by elefeint** [comment]
This looks like a useful operator-like approach for reactive push applications. Thanks!

**Comment by elefeint** [comment]
I am going to close this issue -- there are enough examples of how Pub/Sub push users might accomplish trace reconstruction, and since most Java/Spring users use either polled or streaming pull, it is unlikely we will get to implementing it in the project.
