### ISSUE TITLE
Upgrade samples to Boot 2.4.0-M4 once spring-cloud supports it

### ISSUE THREAD

**Issue by ttomsu** [GoogleCloudPlatform/spring-cloud-gcp#90]
I tried updating us manually but the integration tests fail because various `@SpringBootApplication` applications can't start up. I think it's because of near-duplicate libraries on the classpath (like versions 5.4.0 vs 5.4.1)

I think this `spring-boot.version` is what limits us.

https://github.com/spring-cloud/spring-cloud-build/blob/master/pom.xml#L31

**Comment by meltsufin** [comment]
Right, our samples should use the highest version of Spring Boot supported by the latest Spring Cloud version.

**Comment by ttomsu** [comment]
Fixed in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/133
