### ISSUE TITLE
Application cannot start after migration to gcp-datastore 3.0.0

### ISSUE THREAD

**Issue by beunick** [GoogleCloudPlatform/spring-cloud-gcp#905]
I migrate from  version of datastore

`	<dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-gcp-starter-data-datastore</artifactId>
		    <version>1.2.8.RELEASE</version>
		</dependency>`

to this version

`	<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId> 
      <artifactId>spring-cloud-gcp-dependencies</artifactId>
      <version>3.0.0</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>`

`	<dependency>
    <groupId>com.google.cloud</groupId> 
    <artifactId>spring-cloud-gcp-starter</artifactId>
  </dependency>`
 
`	<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>spring-cloud-gcp-starter-data-datastore</artifactId>
  </dependency>`
  
  

Since then my application is not able to start. Here is the errors I got from the logs

Description:

Parameter 1 of constructor in com.google.cloud.spring.autoconfigure.datastore.GcpDatastoreAutoConfiguration required a bean of type 'com.google.cloud.spring.core.GcpProjectIdProvider' that could not be found.

Action:

Consider defining a bean of type 'com.google.cloud.spring.core.GcpProjectIdProvider' in your configuration.

Here is what I add in my property:
spring.main.allow-bean-definition-overriding=true 

I am using springboot starter version 2.6.0

Please I need your help since this is a big blocker for one of our major release. 
Thanks

**Comment by elefeint** [comment]
@beunick Could you get the Spring Boot bean autoconfiguration debug report (with `--debug=true` [when starting the app](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.spring-application.startup-failure))?

Also, take a look at the [Datastore sample application](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/pom.xml) -- are there obvious differences between your application dependencies and the setup? 

It would help a lot if you could make a minimal reproducible sample application.

Normally, `GcpProjectIdProvider` is provided by [`GcpContextAutoConfiguration`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/v3.0.0/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/core/GcpContextAutoConfiguration.java#L67).

**Comment by beunick** [comment]
@elefeint Thanks for the note. I was able to figure out the issue with the ressources you sent. 
I think the problem was due to the fact that I was using an older version of cloud storage. I should have use the same version for gcloud storage and datastore... Thanks
