### ISSUE TITLE
Firestore Data Mapping Does not work with Groovy Classes

### ISSUE THREAD

**Issue by jjathman** [GoogleCloudPlatform/spring-cloud-gcp#939]
**Describe the bug**
It currently seems impossible to use a Groovy class as the object to save to Firestore due to the object mapping attempting to map some of the "hidden" fields that Groovy automatically adds to every class. I don't think there is any available configuration which allows for excluding these fields.

**Sample**

`Data.groovy`
```
@Document
class Data {
  @DocumentId
  String id
}
```

Attempting to save this document will generate this error:
```
reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.IllegalArgumentException: Could not serialize object. Serializing Arrays is not supported, please use Lists instead (found in field 'metaClass.additionalMetaMethods')
Caused by: java.lang.IllegalArgumentException: Could not serialize object. Serializing Arrays is not supported, please use Lists instead (found in field 'metaClass.additionalMetaMethods')
```

I think there would be two relatively simple solutions that I would like to use. One would be to configure the mapper to always ignore certain classes `MetaClass` in this case, or allow the `Exclude` annotation to be applied to the class level and provide string properties to exclude. This would allow me to exclude the `metaClass` since I am unable to annotate it.

**Comment by elefeint** [comment]
Spring Data already has handling for [excluding such autogenerated fields](https://github.com/spring-projects/spring-data-commons/blob/788457c90132ae7ca893791d091279faa8e76abe/src/main/java/org/springframework/data/mapping/context/AbstractMappingContext.java#L695), so this is likely a matter of finding where the Firestore implementation missed plugging into the property exclusion process.

**Comment by jjathman** [comment]
That’s very interesting. Good find! Hopefully that means it’s not too much work to support it in the future.

**Comment by elefeint** [comment]
Leaving it open as a new feature.

**Comment by elefeint** [comment]
We've looked into this some more, and the object-to-document functionality lives entirely in the client library. I will close this issue; please watch googleapis/java-firestore#996 for updates.
