### ISSUE TITLE
Can other modules of GCP support IAM authentication?

### ISSUE THREAD

**Issue by spyros87** [GoogleCloudPlatform/spring-cloud-gcp#949]
Cloud SQL Postgres supports passwordless authentication using IAM roles. On the other hand, the rest of GCP modules require a credentials file for accessing these modules.

It could be great if there is a solution which provides an IAM authentication to service accounts so that they are able to work without the need for providing credential files to the Spring App for authentication

**Comment by elefeint** [comment]
All Spring Cloud GCP modules allow you to authenticate with a service account by using either Application Default Credentials or a JSON key ([documentation](https://googlecloudplatform.github.io/spring-cloud-gcp/3.0.0/reference/html/index.html#credentials)). 

You can set specific IAM permissions for the service/user account you are using in Cloud Console.

It sounds like your usecase is to authenticate as a service account when running locally. You can do that with either [`gcloud`](https://cloud.google.com/sdk/gcloud/reference/auth/login) or by manually setting [`GOOGLE_APPLICATION_CREDENTIALS`](https://cloud.google.com/docs/authentication/production#passing_variable) environment property. Spring Cloud GCP modules will then fall back to the environment when they don't find an explicitly configured property.

**Comment by spyros87** [comment]
> All Spring Cloud GCP modules allow you to authenticate with a service account by using either Application Default Credentials or a JSON key

That's the typical use case except the Postgres Cloud SQL where you authenticate using a user with just the IAM credentials via the `Cloud SQL socket factory`. Locally you can use an impersonation of the IAM and connect to a remote instance.

My initial intention was to have an IAM authentication similar to the Database for other GCP modules without the need to provide any static credentials inside a GCP Kubernetes Pod. Is this possible?

>It sounds like your usecase is to authenticate as a service account when running locally.

Locally GCP modules can be emulated.

**Comment by meltsufin** [comment]
I'm still a little lost in what you're trying to do. Can you give an example of how you would do this without Spring Cloud GCP? Remember, Spring Cloud GCP is wrapping GPC libraries. So, if it's possible to do directly with the Postgres Cloud SQL connector, we should be able to do it with Spring Cloud GCP.
