### ISSUE TITLE
ScheduledThreadPoolExecutor not closing down

### ISSUE THREAD

**Issue by seleroy** [GoogleCloudPlatform/spring-cloud-gcp#957]
Hello,

I am using spring-cloud-gcp version 3.0.0 with Spring boot 2.6.2. I have a subscriber consuming from a Pubsub subscription
I have an issue on a server, where the JVM receives a signal and is requested to shutdown. I can see in the thread dump that we have the "Signal Dispatcher", "SpringApplicationShutdownHook" and "DestroyJavaVM" threads in a runnable/alive state so the JVM is really trying to shutdown.

My application beans start to shutdown and my DB connections are closed for example.
But the CPU spins at 100%, the subscriber threads do not shutdow and the messages continue piling up in the workQueue of the executor. 48hours after the signal, there are 514k messages in the workQueue of the executor.

The way I am configuring my consumer is by:
- Creating a PublisherFactory and SubscriberFactory beans (default config)
- Creating a PubsubTemplate from these 2 beans
- The consumer subscribes to the subscription by using pubsubTemplate.subscribe("subname", consumerMethod())

I have checked the docs and noticed that there is a method on the PubSubSubscriberTemplate that is called destroy() and that is supposed to destroy the executor. 
Should this method be called automatically or should I call it manually in the predestroy lifecyclle of the bean ?

@Predestroy
public void shutdown() {
  this.pubsubTemplate.getPubSubSubscriberTemplate().destroy();
}

Thank you in advance

**Comment by elefeint** [comment]
Thank you for the report!
Are you constructing `PubSubSubscriberTemplate`, `PublisherFactory` and `SubscriberFactory` objects or injecting the autoconfigured ones?

Also, is this new behavior -- did this happen with an older version of Spring Cloud GCP?

The `destroy()` method is an implementation of `DisposableBean`, so Spring will call it automatically ([docs](https://docs.spring.io/spring-framework/docs/5.3.x/reference/html/core.html#beans-factory-lifecycle-combined-effects))

**Comment by seleroy** [comment]
Hi,
Here is my bean config. I just have a special case to support using the emulator, but otherwise I use the defaults as much as possible:

`    @Bean
    public GcpProjectIdProvider projectIdProvider(@Value("${spring.cloud.gcp.pubsub.project-id}") String projectId) {
        return new DefaultGcpProjectIdProvider() {
            @Override
            public String getProjectId() {
                return projectId;
            }
        };
    }

    @Bean
    PublisherFactory publisherFactory(GcpProjectIdProvider projectIdProvider,
                                      @Value("${spring.cloud.gcp.pubsub.emulator-enabled:false}") boolean emulatorEnabled,
                                      @Value("${spring.cloud.gcp.pubsub.emulator-host:}") String host) {
        DefaultPublisherFactory factory = new DefaultPublisherFactory(projectIdProvider);
        if (emulatorEnabled) {
            factory.setChannelProvider(FixedTransportChannelProvider.create(GrpcTransportChannel.create(ManagedChannelBuilder.forTarget(host).usePlaintext().build())));
            factory.setCredentialsProvider(NoCredentialsProvider.create());
        }
        return factory;
    }

    @Bean
    SubscriberFactory subscriberFactory(GcpProjectIdProvider projectIdProvider,
                                        @Value("${spring.cloud.gcp.pubsub.emulator-enabled:false}") boolean emulatorEnabled,
                                        @Value("${spring.cloud.gcp.pubsub.emulator-host:}") String host) {
        DefaultSubscriberFactory factory = new DefaultSubscriberFactory(projectIdProvider, new com.google.cloud.spring.pubsub.core.PubSubConfiguration());
        if (emulatorEnabled) {
            factory.setChannelProvider(FixedTransportChannelProvider.create(GrpcTransportChannel.create(ManagedChannelBuilder.forTarget(host).usePlaintext().build())));
            factory.setCredentialsProvider(NoCredentialsProvider.create());
        }
        return factory;
    }

    @Bean
    public JacksonPubSubMessageConverter converter() {
        return new JacksonPubSubMessageConverter(new ObjectMapper());
    }

    @Bean
    public PubSubTemplate pubSubTemplate(PublisherFactory publisherFactory, SubscriberFactory subscriberFactory) {
        return new PubSubTemplate(publisherFactory, subscriberFactory);
    }
`

I am unable to tell you if this behaviour is new as it is a brand new service. I have the feeling that it happens only if there is constant traffic coming on the subscription. I don't have the issue in test environments where the traffic is lower. I assume that when there is not a constant traffic, the executor is able to reach a point where the workingQueue is empty, all "task" threads are completed and the executor can shutdown.

I have seen in the implementation of PubSubSubscriberTemplate that the destroy() method calls shutdown() on the ExecutorService, so if it was called it should not accept new tasks, even if an old task was stuck.

**Comment by seleroy** [comment]
Hi Elena,
Thank you for your feedback. I have simplified our bean config so that we let the autoconfiguration create the SubscriberFactory and PubsubTemplate beans as we don't really need a special configuration. That should let the autoconfiguration take care of creating and destroying the thread pool executor properly.

**Comment by meltsufin** [comment]
Thank you for the update. I will close this, but if the issue comes back with the new configuration, please re-open.
