### ISSUE TITLE
Retrieving Child Entity in one request

### ISSUE THREAD

**Issue by beunick** [GoogleCloudPlatform/spring-cloud-gcp#978]
Hello All,
What is the best way to retrieve child entities in one request to Datastore using spring boot. 
For examples in this scenario below, how can I retrieve the list of Product entities when I retrieve the list of Invoices ? Thanks for your help.

Here are the entities.
**The Invoice entity:**
`@Entity(name="invoice")
public class Invoice {
	@Id
	private Key id;
	private List<Item> items;
}`

**The Items object is not an entity. I used a Converter for it.**
`public class Item {
	@Field(name="product_id")
	private String productId;
	private Long quantity;
}`

**The Product entity is as followed**
`@Entity(name="product")
public class Product {
	@Id
	private Key id;	
        private String name;
	private String code;
	private String description;
}`

**Comment by mpeddada1** [comment]
Hi @beunick, thanks for the question. Parent and child relationships are supported via the @Descendant annotation. This [section in our official docs ](https://docs.spring.io/spring-cloud-gcp/docs/current/reference/html/datastore.html#_ancestor_descendant_relationships) provides some information on how that can be established.

In this case, you may need to do something similar where you annotate `List<Item>` with the `@Descendant` annotation and add a getter/setter for `items`. Our sample is a good starting point to determine how a list of descendant entities can be retrieved from an entity:

https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/e04f755f75c98619c11fde42106cff81e95f1540/spring-cloud-gcp-samples/spring-cloud-gcp-data-datastore-sample/src/test/java/com/example/DatastoreSampleApplicationIntegrationTests.java#L170

Please let us know if this option works for your case.

**Comment by meltsufin** [comment]
Closing. Please re-open if you have further questions.
